# -*- coding: utf-8 -*-
# Phase B: menu 未译占位补译（菜单 UI；TAA/HDR/FXAA 缩写、UI_TEST_FONT、XX:XX 损坏占位保留英文）
import re, os
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCH = os.path.join(BASE, "schinese", "menu_us.txt")
T = {
 "SAVELOAD_CORRUPT_DISPLAY_TIME": "XX:XX:XX",
 "SAVELOAD_CORRUPT_DISPLAY_DATE": "XX.XX.XX",
 "SAVELOAD_AUTOSAVE_DEVICE_FULL": "当前设备空间不足。要执行自动存档，你必须选择其他设备。\\n现在就选择其他设备吗？",
 "RADIO_STATION_GENRE_KLASSIC": "古典音乐",
 "CONTROL_DESC_NOT_USED": "未使用",
 "INFO_COLLECTIONS_HITMAN": "职业杀手",
 "CONTROL_DESC_VEH_CLICK_HORN": "喇叭",
 "SAVE_BEFORE_JOINING_TITLE": "加入新游戏",
 "MENU_OPTIONS_GAMEPLAY": "玩法",
 "INFO_UNLOCKABLES_PLAYER_ABILITIES": "能力",
 "CELL_OPTION_CHEATS": "作弊",
 "SAVELOAD_SIGN_IN": "登录",
 "SAVELOAD_SAVE_GAME_TOO_MANY_ABORT": "不保存并继续",
 "MENU_DISPLAY_BRIGHTNESS": "亮度",
 "MAP_ADD_BOOKMARK": "添加书签",
 "COMPLETION_RESTART_CHECKPOINT": "从检查点重试",
 "PAUSE_MAP_FILTERS": "更改筛选",
 "PAUSE_ACT_CHOP_SWITCH_SELECT": "切换活动 / 选择商店",
 "PLAYLIST_MOVE_TRACK": "移动",
 "CONTROL_DESC_FOOT_TAUNT": "嘲讽",
 "PLAYLIST_REMOVE_TRACK": "删除",
 "CONTROLS_MINIMAP_VIEW": "小地图视角",
 "COMPLETION_RESTART_BEGINNING": "从任务开头重试",
 "GAMER_PROFILE_REINSERT_EXIT": "返回主菜单",
 "CONTROL_DESC_VEH_RADIO_PREV": "切换电台",
 "CONTROL_DESC_MP_HEAL": "治疗",
 "CONTROL_CHANGE_OPTION": "更改选项",
 "COMPLETION_MISSION_FAILED": "{0} 失败",
 "COMPLETION_CONTINUE_ACTIVITY": "继续活动",
 "MENU_QUICKMATCH_OVERSIZED": "包含超大型载具",
 "HELP_TEXT_CHARGED_MELEE_ATTACK": "按住 {ATTACK_PRIMARY_IMG} 蓄力越久，蓄力近战攻击的威力越强",
 "CONTROL_DESC_GRENADE": "手雷",
 "CONTROL_DESC_JUMP": "跳跃",
 "MENU_BACK": "返回",
 "MAP_ICON_COLLECTIBLE_PHOTO_OP": "合影点",
 "MAINMENU_QUIT_DEMO_CONFIRM_TEXT": "确定要退出《黑道圣徒》吗？",
 "CONTROL_SETUP_CHANGE_SCHEME": "更改方案",
 "CONTROL_DESC_VEH_STEER": "转向",
 "CONTROL_DESC_FOOT_RELOAD": "装填",
 "COMMUNITY_ERROR_OTHER": "社区功能发生错误。请稍后再试。",
 "CRIB_CASH_PLAYER_CASH": "你的现金",
 "PAUSE_MAP_FILTER_STORES": "商店",
 "MAINMENU_WIRELESS": "无线",
 "JOIN_IN_PROGRESS": "正在加入",
 "INFO_HELP_TITLE": "帮助",
 "CONTROL_DESC_MP_TAUNT_1": "嘲讽",
 "RANDOM_WARNING_HEADING": "警告",
 "SAVELOAD_MUST_SELECT_DEVICE": "要使用存档/读档功能，你必须选择存储设备。",
 "SAVELOAD_HDR_DIFFICULTY": "难度：{0}",
 "CONTROL_DESC_PAUSE": "暂停菜单",
 "PLAYLIST_HEADER_TRACKS": "曲目",
 "MENU_DISPLAY_TITLE": "显示",
 "MAP_ICON_TRAILBLAZING": "火烧特技",
 "DLT_CASUAL": "休闲",
 "CONTROLS_INVERT_Y": "反转视角 Y 轴",
 "CELL_OPTION_HOMIES": "兄弟",
 "COOP_CLIENT_GANG_CUST_TRIGGER": "加入方无法自定义主机方的帮派",
 "SAVELOAD_SAVE_DEVICE_UNAVAILABLE_LINE1": "存档失败：默认",
 "PLAYLIST_NO_STATION_ITEMS": "电台列表中没有曲目",
 "MENU_VSYNC_CUTSCENE_TEXT": "垂直同步（过场动画）",
 "MAP_ICON_COLLECTIBLE_DRUG": "毒品包裹",
 "CONTROL_DESC_FOOT_DISMISS": "（按住）遣散同伴",
 "INFO_ACHIEVE_TITLE": "成就",
 "CONTROL_DESC_VEH_NOS": "氮气",
 "NO_NETWORK_CONNECTION": "访问此功能需要网络连接。",
 "SAVELOAD_CHEATS_ENABLED": "作弊已开启。\\n确定要在开启作弊的情况下保存吗？",
 "PAUSE_MENU_DRIVEUP_HOMIE": "已存载具送达",
 "COOP_DISCONNECT": "按 {MAP_MENU_CLOSE_IMG} 断开连接。",
 "MAP_ICON_COLLECTIBLE_SEX_DOLL": "充气娃娃",
 "COMPLETION_CASH_PER_DAY": "每小时收入",
 "MENU_MAP": "地图",
 "SAVELOAD_SAVE_ABORT": "不保存并继续",
 "PAUSE_MESSAGES_NONE": "暂无消息",
 "PAUSE_INFO_UNKNOWN_HOOD": "未知街区",
 "CONTROL_SETUP_RETURN": "返回操作设置",
 "MENU_AUDIO_VOICE": "语音",
 "MAP_ICON_RUNNING_MAN": "元气博士",
 "CUTSCENE_TITLE_DEFAULT": "过场动画播放",
 "CONTROL_CHEAT_YES": "启用作弊",
 "PAUSE_ACT_CHOPSHOP_EMPTY": "没有拆车厂载具",
 "INFO_STORY_TITLE": "剧情",
 "CONTROLS_SETUP_TITLE": "操作设置",
 "CONTROL_DESC_PRIM_ATTACK": "主要攻击",
 "CONTROL_DESC_MP_TAUNT_2": "嘲讽",
 "CELL_CHEAT_ACTIVATE_INSTRUCTIONS": "前往手机中的作弊选项，即可启用作弊。",
 "SAVE_BEFORE_JOINING_BODY": "加入新游戏会让你离开当前游戏。要先保存吗？",
 "MENU_TITLE_WARNING": "警告",
 "MENU_OPTIONS_DISPLAY": "显示",
 "MENU_AUDIO_SFX": "音效",
 "MAINMENU_CONTINUE": "继续",
 "CONTROL_DESC_VEH_VTOL_TRANSFORM": "（VTOL）切换飞行模式",
 "COMMUNITY_EMAIL_FIELD": "电子邮箱地址",
 "MENU_EXTRAS": "附加内容",
 "PAUSE_MENU_CONTROL_CLICK": "（按下）",
 "COMPLETION_CONTROL_PER_DAY": "每小时 ${0}",
 "SAVELOAD_SAVE_GAME_DEVICE_FULL_TITLE": "设备已满",
 "SAVELOAD_SAVE_DEVICE_UNAVAILABLE_LINE2": "存储设备已不可用。",
 "PAUSE_MAP_FILTER_SAVE": "存档点",
 "MENU_TITLE_CONFIRM": "确认",
 "INFO_UNLOCKABLES_SPECIALS": "特殊奖励",
 "PAUSE_MENU_QUIT_TITLE": "退出游戏？",
 "DOWNLOADABLE_REMOVED_EXPOSITION": "你移除了一个\\n存有可下载内容的存储设备。",
 "CONTROLS_SETUP_VCAM_FAR": "远景",
 "COMPLETION_EXIT_ACTIVITY": "退出活动",
 "PAUSE_MENU_SECONDS": "{0} 秒",
 "PAUSE_MAP_FILTER_COLLECTIBLES": "收集品",
 "PAUSE_ACHIEVES_TITLE": "成就",
 "MM_LOAD_LOADING": "加载中",
 "MAP_REMOVE_BOOKMARK": "移除书签",
 "CONTROL_DESC_VEH_CLICK_HYDRAULICS": "氮气/液压悬挂",
 "PAUSE_MENU_STATION_SELECTION": "选择电台",
 "PLAYLIST_HEADER_PLAYLIST": "播放列表",
 "MENU_OPTIONS_NONE": "暂无可用选项",
 "CONTROL_DESC_PAUSE_MAP": "手机",
 "MENU_MISSIONS": "任务",
 "COOP_REVIVAL_PENDING": "你有 %d 秒等待救援",
 "SAVELOAD_SAVE_WARNING": "硬盘访问指示灯闪烁表示系统正在保存。\\n在此期间请勿关闭系统。\\n",
 "RADIO_STATION_GENRE_ADULT_SWIM": "Adult Swim 与卡通频道",
 "INFO_UNLOCKABLES_VEHICLES": "载具",
 "CONTROL_DESC_VEH_LOOK_BACK": "向后看",
 "SB_TITLE": "圣徒簿",
 "CONTROL_DESC_FOOT_HUMANSHIELD_KILL": "处决人盾",
 "BUILDING_PURCHASE_BUILDING": "要以 ${1} 的价格购买 {0:text_tag_crc} 吗？",
 "PAUSE_MENU_ACCEPT": "接受",
 "Control_Scheme": "方案",
 "COMPLETION_NEIGHBORHOOD_GAINED": "占领街区",
 "COMPLETION_EXIT_MISSION": "退出任务",
 "MENU_OPTIONS_AUDIO": "音频",
 "CELL_VEHICLE_DIALOG_REPAIRS_HEADER": "修理并取回载具？",
 "SAVELOAD_SAVING_MESSAGE_TITLE": "正在保存",
 "OPT_CONTROL_DISABLED": "已禁用",
 "INFO_UNLOCKABLES_MISSIONS": "任务",
 "INFO_DIVERSIONS_JOBS": "差事",
 "CONTROL_DESC_FOOT_HUMANSHIELD": "挟持人盾",
 "MISSION_RESTART_PROMPT": "要重玩此任务吗？",
 "MENU_OPTIONS_SELECT_STORAGE": "选择存储设备",
 "COMPLETION_ACTIVITY_LEVEL_FAILED": "第 {0} 关失败",
 "INFO_UNLOCKABLES_HOMIES": "帮派能力",
 "CONTROL_DESC_VEH_TOGGLE_CAM": "切换视角",
 "COMPLETION_CONTROL": "{0}\\n街区控制",
 "CELL_OPTION_CALL": "呼叫",
 "MSN_NO_RESPECT_TITLE": "声望不足！",
 "CONTROLS_SETUP_DRIVING": "驾驶操作",
 "COMPLETION_RETRY_ACTIVITY": "重试活动",
 "COMPLETION_ACTIVITY_LEVEL_COMPLETE": "第 {0} 关完成",
 "CELL_OPTION_CLR": "清除",
 "CELL_PHONEBOOK_NONE": "暂无条目",
 "SAVELOAD_HDR_STATUS": "{0} 已完成           {1}",
 "INFO_DIVERSIONS_FRENZY": "特殊",
 "CONTROL_DESC_VEH_BRAKE_REV": "刹车/倒车",
 "INFO_DIVERSIONS": "小游戏",
 "SAVELOAD_SAVE_GAME_TOO_MANY_EXPOSITION": "此存储设备上已没有可用的存档位。",
 "PAUSE_MAP_FILTER_ACTIVITIES": "活动",
 "MENU_AUDIO_MICAUDIO": "音频麦克风",
 "INVALID_SAVE_MSG": "你尝试读取的存档\\n已损坏或不受本作支持。",
 "GAME_LOADING": "加载中",
 "CONTROL_DESC_FOOT_RECRUIT": "招募同伴",
 "COMPLETION_ENOUGH_RESPECT": "你的声望已足以游玩更多任务",
 "MENU_CONTROLS_INVERT_Y": "反转视角 Y 轴",
 "MENU_AUDIO_HEADSET": "耳机",
 "MAINMENU_EXTRAS": "附加内容",
 "INFO_DIVERSIONS_STUNTS": "特技",
 "CELL_CALL_CALLING": "正在呼叫",
 "STATS_STATS_NONE": "暂无统计数据",
 "MAP_BLANK_DISTRICT": "%ls 区",
 "COMPLETION_MISSION_NUMBER": "任务 {0}",
 "REMOVE_BOOKMARK": "移除书签",
 "PAUSE_MAP_FILTER_NONE": "全部",
 "MAP_D_PERCENT_CONTROL": "%d%%%% 控制",
 "PAUSE_MAP_FILTER_FLASHPOINTS": "帮派行动",
 "CONTROLS_SIXAXIS_BRAKE": "六轴感应 加速/刹车",
 "CONTROL_DESC_FOOT_RADIAL": "道具栏",
 "MENU_STYLE_DIALOG_BODY": "已授予[format][color:yellow]风格等级 {0}[/format]。活动与小游戏中获得的声望现在额外增加[format][color:yellow]{1}%[/format]。",
 "INFO_COLLECTION": "收藏",
 "CONTROLS_SENSE_V": "垂直灵敏度",
 "COMPLETION_BONUS": "{0}%%% 奖励",
 "SAVELOAD_SAVE_GAME_DEVICE_FULL_OPEN_DEVICE_SELECTOR": "选择其他设备",
 "SAVELOAD_MUST_SIGN_IN": "要使用存档/读档功能，你必须先登录。",
 "CONTROLS_SETUP_VCAM_DIST": "载具视角距离",
 "CONTROL_DESC_VEH_HELI_SECONDARY_FIRE": "（直升机）副攻击",
 "RADIO_STATION_GENRE_KABRON": "拉丁城市与雷鬼顿",
 "INFO_MESSAGES_TITLE": "消息记录",
 "NO_MISSIONS_COMPLETED": "暂无完成任务",
 "INFO_UNLOCKABLES_ACTIVITIES": "活动",
 "MAINMENU_CREDITS": "制作人员",
 "HELP_TEXT_SKYDIVE_FLIP": "按 {JUMP_CLIMB_IMG} 翻身",
 "CONTROLS_DESC_BLOCK": "格挡",
 "PAUSE_MAP_FILTER_CRIBS": "据点",
 "INFO_UNLOCKABLES_HEALTH": "生命值",
 "INFO_MESSAGES": "消息记录",
 "CONTROLS_SETUP_FOOT_SCHEMES": "步行操作方案",
 "CONTROL_DESC_FOOT_SEL_WPN": "选择武器",
 "CELL_HEADER_ACTIVATED": "已启用",
 "MENU_DISPLAY_SUBTITLES": "字幕",
 "MAINMENU_DOWNLOADS": "可下载内容",
 "INFO_DIVERSIONS_TITLE": "小游戏",
 "CONTROL_DESC_FOOT_PICKUP": "（按住）拾取武器/物品",
 "CELL_VEHICLE_DIALOG_REPAIRS_BODY": "要花 ${0} 修理并取回你的载具吗？",
}
lines = open(SCH, encoding="utf-8").read().replace("\r\n", "\n").split("\n")
out, seen = [], set()
for ln in lines:
    m = re.match(r'^\s*"([^"]+)":\s*"(.*)"\s*$', ln)
    if m and m.group(1) in T:
        k = m.group(1); out.append('"%s": "%s"' % (k, T[k])); seen.add(k)
    else:
        out.append(ln)
open(SCH, "w", encoding="utf-8").write("\n".join(out) + "\n")
print("written", len(T), "; lines", len(out))
