# -*- coding: utf-8 -*-
# Phase B: platform_pc 未译占位补译（剪辑器/按键/图形选项 UI；纯图片 BTN_* 与路径键跳过保留）
import re, os
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCH = os.path.join(BASE, "schinese", "platform_pc_us.txt")
T = {
 "PC_EXPORT_LOCK_HINT": "在此摄像机区域内锁定摄像机的运动",
 "PC_CHARACTER_MODEL": "角色模型",
 "PCACTION_MAP": "显示地图",
 "PCACTION_SPRINT": "冲刺",
 "PCACTION_CONSUME_UP": "向上使用物品",
 "MAINMENU_ONLINE_GAME": "在线",
 "PC_W_RAINY": "雨天",
 "PC_WEATHER": "天气",
 "PC_CM_TRACKING": "跟随追踪",
 "PC_CM_FOLLOW_WATCH": "跟随观察",
 "PC_REWIND_HINT": "重新加载并回卷到开头",
 "PC_CAMERA_UNLOCKED": "摄像机已解锁",
 "PCACTION_WEAPON_4": "武器 4",
 "MENU_CONTROLLER_SCHEMES": "操作键位图",
 "PLT_MENU_DISPLAY_MODE": "显示模式",
 "PCACTION_RADIO_NEXT": "下一个电台",
 "CBA_GAC_TAKE_SCREENSHOT": "   社区截图",
 "PLT_MENU_HIGH_DX10_ONLY": "高（DX10 或以上）",
 "PC_EXIT_EXPLANATION": "退出电影剪辑器？未保存的修改将全部丢失。",
 "HUD_HOLD_DPADUP_PARTY_DISMISS": " 解散队伍",
 "CBA_VDC_TANK_FIRE_SECONDARY": "   发射武器 2",
 "COOP_JOIN_CHEAT": "你的合作队友正在使用作弊。之后新建的存档都会默认开启作弊。\\n自动存档已停用，你也无法再获得任何成就。",
 "PC_TOD_DEFAULT": "默认",
 "PC_CAM_MODE": "摄像机模式",
 "PAUSE_MENU_RECORD_MODE": "录制电影片段",
 "PC_ADVANCED_MODE_HINT": "允许使用更高级的剪辑手法",
 "PCACTION_JUMP": "跳跃",
 "PC_DOF_WIDE": "广角",
 "PC_EDIT_WARNING": "警告",
 "PC_SHOW_KEYS": "显示按键",
 "HUD_REPLACE_BLANK_WITH_BLANK_MESSAGE": "将 %ls 与 %ls 互换",
 "PCACTION_ACCELERATE": "加速",
 "PCACTION_CONSUME_RIGHT": "向右使用物品",
 "PLT_ANISOTROPIC_SIXTEEN": "各向异性 16X",
 "PC_PROPS_EXIT_HINT": "关闭属性对话框",
 "PC_UNBOUND_KEY": "未绑定",
 "PLT_MENU_STANDARD": "标准",
 "MULTI_MENU_SYSLINK": "局域网游戏",
 "PC_CAM_MODE_HINT": "此摄像机区域内摄像机的行为方式",
 "PCACTION_WEAPON_1": "武器 1",
 "OPTIONS_MENU_AUTO_DETECT_DESC": "这会用默认设置替换你的当前设置，并根据你的显卡选择一套性能预设。确定要这样做吗？",
 "PLT_MENU_DISPLAY_3": "第三屏",
 "PLT_MENU_AUDIO_VOICE_ENABLE": "语音聊天",
 "PC_EASE_HINT": "在混合动画类型之间循环切换",
 "PC_DELETE_CZ_HINT": "删除当前摄像机区域",
 "MULTI_GAMETYPE_1": "局域网游戏",
 "PC_TOD_NOON": "正午",
 "PC_TOD": "时段",
 "PC_GS_PEOPLE": "人群",
 "PC_POSITION_CAMERA_HINT": "使用操作键摆放摄像机",
 "BTN_LTHUMB_TXT": "左摇杆",
 "PC_OUTPUT_ONLY": "仅显示输出",
 "PC_GS_PLAYER": "玩家",
 "PC_CM_FOLLOW": "跟随",
 "PC_CAMERA_LOCKED": "摄像机已锁定",
 "PC_W_CLEAR": "晴朗",
 "PC_CAMERA_ZONE": "摄像机区域",
 "PC_ZT_BLEND": "混合",
 "PC_SAVE_HINT": "保存剪辑修改",
 "PC_COPY_NEXT_HINT": "基于下一个区域创建新的摄像机区域",
 "PCACTION_STRAFE_RIGHT": "向右平移",
 "PC_DOF": "景深",
 "RECORD_MODE_WARNING_TEXT": "录制电影片段将停用全部任务、活动、商店与游戏内音乐，直到你返回主菜单。要开始录制电影片段吗？",
 "PC_HIDE_KEYS": "隐藏按键",
 "PCACTION_WEAPON_5": "武器 5",
 "PCACTION_ATTACK_SECONDARY": "次要攻击",
 "CBA_OFC_JUMP_CLIMB": "   跳跃/攀爬",
 "PC_ROTATION_SENSITIVITY": "旋转灵敏度",
 "PC_SLOWMO": "回放速度",
 "PC_EDIT_PROPS_HINT": "显示摄像机区域属性对话框",
 "PC_ADDITIONAL_PROPS": "其他属性",
 "PC_NEW_ZONE": "新建区域",
 "PLT_MENU_ASPECT_TOOLTIP": "宽高比只能在主菜单中切换",
 "PC_CM_DEFAULT": "默认",
 "PC_COPY_CURRENT": "复制当前",
 "BTN_RTHUMB_TXT": "右摇杆",
 "PCACTION_BACKWARD": "向后移动",
 "CBA_VDC_PLANE_ROLL_TURN_SELECT2": "   偏航覆盖",
 "PLT_MENU_PAUSE_FOCUS_TOOLTIP": "游戏失去焦点时自动暂停",
 "PC_ROTATION_SENSITIVITY_HINT": "摄像机旋转灵敏度",
 "PCACTION_ATTACK_PRIMARY": "主要攻击",
 "PLT_QUIT_GAME_WARNING": "确定要退出到桌面吗？",
 "PC_TOD_NIGHT": "夜晚",
 "PC_TOD_HINT": "光照设置",
 "PC_DOF_CLOSEUP": "特写",
 "PC_OPTIONS_HINT": "显示常规选项对话框",
 "PC_SHOW_HUD": "显示 HUD",
 "PCACTION_HORN": "喇叭",
 "PC_PLAY_SLOW_HINT": "慢速回放录制内容",
 "PLT_MENU_REFLECTIONS": "   反射",
 "PLT_MENU_DISPLAY_2": "第二屏",
 "PC_CREATE_CHAR_HINT": "创建或导入新的角色模型",
 "PC_CAM_TILT": "摄像机俯仰",
 "HUD_PICK_UP_MESSAGE": "拾取  %ls",
 "PC_FOV": "视野",
 "PCACTION_FINE_AIM": "精准瞄准",
 "PC_DOF_DIST": "景深距离",
 "PLAYBACK_MODE_WARNING": "编辑电影片段",
 "PCACTION_BREAK": "手刹",
 "HUD_DUAL_WIELD_MESSAGE": "双持 %ls",
 "PLT_MENU_DISPLAY_PRESET": "预设",
 "PC_DOF_RANGE": "景深焦段范围",
 "PC_FOV_HINT": "摄像机视野",
 "PC_HANDYCAM_HINT": "手持摄像抖动强度",
 "PC_W_DEFAULT": "默认",
 "PC_WEATHER_HINT": "天气设置",
 "PC_DOF_ZOOM": "变焦",
 "PC_PAUSE_HINT": "暂停回放",
 "CAA_PLANE_PITCH_UP_DOWN_POS2": "   机头下压",
 "PLT_MENU_DISPLAY_1": "主屏",
 "SAVELOAD_CANNOT_SAVE_TO_FULL_DEVICE": "硬盘已满。\\n请选择其他位置保存。",
 "PC_VOICE_HINT": "开启/关闭全部语音",
 "PC_ZT_CUT": "硬切",
 "PC_EXPORT_LOCK": "导出锁定",
 "PC_EXPORT_SETTINGS": "导出设置",
 "PC_SELECT_TARGET_HINT": "使用操作键选择目标",
 "PC_AV_OPTIONS_HINT": "显示环境选项对话框",
 "PC_PLAY_FAST_HINT": "快速回放录制内容",
 "PCACTION_CONSUME_DOWN": "向下使用物品",
 "PCACTION_RELOAD": "装填武器",
 "PC_SM_FAST": "快速",
 "PC_CAMERA_DONE": "完成",
 "PLAYBACK_MODE_WARNING_TEXT": "这会停止当前录制，让你对其进行剪辑、保存并导出为视频。若要录制新的电影片段，你需要返回主菜单。要继续进入电影剪辑器吗？",
 "PCACTION_FORWARD": "向前移动",
 "CAA_WALK_TURN_LEFT_RIGHT_POS": "   向右移动",
 "PC_PLAY_HINT": "回放录制内容",
 "PC_EXPORTING_VIDEO": "正在导出视频",
 "PC_W_THUNDERSTORM": "雷雨",
 "PC_FADE_HUD": "淡出 HUD",
 "PCACTION_ACTION": "动作",
 "PC_DOF_RANGE_HINT": "景深焦段范围",
 "PC_COPY_NEXT": "复制下一个",
 "PC_EXPORT_EXPLANATION": "停止剪辑并开始导出为视频？",
 "PC_SLOWMO_HINT": "慢动作设置",
 "RECORD_MODE_WARNING": "录制电影片段",
 "PCACTION_RADIO_PREVIOUS": "上一个电台",
 "PCACTION_WEAPON_3": "武器 3",
 "PC_EDIT_PROPERTIES": "编辑属性",
 "PCACTION_WEAPON_6": "武器 6",
 "PLT_MENU_SHADOW_DETAIL": "   阴影细节",
 "PC_OPTIONS_EXIT_HINT": "关闭选项对话框",
 "PRESS_ANY_KEY_TEXT": "按下任意新按键，或按 ESC 取消。",
 "PCACTION_RADIAL_MENU": "环形菜单",
 "PC_OPTIONS": "选项",
 "PC_ZONE_TYPE": "区域类型",
 "PC_CZ_EXIT_HINT": "关闭摄像机区域对话框",
 "CBA_VDC_PLANE_FIRE_SECONDARY": "   发射武器 2",
 "PLT_TRILINEAR": "三线性",
 "PC_LOAD_CHAR": "载入默认",
 "PC_SM_NORMAL": "正常",
 "PC_DOF_DIST_HINT": "景深距离",
 "PCACTION_PAUSE": "暂停菜单",
 "CAA_PLANE_ROLL_LEFT_RIGHT_NEG2": "   向左滚转",
 "PC_VOICE": "语音",
 "PC_SHOW_KEYS_HINT": "显示剪辑快捷键",
 "PC_EDIT_EXPLANATION": "你即将剪辑一个非活动摄像机区域的摄像机。当前的摄像机位置将覆盖之前的位置。",
 "PCACTION_LOOK_RIGHT": "向右看",
 "PC_TOD_MORNING": "早晨",
 "PC_GS_BACKGROUND": "背景",
 "PLT_MENU_DISPLAY_4": "第四屏",
 "SAVELOAD_SAVE_GAME_DEVICE_FULL_EXPOSITION": "硬盘剩余空间不足，无法完成存档。",
 "PC_MOVEMENT_SENSITIVITY_HINT": "摄像机移动灵敏度",
 "PC_CONFIRM_EXIT": "确认退出",
 "PCACTION_WEAPON_8": "武器 8",
 "PCACTION_CROUCH": "蹲下",
 "MAINMENU_SYSLINK": "局域网游戏",
 "PC_HIDE_HUD": "隐藏 HUD",
 "PRESS_ANY_KEY_CAPTION": "按下新按键",
 "PCACTION_CONSUME_LEFT": "向左使用物品",
 "PCACTION_WEAPON_2": "武器 2",
 "PC_AV_EXIT_HINT": "关闭环境对话框",
 "PC_EXIT_HINT": "退出剪辑编辑器",
 "PCACTION_REVERSE": "刹车/倒车",
 "PLT_MENU_MINIMAP_VIEW_TOOLTIP": "小地图相对玩家朝向的旋转方式",
 "PC_HANDYCAM": "手持摄像",
 "PC_POSITION_CAMERA": "摆放摄像机",
 "PC_SM_VERY_SLOW": "极慢",
 "PC_CAMERA_DONE_HINT": "关闭对话框",
 "PC_GREEN_SCREEN": "绿幕",
 "MENU_HIGH": "高",
 "PC_MOVEMENT_SENSITIVITY": "移动灵敏度",
 "PC_CM_FOLLOW_LOOK": "跟随查看",
 "PC_SOUNDFX": "音效",
 "PAUSE_MENU_PLAYBACK_MODE": "编辑电影片段",
 "HUD_DROP_ITEM_MESSAGE": "丢弃 %ls",
 "PCACTION_STRAFE_LEFT": "向左平移",
 "PC_ADVANCED_MODE": "高级模式",
 "PC_SHOW_HUD_HINT": "切换界面透明度",
 "PC_CONFIRM_EXPORT": "确认导出",
 "HUD_PICKUP_HAVOK_WEAPON_MESSAGE": "拾取 %ls",
 "DPAD_LR_TXT": "方向键左/右",
 "PC_DOF_HINT": "景深类型 - 影响距离与焦段范围",
 "PC_AUDIO_TOGGLES": "音频",
 "HUD_PICKUP_UNNAMED_OBJECT": "拾取",
 "PCACTION_LOOK_LEFT": "向左看",
 "CAA_TANK_DRIVE_FORWARD_BACKWARD_POS": "   向前行驶",
 "PC_OUTPUT_ONLY_HINT": "导出时隐藏时间轴等信息",
 "PLT_MENU_TEXTURE_FILTER_MODE_TOOLTIP": "越高越好，但速度越慢",
 "MENU_LOW": "低",
 "PLT_MENU_SETUP_MIC": "设置麦克风",
 "MENU_OPTIONS_CLIP_SELECT": "电影片段",
 "PC_SM_SLOW": "慢速",
 "PC_GS_PLAYER_HINT": "切换玩家渲染",
 "PC_SELECT_TARGET": "选择目标",
 "DPAD_TXT": "方向键",
 "PC_EXPORT_HINT": "将片段导出为视频",
 "PCACTION_GRAB_HUMAN": "抓取人质",
 "PLT_MENU_DISPLAY_MODE_TOOLTIP": "全屏、窗口或无边框",
 "PLT_MENU_TEXTURE_FILTER_MODE": "   过滤模式",
 "MAINMENU_MACHINIMA_MODE": "编辑电影片段",
 "PC_COPY_CURRENT_HINT": "基于当前区域创建新的摄像机区域",
 "MENU_ULTRA": "极致",
 "PCACTION_WEAPON_7": "武器 7",
 "PC_LOAD_CHAR_HINT": "载入默认角色模型",
 "PC_GS_VEHICLES_HINT": "切换载具渲染",
 "PC_PROPS": "属性",
 "PC_CAM_TILT_HINT": "摄像机俯仰",
}
lines = open(SCH, encoding="utf-8").read().replace("\r\n", "\n").split("\n")
out, seen = [], set()
for ln in lines:
    m = re.match(r'^\s*"([^"]+)":\s*"(.*)"\s*$', ln)
    if m and m.group(1) in T:
        k = m.group(1); out.append('"%s": "%s"' % (k, T[k])); seen.add(k)
    else:
        out.append(ln)
open(SCH, "w", encoding="utf-8").write("\n".join(out) + "\n")
print("written", len(T), "; lines", len(out))
