# -*- coding: utf-8 -*-
"""术语/专名一致性扫描：original EN 命中 token 的条目，若 zh(含CJK) 不含定名/豁免变体则列出。
只读。豁免：整条保留英文(zh 基本为 ASCII)。"""
import re, io, sys, glob, os, json
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ORIG = os.path.join(ROOT, "original"); SCH = os.path.join(ROOT, "schinese")
LINE_RE = re.compile(r'^"((?:[^"\\]|\\.)*)"\s*:\s*"((?:[^"\\]|\\.)*)"\s*$')
def load(p):
    d={}
    for ln in open(p, encoding="utf-8"):
        m = LINE_RE.match(ln.rstrip("\n"))
        if m: d[m.group(1)] = m.group(2)
    return d
def hasCJK(s): return any('\u4e00'<=c<='\u9fff' for c in s)

# token -> (定名, 豁免变体list)
T = {
 "shaundi": ("肖恩蒂", ["肖恩蒂","肖恩迪"]),
 "shaundi's loft": ("肖恩蒂的阁楼", []),
 "kinzie": ("金吉", ["金吉","金茜"]),
 "kinzie's warehouse": ("金吉的仓库", []),
 "steelport": ("钢埠", []),
 "stilwater": ("斯蒂尔沃特", []),
 "stilwater u": ("斯蒂尔沃特大学", []),
 "stilwater butcher": ("斯蒂尔沃特屠夫", []),
 "the syndicate": ("辛迪加", []),
 "syndicate": ("辛迪加", []),
 "morningstar": ("晨星帮", ["晨星帮"]),
 "phillipe loren": ("菲利普·洛伦", ["菲利普"]),
 "killbane": ("杀霸", ["杀霸","杀神"]),
 "eddie pryor": ("埃迪·普赖尔", ["埃迪·普赖尔","埃迪·普里奥"]),
 "angel de la muerte": ("死神安吉尔", ["死神安吉尔"]),
 "matt miller": ("马特·米勒", ["马特·米勒"]),
 "kiki dewynter": ("琦琦·德温特", ["琦琦","琪琪"]),
 "kiki": ("琦琦·德温特", ["琦琦","琪琪","琦琦·德温特"]),
 "viola": ("薇奥拉", ["薇奥拉","维奥拉"]),
 "oleg kirrlov": ("奥列格·基尔洛夫", ["奥列格"]),
 "zimos": ("齐莫斯", ["齐莫斯"]),
 "cyrus temple": ("赛勒斯·坦普尔", ["赛勒斯"]),
 "kia": ("琪亚", ["琪亚","琪雅"]),
 "monica hughes": ("莫妮卡·休斯", ["莫妮卡"]),
 "jane valderama": ("简·瓦尔德拉玛", ["简·瓦尔德拉玛","简·瓦尔德拉马"]),
 "burt reynolds": ("伯特·雷诺兹", ["伯特·雷诺兹"]),
 "murderbrawl": ("屠杀格斗", ["屠杀格斗","屠杀乱斗","谋杀乱斗","杀戮乱斗"]),
 "nyte blayde": ("夜刃", ["夜刃"]),
 "gangstas in space": ("太空黑帮", ["太空黑帮","太空帮"]),
 "professor genki": ("元气博士", ["元气博士","元气教授","元气"]),
 "genkibowl": ("元气杯", ["元气杯","吉尼斯碗"]),
 "sad panda skyblazing": ("忧郁熊猫飞天", ["忧郁熊猫飞天"]),
 "sad panda": ("忧郁熊猫", ["忧郁熊猫","悲伤熊猫"]),
 "verminator": ("鼠辈终结者", ["鼠辈终结者","害虫终结者"]),
 "sexy kitten": ("性感小猫", ["性感小猫"]),
 "yarnie": ("毛线球", ["毛线球","亚妮"]),
 "yarnball": ("毛线球", ["毛线球"]),
 "cheapy": ("抠抠", ["抠抠","廉价哥"]),
 "money shot": ("一击命中", ["一击命中","金钱射击"]),
 "the deckers": ("赛博帮", ["赛博帮","迪克帮"]),
 "decker": ("赛博帮", ["赛博帮","迪克帮","迪克","赛博"]),
 "the luchadores": ("摔跤手帮", ["摔跤手帮","摔角手","摔跤手"]),
 "luchador": ("摔跤手帮", ["摔跤手帮","摔角手","摔跤手"]),
 "henry steel mills": ("亨利米尔斯钢铁厂区", ["亨利米尔斯钢铁"]),
 "henry mills": ("亨利米尔斯", ["亨利米尔斯","亨利·米尔斯"]),
 "rosen oaks": ("罗森橡树区", ["罗森橡树"]),
 "the grove": ("格罗夫区", ["格罗夫"]),
 "brickston": ("布里斯顿区", ["布里斯顿"]),
 "point pryor": ("普赖尔角", ["普赖尔角"]),
 "new baranec": ("新巴拉内克", ["新巴拉内克"]),
 "camano place": ("卡马诺广场", ["卡马诺"]),
 "carver island": ("卡弗岛", ["卡弗岛"]),
 "new colvin": ("新科尔文", ["新科尔文"]),
 "salander": ("萨兰德", ["萨兰德"]),
 "sunset park": ("落日公园", ["落日公园"]),
 "espina": ("埃斯皮纳", ["埃斯皮纳"]),
 "loren square": ("洛伦广场", ["洛伦广场"]),
 "bridgeport": ("桥港区", ["桥港区"]),
 "burns hill": ("伯恩斯山", ["伯恩斯山"]),
 "yearwood": ("厄尔伍德", ["厄尔伍德","伊尔伍德"]),
 "ashwood": ("灰木区", ["灰木"]),
 "magarac island": ("马加拉奇岛", ["马加拉奇"]),
 "thermopylae": ("温泉关", ["温泉关"]),
 "whored mode": ("妓望工程", ["妓望工程"]),
 "trail blazing": ("烈火流星", ["烈火流星","火烧特技","引火烧身"]),
 "cyber blazing": ("赛博流星", ["赛博流星"]),
 "tiger escort": ("老虎护驾", ["老虎"]),
 "ho traffic": ("皮肉生意", ["皮肉生意"]),
 "trafficking": ("黑货押运", ["黑货押运"]),
 "insurance fraud": ("碰瓷索赔", ["碰瓷索赔","保险诈骗","保险欺诈"]),
 "guardian angel": ("天使护卫", ["天使护卫","守护天使"]),
 "heli assault": ("武直突击", ["武直突击","直升机突袭"]),
 "phone phreak": ("电话飞客", ["电话飞客"]),
 "pub crawl": ("酒吧巡游", ["酒吧巡游"]),
 "high times": ("醉生梦死", ["醉生梦死"]),
 "eye of the tiger": ("虎之眼", ["虎之眼"]),
 "zombie uprising": ("丧尸暴动", ["丧尸暴动"]),
 "gang operation": ("帮派行动", ["帮派行动"]),
 "stronghold": ("根据地", ["根据地"]),
 "saints hq": ("圣徒总部", ["圣徒总部"]),
 "safeword": ("安全词", ["安全词"]),
 "rim jobs": ("边缘工坊", ["边缘工坊","菊部改装","边缘车行","轮毂工坊"]),
 "friendly fire": ("队友火力", ["队友火力"]),
 "let's pretend": ("假装一下", ["假装一下"]),
 "nobody loves me": ("没人爱我", ["没人爱我"]),
 "image as designed": ("天生设计", ["天生设计","形象设计室","形象设计"]),
 "impressions": ("印象刺青", ["印象刺青"]),
 "rusty's needle": ("锈针纹身", ["锈针"]),
 "technically legal": ("法律边缘", ["法律边缘"]),
 "planet saints": ("圣徒星球", ["圣徒星球"]),
 "angel's casino": ("安吉尔的赌场", ["安吉尔"]),
 "smiling jacks": ("微笑杰克", ["微笑杰克"]),
 "gat mobile": ("盖特座驾", ["盖特座驾"]),
 "rondini's boat dock": ("龙迪尼船坞", ["龙迪尼"]),
 "cutter international": ("卡特国际机场", ["卡特"]),
 "saintsbook": ("圣徒簿", ["圣徒簿"]),
 "agnes": ("阿格尼丝", ["阿格尼丝","阿格尼斯"]),
 "dr. wang": ("王医生", ["王医生","王博士"]),
 "dj enigmus": ("伊尼格玛斯", ["伊尼格玛斯","伊尼格玛","恩尼格玛斯","恩尼格玛"]),
 "enigmus": ("伊尼格玛斯", ["伊尼格玛斯","伊尼格玛","恩尼格玛斯","恩尼格玛"]),
 "hess": ("赫斯", ["赫斯"]),
 "chandler": ("钱德勒", ["钱德勒"]),
 "dieter": ("迪特尔", ["迪特尔","迪特"]),
 "kirsten": ("柯尔斯滕", ["柯尔斯滕","克尔斯滕"]),
 "gorshin": ("戈尔欣", ["戈尔欣"]),
 "dealy": ("迪利", ["迪利"]),
 "blaize": ("布莱兹", ["布莱兹"]),
 "almonzo": ("阿尔蒙佐", ["阿尔蒙佐"]),
 "barry": ("巴里", ["巴里"]),
 "rasputin": ("拉斯普京", ["拉斯普京","拉普斯汀"]),
 "smoov": ("斯穆夫", ["斯穆夫"]),
 "steiner": ("斯坦纳", ["斯坦纳","施泰纳","斯泰纳"]),
 "grigor": ("格里戈尔", ["格里戈尔"]),
 "dickson": ("迪克森", ["迪克森"]),
 "clovis": ("克洛维斯", ["克洛维斯"]),
 "ulysses": ("尤利西斯", ["尤利西斯"]),
 "johnny gat": ("强尼·盖特", ["强尼·盖特","强尼·盖","盖特"]),
 "gat": ("盖特", ["盖特"]),
 "johnny tag": ("强尼·泰格", ["强尼·泰格","约翰尼·塔格","强尼·塔格"]),
 "josh birk": ("乔什·伯克", ["乔什·伯克","乔希·伯克"]),
 "tammy tolliver": ("塔米·托利弗", ["塔米·托利弗","塔米·托利佛"]),
 "mr. zhen": ("郑先生", ["郑先生"]),
 "kwilanna": ("奎拉娜", ["奎拉娜"]),
 "brutella": ("猛男芭比", ["猛男芭比"]),
 "aisha brutella": ("艾莎猛男芭比", ["艾莎"]),
 "space brutina": ("太空猛女", ["太空猛女"]),
 "legal lee": ("律师李", ["律师李"]),
 "penthouse pets": ("阁楼宝贝", ["阁楼宝贝"]),
 "freckle bitch's": ("雀斑婊子", ["雀斑婊子"]),
 "wondermart": ("沃德玛特", ["沃德玛特"]),
 "eromenos museum": ("埃罗墨诺斯博物馆", ["埃罗墨诺斯"]),
 "skeeters": ("斯基特斯", ["斯基特斯"]),
 "kabana": ("卡巴纳", ["卡巴纳"]),
 "ultor": ("乌托尔", ["乌托尔"]),
 "pierce": ("皮尔斯", ["皮尔斯"]),
 "the brotherhood": ("兄弟会", ["兄弟会"]),
 "ronin": ("罗宁帮", ["罗宁帮","罗宁"]),
 "sons of samedi": ("萨梅迪之子", ["萨梅迪之子"]),
 "maero": ("马埃罗", ["马埃罗"]),
 "shaundi's loft": ("肖恩蒂的阁楼", []),
 "angel's gym": ("安吉尔的健身房", []),
 "zimos' pad": ("齐莫斯的宅子", []),
 "nuke plant": ("核电站", ["核电站","核电厂"]),
 "ocean loft": ("海洋阁楼", []),
 "the penetrator": ("穿透者", ["穿透者"]),
 "apoco-fists": ("末日神拳", ["末日神拳"]),
 "d4th blossom": ("D4TH 花瓣", ["D4TH"]),
 "mcmanus 2015": ("麦克马纳斯 2015", ["麦克马纳斯"]),
 "ka-1 kobra": ("KA-1 眼镜蛇", ["眼镜蛇"]),
 "k-8 krukov": ("K-8 库鲁科夫", ["库鲁科夫"]),
 "as3 ultimax": ("AS3 终极者", ["终极者"]),
 "sa-3 airstrike": ("SA-3 空袭呼叫", ["空袭"]),
 "cyber blaster": ("赛博冲击枪", ["赛博冲击枪"]),
 "cyber buster": ("赛博克星", ["赛博克星"]),
 "viper laser rifle": ("蝰蛇激光步枪", ["蝰蛇"]),
 "reaper drone": ("死神无人机", ["死神无人机"]),
 "rc possessor": ("遥控夺取器", ["遥控夺取器"]),
 "satchel charges": ("炸药包", ["炸药包"]),
 "shock hammer": ("电击锤", ["电击锤"]),
 "sonic boom": ("音爆", ["音爆"]),
 "s3x hammer": ("S3X 大锤", ["S3X"]),
 "pimp slap": ("老鸨巴掌", ["老鸨巴掌"]),
 "bootlegger": ("私酒贩", ["私酒贩"]),
 "attrazione": ("阿特拉齐奥内", ["阿特拉齐奥内"]),
 "kaneda": ("金田", ["金田"]),
 "kenshin": ("剑心", ["剑心"]),
 "peterliner": ("彼得莱纳", ["彼得莱纳"]),
 "widowmaker": ("寡妇制造者", ["寡妇制造者"]),
 "estrada": ("埃斯特拉达", ["埃斯特拉达"]),
 "nocturne": ("夜曲", ["夜曲"]),
 "gravedigger": ("掘墓人", ["掘墓人"]),
 "n-forcer": ("N-FORCER", ["N-FORCER","N-FORCE"]),
 "oppressor": ("压迫者", ["压迫者"]),
 "peacemaker": ("和平使者", ["和平使者"]),
 "quasar": ("类星体", ["类星体"]),
 "neuron": ("神经原", ["神经原","神经元"]),
 "halberd": ("戟", ["戟"]),
 "compensator": ("补偿者", ["补偿者"]),
 "sovereign": ("君临", ["君临"]),
 "longhauler": ("长途霸主", ["长途霸主"]),
 "mixmaster": ("搅拌大师", ["搅拌大师"]),
 "daedalus": ("代达罗斯号", ["代达罗斯"]),
 "broken shillelagh": ("断木棍酒吧", ["断木棍"]),
 "condor": ("秃鹫号", ["秃鹫"]),
 "tempress": ("妖姬", ["妖姬"]),
 "fuzz": ("警况", ["警况"]),
}

hits=[]
for fp in sorted(glob.glob(os.path.join(ORIG,"*_us.txt"))):
    pref=os.path.basename(fp)[:-len("_us.txt")]
    org=load(fp); sch=load(os.path.join(SCH, pref+"_us.txt"))
    for k in org:
        ov=org[k]; sv=sch.get(k)
        if not sv or not hasCJK(sv): continue
        olo=ov.lower()
        for tok,(canon,alts) in T.items():
            if re.search(r'(?<![a-z0-9])'+re.escape(tok)+r'(?![a-z0-9])', olo):
                ok = canon in sv or any(a in sv for a in alts)
                if not ok:
                    hits.append((pref,k,tok,canon,ov[:70],sv[:70]))
print('HITS', len(hits))
import collections
c=collections.Counter(h[2] for h in hits)
for tok,n in c.most_common(): print('TOKEN',tok,n)
for h in hits:
    print('%s | %s | %s | %s | EN=%s | ZH=%s'%(h[0],h[1],h[2],h[3],h[4],h[5]))
