# -*- coding: utf-8 -*-
# activity 人工翻译批2(末批)
import re, os
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCH = os.path.join(BASE, "schinese", "activity_us.txt")
T = {
 "ACT_PIMPING_GET_CLOSER_TO_HOS": "靠近[format][color:green]姑娘[/format]",
 "ACT_VANDAL_TRUCK_BIG_SEMI_CAB_MSG": "半挂卡车",
 "ACT_VANDAL_AIRPLANE_MSG": "飞机",
 "ACT_PIMPING_RESCUE_PIMPS_REROUTE": "[format][color:green]姑娘[/format]们被带走了，快去救她们",
 "ACT_ESCORT_FAIL_CAR_DESTROYED": "你的车被摧毁了",
 "ACT_WHORED_ZOMBIE_CHAINSAW_FAIL": "火鸡也不会怕你。",
 "ACT_WHORED_SAUSAGE_FEST": "丰盛扎实的香肠供应。",
 "ACT_PIMPING_CONTACTS_COLON": "联络人：",
 "ACT_GUARDIAN_ANGEL_NAME": "天使护卫",
 "ACT_TRAFFIC_DEALER_WAITING": "[format][color:green]毒贩[/format]已准备好开车。",
 "ACT_HELI_LIBERATOR_ATTACK_INFORMATION_MESSAGE": "向[format][color:red]巴士[/format]射击以逼停它们",
 "ACT_ESCORT_SPOUSE_SPAWNED": "甩开[format][color:green]客户[/format]的[format][color:red]另一半[/format]",
 "ACT_FRAUD_BONUS_COOP_CHAIN": "连击奖励",
 "ACT_ESCORT_ALMOST_LOSE_MSG": "媒体快拍到足够的画面了",
 "ACT_ESCORT_OBJECTIVE_TEXT_01": "满足客户的一切需求",
 "ACT_FRAUD_VISIT_BONUS_AREA": "地图上特别标记的[format][color:teal]位置[/format]能让你获得额外肾上腺素",
 "ACT_FRAUD_HUD_MULT_X": "X",
 "ACT_VANDAL_SUMMARY_PEOPLE_KILLED": "杀死的人数",
 "ACT_HELI_PROTECTION_HUD_TEXT": "已完成拦截",
 "ACT_ESCORT_NEAR_MISS_MSG": "[format][color:green]客户[/format]要你连续获得 %d 次贴车险过",
 "ACT_FRAUD_FIELD_DIVIDER": "/",
 "ACT_PIMPING_RESCUE_KILL_PIMPS": "杀死[format][color:red]晨星帮[/format]成员并营救[format][color:green]姑娘[/format]",
 "ACT_HUMAN_TORCH_TITLE": "烈火流星关卡选择",
 "ACT_GUARDIAN_ANGEL_HELICOPTER_ATTACKER": "瞭望员发现有架[format][color:red]直升机[/format]正飞过来。",
 "ACT_FRAUD_NO_SCORE": "你在[format][color:teal]计分区[/format]外摔倒了，没有赚到钱",
 "ACT_FRAUD_MESSAGE_WITNESS_MULT_TYPE": "碰瓷目击纪录",
 "ACT_FRAUD_MESSAGE_DISTANCE_MULT_TYPE": "碰瓷距离纪录",
 "ACT_VANDAL_BONUS_WEAPON": "武器奖励",
 "ACT_TRAFFIC_POLICE_STING_DEALER_ARRESTED_4SEC": "4……",
 "ACT_PIMPING_YOU_NEED_MORE_CONTACTS": "你需要更多[format][color:green]联络人[/format]",
 "ACT_PIMPING_TRAP_SPRUNG_KILL_PIMPS": "有埋伏！在招募[format][color:green]姑娘[/format]之前先杀光所有[format][color:red]晨星帮[/format]成员。",
 "ACT_HELI_VAN_LOW_HEALTH_TEXT": "[format][color:green]你兄弟的车[/format]严重受损",
 "ACT_CHOP_SHOP_FAIL_TIME_MSG": "时间到了。",
 "ACT_VANDAL_PEDESTRIAN": "行人",
 "ACT_VANDAL_IN_DISTRICT_MSG": "用提供的武器摧毁物体、车辆和人来赚钱。",
 "ACT_HUMAN_TORCH_OBJECTIVE_MSG": "冲刺到终点的路上撞击并摧毁路人与车辆，赚取奖励时间",
 "ACT_FRAUD_ADRENALINE_READY": "肾上腺素模式已激活",
 "ACT_VANDAL_CAR_BIG_DOMESTIC_MSG": "大型车",
 "ACT_CLIENT_HASNT_COMPLETED": "（{CLIENT_NAME} 尚未完成）",
 "ACT_LEVEL_7": "第 7 关",
 "ACT_GUARDIAN_ANGEL_CAR_ATTACKER": "瞭望员发现有辆车正开过来。",
 "ACT_HELI_CHOPLIFTER_FULLY_LOADED_MESSAGE": "直升机已满载，把乘客送到[format][color:blue]安全处[/format]",
 "ACT_FRAUD_HITS_HUD": "撞击：",
 "ACT_ESCORT_LIMO_MSG": "开[format][color:green]车[/format]去接客户",
 "ACT_WHORED_OLD_SCHOOL": "没有冲刺，没有生命恢复；只有一把霰弹枪和你求生的意志。",
 "ACT_PIMPING_TRAP_SPRUNG_GET_HOS": "有埋伏！招募[format][color:green]姑娘[/format]并撤离。",
 "ACT_HELI_CONVOY_AIRPORT_DESTINATION_MESSAGE": "机场",
 "ACT_VANDAL_BONUS_STATIC_VEHICLE": "奖励：摧毁 %s  （+$%d）",
 "ACT_TRAFFIC_PROTECT_M": "在今天的送货中保护[format][color:green]毒贩[/format]",
 "ACT_PIMPING_VEHICLE_ROUTE_HO": "拦下[format][color:red]车辆[/format]并带走[format][color:green]姑娘[/format]",
 "ACT_HELI_ACTIVITY_BOMB_ESCAPE_MESSAGE": "你有 %d 秒时间逃离目标",
 "ACT_FRAUD_BONUS_WINDSHIELD_CANNON": "挡风玻璃炮弹奖励",
 "ACT_ESCORT_TIGER_RAGE_POWERSLIDE_MSG": "{HANDBRAKE_IMG} 漂移 %0.1f 秒来安抚老虎",
 "ACT_ESCORT_FAIL_CAR_SUBMERGED": "你把车开沉了",
 "ACT_VANDAL_TEAM_BONUS_MSG": "击杀 %ls 可获得奖励。",
 "ACT_ESCORT_CLIENT_MSG": "接上[format][color:green]客户[/format]",
 "ACT_WHORED_ZOMBIE_INFERNO": "丧尸会跑、会爆炸，还会把你点着。你的生命值也不会恢复。我知道，我们很坏。",
 "ACT_RUNNING_MAN_WAGER_TITLE": "翻倍下注？",
 "ACT_ESCORT_NAME": "护送",
 "ACT_EARNED_RESPECT": "你获得了 %d 点声望！",
 "ACT_VANDAL_STATION_WAGON_MSG": "旅行车",
 "ACT_FRAUD_CURRENT_HIT": "本次撞击：",
 "ACT_CHOP_NOT_WANTED": "这家店不想要那辆车。",
 "ACT_TORCH_FRENZY_INSTRUCTIONS": "在时间耗尽前烧掉所有标记目标。",
 "ACT_VANDALISM_TITLE": "大破坏关卡选择",
 "ACT_LEVEL_3": "第 3 关",
 "ACT_CHOP_SHOP_NAME": "拆车坊",
 "ACT_FRAUD_MESSAGE_CLIFF_MULT_TYPE": "碰瓷悬崖跳水纪录",
 "ACT_CHOP_SHOP_MODS_REQUIRED": "有些车需要特定的改装。",
 "ACT_VANDAL_SUMMARY_PEOPLE": "人数",
 "ACT_VANDAL_GOAL_MSG": "目标：",
 "ACT_TRAFFIC_PROTECT_F": "在今天的送货中保护[format][color:red]毒贩[/format]",
 "ACT_HELI_CHOPLIFTER_START_MESSAGE": "接上[format][color:green]圣徒[/format]们，把他们送到[format][color:blue]安全处[/format]",
 "ACT_TRAFFIC_POLICE_STING_UNCUFF_USE": "给毒贩松绑",
 "ACT_FRAUD_BONUS_COP_WITNESS": "警察目击奖励",
 "ACT_CHOP_REJECT_BURNING": "这家店不收着火的汽车！",
 "ACT_HUMAN_TORCH_NAME": "烈火流星",
 "ACT_GUARDIAN_ANGEL_CRITICAL_VEHICLE_DESTROYED_MESSAGE": "一辆逃亡车被摧毁了。",
 "ACT_VANDAL_STATIC_BONUS_SPORTS_CAR_MSG": "跑车奖励",
 "ACT_PIMPING_CAPTURED_CONTACT_DIED": "一名联络人死了，你还需要再找一个",
 "ACT_FRAUD_HIT": "撞击：",
 "ACT_VANDAL_LAUNCHER_MSG": "火箭筒",
 "ACT_VANDAL_NIGHTSTICK_MSG": "警棍",
 "ACT_VANDAL_BONUS_STATIC_WEAPON": "奖励：使用 %s  （+$%d）",
 "ACT_VANDAL_BONUS_STATIC_TEAM": "奖励：击杀 %s  （+$%d）",
 "ACT_ESCORT_SPAWNED_MSG": "甩掉跟踪你的新闻车",
 "ACT_ESCORT_ROADBLOCK_MSG": "前方有新闻车路障",
 "ACT_GUARDIAN_ANGEL_STARTING_HELP_TEXT": "用狙击步枪保护[format][color:green]劫匪[/format]。",
 "ACT_ESCORT_OUTRUN": "甩掉追你的人",
 "ACT_ESCORT_FAIL_CLIENT_DEAD": "客户被杀了",
 "ACT_FRAUD_IN_AREA": "在[format][color:teal]计分区[/format]移动前尽可能多赚钱",
 "ACT_ESCORT_FAIL_CLIENT_RUNOVER": "你碾到了客户",
 "ACT_ZOMBIE_LEVEL_CLEARED_FORMAT": "第 %d 波存活",
 "ACT_FRAUD_BEST_HIT_HUD": "最佳撞击：",
 "ACT_WHORED_SAUSAGE_FEST_FAIL": "早该尊重那块肉。",
 "ACT_LEVEL_5": "第 5 关",
 "ACT_PIMPING_FAIL_HOS_ALL_DIED": "太多姑娘死了，招募她们 {RECRUIT_DISMISS_IMG} 然后迅速逃离现场",
 "ACT_FRAUD_MESSAGE_PINBALL_MULT_TYPE": "碰瓷弹球车纪录",
 "ACT_FRAUD_BONUS_AREA": "区域奖励",
 "CHOP_CONVERTIBLE_ROOF": "敞篷车顶",
 "ACT_TORCH_FAIL_WATER": "你的衣服熄灭了，小心别靠近水",
 "ACT_GUARDIAN_ANGEL_START": "开始天使护卫",
 "ACT_FRAUD_BONUS_LUXURY_VEHICLE": "富人司机奖励",
 "ACT_RUNNING_MAN_INTRO_L_3": "在时间耗尽前通过摧毁目标、击杀敌人并离开竞技场赚取 $3,500。如果你连续快速摧毁物品，将获得连击奖励。",
 "ACT_VANDAL_PASSENGER": "乘客",
 "ACT_FRAUD_NO_TIME": "你没时间了。",
 "ACT_ESCORT_TIGER_RAGE_MINIGAME_MSG": "快！把老虎安抚下来！",
 "ACT_CHOP_SHOP_START": "开始拆车坊",
 "ACT_HELI_VAN_LIFE_TEXT": "车的生命",
 "TUT_TITLE_ACT_TANK_MAYHEM_HVT": "高价值目标",
 "ACT_HELI_TIMES_UP_FAILED_MESSAGE": "时间到",
 "ACT_FRAUD_TOTAL_MULTIPLIER": "总倍率：%.2fx",
 "ACT_FRAUD_BONUS_VEHICLE_EJECT": "跳车奖励",
 "ACT_HELI_PROTECTION_CATCH_UP": "你的[format][color:green]兄弟[/format]在等你",
 "ACT_GUARDIAN_ANGEL_BIKE_ATTACKER": "瞭望员发现有辆[format][color:red]摩托车[/format]正开过来",
 "ACT_ESCORT_CLIENT_REQUEST_MSG": "客户要你表演 %ls %ls",
 "ACT_PIMPING_OBJECTIVE_1": "招募 %d 名姑娘并把她们带回齐莫斯处",
 "ACT_HELI_SET_BOMB_CHARGES_MESSAGE": "安装炸药",
 "ACT_FRAUD_BONUS_CIVIL_VEHICLE": "民用车辆奖励",
 "ACT_CHOP_SHOP_VEHICLE_COUNT": "剩余车辆：%i",
 "ACT_ZOMBIE_LIMITED_USES": "明智地使用你的武器。你的使用次数有限。",
 "ACT_VANDAL_BONUS_VEHICLE": "载具奖励",
 "ACT_PIMPING_FAIL_KILLED_HO": "你杀了自己的姑娘",
 "ACT_FRAUD_MESSAGE_COPS_MULT_TYPE": "碰瓷警察目击纪录",
 "ACT_TORCH_TIME_ACCRUED": "奖励：",
 "ACT_HELI_DIVIDER_TEXT": "/",
 "ACT_ESCORT_COMPLETE_MSG": "干得好",
 "ACT_PIMPING_TITLE": "拐人救美关卡选择",
 "ACT_VANDAL_BONUS_MULTIPLIER": "奖励倍率：",
 "ACT_VANDAL_BAT_MSG": "棒球棒",
 "ACT_ESCORT_GETBACK_MSG": "回到[format][color:yellow]车[/format]上",
 "ACT_PIMPING_DRIVE_TO_CONTACT_LOCATION": "营救[format][color:green]联络人[/format]并把他们带回来",
 "ACT_ESCORT_SATISFIED_MSG": "把[format][color:green]客户[/format]放下",
 "ACT_HOSTAGE_START": "开始人质",
 "ACT_VANDAL_COP_CAR_OLD_4_DOOR_MSG": "警用巡逻车",
 "ACT_FRAUD_GO_TO_SCORING_AREA": "前往计分区",
 "ACT_CHOP_BRING_CAR": "弄辆车回来。",
 "ACT_VANDALISM_COMBO_NUMBER": "%i   ",
 "ACT_VANDAL_POLICE_MSG": "警察",
 "ACT_VANDAL_STATIC_BONUS_STANDARD_CAR_MSG": "标准轿车奖励",
 "ACT_TRAFFIC_POLICE_STING_DEALER_ARRESTED_3SEC": "3……",
 "ACT_FRAUD_MESSAGE_VEHICLE_MULT_TYPE": "碰瓷载具纪录",
 "ACT_CHOP_SHOP_FAIL_CARS_MSG": "丢失的车辆太多了。",
 "ACT_GUARDIAN_ANGEL_ZOOM_HELP_TEXT": "按 {SHOULDER_CAM_IMG} 进入精确瞄准模式。按 {ZOOM_IN_IMG}/{ZOOM_OUT_IMG} 拉近拉远镜头",
 "ACT_ESCORT_STRIPPER_MSG": "等舞女上车",
 "ACT_ESCORT_GETBACK_COUNT_MSG": "你有 %d 秒时间回到[format][color:yellow]车[/format]上",
 "ACT_TRAFFIC_POLICE_STING_START": "卧底行动！把[format][color:green]毒贩[/format]从警察手里救出来！",
 "ACT_TRAFFIC_OBJECTIVE_1_DRIVER": "开车把[format][color:green]毒贩[/format]送到客户那里",
 "ACT_HELI_TIMER_TEXT": "剩余时间",
 "ACT_ESCORT_FAIL_STRIPPER_DEAD": "舞女被杀了",
 "CHOP_STYLISH_RIMS": "时尚轮辋",
 "ACT_VANDAL_VEHICLE_PENALTY_MSG": "摧毁[format][color:red]%ls[/format]不会获得任何钱",
 "ACT_ZOMBIE_NAME": "丧尸暴动",
 "ACT_VANDAL_VAN_MINIVAN_MSG": "面包车",
 "ACT_TRAFFIC_BUYER_ATTACK": "买家正遭到攻击",
 "ACT_HELI_NAME": "武直突击",
 "ACT_HELI_CONVOY_BASE_MESSAGE": "在车队抵达 %s 前拦下它",
 "ACT_FRAUD_ADRENALINE_TAG": "肾上腺素：",
 "ACT_VANDAL_SUV_MSG": "SUV",
 "ACT_GUARDIAN_ANGEL_HUD_TIMER_MESSAGE": "时间",
 "CHOP_STYLISH_HOOD": "时尚引擎盖",
 "ACT_TRAFFIC_POLICE_STING_DEALER_ARRESTED_1SEC": "1……",
 "ACT_TRAFFIC_POLICE_STING_DEALER_ARRESTED": "毒贩被捕了",
 "ACT_PIMPING_TRAP_ATTACK_KILL_DECKERS": "你中计了！在招募[format][color:green]联络人[/format]之前先杀光所有[format][color:red]赛博帮[/format]成员。",
 "ACT_PIMPING_CAPTURED_HO_DIED": "你的一个姑娘死了，你还需要再找一个",
 "ACT_FRAUD_BONUS_DISTANCE": "直线距离奖励",
 "ACT_HELI_DISH_HUD_TEXT": "已摧毁卫星天线",
 "ACT_FRAUD_FIRST_VISIT_BONUS_STRING": "在这个奖励区内受伤将获得额外肾上腺素",
 "ACT_CHOP_SHOP_SEEK_CARS_MSG": "把所需车辆送到[format][color:green]拆车坊[/format]以赚取现金。",
 "ACT_ESCORT_TITLE": "护送关卡选择",
 "ACT_VANDAL_PISTOL_MSG": "手枪",
 "ACT_CHOP_SHOP_APPROACH_CAR_MSG": "追上那辆车并偷走它。",
 "ACT_VANDAL_STATIC_BONUS_LUXURY_CAR_MSG": "豪华车奖励",
 "ACT_ESCORT_OBJECTIVE_TEXT_02": "甩开媒体",
 "ACT_PIMPING_TRAP_ATTACK_GET_CONTACTS": "你中计了！招募[format][color:green]联络人[/format]并迅速撤离。",
 "ACT_HELI_TARGETS_TEXT": "已完成目标",
 "ACT_VANDAL_BOAT_MSG": "船只",
 "ACT_PIMPING_HOS_COLON": "姑娘：",
 "ACT_FRAUD_KILLED": "你因为杀人而失去了信誉。",
 "ACT_TRAFFICKING_START": "开始黑货押运",
 "ACT_VANDAL_CAR_COMPACT_MSG": "紧凑型车",
 "ACT_VANDAL_STATIC_BONUS_VAN_MSG": "面包车奖励",
 "ACT_FRAUD_BONUS_DISTRICT": "区域奖励",
}

lines = open(SCH, encoding="utf-8").read().replace("\r\n", "\n").split("\n")
out, seen = [], set()
for ln in lines:
    m = re.match(r'^\s*"((?:[^"\\]|\\.)*)":\s*"(.*)"\s*$', ln)
    if m and m.group(1) in T:
        out.append('"%s": "%s"' % (m.group(1), T[m.group(1)]))
        seen.add(m.group(1))
    else:
        out.append(ln)
miss = [k for k in T if k not in seen]
open(SCH, "w", encoding="utf-8").write("\n".join(out) + "\n")
print("written", len(T) - len(miss), "miss", miss)
