# -*- coding: utf-8 -*-
# hud 人工翻译批1
import re, os
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCH = os.path.join(BASE, "schinese", "hud_us.txt")
T = {
 "HOMIES_VTOL": "VTOL",
 "TUT_WHORED_D_YKANO": "Y.卡诺",
 "TUT_TITLE_DLC_MONEYSHOT": "TOGO-13",
 "SHOTGUN_POLICE": "AS3 终极",
 "PISTOL_POLICE": "KA-1 眼镜蛇",
 "SPECIAL_SNIPERRIFLE": "麦克马纳斯 2015",
 "RIFLE_GANG": "K-8 克鲁科夫",
 "PISTOL_GANG": "45 牧羊犬",
 "HUD_RESPECT_RANK_006": "守卫",
 "TUT_QUICK_KILL": "{CBA_OFC_HS_EXECUTE_IMG} 处决人盾",
 "HUD_PRESS_BACK_CANCEL_PERSISTENT": "再次按下 %ls 以清除 HUD",
 "UNL_HOMIE_HELI": "兄弟 - 直升机",
 "MISSION_COOP_CONFIRM_ACTIVITY": "正在与 %ls 确认开始活动",
 "TUT_ACT_GUARDIAN": "为你的联络人提供保护。",
 "PLAYER_CHOICE_M16_OPTION1_TITLE": "[format][color:Purple]接管一家载具制造商[/format]",
 "TUT_TITLE_NAG_CHANGE_CLOTHES": "更换服装",
 "TUT_CHARGE_WEAPON": "按住 {ATTACK_PRIMARY_IMG} 蓄力射击",
 "TUT_TITLE_RADIO_CONTROL": "电台控制",
 "WE_MOUNTED_GUN": "车载 .50 机枪",
 "FLASHPOINT_COMPLETE_DESC_1": "已摧毁",
 "CANT_USE_MECHANIC": "任务或活动期间无法自定义你的载具",
 "TUT_TITLE_MINIMAP_ICONS": "小地图图标",
 "ACHIEVE_SR3_BROMANCE_IN_THE_ROW": "兄弟情深",
 "HUD_RESPECT_RANK_008": "圣徒",
 "HOMIES_GREETING": "哟 %ls！近来如何？",
 "HUD_FINISH_BRUTE": "终结壮汉",
 "CS_TITLE_SURFACE_OF_MARS": "火星表面",
 "COMBAT_DAMAGE": "你造成了 %5.1f 点伤害！",
 "PLAYER_INCREASE_HEALTH": "你的生命值已提升",
 "TUT_TITLE_NITROUS": "氮气",
 "HUD_AMT_DEGREES": "{0}{TEMP_DEGREES}",
 "TUT_NAG_HUMAN_SHIELD": "记住：使用人盾 {ACTION_IMG} 能让你在战斗中活得更久",
 "SPECIAL_AIRSTRIKE": "SA-3 空袭",
 "WPNCAT_THROWN": "投掷",
 "MULTI_PRESS_AND_HOLD_BLANK_TO_HEAL": "按住 %ls 进行治疗",
 "UNL_DESC_CLOTHING_AVATAR": "动作捕捉服已添加到你的据点衣柜中",
 "UNL_SPRINT_2": "冲刺 - 提升 2",
 "TUT_TERRITORY": "你现在拥有这个街区。\\n每小时你会从中获得一笔小额收入，存入你的据点藏匿处。你还可以购买这个街区任意商店的股份，以获得额外的每小时收入。",
 "TUT_WHORED_Z_BDSM": "BDSM",
 "TUT_WHORED_D_STEELPORT_CONNECTION": "钢埠连线",
 "TUT_WHORED_MALLCOP": "商场保安",
 "TUT_TITLE_CRIB_WEAPONS": "武器库",
 "ACHIEVE_SR3_PORKCHOP_SANDWICHES": "猪排三明治",
 "ACHIEVE_SR3_AND_BOOM_GOES_THE_DYNAMITE": "炸药轰然作响",
 "SATELLITE_EXIT_GUIDED_MODE": "放弃导弹",
 "PLAYER_CHOICE_M19_OPTION2_BODY": "奖励：伯特·雷诺兹与特警兄弟",
 "HUD_HOURS_ABR": "小时",
 "TUT_TITLE_NP_CAR_CONTROLS": "载具操控",
 "GARAGE_CARS_ONLY": "你不能在这里存放这种载具",
 "STRONGHOLD_CANCEL_SUB_TEXT": "据点已取消",
 "TUT_TITLE_SECONDARY_FIRE": "副武器开火",
 "TUT_TITLE_STYLE_RANK": "风格等级",
 "ACHIEVE_SR3_BRIGHT_LIGHTS_BIG_CITY": "不夜大都市",
 "DIVERSIONS_RESPECT": "声望 {0}",
 "TUT_TITLE_NAG_GANG_CUSTOMIZE": "帮派自定义",
 "TUT_NP_HELI_WEAPON_CONTROLS": "{HELI_FIRE_PRIMARY_IMG} 发射机枪 \\n{HELI_FIRE_SECONDARY_IMG} 发射火箭",
 "FART_IN_A_JAR": "罐中臭屁",
 "UNL_DESC_CASH_FOR_RESPECT_2": "支付现金购买 8,000 点声望",
 "UNL_DESC_CRIB_NUKE": "伯恩斯山核反应堆现在是一座圣徒据点。在这里可以存取武器库、服装，并自定义你的帮派。",
 "TUT_CONTINUE_MSG": "按下 {PAUSE_MENU_IMG} 继续",
 "TUT_ACT_INTRO_SNATCH": "把妓女从施虐的皮条客手中安全救回。",
 "ACHIEVE_SR3_TUNE_IN_DROP_OFF": "调频收货",
 "HUD_TRIGGER_VEHICLE_REPAIR_PRICE": "支付 $%d 维修载具",
 "TUT_TITLE_ACT_TANK_MAYHEM": "坦克大破坏",
 "ACHIEVE_SR3_OW_MY_BALLS": "嗷，我的蛋蛋！",
 "ACTIVITY_COOP_START_MSG": "开始合作活动？",
 "TUT_NP_BOAT_CONTROLS": "{ACCELERATE_IMG} 加速 \\n{BRAKE_REVERSE_IMG} 倒车",
 "TUT_AIRPLANE_CONTROL_ALT": "{PLANE_ACCELERATE_IMG} 加速 \\n{PLANE_BRAKE_REVERSE_IMG} 刹车 + 倒车 \\n{PLANE_TURN_LEFT_IMG}/{PLANE_TURN_RIGHT_IMG} 翻滚",
 "ACHIEVE_SR3_YOURE_MY_HERO": "你是我的英雄！",
 "HUD_CONTINUE_TEXT": "%ls 继续",
 "HOMIES_GAINED_CASH": "你通过拉客赚取了 %ls 现金",
 "UNL_DESC_WEP_CYBERSPACE_CANNON": "在你的据点武器库中装备赛博破坏炮。",
 "TUT_TITLE_CHARGE_WEAPON": "蓄力武器",
 "TUT_RADIO_CONTROL": "{AUDIO_PLAYER_PREV_TRACK_IMG} / {AUDIO_PLAYER_NEXT_TRACK_IMG} 切换电台 \\n收听广播，或通过手机音乐界面 {MAP_MENU_IMG} 创建你自己的电台",
 "WPN_GENKI_DESCRIPT": "会唱歌、会爆炸、毛茸茸、还能控制心灵的章鱼。没错，控制心灵。我们是认真的。",
 "HUD_VEHICLE_DRIVE": "%s 加速，%s 刹车与倒车",
 "TUT_MINIMAP_ICONS": "这是你的小地图。\\n红点是敌人，蓝、红、绿方块是目标标记。\\n如果迷路了，跟着 GPS 前往最近的目标。",
 "ACHIEVE_SR3_OUCH": "哎哟。",
 "WPN_BLOWUPDOLL": "充气娃娃",
 "THEATER_PLAY_STRONGHOLD": "游玩据点",
 "TUT_TITLE_HELICOPTER_CONTROL": "直升机操控",
 "TUT_STORE_OWNERSHIP": "拥有房产会提供每小时收入，并在该处购物时享受折扣。",
 "SMG_AMMO": "冲锋枪弹药",
 "HUD_RESPECT_RANK_002": "盾卫",
 "HOMIES_WAS_BUSTED": "%ls 被捕了！",
 "UNL_DESC_PLAYER_HEALTH_4": "玩家生命值提升 100%%",
 "ACHIEVE_SR3_GANGSTAS_IN_SPACE": "太空黑帮……出击！",
 "HUD_COOL_OVERHEATED_MESSAGE": "冷却武器",
 "TUT_TITLE_COMBAT_GRENADES": "副手手雷",
 "ACHIEVE_SR3_MR_FURY_WOULD_BE_PROUD": "狂怒先生会为你骄傲",
 "HUD_WARP_TO_SHORE_MESSAGE_PLACEHOLDER": "传送回岸边",
 "TUT_WHORED_D_THE_RUNNING_DEAD": "行尸走肉",
 "ACHIEVE_SR3_SHAKE_AND_BAKE": "摇一摇烤一烤",
 "TUT_TITLE_CRUISE_CONTROL": "巡航控制",
 "baseball_bat": "棒球棒",
 "TUT_FINEAIM_0": "{SHOULDER_CAMERA_IMG} 缩放",
 "PLAYER_ABANDON_FOLLOWER": "你正在抛弃 %d 名[format][color:purple]随从[/format]",
 "UNL_UNLIMITED_AMMO_SMG": "弹药 - 冲锋枪 4",
 "TUT_NEW_MISSIONS": "{MAP_MENU_IMG} 接取新任务\\n当有新任务可用时，它们会显示在你的手机任务菜单中。",
 "ACHIEVE_SR3_JUMPED_IN": "入伙",
 "WPN_SMGGANG_DESCRIPT": "冲锋枪的街头版。完全升级后可发射燃烧弹。",
 "ACHIEVE_SR3_LOVE_HATE_RELATIONSHIP": "爱恨交织",
 "WPN_APOCOFIST": "末日拳",
 "SHOTGUN_STAG": "S3X 巨锤",
 "HUD_BONUS_CLOTHING": "服装加成",
 "GARAGE_CANT_STORE": "你不能把这辆载具存进车库",
 "WPN_RIFLEKILLSHOT_DESCRIPT": "适合在 500 码外送上“爱的轻抚”……而所谓“爱的轻抚”，我们指的是“爆头开花”。",
 "MAP_TOTAL_RESPECT": "总声望：%d",
 "ACHIEVE_SR3_TOWER_DEFENSE": "塔防",
 "WPN_TOILET": "马桶",
 "UNL_RESPECT_EURO_2": "声望加成",
 "MAP_STORENAME_UNKNOWN": "未知",
 "TUT_TITLE_SNIPER_UPGRADE": "狙击镜升级",
 "WPN_PROTOTYPE_GENERIC_DESCRIPT": "这是原型武器，如果你看到我，请告诉我",
 "HUD_FEET_ABR": "英尺",
 "TUT_MINIMAP": "左下角的小地图会沿最短的合法路线显示通往目标的 GPS 路径。",
 "ACHIEVE_SR3_EVERYTHING_IS_PERMITTED": "一切皆被允许",
 "FLASHPOINT_NAME": "帮派行动",
 "HUD_CANCEL_MISSION": "重试或退出任务",
 "HUD_MINUTES_ABR": "分",
 "HUD_CANCEL_STRONGHOLD": "重试或退出据点",
 "COMBAT_DISTANCE": "%.1f 米！",
 "TUT_TITLE_COLLECTION": "收集",
 "TUT_TITLE_HITMAN_NEW": "暗杀",
 "STUN_GUN": "电击枪",
 "WPNCAT_MELEE": "近战",
 "TUT_NAG_CRUISE_CONTROL": "记住：使用巡航控制 {CRUISE_CONTROL_B_IMG} 可以让你边射击边驾驶",
 "TUT_HOMIE_REVIVE": "如果随从失去全部生命值，你只有几秒钟时间赶到并救起他们。",
 "HUD_TRIGGER_DISABLED_ACT": "此活动期间你不能来这里",
 "MISSION_COOP_CONFIRM_STRONGHOLD": "正在与 %ls 确认开始据点",
 "TUT_WHORED_BEERMUSCLES": "巨型肌肉",
 "TUT_TITLE_CHOPSHOP": "偷车任务",
 "TUT_STORE_INTRO_SURGEON": "天生设计能让你改变外貌、嘲讽动作和赞美动作。",
 "ENTER_WATERCRAFT_MESSAGE": "进入船只",
 "HUD_CRUISE_CONTROL_ACTIVE_NEW": "[format][scale:1]{CRUISE_CONTROL_B_IMG}[/format] 巡航控制",
 "TUT_DIV_INTRO_STREAKING": "展示你的好身材来赚钱！",
 "TUT_TAUNTING": "{MENU_DP_LEFT_IMG} 嘲讽 \\n{MENU_DP_RIGHT_IMG} 赞美 \\n与人互动，通过嘲讽和击杀帮派成员来赚取声望。",
 "RESPECT_RANK_UP": "升级",
 "ACHIEVE_SR3_ONCE_BITTEN_BRAAAAAAAINS": "一朝被咬……脑脑脑脑脑",
 "ENTER_VEHICLE_PASSENGER_SEAT_MESSAGE": "%ls 进入载具乘客座",
 "TUT_STORE_INTRO_TATTOO": "纹身店能让你自定义角色。购买纹身可获得声望。",
 "HUD_RESPECT_RANK_004": "枪手",
 "HUD_KICK_DOOR_MESSAGE": "开门",
 "UNL_DESC_GARAGE_TANK": "在你的据点车库取回坦克。",
 "WPNCAT_PISTOL": "手枪",
 "TUT_WHORED_NUTSHOTS": "噢蛋蛋",
 "TUT_TITLE_IMPROVISED_WEAPONS": "临时武器",
 "TUT_TITLE_AUTOSAVE": "游戏自动存档",
 "TUT_ACT_INTRO_INS_FRAUD": "{PRATFALL_ALT_IMG} / {PRATFALL_IMG} 布娃娃摔\\n把你自己摔向汽车、物体和建筑物，以赚取更多保险理赔。",
 "CS_TITLE_STAG_HQ_PR_CENTER": "STAG 总部 - 公关中心",
 "WPN_RC_GUN_DESCRIPT": "能遥控全尺寸载具，何必还要玩小小的遥控车！",
 "FLASHPOINT_COMPLETE_TITLE": "帮派行动",
 "HOMIES_RANK_UP": "%ls 升级了！",
 "TUT_VEHICLE_TURRET": "{ATTACK_PRIMARY_IMG} 发射炮塔武器 \\n当你在带炮塔的载具中时。",
 "WPN_KBGLOVES_DESCRIPT": "杀霸那招毁灭性的招牌攻击，如今浓缩在一双手套里！",
 "HUD_HEALTH": "生命值",
 "CHOP_SHOP_DISPLAY_DISTRICT_UNKNOWN": "未知",
 "CS_TITLE_STILWATER": "斯蒂尔沃特",
 "HOMIES_DISMISSED": "%ls 已被遣散！",
 "UNL_FOLLOWER2": "帮派 - 随从 2",
 "TUT_WHORED_Z_10_CENTS": "找零 10 美分",
 "TUT_DRIVING_STUNTS": "特技驾驶能赚取声望。每种特技都会在即时挑战 HUD 中播报。",
 "TUT_TEMP_WEAPON": "这种武器使用次数有限，不能像常规武器那样随身携带。进入载具前必须丢弃它。",
 "TUT_TITLE_NOTORIETY_DECREASES": "恶名",
 "PLAYER_CHOICE_M22_OPTION1_BODY": "杀死杀霸，但肖恩蒂会死",
 "TUT_TITLE_EXPLORE": "领地所有权",
 "SATELLITE_MISSILES_LEFT": "导弹",
 "TUT_WHORED_D_31DAYS": "惊变31天",
 "TUT_DLC_GENKI_GUN": "{ATTACK_SECONDARY_IMG} 引爆章鱼\\n用元气章鱼击中路人会让他们站到你这边作战。章鱼可随时手动引爆。",
 "PLAYER_CHOICE_M13_OPTION1_BODY": "奖励：STAG 城市接管协助",
 "CHOP_SHOP_DISPLAY_DISTRICT_FREEWAY": "高速公路",
 "TUT_TITLE_STORE_INTRO_VEHICLE_DEALER": "载具经销店",
 "HUD_USE_PARACHUTE": "打开降落伞",
 "UNL_DESC_HOMIE_JOSH": "乔什可在你的手机“PHONE”菜单中找到。他会在战斗中协助圣徒。",
 "TUT_TITLE_JUMP_CLIMB": "跳跃/攀爬",
 "TUT_DIV_INTRO_BASE_JUMPING": "尽量落在离标记最近的位置以赚取声望。",
 "HUD_USE_LEFT_STICK_MESSAGE": "使用 {ANALOG_LS_IMG} 移动",
 "TUT_MIS_02_SKYDIVE_FLIP": "{ANALOG_LS_IMG} 移动\\n{ANALOG_RS_IMG} 视角\\n{SKYDIVE_FLIP_IMG} 上下翻转",
 "HUD_TRIGGER_DISABLED_MISSION": "此任务期间你不能来这里",
 "HUD_OPEN_DOOR_MESSAGE": "开门",
 "RIFLE_NG": "AR-55",
 "SATELLITE_FIRE_MISSILE": "无制导导弹",
 "HUD_MINUTES": "分钟",
 "UNL_SPRINT_4": "冲刺 - 提升 4",
 "TUT_TITLE_ACT_INTRO_HUMAN_TORCH": "火烧特技",
 "TUT_TITLE_ACT_INTRO_MAYHEM": "大破坏",
 "HOMIES_ANGRY_LEFT": "%ls 离开了你！",
 "UNL_DESC_NOTORIETY_COPS_1": "你的警方恶名衰减速度略微加快",
 "TUT_WHORED_A_AW_NUTS": "噢，蛋蛋",
 "TUT_WHORED_A_WELCOME": "锤子时间",
 "TUT_TITLE_ACTIVITY_COMPLETE": "活动完成",
 "USE_TRIGGER_DROP_BIKE": "放下摩托车",
 "TUT_WHORED_Z_START_YOUNG": "从小培养",
 "TUT_WHORED_D_WEENIE ROAST": "烤香肠",
 "TUT_TITLE_STORE_INTRO_SURGEON": "整容医生",
 "HUD_CANCEL_PERSISTENT": "清除 HUD",
 "TUT_WHORED_DRUNKENROCKETS": "醉汉火箭",
 "FORMAT_TIME_SECS": "{0} 秒",
 "TUT_WHORED_MINISNIPERS": "迷你狙击手",
 "PLAYER_CHOICE_M21_OPTION2_BODY": "奖励：末日拳武器",
}

lines = open(SCH, encoding="utf-8").read().replace("\r\n", "\n").split("\n")
out, seen = [], set()
for ln in lines:
    m = re.match(r'^\s*"((?:[^"\\]|\\.)*)":\s*"(.*)"\s*$', ln)
    if m and m.group(1) in T:
        out.append('"%s": "%s"' % (m.group(1), T[m.group(1)]))
        seen.add(m.group(1))
    else:
        out.append(ln)
miss = [k for k in T if k not in seen]
open(SCH, "w", encoding="utf-8").write("\n".join(out) + "\n")
print("written", len(T) - len(miss), "miss", miss)
