# -*- coding: utf-8 -*-
# 接管重译 mission：读 original/mission_us.txt 抽 KEY，逐条重写中文。
# 定名统一：肖恩蒂(Shaundi)/金吉(Kinzie)/安吉尔(Angel短称)/齐莫斯/杀霸；保留格式 token。
import re, os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCH = os.path.join(BASE, "schinese", "mission_us.txt")
ORG = os.path.join(BASE, "original", "mission_us.txt")

src = open(ORG, encoding="utf-8").read().replace("\r\n", "\n")
od = dict(re.findall(r'^\s*"([^"]+)":\s*"(.*)"\s*$', src, re.M))

T = {
 "m12_failure_suko_died": "薇奥拉阵亡！",
 "M08_OBJ_GO_UP_TO_BAR": "上到[format][color:location]酒吧[/format] ",
 "M06_FAILURE_ABANDON_HOMIE": "兄弟被抛下了！\\n圣徒可不能各自单飞！",
 "M04_OBJ_FIND_MECHANIC": "开车去[format][color:location]修车师傅[/format]那里",
 "m07_failure_angel_died": "安吉尔阵亡！",
 "MM_K_02_obj_goto_kinzie": "前往[format][color:location]金吉的藏身处[/format]",
 "M09_OBJ_FIND_THE_GIRLS": "找到[format][color:use]姑娘箱[/format]",
 "M17_OBJ_JAILBREAK": "救出你的[format][color:use]朋友[/format]",
 "M11_OBJ_DESTROY_STAG": "引起[format][color:kill]STAG[/format]的注意",
 "M11_OBJ_DISTRACT_STAG": "找到一处[format][color:location]STAG 基地[/format]",
 "M08_OBJ_SURVIVE_ASSAULT": "[format][color:defend]挺过[/format]第一波攻势",
 "M07_OBJ_FIND_KINZIE": "找到[format][color:location]金吉[/format]",
 "SH02_OBJ_SECURITY": "解除安保系统",
 "M16_TXT_ADV_SC_03": "你从壁架上取下火把，推开了门。眼前是一条幽暗的走廊，一路延伸向墨黑、阴森、深不见底的黑暗。你走了仿佛一个世纪那么久，这才发觉火把快要烧完了。\\n\\n你要怎么做？\\n\\n",
 "SH03_DIRECTIVE_ONE": "已入侵[format][color:location]上行链路[/format]",
 "m17_failure_shaundi_died": "肖恩蒂阵亡！",
 "M16_TXT_ADV_SC_00_CH2": "拿起火把",
 "M16_OBJ_GOTO_ANTI_VIRUS": "前往[format][color:location]反病毒区[/format]",
 "M13_OBJ_DEFEND_THE_SOUTH": "守住[format][color:defend]南侧[/format]",
 "M08_OBJ_FIND_SNIPER_RIFLE": "拿到[format][color:use]狙击枪[/format]",
 "M02_OBJ_OPEN_DOORS": "打开[format][color:location]货舱门[/format]",
 "M22_OBJ_CLEAR_ARMORY": "肃清[format][color:kill]军械库[/format]",
 "M08_OBJ_DESTROY_VEHICLES": "摧毁[format][color:kill]直升机[/format]",
 "M03_OBJ_GO_TO_WEAPON_STORE": "前往[format][color:location]友军火力[/format]",
 "M16_TXT_ADV_SC_06": "你继续往前走，向迪亚兹的31位神明祈祷火把千万别熄。幸好，它真没熄。前方黑暗渐渐让位于光亮，一抹暗淡的靛蓝光辉照亮了走廊深处。你听见一块巨石在岩壁上摩擦的声响。\\n\\n你要怎么做？\\n\\n",
 "M04_OBJ_GET_CAR": "上一辆[format][color:use]车[/format]",
 "STRONGHOLD_HUD_TITLE": "根据地",
 "m20_failure_no_tanks_to_you": "STAG 坦克全被摧毁！",
 "M13_OBJ_HELP_VIOLA": "救援[format][color:defend]薇奥拉[/format]",
 "M16_TXT_ADV_SC_08": "你感觉到一股邪到极致的气息正沿走廊逼近。你还在等，一块松动的石板就从天花板掉了下来。\\n\\n它砸在你头上，摔断了你的脖子。\\n\\n你死了。\\n\\n感谢游玩《龙与泪》——螺旋黑暗三部曲第一部\\n\\n",
 "M15_OBJ_DISABLE_THE_TRUCK": "打坏卡车[format][color:kill]车轮[/format]",
 "m13_failure_oleg_died": "奥列格阵亡！",
 "M08_OBJ_GET_TO_ROOF": "上到[format][color:location]屋顶[/format]",
 "M22_OI_KILLBANE_BODY_TEXT": "杀死杀霸，但肖恩蒂会死",
 "M14_LABEL_PLANTING_TRANSMITTER": "正在安放发射器",
 "M02_OBJ_CATCH_SHAUNDI": "接住[format][color:location]肖恩蒂[/format]",
 "M22_OBJ_PROCEED_UP_STATUE": "沿[format][color:location]雕像[/format]向上攀爬",
 "MSN_PROTO_SELECT_SATCHEL_DESC": "原型遥控炸弹，带有特殊纳米黏性涂层，能牢牢黏附在接触到的任何表面上。",
 "MM03_OBJ_KILL_FP": "铲除[format][color:kill]帮派行动点[/format]",
 "M22_UNTIE": "松绑",
 "M16_TXT_ADV_SC_00_CH3": "钻过洞口",
 "M14_ACTION_TRANSMITTER": "安放发射器",
 "M13_OBJ_ESCAPE": "从顶层公寓[format][color:location]跳下[/format]",
 "M07_OBJ_GO_TO_CLUB": "前往[format][color:location]BDSM 俱乐部[/format]",
 "M15_OBJ_GET_TO_THE_GARAGE": "前往[format][color:location]车库[/format]",
 "m09_failure_girls_heli": "姑娘们的直升机被摧毁了！\\n快干掉晨星帮，别让他们干掉你！",
 "m06_failure_shaundi_died": "肖恩蒂阵亡！",
 "M06_OBJ_TO_OLEG": "上[format][color:location]楼[/format]",
 "m02_failure_shaundi_died": "肖恩蒂被杀了",
 "M15_OBJ_GO_TO_PR_CENTER": "前往[format][color:location]STAG 公关中心[/format]",
 "M12_OBJ_GET_TO_THE_ELEVATORS": "前往[format][color:location]电梯[/format]",
 "M07_OBJ_PROTECT_ANGEL": "保护[format][color:defend]安吉尔[/format]",
 "M01_RIDE_VAULT": "活下来",
 "M06_Y_FOR_DESTROY_BUILDING": "摧毁大楼",
 "M03_OBJ_CUTSCENE_FOUND_WEAPONS_CACHE": "[format][color:location]过场动画：发现武器库[/format]",
 "M15_OBJ_GET_IN_THE_TANK": "夺取[format][color:use]坦克[/format]",
 "M01_GO_TO_VAULT": "前往[format][color:location]金库[/format]",
 "METAGAME_OTHER": "其他",
 "M08_OBJ_GET_TO_BASEMENT": "前往[format][color:location]维修间[/format]",
 "M02_OBJ_KILL_PURSUERS": "消灭[format][color:kill]追兵[/format]",
 "MSN_PLAYER_ESCAPED": "你们中有一人活着逃了出来！",
 "M15_OBJ_CATCH_THE_TRUCK": "追上[format][color:location]卡车[/format]",
 "m14_failure_killbane_escaped": "时间到！杀霸跑了！",
 "M05_OBJ_GRENADES": "拿起[format][color:use]手雷[/format]",
 "M04_OBJ_RETURN_HOME": "回到[format][color:location]安全屋[/format]",
 "M16_TXT_ADV_SC_10_CH1": "抚摸独角兽",
 "M12_OBJ_ESCAPE_THE_STAG_BUILDING": "[format][color:location]逃出[/format]STAG 大楼",
 "M11_OBJ_HELP_OLEG": "救援[format][color:defend]奥列格[/format]",
 "M13_OBJ_COVER_PIERCE": "为[format][color:defend]皮尔斯[/format]提供掩护火力",
 "M11_OBJ_KILL_AIR_BASE": "摧毁[format][color:kill]监视飞机[/format]",
 "M07_OBJ_GO_TO_ZIMOS": "找到[format][color:location]齐莫斯[/format]",
 "METAGAME_HEADSHOT_KILL": "爆头击杀",
 "M18_HELP_GET_CLOSER_TO_DOOR": "[format][color:use]音爆[/format]在这个距离似乎毫无效果。试着靠近那扇[format][color:location]门[/format]",
 "M16_TXT_ADV_SC_09": "你朝着那片靛蓝光辉走去，走廊尽头豁然开朗，出现一座更大的洞窟，光源也真相大白……整间石室被一片巨大的发光湖泊照得通亮。一头独角兽正在湖边饮水。\\n\\n你要怎么做？\\n\\n",
 "M06_Y_FOR_ELEVATOR": "呼叫电梯",
 "M10_OBJ_KILL_STAG_VTOL": "摧毁[format][color:kill]VTOL[/format]",
 "MSN_MORN_START": "开始晨星帮任务",
 "M12_OBJ_GRAB_JOSH_BIRK": "抓走[format][color:use]乔什·伯克[/format]",
 "M07_OBJ_REACH_BARGE": "前往[format][color:location]驳船[/format]",
 "MSN_PROTO_SELECT_OPTION_1": "选择第一种原型装备",
 "M09_OBJ_KILL_ATTACKERS": "消灭[format][color:kill]袭击者[/format]",
 "m07_failure_zimos_died": "齐莫斯阵亡！",
 "M12_OBJ_FIND_JOSH_BIRK": "找到[format][color:teal]乔什·伯克[/format]",
 "m10_failure_viola_dismissed": "薇奥拉被抛弃了！\\n圣徒可不能各自单飞！",
 "M06_OBJ_SET_BOMB": "启动[format][color:use]炸弹[/format]",
 "M13_OBJ_CLEAR_THE_FLOOR": "消灭观景台上的[format][color:kill]STAG[/format]",
 "M13_OBJ_DETONATE_CAR_BOMBS": "射击[format][color:kill]汽车炸弹[/format]",
 "M09_OBJ_GET_INTO_TRUCK": "钻进[format][color:use]卡车[/format]",
 "M21_OBJ_KILL_LUCHADORES": "消灭[format][color:kill]摔跤手帮[/format]",
 "M16_TXT_ADV_SC_10_CH2": "宰了独角兽",
 "M09_OPEN_CONTAINER": "打开集装箱",
 "M08_OBJ_STAIRS_TO_BASEMENT": "找到通往维修间的[format][color:location]楼梯[/format]",
 "MSN_PROTO_SELECT_OPTION_2": "选择第二种原型装备",
 "m10_failure_oleg_died": "奥列格阵亡！",
 "M06_OBJ_FIND_BALL": "利用[format][color:use]配重块[/format]",
 "M05_OBJ_INTERROGATE": "抓住[format][color:use]副官[/format]",
 "M05_OBJ_LET_IN_SAINTS": "放[format][color:use]圣徒[/format]进来",
 "M03_OBJ_DESTROY_TANKS": "摧毁[format][color:kill]坦克[/format]",
 "m06_failure_destroy_bomb": "炸弹爆了！",
 "m03_failure_pierce_destroyed": "皮尔斯的直升机被摧毁！",
 "M03_OBJ_USE_SATELLITE_WEAPON": "使用[format][color:use]死神无人机[/format]",
 "M03_OBJ_GO_TO_WAREHOUSE": "前往[format][color:location]仓库[/format]",
 "METAGAME_MISSION_OBJECTIVE": "任务目标",
 "METAGAME_PLAYER_DEATH": "死亡",
 "M16_TXT_ADV_SC_06_CH2": "拔剑",
 "METAGAME_GANG_LIEUTENANT": "帮派副官",
 "M16_TXT_ADV_SC_11_CH1": "重新开始",
 "m15_failure_pierce_dismissed": "皮尔斯被抛弃了！\\n圣徒可不能各自单飞！",
 "M07_OBJ_FIND_ANGEL": "找到[format][color:location]安吉尔[/format]",
 "M05_MSG_TAUNT": "挑衅[format][color:location]守卫[/format]。",
 "m14_failure_jane_died": "简死了！\\n 别杀简，她能帮你找到杀霸。",
 "m07_failure_oleg_died": "奥列格阵亡！",
 "M05_OBJ_PARACHUTE": "空降[format][color:location]顶层公寓[/format]",
 "M17_12_HOURS_LATER": "12 小时后",
 "M20_OBJ_GO_TO_AIRPORT": "赶到[format][color:location]机场[/format]",
 "m19_failure_suko_died": "薇奥拉阵亡！",
 "m12_failure_cover_blown": "假扮红衣主教的身份暴露了！\\n 别干任何引人注意的事。",
 "M09_OBJ_KILL_GUARDS": "杀掉[format][color:kill]守卫[/format]",
 "M16_TXT_ADV_SC_07_CH1": "继续前进",
 "m12_failure_josh_abandoned": "乔什被抛弃了！\\n圣徒可不能各自单飞！",
 "M04_OBJ_KILL_BRUTE": "杀掉[format][color:kill]巨兽[/format]",
 "MSN_MAP_MESSAGE": "随时按下 START，即可在地图上找到{MAP_IMG_UNKNOWN_ACT}活动。",
 "M18_OBJ_DESTROY_COCKPIT": "用音爆摧毁[format][color:kill]舱门[/format]",
 "M06_OBJ_PHILLIPE": "跟上[format][color:location]奥列格[/format]",
 "SR3_MISSION_DEBUG_OBJECTIVE": "[format][color:red]未本地化：[color:teal]%s [color:red](!!!)[/format]",
 "M06_OBJ_TO_FACTORY": "前往[format][color:location]工厂[/format]",
 "M05_OBJ_BARRIER": "摧毁[format][color:kill]屏障[/format]",
 "M16_TXT_ADV_SC_05": "你开始不顾一切地往主厅跑，脚下却被一块松动的石板绊了一下。\\n\\n你摔倒了，摔断了脖子。\\n\\n你死了。\\n\\n感谢游玩《龙与泪》——螺旋黑暗三部曲第一部\\n\\n",
 "M07_OBJ_FIND_OWNER": "找到[format][color:location]老板[/format]",
 "M02_FAILURE_PLAYER_EJECTED": "你从飞机上摔了出去，死掉了！",
 "m24_failure_killed_in_blast": "你被炸死了！",
 "M16_TXT_ADV_SC_06_CH3": "施放法术",
 "M13_OBJ_DEFEND_THE_NORTH": "守住[format][color:defend]北侧[/format]",
 "M09_OBJ_DEFEND_HELI": "保护[format][color:defend]直升机[/format]",
 "MSN_PROTO_SELECT_OPTION_3": "确认原型装备",
 "M16_TXT_ADV_SC_00_CH4": "打个盹",
 "m15_failure_truck_destroyed": "超级计算机被摧毁了！ \\n用机枪{TANK_FIRE_PRIMARY_IMG}安全地打爆它的轮胎。",
 "SH03_PROTECT_KINZIE": "保护[format][color:defend]金吉[/format] ",
 "M20_OBJ_ALIGN_HELI": "悬停在[format][color:location]车辆[/format]附近",
 "M06_OBJ_RIDE_BALL": "消灭[format][color:kill]目标[/format]",
 "M04_OBJ_KILL_GOONS": "消灭[format][color:kill]晨星帮[/format]",
 "M08_OBJ_ENTER_CHOPPER": "登上[format][color:use]直升机[/format]",
 "M07_OBJ_GRAB_OWNER": "审问[format][color:use]老板[/format]",
 "STRONGHOLD_START_MESSAGE_STAG": "开始 STAG 根据地",
 "M20_OBJ_GET_UP_TO_SPEED": "把[format][color:kill]车[/format]开到全速",
 "M10_OBJ_CALL_ELEVATOR": "试着呼叫[format][color:use]电梯[/format]",
 "M05_Jump": "跳",
 "M02_OBJ_KILL_GUARDS": "杀掉[format][color:kill]守卫[/format]",
 "M16_TXT_ADV_SC_01_CH2": "拿起火把",
 "m15_failure_truck_crushed": "超级计算机被摧毁了！ \\n用机枪{TANK_FIRE_PRIMARY_IMG}安全地打爆它的轮胎。",
 "m11_fail_stag": "你没能留住 STAG 的注意力。",
 "m04_failure_pierce_died": "皮尔斯阵亡！",
 "m01_failure_josh_died": "乔什死了！",
 "M17_OBJ_FIND_BRIG": "找到[format][color:location]禁闭室[/format]",
 "M14_OBJ_PLANT_TRANSMITTER": "安放[format][color:use]发射器[/format]",
 "M11_OBJ_KILL_ROADBLOCK": "清除[format][color:kill]路障[/format]",
 "m04_failure_car_destroyed": "车被摧毁了！",
 "M14_LABEL_ACQUIRING_TARGET": "正在锁定目标",
 "M13_OBJ_TAKE_OUT_THE_SNIPERS": "干掉[format][color:kill]狙击手[/format]",
 "MSN_FAIL": "警察把你们打得屁滚尿流！",
 "m14_failure_heli_abandoned": "你抛弃了直升机！",
 "METAGAME_SUCCESS_WIN": "你的得分超过了搭档，赢得了 $%.0f！",
 "M08_OBJ_REVIVE_PIERCE": "救活[format][color:revive]皮尔斯[/format]",
 "m01_failure_gat_died": "盖特阵亡！",
 "M01_SET_EXPLOSIVES": "去安放[format][color:use]炸药[/format]",
 "M01_TITLE": "银行劫案",
 "M16_TXT_ADV_SC_00_CH1": "打开门",
 "M13_OBJ_TAKE_OUT_THE_VTOLS": "摧毁[format][color:kill]VTOL[/format]",
 "M14_OBJ_GO_TO_HELI": "前往[format][color:location]直升机[/format]",
 "m10_failure_oleg_dismissed": "奥列格被抛弃了！\\n圣徒可不能各自单飞！",
 "m09_failure_zimos_abandoned": "齐莫斯被抛弃了！\\n圣徒可不能各自单飞！",
 "m08_failure_zimos_died": "齐莫斯阵亡！",
 "STRONGHOLD_START_MESSAGE_MORN": "开始晨星帮根据地",
 "MSN_ACTIVITES_RESPECT_REPEAT_GERMAN": "活动{MAP_IMG_UNKNOWN_ACT}能赚取声望。查看地图确认活动位置。",
 "M14_OBJ_TARGET_VAN": "瞄准[format][color:use]广播车[/format]",
 "M10_OBJ_SURVIVE": "活下来",
 "M06_Y_FOR_NO_BOMB": "拆除炸弹",
 "METAGAME_QUICK_KILL": "快速击杀",
 "M17_BRIG_DOORS": "启动安保门",
 "M16_TXT_ADV_SC_03_CH3": "跑回去拿另一支火把",
 "m13_failure_saints_hq_abandoned": "圣徒总部被弃守了！",
 "M03_OBJ_PROTECT_THE_STASH": "保护[format][color:defend]直升机[/format]",
 "MSN_LUCH_START": "开始摔跤手帮任务",
 "M08_OBJ_TAKE_COVER_BEHIND_BAR": "躲到[format][color:location]吧台[/format]后面 ",
 "M04_OBJ_FIND_CLOTHES": "前往[format][color:location]圣徒星球[/format]",
 "M03_OBJ_PROTECT_THE_BOMB": "保护[format][color:defend]炸弹[/format]",
 "m20_failure_vehicle_exit": "乘客逃跑了！",
 "M13_OBJ_GOTO_PENTHOUSE": "前往[format][color:location]顶层公寓[/format]",
 "M20_OBJ_RC_A_BOAT": "遥控一艘[format][color:use]船[/format]",
 "M06_Y_FOR_BOMB": "启动炸弹",
 "SH02_OBJ_GET_VEHICLE": "钻进[format][color:use]载具[/format]",
 "m14_failure_shaundi_died": "肖恩蒂阵亡！",
 "M13_PROMPT_THROW_JOSH_TO_CYRUS": "把乔什交给赛勒斯",
 "m07_failure_club_owner_died": "俱乐部经理死了！\\n 审问完之前别让他死了。",
 "M03_FAILURE_ABANDON_HOMIE": "肖恩蒂被抛弃了！\\n圣徒可不能各自单飞！",
 "M03_OBJ_ACCESS_MAP_USE_MSG": "打开手机地图",
 "SH03_HACKING_TIME": "入侵中",
 "M11_OBJ_GO_STAG_BASE": "赶到[format][color:location]STAG 基地[/format]",
 "M05_OBJ_KILL_LIEUTENANT": "干掉[format][color:kill]副官[/format]",
 "M01_Y_FOR_EXPLOSIVES": "安放炸药",
}

# 逐行写回
lines = open(SCH, encoding="utf-8").read().replace("\r\n", "\n").split("\n")
out = []
seen = set()
for ln in lines:
    m = re.match(r'^\s*"([^"]+)":\s*"(.*)"\s*$', ln)
    if m and m.group(1) in T:
        k = m.group(1)
        out.append('"%s": "%s"' % (k, T[k]))
        seen.add(k)
    else:
        out.append(ln)
for k in T:
    if k not in seen:
        out.append('"%s": "%s"' % (k, T[k]))

open(SCH, "w", encoding="utf-8").write("\n".join(out) + "\n")
print("written", len(T), "entries; total lines", len(out))
