# -*- coding: utf-8 -*-
# 接管重译 hud：读 original/hud_us.txt 抽 KEY，逐条重写中文。
import re, os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCH = os.path.join(BASE, "schinese", "hud_us.txt")
ORG = os.path.join(BASE, "original", "hud_us.txt")

src = open(ORG, encoding="utf-8").read().replace("\r\n", "\n")
od = dict(re.findall(r'^\s*"([^"]+)":\s*"(.*)"\s*$', src, re.M))

T = {
 "TUT_TITLE_RECRUITING": "招募兄弟",
 "dildo_bat": "穿透者",
 "PAUSE_ACT_CHOP_REMOVE_HUD": "从 HUD 中移除",
 "ACHIEVE_SR3_WERE_TAKIN_OVER": "这地盘我们接管了",
 "HUD_DIVERSION_RESPECT": "声望 ",
 "TUT_TITLE_GANG_VEHICLE_CUSTOMIZE": "帮派载具改装",
 "HUD_START_QTE_MESSAGE": "痛揍壮汉",
 "HUD_NEW_MISSION_AVAILABLE": "新任务已开放",
 "TUT_WHORED_D_LEAGUE_OF_OWN": "自成一派",
 "TUT_NAG_CHANGE_CLOTHES": "记住：购买并更换服装可获得声望",
 "TUT_TITLE_STORE_INTRO_MECHANIC": "菊花保养行",
 "TUT_GENERAL_SMOKED": "你被干掉了！  \\n生命值耗尽后，会扣掉一小笔现金，然后你会在医院复活。",
 "TUT_CRIB_WEAPONS": "这是你的武器库。  \\n在这里武装自己。",
 "WPN_RIFLEGANG_DESCRIPT": "工薪阶层的突击步枪。",
 "CONFIRM_RESTART_TITLE": "确认重启",
 "TUT_DLC_MONEYSHOT": "这是一把特殊狙击步枪。",
 "ACHIEVE_SR3_LIFE_OF_THE_PARTY": "派对之王",
 "WPN_GRENADELAUNCHER_DESCRIPT": "一口气射出海量榴弹，把爆炸效果拉满。",
 "HUD_FEET": "英尺",
 "WPN_URINAL": "小便池",
 "RPG_AMMO": "RPG 弹药",
 "HUD_TRIGGER_VEHICLE_REPAIR_NSF": "修理载具需要 $%d",
 "TUT_VEHICLE_ENTRY": "{ACTION_IMG} 抢夺载具 \\n{SPRINT_IMG} + {ACTION_IMG} 快速抢夺载具",
 "TUT_THROW_KILL": "{ACTION_IMG} 扔出人盾",
 "ACHIEVE_SR3_YOUR_BACKSEAT_SMELLS_FUNNY": "你后座的味道不对劲",
 "HUD_UNLOCKED_SHORTCUT": "GPS 快捷路线已解锁！",
 "PAUSE_ACT_HITMAN_REMOVE_HUD": "从 HUD 中移除",
 "UNL_DESC_RESPECT_BONUS_PURCHASE4": "所有声望收益提高 20%%",
 "UNL_WEEKLY_PAYMENTS_2": "奖励 - 城市每小时收入 2",
 "TUT_FINEAIM_1": "精准瞄准模式可提升准度，但会降低速度",
 "TUT_TITLE_ACT_GUARDIAN": "守护天使",
 "HYDRAULICS_ON": "液压悬挂开启",
 "UNL_DESC_DBNO_EXTRA_TIME_3": "所有同伴流血死亡时间延长 30 秒",
 "TUT_WHORED_MINI_HAMMER": "迷你锤",
 "TUT_TITLE_AIRSTRIKE": "空袭武器",
 "PLAYER_CHOICE_M13_OPTION1_TITLE": "[format][color:blue]把乔什交还给 STAG[/format]",
 "TUT_SATCHEL_CHARGES": "{DETONATE_CHARGES_IMG} 引爆已投掷的炸药包",
 "WPN_SHOTGUNGANG_DESCRIPT": "老派霰弹枪，配上圣徒新风格。",
 "HUD_RESPECT_RANK_003": "街头混混",
 "TUT_WHORED_Z_THEME_PARK": "游乐园大屠杀",
 "TUT_AIRPLANE_CONTROL": "{PLANE_ACCELERATE_IMG} 加速 \\n{PLANE_BRAKE_REVERSE_IMG} 刹车 + 倒退 \\n用 {ANALOG_LS_IMG} 控制滚转和俯仰，让飞机转向。",
 "HUD_FLIP_VEHICLE_INSTRUCTIONS": "按 {ACTION_IMG} 翻正载具",
 "SATELLITE_FIRE_MISSILES": "发射非制导导弹",
 "HUD_RESPECT_RANK_009": "老哥",
 "USE_TRIGGER_GANG_CUSTOMIZE": "自定义你的帮派",
 "HUD_DIVERSION_POINTS": "点数 ",
 "TUT_TITLE_NEW_MISSIONS": "新任务",
 "THEATER_STRONGHOLD": "根据地",
 "HUD_PRESS_BACK_CANCEL_ACTIVITY": "长按 %ls 退出活动",
 "TUT_TITLE_HYDRAULICS": "液压悬挂",
 "TUT_GENERAL_BUSTED": "你被抓了！  \\n被捕后会扣掉一小笔现金，然后你会在警察局门外被释放。",
 "PLAYER_CHOICE_M22_OPTION1_TITLE": "[format][color:red]前往机场[/format]",
 "PLAYER_CHOICE_M09_OPTION2_TITLE": "[format][color:Purple]把姑娘们留给圣徒[/format]",
 "PLAYER_CHOICE_M06_OPTION1_TITLE": "[format][color:red]炸掉大楼[/format]",
 "TUT_TITLE_ACT_INTRO_HELI_ASSAULT": "直升机突击",
 "HUD_HELIPORT_NEED_VEHICLES": "添加直升机以使用停机坪",
 "UNL_DESC_HOMIE_PIERCE": "在你手机的“电话”菜单中可以找到皮尔斯。他会在战斗中帮助圣徒。",
 "TUT_CRIB_CARSTORAGE_1": "这是你的车库。  \\n在这里可以存放或取出你拥有的载具。",
 "UNL_DESC_INSTANT_RELOAD_SHOTGUN": "霰弹枪瞬间完成装填",
 "TUT_NAG_FINE_AIM": "记住：使用精准瞄准 {ANALOG_RS_IMG} 助你瞄准远处的敌人",
 "PLAYER_CHOICE_M13_OPTION2_BODY": "奖励：夜刃成为兄弟",
 "TUT_TITLE_UNDERCOVER": "卧底行动",
 "TUT_COMBAT_WEAPONS_1": "{PICKUP_RELOAD_IMG} 换弹",
 "TUT_TITLE_NP_MOTORCYCLE_CONTROLS": "摩托车操作",
 "HUD_RESPECT_RANK_007": "珠光宝气",
 "PLAYER_CHOICE_M19_OPTION1_TITLE": "[format][color:blue]把丧尸病毒还给奥列格[/format]",
 "PLAYER_CHOICE_M16_OPTION2_TITLE": "[format][color:blue]接管一家武器制造商[/format]",
 "TUT_TITLE_ACT_INTRO_ESCORT": "护花使者",
 "TUT_STORE_INTRO_WEAPONS": "你可以在友军火力枪店购买武器和弹药，还能升级武器和手榴弹。",
 "RESPECT_UPGRADE": "升级",
 "EXPLOSIVE_ROCKETLAUNCHER": "歼灭者",
 "OVL_IN_USE": "使用中",
 "TUT_SPRINT_RECHARGE": "冲刺槽耗尽后，等它重新充满再继续冲刺。",
 "GARAGE_TOO_SMALL": "车库太小，放不下这辆载具",
 "MAP_HIDDENNAME_STORE": "商店",
 "UNL_DESC_CRIB_POWDER": "火药现在是一座圣徒据点。在这里可以访问武器库和服装，并自定义你的帮派。",
 "TL_MIS_21_RIDE_KILLBANE": "{ANALOG_LS_IMG} 转向 \\n{ATTACK_PRIMARY_IMG} 出拳 \\n出拳揍杀霸，让他朝你转向的方向移动。",
 "HUD_METERS_ABR": "米",
 "TUT_TITLE_STORE_INTRO_CLOTHES": "服装店",
 "ACHIEVE_SR3_A_BETTER_PERSON": "更好的自己  ",
 "HUD_AMT_POINTS": "+{0}点数",
 "TUT_ACT_INTRO_SNATCH_KINZIE": "把联系人从赛博帮手里安全带回来。",
 "ACHIEVE_SR3_THIRD_AND_30": "三档30码",
 "COOP_WAITING_ON_PLAYER": "正在等待其他玩家...",
 "WPN_AIR_STRIKE_DESCRIPT": "用激光“标记”目标，然后看着死亡之雨砸向那片区域。  最好退远一点...",
 "TUT_COMBAT_MELEE_1": "{MELEE_POWER_ATTACK_IMG} 重击 \\n{ATTACK_PRIMARY_IMG} 轻击",
 "COOP_KICK_PLAYER_CONFIRM": "你确定要把 %ls 踢出游戏吗？\\n未保存的任务或活动进度将会丢失",
 "UNL_DESC_HOMIE_SHAUNDI": "在你手机的“电话”菜单中可以找到肖恩蒂。她会在战斗中帮助圣徒。",
 "HUD_HOLD_BACK_CANCEL_TAGGING": "退出涂鸦",
 "HYDRAULICS_TOGGLE": "按 %ls 切换",
 "TUT_TITLE_LOW_AMMO": "弹药不足",
 "PLAYER_CHOICE_M19_OPTION1_BODY": "奖励：丧尸兄弟",
 "TUT_TITLE_ACT_INTRO_DRUG_TRAFFICKING": "黑货押运",
 "TUT_DIV_INTRO_HOSTAGE": "高速行驶甩开警察，直到人质崩溃掏钱。  一旦减速，人质就会逃跑。",
 "ACHIEVE_SR3_GOTTA_BREAK_EM_IN": "总得先磨合磨合",
 "HUD_RESPECT_RANK_001": "新血",
 "TUT_WHORED_A_LITTLE_NIKITA": "小尼基塔",
 "TUT_WHORED_ZOMBIE_SLAYER": "丧尸杀手",
 "TUT_WHORED_BIG": "东京告急！",
 "WPN_SONIC_WAVE_GUN_DESCRIPT": "聚焦声波能震倒你面前的大多数东西。  蓄力之后，看看会发生什么！",
 "WPN_SMGCYBER_DESCRIPT": "从赛博帮网络里扒来的赛博帮冲锋枪，真的能用。",
 "RESTRICTED_ZONE_ENTER": "正在进入禁区",
 "UNL_DESC_NOTORIETY_LUCHA_3": "你的摔跤手帮恶名消退速度会大幅加快",
 "TUT_TITLE_HOMIE_REVIVE": "救起同伴",
 "Flashbang": "闪光弹",
 "TUT_WHORED_Z_BRUTE_ACTION": "壮汉手办",
 "ACHIEVE_SR3_KILL_DECKERS_EXE": "干掉赛博帮.EXE",
 "TUT_NP_TANK_CONTROLS": "{ANALOG_LS_IMG} 移动 \\n{ANALOG_RS_IMG} 瞄准 \\n{TANK_FIRE_SECONDARY_IMG} 发射主武器 \\n{TANK_FIRE_PRIMARY_IMG} 发射副武器",
 "PLAYER_ALL_HEALED": "满血复活！",
 "TUT_WHORED_A_KEEP_AWAY": "休想拿走",
 "TUT_WHORED_BRUTES": "奥列格家族大团圆",
 "HUD_TARGET_ELIMINATED": "目标已消灭",
 "UNL_DESC_CASH_FOR_RESPECT_1": "支付现金购买 4,000 点声望",
 "TUT_TITLE_STORE_INTRO_TATTOO": "纹身店",
 "CS_TITLE_SYNDICATE_JET": "辛迪加喷气机",
 "USE_TRIGGER_PENTHOUSE": "前往顶层公寓",
 "RADIO_OFF": "关",
 "UNL_DESC_WEP_AIRSTRIKE": "在据点的武器库装备 SA3 空袭指示器。",
 "USE_TRIGGER_GARAGE": "前往车库",
 "WPN_EGRENADE_DESCRIPT": "造成电击伤害，还能麻倒你周围的敌人。",
 "WPN_VTOL_MISSILES": "蜂群导弹",
 "USE_TRIGGER_DROP_HELI": "放下直升机",
 "UNL_DESC_POLICE_CUSTOMIZATION": "警察主题自定义物品",
 "EXPLOSIVE_GENKI": "软体动物发射器",
 "ACT_CANCEL_TEXT": "你确定要离开当前活动吗？\\n开始活动以来的所有进度都会丢失。",
 "SATELLITE_SLOW_DOWN": "减速",
 "SATLLITE_SPEED_UP": "加速",
 "ACT_CANCEL_TITLE": "重试还是退出活动？",
 "UNL_WEAPON_KILLBANES_GLOVES": "武器 - 末日铁拳",
 "ACHIEVE_SR3_FLASH_THE_PAN": "一锅端",
 "WPN_SNIPER_DESCRIPT": "专治讲究精准的远距离一击。",
 "UNL_SPRINT_1": "冲刺 - 提速",
 "TUT_NAG_TAUNTING": "记住：一边杀敌一边用 {MENU_DP_LEFT_IMG} 嘲讽他们，可获得额外声望",
 "UNL_DAMAGE_FIRE_2": "伤害 - 火焰 2",
 "TUT_PAUSE_MAP": "{MAP_MENU_IMG} 打开手机地图\\n现在就打开手机地图，设定一条通往友军火力枪店的 GPS 路线。",
 "TUT_WHORED_MINI_SAMURAI": "迷你武士",
 "ACHIEVE_SR3_YOURE_THE_BEST": "你是最棒的...",
 "WPN_STUNGUN_DESCRIPT": "快速撂倒你的目标。",
 "RIFLE_AMMO": "步枪弹药",
 "PISTOL_AMMO": "手枪弹药",
 "CS_TITLE_SYNDICATE_BOARDROOM": "辛迪加会议室",
 "ACHIEVE_SR3_PIMPED_OUT_PAD": "爆改据点",
 "TEMP_SHIELD": "防暴盾牌",
 "TUT_WHORED_SWAG_BAG": "战利品袋",
 "USE_TRIGGER_HE_CRIB_ENTER": "乘电梯上楼",
 "HUD_ACT_CONTINUE": "%ls 继续活动",
 "ACHIEVE_SR3_DEAD_PRESIDENTS": "钞能力",
 "WPN_PISTOLPOLICE_DESCRIPT": "警察赶到时，你通常忙着躲的就是这玩意。",
 "HUD_UNLOAD_VEHICLE_MESSAGE": "按 %ls 卸下载具",
 "TUT_CHALLENGES": "挑战会为完成艰难任务提供奖励。在圣徒簿 {MAP_MENU_IMG} 中追踪你的进度。",
 "HUD_FEAR": "恐惧",
 "STRONGHOLD_COOP_TITLE": "合作根据地",
 "S_FOUND_A_COLLECTIBLE_YOU_MISSED": "%ls 找到了你错过的收集品",
 "TUT_HELICOPTER_ENTRY": "{HELI_UP_IMG} 上升\\n{HELI_DOWN_IMG} 下降\\n{HELI_STRAFE_LEFT_IMG}/{HELI_STRAFE_RIGHT_IMG} 快速转向",
 "SATELLITE_RC_MODE_DESTRUCT": "自爆",
 "HOOD_OWNED_FRACTION": "已占领 %d/%d",
 "HUD_LOAD_VEHICLE_MESSAGE": "%ls 装载载具",
 "UNL_UPGRADE_AMMO_SHOTGUN_3": "弹药 - 霰弹枪 3",
 "TUT_NAG_IMPROV_WEAPONS": "记住：用 {PICKUP_RELOAD_IMG} 拾取场景里的物件，把它们当临时武器用",
 "TUT_WHORED_SAUSAGEFEST": "香肠派对",
 "SATELLITE_EXIT_RC_MODE": "退出遥控模式",
 "HOMIES_HOSPITAL_BILL": "%ls 的住院费花了 %ls",
 "HUD_RESPECT_RANK_005": "兄弟",
 "GENERAL_LIGHT": "轻伤",
 "PLAYER_CHOICE_M06_OPTION1_BODY": "奖励：永久声望加成",
 "TUT_TITLE_BARNSTORMING_NEW": "低空穿越",
 "ACHIEVE_SR3_I_HEART_NYTE_BLAYDE": "我爱夜刃",
 "SHOTGUN_GANG": "掘墓人",
 "HUD_DOWNED_REVIVE": "复活",
 "UNL_DESC_RESPECT_BONUS_PURCHASE2": "所有声望收益提高 10%%",
 "UNL_WEEKLY_PAYMENTS_4": "奖励 - 城市每小时收入 VIP",
 "TUT_TITLE_GANG_CUSTOMIZE": "帮派自定义",
 "TUT_CITY_TAKEOVER": "{MAP_MENU_IMG} 打开地图 \\n查看地图，找到城市接管玩法，提升你的每小时收入。",
 "TUT_TITLE_STORE_OWNERSHIP": "地产所有权",
 "HUD_HANGAR_NEED_VEHICLES": "添加飞机以使用机库",
 "WPN_MOLOTOV_DESCRIPT": "放火好帮手。",
 "TUT_SHORTCUT_SPLINES": "每发现一条捷径，GPS 就会更新出更新、更短的路线。",
 "GARAGE_WATERCRAFT_ONLY": "此处只能存放水上载具",
 "UNL_DAMAGE_VEHICLE_4": "伤害 - 载具 4",
 "FLAME_AMMO": "燃烧弹药",
 "HUD_TAUNT": "嘲讽",
 "TUT_WHORED_A_T_BIRD": "T BIRD 的浪潮",
 "TUT_TITLE_RANK_UP": "升级",
 "TUT_TITLE_GENERAL_BUSTED": "被捕",
 "TUT_TITLE_THROW_KILL": "人盾 - 扔出",
 "TUT_ACT_TANK_MAYHEM": "消灭钢埠各处的辛迪加高价值目标。",
 "TUT_TITLE_STRONGHOLD_RESPECT": "声望不足！",
 "TUT_WHORED_HUMANTORCH": "给我烧起来",
 "HUD_CRUISE_CONTROL_ACTIVE": "定速巡航已开启",
 "COOP_PLAYER_KICKED": "%ls 已被踢出游戏",
 "CANT_STORE_PARTNERS_CAR": "无法存放队友的载具",
 "TUT_WHORED_PICKUPS_BODY": "在关卡各处寻找补给包，获取新武器、升级件和弹药。",
 "TUT_TITLE_OLEG_FOLLOW": "正在离开奥列格",
 "FORMAT_TIME_MINS": "{0} 分钟",
 "HUD_TRIGGER_DISABLED_OTHER": "现在不能来这里",
 "WEP_HELI_FIGHTER_01": "机枪/火箭弹",
 "HUD_TAP_BUTTON": "连点",
 "HUD_HOLD_BUTTON": "长按",
 "HUD_PRESS_BACK_CANCEL_DIVERSION": "再按一次 %ls 取消即时挑战",
 "UNL_DESC_HOMIE_VTOL": "在你手机的“电话”菜单中可以呼叫 VTOL 兄弟。他会在战斗中给你送来一架 VTOL。",
 "UNLOCKABLE_VIEW_MAP_TEXT": "游戏中按 %s 查看地图。",
 "TUT_M16_CHARGE_CYBERCANNON": "{ATTACK_PRIMARY_IMG} 长按扳机蓄力",
 "TUT_RECIEVE_CRIB": "你现在拥有自己的据点了 {MAP_IMG_CRIB}。\\n在据点可以存放武器和服装，并进行帮派形象定制。",
 "HUD_CANCEL_ACTIVITY": "重试或退出活动",
 "HUD_METERS": "米",
 "UNL_DEPRECATED_SR2": "我的文本来自二代，早就过时了，这个奖励已失效，我不该在游戏里出现",
 "TUT_TITLE_ACT_INTRO_ESCORT_TIGER": "老虎护驾",
 "TUT_OLEG_FOLLOW": "把奥列格甩在身后他自己会追上来，不用等他。",
 "TUT_RECRUITING": "有兄弟加入后，屏幕右上角会显示他的图标。随着等级提升，你可以用 {RECRUIT_DISMISS_IMG} 招募更多兄弟。",
 "WPNCAT_SHOTGUN": "霰弹枪",
 "MAP_HIDDENNAME_PROPERTY": "地产",
 "UNL_WEP_DILDO_BAT": "武器 - 穿透者",
 "TUT_COMBAT_GRENADES": "{ATTACK_SECONDARY_IMG} 投掷手榴弹 \\n{WEAPON_MENU_IMG} + {DPAD_IMG} 切换装备的手榴弹",
 "PLAYER_HAS_FULL_HEALTH": "你已恢复满血",
 "TUT_TITLE_COMBAT_RANGED": "远程战斗",
 "WPNCAT_SPECIAL": "特殊武器",
 "TUT_TITLE_ACT_FRAUD_ADRENALINE": "肾上腺素模式",
 "TUT_TITLE_CRIB_CASH": "现金储藏室",
 "WPN_SHOTGUNCHUM_DESCRIPT": "哎哟喂！  用鱼杂碎招呼那帮旱鸭子，引出神出鬼没的钢埠下水道鲨鱼，没比这更带劲的了。  呦嗬嗬！",
 "SMG_SPREAD": "赛博克星",
 "SMG_CYBERSPACE": "赛博冲击枪",
 "FRIENDLY_FIRE_TURNED_ON__NYOU_CAN_NOW_DAMAGE_YOUR_PARTNER": "队友伤害已开启\\N你现在可以打伤队友了",
 "TUT_NAG_UPGRADE_STORE": "升级件在手机升级商店有售；买下来，让你和你的帮派更上一层楼。",
 "TUT_TITLE_CITY_TAKEOVER": "接管城市",
 "TUT_TITLE_NP_TANK_CONTROLS": "坦克操作",
 "TUT_CRIB_CLOSET": "这是你的衣橱。 \\n在这里更换服装。",
 "WPN_SATELLITE_DRONE_DESCRIPT": "在空中盯着导弹一路飞向它命中注定的目标。",
 "HUD_TRIGGER_DISABLED_NOT_UNLOCKED": "这里尚未解锁，暂时进不去",
 "VEHICLE_ADDED_TO_GARAGE": "%ls 已存入你的车库",
 "TUT_WHORED_A_TANK": "坦克来了！",
 "WPN_VTOL02": "激光束",
 "EXPLOSIVE_SATCHEL": "炸药包",
 "UNL_DAMAGE_EXPLOSIVE_1": "伤害 - 爆炸",
 "TUT_TITLE_RESPECT_DIVERSIONS": "即时挑战 HUD",
 "TUT_TITLE_FLASHING": "当街露鸟",
 "ACHIEVE_SR3_GELLIN_LIKE_MAGELLAN": "麦哲伦也没我浪",
 "ACHIEVE_SR3_MOURNING_STARS": "哀悼之星",
 "UNL_DESC_DAMAGE_EXPLOSIVE_2": "受到的爆炸伤害降低 10%%",
 "TUT_WHORED_MEGANINJA": "超级忍者",
 "TUT_AIRSTRIKE": "空袭必须完整标记目标后，导弹雨才会倾泻而下。",
 "TUT_TITLE_GAME_WIN": "恭喜通关！",
 "TUT_TITLE_DLC_BLING_SHOTGUN": "土豪金霰弹枪",
 "TUT_NAG_CRIB_STASH": "记住：用手机定期收取你名下地产的现金。",
 "TUT_TITLE_DIVERSION_COMPLETE": "即时挑战完成",
 "TUT_STORE_INTRO_MECHANIC_LARGE": "大型车辆修理行可以改装和修理你那些超规格的载具。大型载具只能从这里或你的据点车库取回。",
 "MAP_BOOKMARK": "地图书签",
 "TUT_WHORED_Z_TEXAS_ZOMBIES": "德州丧尸",
 "TUT_WHORED_A_TINY_PROBLEMS": "小麻烦",
 "TUT_WHORED_A_BOOM_HEADSHOT": "砰！爆头",
 "TUT_WHORED_A_GENKI_GAMES": "元气运动会",
 "TUT_WHORED_D_LILLIPUTIANS": "小人国",
 "WPN_SHARK": "鲨鱼",
 "EXPLOSIVE_GRENADELAUNCHER": "M2 榴弹发射器",
 "HOOD_MONEY_EARN_RATE": "每小时收入：%s",
 "UNL_DESC_UNLIMITED_SPRINT": "无限冲刺，永远，不停",
 "UNL_AMMO_DECKER_2": "武器库弹药",
 "UNL_DESC_CASH_MULTIPLIER_1": "所有现金收益提高 5%%",
 "SGI_RETRY": "要重试吗？",
 "MISSION_CANCEL_SUB_TEXT": "任务已取消",
 "TUT_NP_CAR_CONTROLS": "{ACCELERATE_IMG} 加速 \\n{BRAKE_REVERSE_IMG} 刹车 + 倒车\\n{HANDBRAKE_IMG} 漂移",
 "HUD_DIVERSION_CASH": "现金 ",
 "TUT_UNDERCOVER": "别攻击任何人，也别太张扬，否则你会暴露，任务就砸了。",
 "TUT_TITLE_VTOL_CONTROL": "VTOL 操作",
 "TUT_TITLE_CRIB_CLOSET": "衣橱",
 "TUT_TITLE_CRIB_RECEIVE": "据点",
 "TUT_TITLE_PUSHBACK": "反攻",
 "TUT_TITLE_DIV_INTRO_MUGGING": "街头抢劫",
 "STRONG_CANCEL_TITLE": "重试还是退出根据地？",
 "TUT_TITLE_TAUNTING": "嘲讽 / 捧场",
 "TUT_WHORED_Z_BIG_BONED": "她只是骨架大",
 "UNL_HIDDEN": "隐藏",
 "Molotov": "燃烧瓶",
 "UNL_DESC_FOLLOWER2": "招募两名圣徒兄弟。按 {RECRUIT_DISMISS_IMG}  招募附近的圣徒。",
 "TUT_HUMAN_SHIELD": "{ACTION_IMG} 抓人盾\\n人盾能替你挡子弹，还能给你争取喘息时间。",
 "TUT_WHORED_A_ENDING_DEBATE": "终结辩论",
 "SHOTGUN_CHUM": "鲨鱼喷射器",
 "SATELLITE_GUIDED_MISSILES": "制导导弹",
 "CS_TITLE_3_COUNT_SB": "三秒压制赌场投注站",
 "HITMAN_DISPLAY_DISTRICT_UNKNOWN": "未知",
 "CUTSCENE_REMOTE_SKIPPING": "{SKIP_MODAL_SEQUENCE_IMG} 投票跳过",
 "UNL_DESC_VEHICLE_CUSTOMIZATION": "改装载具",
 "TUT_TITLE_M16_AVATAR_ATTACKS": "阿凡达来袭",
 "WPN_RIFLESTAG_DESCRIPT": "STAG 步枪采用激光技术，彻底免装弹匣。  当心枪管过热。",
 "HUD_JUMP_ON_KILLBANE": "跳上杀霸",
 "PLAYER_CHOICE_M09_OPTION2_BODY": "奖励：每小时现金收入提升",
 "TUT_COMBAT_WEAPONS": "自动拾取你身上没有的武器。\\n按住{WEAPON_MENU_IMG}打开武器菜单，用{WEAPON_SELECT_IMG}切换武器。",
 "SWITCH_MODE": "切换模式",
 "Temp_Flamethrower": "烈焰焚化者",
 "UNL_UPGRADE_AMMO_RIFLE_1": "弹药 - 步枪 1",
 "UNL_DAMAGE_BULLET_2": "伤害 - 子弹 2",
 "TUT_TITLE_WEAPON_UPGRADES": "武器升级",
 "ACHIEVE_SR3_WHO_LOVES_YA_BABY": "谁不爱你呀宝贝",
 "TUT_ACT_INTRO_HUMAN_TORCH": "一路狂飙冲向终点，赢取现金和声望。撞人和撞车赢取的奖励秒数，会在每个检查点计入你的倒计时。",
 "SPECIAL_SONICGUN": "音爆者",
 "USE_TRIGGER_HE_CRIB_EXIT": "乘电梯下去",
 "TUT_TITLE_WAYPOINT": "GPS 路点标记",
 "ACHIEVE_SR3_TITANIC_EFFORT": "泰坦之伟业",
 "HUD_ATTACK_KILLBANE": "干掉杀霸",
 "USE_TRIGGER_GRAB_PARACHUTE": "拾取降落伞",
 "TUT_HUMAN_SHIELD_GENERAL": "{ACTION_IMG} 抓人盾 \\n按{CBA_OFC_HS_EXECUTE_IMG}处决人盾",
 "TUT_TITLE_PAUSE_MAP": "暂停地图",
 "TUT_GANG_CUSTOMIZE": "帮派自定义可以决定圣徒们穿什么、开什么车，以及他们的嘲讽语和夸赞语。",
 "WPN_SHOTGUNSTAG_DESCRIPT": "STAG 版本的霰弹枪。  无需装填，但小心枪管过热。",
 "HUD_ACT_EXIT": "%ls 结束活动",
 "ACHIEVE_SR3_HI_JACK_IT": "夺船大盗",
 "WPN_DILDOBAT_DESCRIPT": "一个荒诞的成人玩具，却有着棒球棍的杀伤力。",
 "TUT_VTOL_CONTROL_B": "{ACCELERATE_IMG}加速/上升。 \\n{BRAKE_REVERSE_IMG}刹车/下降。 \\n按{VTOL_TRANSITION_IMG}在悬停模式和飞机模式之间切换。",
 "HUD_START_FREEFALL": "开始自由落体",
 "ITEM_COMPLETE": "集齐整套了！",
 "WPNCAT_SUB_MACHINE_GUN": "冲锋枪",
 "TUT_WHORED_Z_WELCOME": "上衣配裤衩",
 "HUD_WAIT_FOR_PARTNER_TO_JOIN": "必须等你的搭档加入完毕。",
 "PLAYER_CHOICE_M21_OPTION1_BODY": "奖励：杀霸的面具",
 "PLAYER_CHOICE_M21_OPTION1_TITLE": "[format][color:red]给杀霸摘掉面具[/format]",
 "TUT_TITLE_DLC": "可下载内容",
 "HYDRAULICS_OFF": "液压悬挂 关",
 "MISSION_COOP_CONFIRM_MISSION": "正在等待 %ls 确认开始任务",
 "STRONGHOLD_UPGRADE1": "升级 1",
 "TUT_ACT_INTRO_DRUG_TRAFFICKING": "为你的联络人在钢埠各处的毒品交易保驾护航。",
 "ACHIEVE_SR3_KUH_BOOM": "哞，砰。",
 "HUD_DOCK_NEED_VEHICLES": "需要水上载具才能使用船坞",
 "UNL_DESC_DAMAGE_BULLET_4": "免疫一切子弹伤害",
 "ACHIEVE_SR3_PARTNERS_IN_CRIME": "共同犯罪",
 "SATELLITE_MODE_EXIT": "退出卫星视图",
 "TUT_WHORED_MUSCLESNDILDOS": "比划比划",
 "TUT_WHORED_APACOFISTS": "当心末日铁拳",
 "TUT_TITLE_STORE_INTRO_WEAPONS": "武器商店",
 "FLASHPOINT_HUD_TEXT": "帮派行动已肃清",
 "HUD_SECONDS_ABR": "秒",
 "TAXI_UNAVAILABLE": "出租车不可用",
 "FRIENDLY_FIRE_TURNED_OFF__NYOU_CAN_NO_LONGER_DAMAGE_YOUR_PARTNER": "关闭队友伤害\\N你将无法再伤害你的队友",
 "TUT_TITLE_NP_HELI_WEAPON_CONTROLS": "直升机武器",
 "WPN_BASEBALLBAT_DESCRIPT": "一根长长的木棍。打人打物样样在行。  不解释。",
 "SPECIAL_RCVEHICLEGUN": "遥控夺车器",
 "SHOTGUN_AMMO": "霰弹枪弹药",
 "TUT_WHORED_HITNRUN": "横扫街道",
 "TUT_TITLE_AIRPLANE_CONTROL": "飞机操作",
 "UNL_DAMAGE_VEHICLE_2": "伤害 - 载具 2",
 "TUT_TITLE_DRONE": "无人机武器",
 "TUT_TITLE_DIV_INTRO_BASE_JUMPING": "定点跳伞",
 "TUT_TITLE_SAVE": "游戏存档",
 "WPN_PISTOLGANG_DESCRIPT": "圣徒们的标配手枪。",
 "TUT_WHORED_MEGAFURRIES": "巨型毛毛党",
 "WPN_FLASHBANG_DESCRIPT": "用这颗手雷震晕你的敌人。",
 "WPN_SHOTGUNBLING_DESCRIPT": "怎么用都爽——用它干掉帮派分子，每杀一个都能捞到额外声望。",
 "WPN_SHOTGUNPOLICE_DESCRIPT": "执法部门的制式霰弹枪。  看见它冲你来就赶紧低头……",
 "HUD_REVIVE_HOMIE_MESSAGE": "按住 %ls 救起你的[format][color:purple]兄弟[/format]",
 "TUT_WHORED_D_WAVE_DEAD": "活死人浪潮",
 "WPN_SATCHEL_DESCRIPT": "把这份炸药包粘在任何你想扔的东西上。  按下引爆器之前，先确保你自己已经撤到安全距离。",
 "PLAYER_CHOICE_M16_OPTION2_BODY": "奖励：武器升级费用降低",
 "TUT_TITLE_CHALLENGES": "挑战",
 "TUT_TITLE_CAR_SHOOTING": "载具战斗",
 "BURST_FIRE_TEST": "点射测试武器",
 "HUD_MILES_ABR": "英里",
 "COMBAT_RECORD": "新纪录！",
 "HUD_PRESS_BLANK_TO_BLANK": "%ls 来 %ls",
 "GARAGE_CANT_OPEN": "这辆载具无法存入车库",
 "TUT_NOTORIETY_DECREASE_STORE": "躲进任何一座你名下的建筑，恶名即刻清零：{MAP_IMG_CRIB}、{MAP_IMG_CLOTHING} 等。",
 "HUD_TRIGGER_NEEDS_VEHICLE": "你必须身处载具内才能激活此触发点",
 "HUD_AMT_SECS": "+{0}秒",
 "TUT_TITLE_COMBAT": "近战格斗",
 "TUT_NAG_POWER_ATTACKS": "记住：按住{ATTACK_PRIMARY_IMG} / {ATTACK_SECONDARY_IMG}即可使出蓄力重击",
 "WPN_TIKITORCH": "提基火把",
 "ACHIEVE_SR3_BO_DUKE_EN": "波杜肯飞车",
 "HID_TRIGGER_VEHICLE_REPAIR_NSF": "现金不足，无法修理载具",
 "UNL_DESC_INSTANT_RELOAD_PISTOL": "手枪瞬间换弹",
 "UNL_DAMAGE_EXPLOSIVE_3": "伤害 - 爆炸 3",
 "TUT_TITLE_HUD_TEXT": "帮助文本",
 "ACHIEVE_SR3_GENDER_EQUALITY": "男女平等",
 "ACHIEVE_SR3_GETTING_THE_GOODS": "进货达人",
 "WPN_RPG_DESCRIPT": "想要大爆炸和猛火力，选火箭筒准没错。",
 "DIVERSIONS_CASH": "现金 {0}",
}

lines = open(SCH, encoding="utf-8").read().replace("\r\n", "\n").split("\n")
out = []
seen = set()
for ln in lines:
    m = re.match(r'^\s*"([^"]+)":\s*"(.*)"\s*$', ln)
    if m and m.group(1) in T:
        k = m.group(1)
        out.append('"%s": "%s"' % (k, T[k]))
        seen.add(k)
    else:
        out.append(ln)
for k in T:
    if k not in seen:
        out.append('"%s": "%s"' % (k, T[k]))

open(SCH, "w", encoding="utf-8").write("\n".join(out) + "\n")
print("written", len(T), "entries; total lines", len(out))
