# -*- coding: utf-8 -*-
import re

src = 'original/subtitle_us.txt'
out = 'schinese/subtitle_us.txt'

T = {
"Storye01_In_Crawl_02": "",
"Story19_In_18_Reynolds": "这儿可不是洛杉矶。",
"22_Choice_03_Angel": "不！我不能让他赢。咱们不能让他赢。",
"Story24_Out_05_Player_BM": "抱歉。",
"Story22_OutB_16_Space_Marines": "嗬啦！",
"Story21_In_06_Zach": "好吧，鲍比，这就是圣徒——在这儿可没人待见他们……",
"Story24_Out_02_Player_BM": "但我发现了点东西……该死。",
"Story16_Out_04_Matt": "真感人，不过我觉得该换个活法了。说实话，我有点怕……嗯……死。",
"Story15_In_07_Pierce": "你还能这么玩？",
"CTO_Angel01_07_Player": "没错——等等，你说啥？",
"Story07_Zscene03_02_Oleg": "而且你也不是杀霸手下的摔角手……",
"Story01_Zscene01_01_Josh": "我……我喘不上气。",
"Story24_Out_01_Player_BM": "我来火星是为了讨生活。低低调调，不惹麻烦。可我发现了东西……",
"CTO_Zimos02_01_Player_BM": "这画真他妈丑。",
"Story20_Out_02_Player_BM": "想挑最强的？那就来跟我打。",
"Story21_Zscene01_04_Zach": "等等，斯蒂尔沃特屠夫正朝安吉尔那边过去。",
"Story01_Zscene02_02_Gat": "别碰那东西！",
"CTO_Zimos02_05_Player_BM": "活儿干完再嗨。等我对晨星帮再动手时叫你。",
"Story15_In_18_Kinzie": "他的人现在怕是都快摸到电脑跟前了！快上！",
"Story12_In_11_Pierce": "鱼饵下对了他自会送上门。所以我才需要你跟那个新来的妹子。",
"Story21_In_10_": "我等不及了，动手吧！",
"Story10_Out_04_Reporter_02": "STAG 会怎样影响我们的日常生活？",
"Storye01_In_Crawl_09": "",
"Story07_Zscene01_09_Player_BM": "驾！",
"Story23_Out_11_Player_BM": "我可能有点用力过猛了。",
"Genki_Both10": "谋杀时刻！欢乐时光！",
"CTO_Kinzie01_04_Kinzie": "还不行。",
"Story16_Out_06_Matt": "当然。嗯，我得赶飞机了，所以——",
"Story12_Out_05_Monica": "什么？那就赶紧把他找出来，该死的！",
"CTO_Kinzie02_04_Player_BM": "听着，用这种方式聊天我有点别扭……",
"CTO_Pierce02_04_Player_BM": "听着，你或许觉得该歇歇了，但我可不想再跟这帮混蛋磨蹭。我要洛伦，现在就要。他在哪儿？",
"Story23_Out_15_Player_BM": "那咱们就开工吧。",
"Story15_Out_03_Player_BM": "我出五十块，你挑个好点的。",
"CTO_Pierce02_07_Player_BM": "洛伦是个战术家，他不会躲进一栋恨不得大喊“我是个犯罪天才”的大楼里。我得找点实打实的线索。",
"Story21_In_02_Bobby": "无比疯狂的一夜啊，扎克，正戏这就开场。",
"Story17_In_06_Viola": "我抱歉——你说囚犯？",
"Story17_Mid_04_Cyrus": "咋了？",
"Story07_Out_10_Viola": "你想让我们干啥，杀霸？",
"Story01_In_25_Player": "给乔什留点面子，他不过是在琢磨自己的角色。",
"CTO_Pierce02_10_Pierce": "不是，火药是市中心一家高档定制枪店……我看见洛伦的几个打手跟老板套近乎，那边准有文章。",
"CTO_Kinzie01_02_Kinzie": "不算吧，我讨厌人。",
"Story13_Zscene01_05_Pierce": "老大，你想怎么玩？",
"Story19_Out_01_Monica": "指挥官，你到底在搞什么鬼？！",
"Story19_In_14_Reynolds": "我这儿出了丧尸的麻烦，想——",
"Story15_Out_02_Kinzie": "快了。我还需要一把椅子。",
"Story13_In_06_Shaundi": "我的天，我能直接崩了这货吗？",
"Storye01_In_Crawl_07": "",
"Story16_Zscene01_03_Matt": "乐意之至。",
"Story19_In_24_Reynolds": "你那态度活像我从来没耍过准军事组织似的！搞定了再叫我。",
"CTO_Angel01_04_Angel": "所以你怕吃苦。这种软弱正好让摔角手钻空子。你不强硬起来，杀霸会捏碎你。不过别慌，我会把你雕成钻石。",
"CTO_Pierce01_06_Player_BM": "辛迪加会知道钥匙在我们手上——他们正等着我们动手呢。",
"Story10_Out_01_Cyrus": "我是赛勒斯·坦普尔，特种战术反帮派部队指挥官。今天来回答各位关于 STAG 计划的问题。",
"CTO_Kinzie02_03_Kinzie": "我是认真的。你那部花里胡哨的贵手机也该扔了，我照样能顺着它找到你。",
"CTO_Kinzie01_05_Player_BM": "你出来之后都干些啥了？",
"Story23_In_03_Player_BM": "敬肖迪！",
"CTO_Pierce01_02_Player_BM": "咋了？",
"Story16_Zscene01_05_Matt": "你还不明白吗？在这儿我就是上帝。",
"CTO_Angel02_04_Angel": "别光顾着招式忘了本意。你已战胜了恐惧。",
"CTO_Kinzie01_01_Player_BM": "我以为刚脱离囚禁的人会更想痛快享受一番。",
"Story23_In_07_Player_BM": "去他的。我们要砸了他们那破玩具。",
"Story22_OutB_04_Monica": "他们说的不无道理，指挥官……",
"Story07_Zscene02_05_Player_BM": "我没事。",
"Story21_Zscene03_01_Player_BM": "笑一个，杀霸，咱们要上全国直播了。",
"Story07_Zscene02_06_Player_BM": "找张湿巾什么的擦擦。咋了？",
"Story01_Zscene01_05_Josh": "家伙都在这呢，兄弟。",
"Story22_OutB_15_Player_BM": "杀霸正在整军备战，准备全面进攻。我们会在这儿挡住他。地球需要咱们……别让她失望。",
"Story21_In_05_Player_BM": "我会守在台边，帮你挡开摔角手，你只管收拾杀霸。祝好运，兄弟。",
"22_Choice_08_Kia": "等你们炸了马加拉奇岛，全世界都会看清你们的真面目。",
"Storye01_In_Crawl_03": "",
"CTO_Kinzie02_05_Kinzie": "完全同意。咱们该用那种……纳瓦霍密码方言什么的……",
"CTO_Pierce01_08_Player_BM": "走吧。",
"Story07_Zscene02_01_Player_BM": "抱歉让你……嗯……带着我们绕了一圈。",
"Story01_Zscene01_07_Gat": "想都别想。直接炸了它。",
"Story22_OutB_12_Player_BM": "还不行。",
"22_Choice_06_Player": "行行行，我懂。你们要抓我们，多大点事。",
"Story13_Zscene01_02_Pierce": "是啊，不过我们把你的招牌人物搞到手了。",
"Story06_Mid_04_Player_BM": "这他妈都是些什么？",
"Story21_Zscene01_02_Zach": "看得人揪心，摔角手们把安吉尔当沙包耍。",
"Story06_Zscene01_02_Player_BM": "该死！",
"Story01_Zscene01_10_Player_BM": "该干活了。",
"Story17_In_02_Viola": "我们不能大摇大摆闯进 STAG 的航母。",
"Storye01_In_Crawl_06": "",
"CTO_Zimos02_04_Zimos": "靠，还记得那场马戏团秀吗？我早就不招他们待见了。总之我叫你来不是聊我的。你干掉了菲利普·洛伦，让晨星帮知道你是要长期扎根的。该放松撒欢了，宝贝！",
"SH_Morningstar02_01_Monica": "虽说还没人认领斯蒂尔沃特那场袭击，但我们一直漠视它的根源。失控的媒体和被卖给孩子货色，把帮派文化美化成时尚，把反社会的疯子捧成了英雄。到此为止！",
"Story12_Out_04_Cyrus": "女士，我向您保证——我们一定把他救回来。",
"CTO_Zimos01_09_Player_BM": "听起来不错。",
"CTO_Zimos01_04_Zimos": "你要是嘴里叼着口球、屁股上插着马尾巴熬上几年，估计你也想松快松快。",
"Story20_In_02_Viola": "你想伤杀霸，就得伤他的名声。",
"CTO_Zimos01_07_Player_BM": "圣徒要想在钢埠待下去，就得把晨星帮赶走。市中心那块我已经清过了，可这帮狗娘养的到处都是。",
"Story17_In_09_Pierce": "哎哟，想都别想！",
"SH_Decker_04_Oleg": "NEMO 座椅。果然。",
"Story11_Out_04_Kia": "夜刃成了 STAG 的台面人物？你们干脆找个人套上该死的鹿皮算了？",
"Storye01_In_Crawl_08": "",
"CTO_Zimos01_03_Player_BM": "你办事不拖泥带水。",
"Story17_Mid_03_Kia": "欢迎回来，长官。",
"Story07_Zscene02_02_Zimos": "这是来救人的对吧？不是什么精心布置的群架陷阱吧？",
"Story20_Out_05_Killbane": "想被行走天启拆骨？我乐意为你效劳。",
"CTO_Zimos01_02_Zimos": "嘘，别把那几个娘们吵醒了。",
"Story17_Zscene01_02_Cyrus": "原来你叫这个名。",
"Story24_Out_04_Director": "卡！",
"CTO_Angel02_03_Player_BM": "一头该死的虎？！",
"Story07_Zscene03_03_Player_BM": "是啊，可他们确实是。",
"Story23_Out_09_Player_BM": "我有话传给莫妮卡·休斯和她的走狗。亲爱的贱人：钢埠已经易主，我们不归你管。这儿现在是境外飞地。再敢染指我的城市，你就得装在棺材里滚回去。完。",
"Story22_OutA_02_Player_BM": "嗯。",
"Story17_In_04_Viola": "你上了船之后会怎样？",
"Storye01_In_Crawl_05": "",
"Story16_Zscene02_03_Player_BM": "金齐肯定能琢磨明白。",
"Story24_Out_11_Director": "好……开拍！",
"Story07_Zscene02_04_Zimos": "那我当你是来救人的。本来想跟你握个手，不过这地板有点黏糊，你懂我意思吧。",
"Story07_Zscene01_05_Goon": "他们往这边跑了！",
"Story23_Out_04_Player_BM": "谁都不准跑，谁都不准开枪，明白吗？！",
"Story22_Zscene01_02_Killbane": "于是我们站在这里……两个凌驾凡人之上的泰坦，因带给他们血与火而被众生膜拜！这一刻注定无可避免……",
"Story16_Zscene02_07_Player_BM": "小子，这还像句人话……",
"Story23_Out_12_Pierce": "嗯，你刚才是缔造了一个城邦来着。",
"22_Choice_05_Kia": "你好啊，圣徒。",
"CTO_Pierce02_11_Player_BM": "咱们去逛逛街。",
"Story13_In_03_Josh": "我们初见那一刻我就感觉到了。那种默契。",
"22_Choice_01_Angel": "他在机场——没多少时间了！  ",
"Story21_Zscene02_02_Killbane": "等等！我把末日铁拳的秘技给你，只求你留下我的面具！",
"Story19_In_02_Viola": "你不保证规矩点，我们可不会进去。",
"Story17_Out_11_Kia": "长官，突击队已经在路上了。七十二小时内全城封锁完毕。",
"CTO_Angel02_02_Angel": "你要跟摔角手打，就得做好万全准备。",
"CTO_Angel01_02_Angel": "提醒我杀霸从我身上夺走了什么。这让我保持清醒。",
"CTO_Pierce02_05_Pierce": "不清楚——",
"Story21_Out_05_Goon": "杀霸，这只是一场比赛……",
"Story22_Zscene01_03_Player": "那我宰了你也是一样。",
"CTO_Pierce01_05_Pierce": "保险箱钥匙。话说，你就不想知道他们锁起来的到底是什么……？",
"Story22_Zscene01_05_Player": "你没开玩笑吧？都结束了，艾迪！再过两周，没人会记得你的名字。",
"CTO_Pierce01_03_Pierce": "这地方以前是辛迪加的老窝，我就想翻翻他们留下的东西。",
"Story12_Zscene01_02_Player_BM": "咱们撤吧。",
"Story21_In_07_Bobby": "一点都不——那边简直恨意倾盆。当然会这样；他们的大佬对斯蒂尔沃特干了那种事，粉丝没在去擂台的路上捅他们刀子就算走运了！",
"Story21_Zscene03_02_Killbane": "不！",
"Story24_Out_08_Director": "好了各位，露出大笑脸，皆大欢喜的结局来了。",
"CTO_Kinzie02_11_Kinzie": "记住，把手机扔了！",
"Story19_In_01_Player": "我们还等什么？",
"SH_Decker_03_Kinzie": "然后你就能跟用户的化身互动，腐蚀他们线上运作的基石——那些数据的抽象表征。要做到这点，我得——",
"CTO_Kinzie01_10_Kinzie": "先把这破游戏玩了，我就能锁定迪克帮在现实里的位置。",
"Story18_In_01_Viola": "搞不好有更省事的办法！",
"Story22_OutB_09_Cyrus": "他们能把整座城市的钥匙交给你，可你一旦搞砸，我们立马回来。下次，STAG 会直接摁死你们。",
"Story21_In_04_Bobby": "跟你说，扎克——这疯子就是个彻头彻尾的变态。你知道，这货出娘胎时直接用自己的脐带把接生医生勒到窒息，就他妈这么丧心病狂。",
"Story21_In_03_Zach": "他来了，鲍比——艾迪·“杀霸”·普赖尔，活生生的行走天启本尊。你不得不寻思，斯蒂尔沃特屠夫拿什么跟他掰手腕。",
"Story16_Out_03_Killbane": "我从菲利普的灰烬里像凤凰一样重生时，你一直跟着我。你和我——早就绑在一块了。",
"Story13_Out_05_Kia": "他们要钻地洞了——把人挖出来可不容易。",
"Story12_In_07_Player_BM": "这他妈是什么？",
"Story01_In_26_Shaundi": "希望他签了免责声明。",
"CTO_Pierce02_02_Pierce": "有啥好恨的？啤酒又便宜。",
"CTO_Zimos01_06_Zimos": "我猜你来这儿不是为了找软蛋。",
"Story07_Zscene01_01_Pierce": "咱们怎么找齐莫斯？就找屋里那个叼着口球还一脸享受的家伙？",
"Story21_Out_04_Bobby": "多疯的一夜啊，扎克。多。疯。的。一夜。",
"Story12_In_09_Player_BM": "提醒我给李律师打个电话说说这事。",
"Story10_In_05_Player_BM": "对。约翰尼的死是你害的。",
"Story01_In_24_Shaundi": "拍圣徒电影我没意见，但咱们非得拖着这个混蛋演员到处跑？",
"Storye01_In_Crawl_04": "",
"Story11_Out_08_Cyrus": "那小子会把自己玩死的。",
"Story21_Zscene04_02_Bobby": "我的天！杀霸认输了！",
"Story19_In_06_Player": "我是说，这货以为自己是谁啊？",
"Story17_Mid_02_Cyrus": "安静。",
"Story13_In_08_Player_BM": "东西到手了吗，皮尔斯？",
"Story11_In_04_Player_BM": "这下打平了。",
"Story13_Zscene01_03_Player_BM": "我要 STAG 滚出我的城市。",
"Story23_In_06_Kinzie": "嗯，要是他们把每栋楼都炸了，咱们总归会摊上一栋。",
"Story19_In_15_Viola": "等等，什么麻烦？",
"Story15_In_05_Player_BM": "迪克帮到底对直升机干了什么鬼？",
"CTO_Angel01_06_Angel": "让你尝遍能想象的最痛……好了，该去车流里练练了。",
"CTO_Angel01_05_Player_BM": "怎么练？",
"Story12_Zscene01_01_Josh": "开拍前各位想先热个身不？嘿，你看上去有点眼熟……",
"Story22_OutB_03_Player_BM": "除非你这张嘴接下来吐出的是“谢谢”——不然咱们就有大麻烦了。",
"Storye01_In_Crawl_01": "",
"CTO_Angel02_06_Angel": "你已能直面杀霸，但摔角手还得收拾。要再加练，你知道上哪找我。",
"22_Choice_09_Player": "我不想让你失望，贱人，但圣徒可不是搞本土恐怖主义的。",
"CTO_Angel01_01_Player_BM": "靠——你为啥窝在这种破地方？",
"Story21_Zscene03_03_Zach": "这简直是安吉尔·德·拉穆埃特的翻版，杀霸被揭了面具！",
"Story21_In_10_Bobby": "历史今夜正在书写，扎克！几年前那场胜负存疑的败仗之后，安吉尔就从地球上消失了。如果你是谋杀乱斗的粉丝，今晚注定是你人生最棒的一夜。",
"Story20_In_07_Viola": "杀霸绝不会答应跟安吉尔打。",
"Story17_In_03_Player_BM": "为啥不行？我看着就跟赛勒斯一个样——只要再摆副欠揍的臭脸。",
"Story17_Zscene01_01_Cyrus": "琪亚，我正回温泉关去审那个囚犯。确保没人能接近她。",
"Story16_Zscene01_06_Player_BM": "那正好。在现实里你不过是个敲键盘的贱货。",
"Story16_In_06_Player_BM": "动手吧……",
"Story17_Mid_05_Kia": "有些我正在研制的原型机，需要您签字批准。",
"Story16_Zscene01_02_Player_BM": "躲起来当缩头乌龟当然笑得轻松。有种出来！",
"Story07_Zscene03_01_Angel": "你不是洛伦手下的打手。",
"Story16_In_02_Player_BM": "总比被人拿枪指着强。",
"Story14_In_05_Killbane": "荣幸之至，简……对了，请叫我杀霸。",
"Story16_Zscene02_01_Matt": "等等！",
"Story06_Zscene01_03_Oleg": "那是直达地下层的快车……追不上他了。",
"Story24_Out_03_Player_BM": "词。",
"Story09_Out_06_Killbane": "对……就是这样……都给我听好……",
"SH_Morningstar02_05_Zimos": "要是人人有免费成人片看——我举双手赞成。",
"Genki_Zach03": "杀穿元气博士的超级闪亮实验室，既能找乐子又能赚大钱！",
"SH_Luchadore_02_Angel": "丢了面具是摔角手最大的耻辱。我偷不回来，得自己赢回来。",
"Story07_In_14_Shaundi": "瞧好咯。",
"Story07_In_13_Oleg": "你还没准备好跟辛迪加打。",
"CTO_Zimos02_03_Player_BM": "既然咱们刚让他们知道要接管生意，那笔交易我估摸着撑不了多久。",
"Story01_Zscene02_06_Gat": "甭管了，他死不了。",
"Story21_In_08_Bobby": "等等，我的天！快看那——是安吉尔·德·拉穆埃特！",
"Story16_Out_08_Killbane": "随时可以把我写进你的推荐人列表。",
"CTO_Kinzie01_08_Kinzie": "在弄清迪克帮藏身之处前，我帮不了你扳倒他们。所以我写了个程序，能追踪用户登录时的物理位置。",
"Story21_Zscene01_03_Bobby": "他被踹得跟一袋死小狗似的。",
"Story01_Zscene02_01_Josh": "嘿各位，直升机可以撤了，我找到开保险库的法子了！",
"Genki_Both05": "丧心病狂！",
"22_Choice_07_Kia": "我不想逮捕你；那解决不了问题。百姓该醒醒了，看清你这种人渣对无辜者的威胁。",
"CTO_Pierce02_01_Player_BM": "皮尔斯，这地方可不像你会来的。",
"Story07_Zscene01_08_Player_BM": "没时间了，齐莫斯！",
"Story17_Out_13_Kia": "允许我直言吗？",
"Story17_Out_01_Player_BM": "这段得写进书里。",
"CTO_Kinzie02_02_Player_BM": "知道了……",
"CTO_Pierce02_06_Pierce": "——但我赌一万块，他躲在那栋大得离谱的摩天楼里。",
"Story23_Out_13_Player_BM": "说得在理。这倒提醒我了：这地方得换个新市长……你对公职有兴趣不？",
"Story06_Zscene01_01_Oleg": "洛伦的办公室在这边！",
"Story20_In_03_Shaundi": "所以，咋样，要羞辱他？",
"Story19_In_22_Player": "清理亡灵倒不是咱的强项，不过可以试试。",
"CTO_Kinzie02_06_Player_BM": "冒个泡？迪克帮我已经解决了。",
"Story01_Zscene01_08_Josh": "什么？！",
"Story22_OutB_02_Cyrus": "站住！",
"Story19_In_21_Reynolds": "所以说呢，小子？",
"Story07_Zscene01_02_Player_BM": "或者直接找背上镶着水钻 Z 字的那个。",
"Story23_Out_02_Newscaster": "政府尚未就此次袭击置评，不过我们收到一则消息——",
"Story20_In_10_Pierce": "放松——你穿泳裤绝对辣翻天。",
"Genki_Bobby04": "现在，每放倒一个男人、女人或老虎，奖金就往上飙。可留神！没人乐意看你打熊猫！",
"Story19_Out_02_Cyrus": "出了点……岔子，参议员。",
"Story07_Zscene01_06_Player_BM": "该死……",
"Story07_Zscene01_03_Pierce": "赶紧滚蛋吧你——",
"Story17_Out_09_Monica": "有进展随时汇报，指挥官。",
"Story15_In_12_Kinzie": "差不多这样。",
"Story07_Zscene02_03_Pierce": "兄弟，你非得往我脑子里塞这画面？",
"Story16_In_05_Kinzie": "知道。准备好了？",
"SH_Morningstar02_11_Zimos": "算吧。我打算把你当性奴拍卖掉。",
"Story08_Out_06_Matt": "老天，杀霸——！",
"Story07_In_18_Shaundi": "这帮家伙到底什么来头？",
"CTO_Kinzie01_07_Player_BM": "你真要我命了，金齐。",
"Story23_Zscene01_02_Player_BM": "落得漂亮的，赛勒斯。",
"Story01_Zscene01_02_Shaundi": "呃……",
"Story22_Zscene01_07_Player": "放屁。",
"CTO_Pierce01_04_Player_BM": "所以我在看什么？",
"CTO_Pierce01_01_Pierce": "瞧这个，老大……",
"CTO_Kinzie01_03_Player_BM": "哦。那你对迪克帮有没有什么料？",
"Story22_In_03_Player_BM": "去他的，咱们不当公司走狗了。所以谁赢——",
"Story19_In_03_Player": "你认真的？",
"Story17_Out_04_Shaundi": "那 STAG 呢？",
"Story19_In_25_Player": "我的天，这货也太牛了！",
"Story17_Out_12_Cyrus": "出色。谢谢你，琪亚。",
"Story10_In_18_Kia": "是，指挥官。",
"Story21_In_09_Zach": "安吉尔·德·拉穆埃特：苍白骑士组合的后半壁；有时被誉为行走天启的先驱；史上最年轻夺得超级 K 杯的摔角手，此刻就在钢埠竞技场！",
"Story20_In_09_Shaundi": "无意冒犯，但你有点离谱。",
"Story20_In_01_Player_BM": "行了，我懒得再瞎折腾，我要杀霸。",
"Story21_Zscene04_01_Player_BM": "想求饶？拍地认输。",
"Story19_In_05_Player": "听好，甜心——我看谁不爽就收拾谁。",
"SH_Decker_07_Kinzie": "迪克帮也有一台。",
"Story15_In_11_Player_BM": "你需要什么？",
"Story22_Zscene01_01_Player": "哎哟我靠！",
"CTO_Kinzie01_09_Player_BM": "这……挺带劲？",
"CTO_Pierce01_07_Pierce": "那看来你得替我兜底了。",
"Story07_Zscene01_04_Pierce": "啧。该死。真会挑时候。",
"Story22_OutB_10_Player_BM": "我也爱你，赛勒斯。",
"Story20_In_06_Player_BM": "这更像是安吉尔的活儿。",
"Story22_OutB_11_Pierce": "那接下来怎么走，老大？咱们回斯蒂尔沃特接着混？",
"Story22_OutB_06_Cyrus": "你跟我开玩笑呢，女士？",
"Story20_Out_03_Killbane": "最强？最强是在蒂华纳脚手架赛里干翻蜘蛛神斯韦；最强是一晚上卫冕世界冠军十三次；最强是拖着两条断腿赢下大逃杀……信我吧，小伊卡洛斯：你飞得离太阳太近了。",
"Story19_In_19_Player": "我晚点告诉你。",
"Story12_In_06_Kid": "能给我签个名吗？",
"Genki_Zach07": "但你要是以为这么简单——那你可没见识过元气博士！",
"Story01_Zscene04_01_Player_BM": "唔……该死。",
"Story10_Out_06_Reporter_03": "我不是这个意——",
"Story06_Zscene01_04_Player_BM": "操。那个。",
"Story23_Out_10_Pierce": "不赖。你当个天气预报员之类的也行。",
"Story22_Zscene01_06_Killbane": "没人会记得我？你不过是个小丑，卖卖能量饮料和午餐盒。你不在乎观众，只在乎支票。是我改变了这一切。",
"Story16_Out_09_Matt": "哦天！",
"Story22_OutB_08_Monica": "有什么问题我都可以回答……",
"Genki_Zach09": "祝好运——",
"CTO_Zimos01_05_Player_BM": "有道理。",
"Story19_Out_06_Cyrus": "丧尸和莫妮卡·休斯——？",
"Story07_Zscene02_07_Kinzie": "我找到我说的那个人了……",
"Story17_Out_06_Cyrus": "你早知道会走到军事管制这一步，对吧。",
"CTO_Zimos01_01_Player_BM": "嘿，齐——",
"Story13_Zscene01_01_Cyrus": "投降吧，小子。包围圈我们已经布好了。",
"Story22_In_02_Pierce": "李律师回话了。片方想让你去试镜《太空匪帮》。",
"CTO_Angel02_01_Player_BM": "一头虎？",
"Story10_Out_02_Reporter_01": "STAG 会占领钢埠多久？",
"Genki_Bobby06": "攒够钱后实验室的门就会打开，到时候你随便走。",
"Story22_Zscene01_04_Killbane": "啊不不……剧本不是这么写的。圣徒的传说就此终结——不是轰轰烈烈，而是悄无声息。",
"CTO_Angel02_05_Player_BM": "你他妈是脑子有毛病？",
"Story02_Zscene01_02_Gat": "成，斯蒂尔——那边见",
"Story22_Zscene01_09_Player": "老兄，封住你的嘴我会很享受。",
"Story21_Zscene02_01_Player_BM": "准备好特写镜头了吗？",
"Story01_Zscene02_03_Shaundi": "乔什……你是想把咱们全送进号子？",
"Story24_Out_10_Sound_Guy": "语速！",
"Story23_Out_06_Player_BM": "金齐，你在播报亭里吗？",
"SH_Luchadore_01_Player_BM": "咱们来这儿干啥？",
"Story23_Out_16_Jane": "即便在这见惯了暴力的城市，今天的袭击也堪称钢埠不堪历史中最黑暗的一页。",
"Story23_Out_05_Player_BM": "抱歉……",
"Story20_Out_01_Killbane": "女士们先生们……斯蒂尔沃特屠夫大驾光临。",
"Genki_Bobby08": "哦，还有一事。这节目里谁都不准歇着。想继续打，就记得打急救靶。",
"SH_Decker_08_Oleg": "不可能。他们怎么能把信号藏起来？",
"CTO_Kinzie02_10_Player_BM": "行，要是还需要帮忙我再找你。",
"Story16_Zscene02_05_Player_BM": "马特，你这话说得太含糊，得再清楚点。",
"Story23_Out_01_Player_BM": "金齐，把能找到的圣徒都集结起来……咱们要出门踏青了。",
"Story22_OutA_03_Pierce": "值吗？",
"Story17_Out_03_Viola": "现在我们可以专心对付杀霸了。",
"Story14_Out_04_Player_BM": "我干了什么，我他妈不知道！",
"Story11_Out_06_Cyrus": "震慑必胜，参议员。批准动用代达罗斯号，一切就结束了。",
"Story01_Zscene02_05_Shaundi": "非得我去追他不可吗？",
"Story14_Out_07_Player_BM": "知道知道。不怪你，只是出了点诡异的事——",
"22_Choice_04_Player": "安吉尔，撑住，等我赶到——该死——",
"Story03_Zscene01_01_Pierce": "……我最爱闪亮登场。",
"Story23_Out_07_Kinzie": "准备就绪。",
"Story19_Out_07_Cyrus": "该死。",
"Story08_In_10_Pierce": "咋了妹子？",
"CTO_Kinzie02_07_Kinzie": "当然，你一松懈，他们转头就把你描成给摩萨德卖情报、还兼职当女霸主的模样。",
"CTO_Kinzie02_01_Kinzie": "你该更小心点。两个街区外我就瞄见你了。这城里到处是交通摄像头。",
"Story21_Out_08_Killbane": "……而我正好可以隔岸观火，悠哉得很……",
"Story13_Out_04_Cyrus": "我得抓圣徒的把柄。把目标带进来审问。",
"22_Choice_02_Player": "安吉尔——",
"Storye01_In_Crawl_10": "",
"Story17_Out_05_Pierce": "咱们刚炸了一艘航母……他们还能拿出什么狠招？",
"CTO_Zimos01_08_Zimos": "我是来帮忙的，宝贝。晨星帮操盘的每一条门道我都门儿清。咱们能壮大自己的班底，顺便捅一刀迪威特姐妹。",
"Story01_Zscene01_09_Josh": "太不厚道了哥们！",
"Story15_In_01_Kinzie": "你可以关灯。",
"Story13_In_10_Pierce": "你是故意的。",
"Genki_Zach01": "你好钢埠，欢迎来到元气博士的超级伦理真人秀高潮！",
"Story01_Zscene02_07_Shaundi": "咱们开直升机把这宝贝吊走。",
"Story22_Zscene01_08_Killbane": "记好了——当这双手掐住你喉咙时，你咽气前不会向神祈祷，也不会对家人表白爱意。你会说：“谢谢您，杀霸。”",
"Story01_In_27_Shaundi": "说“下三滥”！",
"Story02_Zscene01_03_Shaundi": "约翰尼……",
"Story22_OutB_07_Monica": "你宣布军事管制，还拆了半座城。圣徒刚救下一座珍贵纪念碑。你觉得到底公众会站谁那边？",
"Story13_In_07_Player_BM": "肖迪——规矩点，这回。",
"Story10_In_01_Oleg": "薇奥拉，我没看出来你还是个艺术赞助人。",
"Story07_In_15_Player_BM": "放松点，肖迪。好了大块头，你手里有什么？",
"22_Choice_10_Kia": "等肖迪和薇奥拉在废墟里被找到时，看还有多少人信你这套。",
"Story21_Zscene04_03_Zach": "行走天启任凭双臂被折断也不认输，而斯蒂尔沃特屠夫却创造了奇迹！",
"Story16_Zscene02_04_Matt": "整个世界简直就在我的指尖上。",
"Story19_Out_03_Monica": "岔子？！别跟我扯什么岔子——我要的是结果！",
"Story11_Out_05_Monica": "得民心者得天下，亲爱的。",
"Story10_In_09_Player_BM": "你能规矩点吗？",
"CTO_Kinzie01_06_Kinzie": "代练升级。",
"Story19_Out_05_Monica": "就算国会点头，国土安全部也绝不会批准！这已经失控了。我要亲自来钢埠！",
"Story21_Zscene03_04_Bobby": "我们见识了行走天启的真容，说实话，就是个发际线后移的男人",
"Story01_Zscene02_04_Josh": "啥？我可不想当哪个男人的小弟！",
"Story01_Zscene01_04_Player_BM": "乔什，过来一下……",
"Story02_Zscene01_01_Shaundi": "约翰尼，我们要跳了！",
"Story11_In_06_Player_BM": "这儿不安全。你们先撤，我给你们拖点时间。",
"Story14_Out_09_Shaundi": "给我学会飞！",
"Story19_Out_04_Cyrus": "你要结果？那就批准动用代达罗斯号！",
"Story15_In_06_Kinzie": "肯定是马特黑进了它的飞行电脑，用电磁脉冲烧了主板。",
"Genki_Bobby02": "该见识这游戏怎么玩了！",
"Story13_Zscene01_04_Cyrus": "没门。STAG 的使命是肃清钢埠的帮派。不过火力往哪打由我说了算。放了伯克，咱们就去狠捶辛迪加一阵子……给你们哥几个喘口气。",
"Story22_OutB_01_Player_BM": "咱们回家吧。",
"Story17_Mid_08_Cyrus": "谢了。",
"Story17_In_08_Player_BM": "好戏开场。",
"Story16_Zscene02_06_Matt": "你报出一家公司名字，它就归了圣徒。你收回你的帝国，我拍拍屁股走人。",
"SH_Luchadore_04_Angel": "我们伤了很多人。",
"Story14_In_01_Player_BM": "咋了？",
"CTO_Angel01_03_Player_BM": "你怎么舒服怎么来，我只是说，我住的地方好歹得有暖气。",
"Story17_Out_10_Cyrus": "当然，女士。",
"CTO_Pierce02_08_Pierce": "那就去火药。",
"Story14_In_02_Kinzie": "你得看看这个……",
"CTO_Kinzie01_11_Player_BM": "这还差不多。",
"Story21_Zscene01_05_Bobby": "一个人能折腾出——",
"Story16_Zscene01_04_Player_BM": "搞什么鬼……",
"Story19_In_20_Viola": "你早就知道这事？",
"Story17_Out_07_Monica": "我认识圣徒。雷诺兹市长什么反应？",
"Story14_In_07_Killbane": "不不，简，亲爱的，求你了。圣徒是罪犯。你尽管说我有怪癖，但我不过是个艺人兼商人兼慈善家兼——",
"Story19_In_09_Reynolds": "除了我谁还撑得起这座城？再说了，我爱我的选民。",
"Story07_Out_12_Player_BM": "找这些家伙聊聊，他们手上有活儿给你干。现在轮到咱们了——开工。",
"Story02_In_30_Shaundi": "那飞机呢？",
"Story17_In_05_Player_BM": "我押着囚犯进去，他们带我去牢区，我拽上肖迪就走。",
"Story15_In_09_Player_BM": "那咱们怎么钉死迪克帮？",
"CTO_Pierce02_03_Pierce": "——而且这儿就数我最靓。",
"SH_Decker_02_Kinzie": "我想把你的潜意识广播进迪克帮的用户网。",
"CTO_Kinzie02_09_Kinzie": "咱们闹出的动静已经够大，你可以去对付马特·米勒了。但你要是想让迪克帮彻底消失——我是说，真的消失——那活儿还多着呢。",
}

missing=[]
seen=set()
out_lines=[]
for raw in open(src,encoding='utf-8'):
    line=raw.rstrip('\n')
    if line.strip()=='':
        continue
    m=re.match(r'^"([^"]+)":\s*"(.*)"\s*$', line)
    if not m:
        raise SystemExit("UNPARSED: "+line)
    k=m.group(1)
    if k in seen:
        # duplicate key, translate again
        out_lines.append('"%s": "%s"'%(k, T.get(k,'')))
        continue
    seen.add(k)
    if k not in T:
        missing.append(k); continue
    out_lines.append('"%s": "%s"'%(k, T[k]))

if missing:
    raise SystemExit("MISSING KEYS: "+", ".join(missing))
open(out,'w',encoding='utf-8').write('\n'.join(out_lines)+'\n')
print("written", len(out_lines), "lines")
