# -*- coding: utf-8 -*-
# 接管重译 subtitle：从 original/subtitle_us.txt 抽 KEY，逐条重写中文。
# 保留优质译文、修正译名漂移（肖迪/肖恩蒂→肖蒂），统一术语（安吉尔/肖蒂/元气杯等）。
import re, os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCH = os.path.join(BASE, "schinese", "subtitle_us.txt")
ORG = os.path.join(BASE, "original", "subtitle_us.txt")

src = open(ORG, encoding="utf-8").read().replace("\r\n", "\n")
od = dict(re.findall(r'^\s*"([^"]+)":\s*"(.*)"\s*$', src, re.M))

# 逐条重译（KEY -> 中文）。基于优质原译，修正译名。
T = {
 "Story05_Out_04_Phillipe": "圣徒不过是空洞威胁拼凑出的白噪音罢了。",
 "Story02_In_31_Gat": "我这就把飞机开回斯蒂尔沃特。",
 "Story18_In_03_Trooper": "我听见枪声了，这边！",
 "Story17_Mid_10_Agent": "不许看指挥官！",
 "Story03_Out_04_Pierce": "姑娘，这种事不用你弄脏手。交给我们来办。",
 "Story13_In_02_Shaundi": "我没事。",
 "Story06_Out01_01_Player_BM": "是时候回家给强尼下葬了。",
 "Story17_Out_08_Cyrus": "他会归顺的，他们全都会。",
 "Story13_Out_08_Kia": "我会找到她的。",
 "Story10_Out_05_Cyrus": "等我们打赢城市反恐这场仗，你们和你们的家人就能重获安全。",
 "Story08_In_09_Pierce": "我操！这帮妹子根本不是妹子！",
 "Story19_In_08_Player": "伯特·他妈的·雷诺兹？！",
 "SH_Morningstar01_01_Player_BM": "里面一帮持枪的家伙。咱们从后面绕进去。",
 "Story02_In_27_Gat": "老大——快跳伞！",
 "Story09_Out_03_Killbane": "我是将军，我是沙皇，我是行走的末日——拿主意的是我，不是你！",
 "Story08_Out_10_Killbane": "道歉我收下了。送你一张屠杀格斗的VIP通行证，保管让你心情好起来。",
 "Story02_In_09_Viola": "这正是我们雇主想找你谈的原因。",
 "Story13_In_04_Shaundi": "什么。",
 "Story02_In_25_Phillipe": "我原本还满心希望，咱们能理性地谈成一桩生意呢。",
 "Story01_In_04_Shaundi": "哥们儿，你就是个跟着凑热闹的——",
 "Story15_Out_04_Kinzie": "真有意思。等这台玩意儿架好了，我再统统解释给你听。",
 "Story12_In_05_Kid": "呃……打扰一下？",
 "Story05_Out_01_Matt": "圣徒是不会就此罢手的……",
 "Story15_In_04_Kinzie": "禁止睡觉。",
 "Story06_Mid_06_Pierce": "既然都能克隆你了，他们干嘛还把你吊在这儿？",
 "Story02_In_28_Player_BM": "没有你我不走。",
 "Story02_In_16_Phillipe": "显然不是，不然你们也不会抢我们的银行。也许你正琢磨，自己到这会儿怎么还能喘气。",
 "Story01_In_22_Player_BM": "这正是我的计划。",
 "Story09_In_02_Player_BM": "等这地方归了我们，晨星帮的皮肉生意也就到头了。",
 "Story08_In_03_Zimos": "我被套上鞍子在人肉小马秀里供人骑，可你见过我为此哭鼻子吗，小姑娘？",
 "Story02_Out_02_Phillipe": "……薇奥拉和琦琦会把话放出去：钢埠属于辛迪加，圣徒在这儿不受欢迎。",
 "Story02_In_15_Shaundi": "没听说过。",
 "CTO_Pierce02_09_Player_BM": "我可没工夫搭理什么脱衣舞女。",
 "Story22_OutB_05_Monica": "不管你愿不愿意……圣徒都是英雄。",
 "Story11_Out_07_Monica": "绝对不行。",
 "Story10_In_08_Viola": "我能亲眼看着杀霸受罪。",
 "Story09_In_03_Zimos": "这帮娘们你打算怎么运走？",
 "Story02_In_22_Player_BM": "听着，你个法国混蛋——",
 "Story02_In_07_Gat": "合着就为这个？",
 "Story01_In_06_Josh": "我可是方法派演员。要想把圣徒演出几分真实的情感，我就得来真的。",
 "Story16_Out_01_Killbane": "马蒂，我真希望你能再想想。我这双手天生是用来撕筋碎骨的，不是用来二指禅戳键盘的。",
 "Story02_Out_01_Phillipe": "先生们，谈判的结果……不太成功。",
 "Story07_Out_03_Killbane": "我心里另有人选。",
 "SH_Morningstar01_04_Pierce": "那里面呢，混账东西？",
 "Story02_In_01_Player_BM": "搞什么鬼，这个月我们可是交过钱了。",
 "Story19_In_13_Player": "呃，好啊，太棒了！您有什么吩咐？",
 "Story17_Mid_07_Agent": "长官，我可以把这两个人押去拘留室。",
 "Story06_Mid_05_Oleg": "菲利普喜欢定制的东西——而他那些壮汉打手，都是照着我的模子造的，明白吗？",
 "Story22_OutA_04_Monica": "你说得对，指挥官。让代达罗斯进场。",
 "Story19_In_04_Viola": "跟我念：别惹市长。",
 "Story22_In_01_Player_BM": "所以，出什么事了？",
 "Story03_Out_08_Player_BM": "放松点，肖蒂——全都包在我们身上。",
 "Story02_In_06_Player_BM": "咱们这块招牌值他妈一大笔钱……",
 "Story12_Out_03_Cyrus": "他们抓了伯克。",
 "Story20_In_05_Viola": "摘掉杀霸的面具，剩下的就只有埃迪·普赖尔。那比要了他的命还狠。",
 "Story14_In_06_Anna": "杀霸，有人说你是个罪犯。",
 "Story12_In_12_Viola": "我叫薇奥拉。",
 "Story03_Out_06_Player_BM": "行。嗯……既然要把兄弟们接过来，咱们就得找个新据点。",
 "Story22_In_08_Player_BM": "咱们得赶到那儿去。",
 "Story20_In_04_Player_BM": "咱们就不能直接宰了那混蛋吗？",
 "SH_Decker_06_Oleg": "NEMO——神经电磁梦境观测仪。克格勃早就毁掉了世上唯一一台。",
 "Story12_In_01_Viola": "哟，快看——皮尔斯还识字呢。",
 "Story07_In_09_Oleg": "他是辛迪加豢养的恶犬。",
 "Story06_Mid_10_Oleg": "相信我——要杀菲利普，我的力气还够用。",
 "SH_Morningstar01_02_Pierce": "你觉得后面就没人守吗？",
 "Story03_Out_02_Player_BM": "下一步就是：你先回斯蒂尔沃特去。",
 "HASH_29CD6718": "我知道我有。",
 "Story09_Out_07_Monica": "各位尊敬的同僚。时机已到……我们已将 STAG 部署至钢埠。",
 "Story06_In_02_Shaundi": "把那把该死的枪给我，皮尔斯。",
 "Story07_In_08_Player_BM": "杀……什么霸？",
 "Story05_In_04_Player_BM": "干吧。",
 "Story02_In_19_Viola": "圣徒/乌托尔传媒集团随你们继续经营，作为交换，我们要抽走你们每月总收入的66%。",
 "Story01_Zscene03_01_Player_BM": "快！快！快！",
 "Story22_OutA_01_Pierce": "那狗娘养的让你给宰了？",
 "Story06_Mid_07_Oleg": "那些复制品有缺陷。他们有我的蛮力，却没有我的脑子。我可以帮你们。",
 "Story12_In_15_Player_BM": "我没意见。",
 "SH_Morningstar02_04_Player_BM": "这个“STAG 计划”到底是什么鬼……？",
 "Story08_In_08_Pierce": "我说姑娘——人活着就得及时行乐嘛，你懂我意思吧？",
 "Story14_In_04_Anna": "……埃迪·“杀霸”·普赖尔。谢谢你来到现场，埃迪。",
 "Story06_In_03_Player_BM": "让那狗娘养的尝尝他应得的下场。",
 "Story16_Out_02_Matt": "呃，要是打字是问题，我可以推荐几款好用的语音识别软件——",
 "Story05_Out_05_Matt": "恕我直言，先生……",
 "Story18_Out_01_Player_BM": "操，我这破命。",
 "Story12_Out_02_Cyrus": "给我接莫妮卡·休斯。",
 "Story23_Out_14_Pierce": "这主意烂透了。算我一个。",
 "Story12_In_04_Pierce": "只要布置得当，咱们就能打那帮狗娘养的一个措手不及。",
 "Story13_Out_02_Kia": "看来该道声恭喜了，指挥官。",
 "Story08_In_07_Shaundi": "随便。",
 "Story05_In_03_Shaundi": "兄弟们都在楼下候着了——你一声令下，我们就去砸场子。",
 "CTO_Zimos02_02_Zimos": "你这个俗不可耐的土包子！你懂什么叫艺术？这可是德温特姐妹的原作！当年我和那对双胞胎还“井水不犯河水”的时候买下的。",
 "Story24_Out_09_Asst_Director": "都安静！准备开拍——",
 "Story01_In_21_Gat": "你有啥计划没，还是说咱们直接把这帮狗娘养的全突突了？",
 "Story22_In_06_Pierce": "我的。老天啊。",
 "SH_Luchadore_03_Player_BM": "行，那咱们怎么干？",
 "Story17_Mid_06_Cyrus": "谢谢你的好意……老兄……但这两个人我要立刻处理。",
 "Story14_Out_06_Shaundi": "我刚才差一点就得手了！",
 "Story14_In_03_Anna": "……幸好这段独家影像得以曝光，此刻负责此事的先生正在我们直播现场……",
 "Story12_In_02_Pierce": "姑娘，这事我还真不用跟你交代。STAG 把夜刃当成他们的吉祥物。咱们把那小子掳来……",
 "Story09_In_01_Zimos": "这上面可全是娘们啊。",
 "Story06_Mid_09_Shaundi": "反正他还能干什么？那堆电线和乱七八糟的玩意儿八成就是他续命的家伙。",
 "Story01_In_10_Josh": "超后现代主义。我爱死了。",
 "Story17_In_01_Pierce": "这是你这辈子出过最烂的主意。",
 "Story14_Out_05_Player_BM": "你没事吧？",
 "Story08_In_01_Shaundi": "强尼人都死了，你们还在开派对？！",
 "Story18_In_02_Player_BM": "那还用说！",
 "Story14_Out_02_Shaundi": "明白。",
 "Story10_Out_07_Cyrus": "我来给你讲讲杰西卡·帕里什的故事吧。一个斯蒂尔沃特的姑娘，为了跟她的硬汉男友在一起离家出走。杰西卡本以为自己日子过得挺美，直到一个黑帮分子绑架了她，把她塞进汽车后备箱，然后在她男友开着怪物卡车把她活活碾死的场地里开怀大笑。如果杰西卡·帕里什是你的女儿……你希望我做到哪一步为止？",
 "Story02_In_17_Gat": "话说回来，我都纳闷儿这会儿我的脚怎么还没踹你屁股上。",
 "Story13_In_01_Josh": "把枪放下。我不会跑的。",
 "Story07_In_01_Monica": "当年我离开斯蒂尔沃特进军参议院时，我发誓绝不忘记故乡的根。我的丈夫为保卫斯蒂尔沃特、抵御黑帮暴行献出了生命。能以这座桥向他致敬，是我最大的荣幸。",
 "Story01_In_12_Josh": "谁动谁死！！",
 "Story07_Out_01_Killbane": "好了，女士们先生们，菲利普死了，我们正站在十字路口。问题是：谁将带领辛迪加走向新时代。",
 "Story14_Out_08_Player_BM": "操！",
 "Story12_In_14_Viola": "你不是认真的吧——！",
 "Story12_In_03_Player_BM": "还能把 STAG 引出来。",
 "SH_Morningstar02_12_Player_BM": "妈的。不干。",
 "Story05_Out_06_Matt": "我想说，“空城”这词已经不适用了。",
 "Story01_In_14_Josh": "抱歉，抢了他的词儿。能再来一遍吗？",
 "Story10_In_16_Kia": "圣徒正和德温特姐妹中的一个躲在掩体里。我们准备突入。",
 "Story08_Out_08_Killbane": "薇奥拉，你的太阳正在西沉，但现在回头还不晚。还有时间抓住阿波罗的太阳战车，赶着那玩意儿横跨天穹杀回来。听懂了吗？",
 "Story02_Out_03_Phillipe": "杀霸先生，带上你的摔跤手帮，把他们老大的脑袋给我带来。米勒先生，黑进圣徒的账户，一分钱都别给他们留。",
 "Story19_In_16_Reynolds": "丧尸。",
 "Story15_In_10_Kinzie": "要是能钻进他们的主机，我能干出一票淘气的坏事。可我手头没那套装备。",
 "Story06_Mid_12_Pierce": "兄弟，要不要弄身衣服穿？",
 "Story02_In_08_Viola": "盖特先生，这世上永远绕不开一个钱字。",
 "Story06_Mid_14_Pierce": "哥们儿，我说过了，上次那个光屁股的大块头……",
 "Story07_Out_05_Viola": "你说什么？",
 "Story02_In_02_Cop": "有人出的价更高。",
 "SH_Morningstar02_09_Zimos": "这等于是在邀请咱们朝晨星帮的娘们窝狠狠踹上一脚。他们今晚有场拍卖会——亮出那张卡，你就能进门。",
 "Story06_In_01_Pierce": "你穿这号有点大。",
 "Story01_In_01_Josh": "拍日本广告。这钱挣得比什么都容易。",
 "Story08_Out_09_Viola": "是，杀霸。",
 "Story02_In_14_Phillipe": "还原度相当高。这两位佳人便是薇奥拉和琦琦。而我，是菲利普·洛伦，跨国组织辛迪加的主席。",
 "Story14_In_12_Kinzie": "要是你去广播塔那儿，我兴许能三角定位出他们的拍摄位置——",
 "Story06_Mid_13_Oleg": "没时间了。",
 "Story06_Mid_08_Pierce": "上次有个光屁股的大块头跟我说他能帮我，结果下场可不太妙。",
 "Story21_In_01_Zach": "今晚真是太精彩了，而且势头一点没减，鲍比！",
 "SH_Decker_11_Player_BM": "行了，书呆子时间到此为止！这玩意儿到底是啥——还有金吉——看在老天的份上，说人话！",
 "Story10_Out_03_Cyrus": "根本不存在什么“占领”。我们得到了雷诺兹市长的全力支持。",
 "Story02_In_18_Phillipe": "由不得你，盖特先生，我们组织正在向斯蒂尔沃特扩张。我给你一个机会，拿你们的命抵你们的产业。两位美女？",
 "Story13_In_05_Josh": "禁忌之恋。",
 "Story01_In_16_Josh": "排队去，贱人！",
 "Story01_Zscene01_06_Josh": "那 B 计划是啥，咱们凿开它？",
 "Story15_In_02_Player_BM": "这儿……还挺温馨。",
 "Story09_Out_01_Killbane": "你当时脑子里在想什么，马蒂？",
 "Story14_In_09_Player_BM": "他们在哪儿？",
 "Story11_Out_09_Monica": "那么你要么保证乔什·伯克的安全，要么我就换个能保证的人来。明白了吗？",
 "Story12_Out_01_Cyrus": "检查尸体。",
 "Story01_In_03_Josh": "放心——特技都是我自己上。",
 "Story17_In_07_Player_BM": "没错，就你跟皮尔斯。我带你们进去。",
 "SH_Decker_10_Oleg": "有意思……",
 "Story08_Out_07_Killbane": "放松。她们之中我们只需要留一个。",
 "Story10_In_02_Viola": "咱们一直没机会好好聊聊，毕竟你当时就是个科学实验品。",
 "Story09_Out_05_Killbane": "咱们咬牙死磕。专心致志。不搞莽撞冲锋，给他们来一记蒙特利尔黑哨阴招。",
 "Story09_Out_04_Matt": "我的错，伙计。那现在怎么办？",
 "Story08_Out_05_Kiki": "菲利普把动脑子的事交给咱们是有原因的。这里没我们的事了。",
 "Story02_In_26_Pilot": "搞什么——",
 "Story10_Out_08_Cyrus": "感谢你们抽出时间。",
 "Story10_In_11_Viola": "那是什么——？",
 "Story01_In_23_Gat": "正合我意。",
 "Story15_In_08_Kinzie": "你还能碰上更糟的呢。要是让马特把赛博帮的 Use-Net 接进中央电网，那可就……相信我，后果很严重。",
 "Story14_In_10_Kinzie": "不清楚，他们的播出地点是保密的。",
 "Story13_Out_06_Cyrus": "要是简单到那地步，我就不浪费你的时间了。",
 "SH_Morningstar01_03_Player_BM": "统共就俩小毛贼。",
 "Story21_Out_03_Zach": "你不得不爱这一幕——万般绝境之下，圣徒依然屹立不倒！",
 "Story19_In_26_Viola": "别一副脑残粉的样子。",
 "Story20_Out_04_Player_BM": "我的天，别磨磨唧唧跟个娘们似的，快把面罩戴上。",
 "Story16_Out_07_Killbane": "马蒂。",
 "Story16_In_03_Kinzie": "枪伤你能扛过去。但要是在这椅子上精神受到太大冲击，你就脑死亡了。",
 "Story09_In_04_Player_BM": "这个你不用操心。走吧，我想去会会我的新员工。",
 "Story07_In_10_Shaundi": "他对强尼葬礼干的事……早就他妈的越界了。",
 "Story19_In_17_Oleg": "你是说比喻意义上的——那些追星成痴、被媒体喂饱了迷药的乌合之众，对吧？",
 "Story19_In_12_Reynolds": "薇奥拉说圣徒是钢埠的新霸主。果真如此的话，算我一个。",
 "SH_Morningstar01_05_Shaundi": "都把卫生棉条塞上，干活了。",
 "Story19_In_11_Reynolds": "借过，亲爱的。",
 "Story08_In_06_Player_BM": "他说得对。",
 "Story01_In_18_Josh": "你们也配叫黑帮？一群怂包软蛋！咱们早该踩到他们头上拉屎了，就像——",
 "Story15_Out_01_Player_BM": "那这边就交给你了，行吧？",
 "Story13_Out_01_Cyrus": "琪亚，收到请回答。",
 "Story01_In_20_Player_BM": "嗯，这可就新鲜了。",
 "Story01_In_05_Shaundi": "所以待会儿在里面，可别整港片那一套。",
 "Story11_Out_10_Cyrus": "是，女士。",
 "Story08_In_05_Pierce": "肖蒂，咱们不能永远悼念盖特。总有一天，你得重新上马。无意冒犯，老哥。",
 "Story19_In_07_Reynolds": "薇奥拉——这就是你说的那小子？",
 "Story08_Out_02_Viola": "他们可是有人极力推荐的。",
 "Story10_In_15_Cyrus": "琪亚——状况如何？",
 "Story02_In_13_Phillipe": "当然。",
 "Story02_In_03_Gat": "出什么事了？",
 "Story07_In_11_Oleg": "他压根不讲什么交战规则。",
 "Story02_In_23_Phillipe": "拜托。我可是比利时人！",
 "Story02_In_10_Kiki": "不知二位可否赏光……？",
 "Story23_In_01_Player_BM": "咱们一路走到今天，失去了太多弟兄，这从来都不容易。但至少我们知道，不管盖特身在何处，都有兄弟陪着他一块儿折腾圣彼得。",
 "Story22_In_07_Player_BM": "他妈的到底怎么回事？",
 "Story15_In_13_Kinzie": "那可是全北美最强大的学习型计算机之一……而 STAG 手里就有一台。",
 "Story24_Out_07_Asst_Director": "全体归位，再来一条！",
 "Story22_In_04_Player_BM": "那是什么——？",
 "Story20_In_08_Player_BM": "比起我，他更怕安吉尔？",
 "SH_Decker_01_Kinzie": "我再解释一遍，慢——慢——讲：",
 "Story13_Out_07_Kia": "明白，长官——",
 "Story11_Out_01_Josh": "我叫乔什·伯克。在电视上，我扮演夜刃——一个帅得没天理却总被世人误解的吸血鬼，每周都豁出性命去保卫世界安全。",
 "Story07_Out_04_Player_BM": "辛迪加必须为他们干下的好事付出代价……这一次，换我们打上门去。",
 "Story10_In_06_Viola": "强尼会死，就因为他觉得自己什么都能单干。",
 "Story03_Out_07_Shaundi": "你还操心上房产了？咱们手里有枪，用就完了。",
 "Story19_In_23_Player": "你就不怕把 STAG 给惹毛了？",
 "SH_Decker_05_Player_BM": "啥椅子？",
 "Story07_Out_06_Killbane": "蛮族都打到家门口了——我们要的是将军，不是大使！",
 "Story08_In_02_Pierce": "呃，你这么一说，确实听着挺糟。",
 "Story07_Out_09_Player_BM": "钢埠咱们人生地不熟，所以我找来几个门儿清的。这位是金吉、齐莫斯，还有安吉尔……",
 "Story03_Out_05_Shaundi": "操你的，我做这一切都是为了强尼。",
 "Story02_In_24_Gat": "那你他妈自己烙个华夫饼吃去。咱们到此为止。",
 "Story01_Zscene01_03_Gat": "这玩意儿根本撬不开。准备好上 B 计划了吗？",
 "Story22_OutB_13_Player_BM": "都听好了，各位。当初开始追这个狗娘养的时，我们说过，哪怕天涯海角也要把他揪出来……我们做到了。",
 "Story15_In_16_Player_BM": "等等——那小屁孩就是马特？",
 "Story15_In_15_Kinzie": "该死……",
 "Story14_In_13_Player_BM": "这就去办。",
 "Story01_In_07_Player_BM": "相信我，伯克。绝对来真的。",
 "Story17_Out_14_Kia": "咱们早他妈该收起那套手下留情的把戏了。",
 "Story10_In_12_Player_BM": "没好事——走！",
 "Story07_In_06_Pierce": "管这帮家伙是哪路的，这漂着的排场可是真够足的。",
 "Story06_Out02_01_Player_BM": "这身粉色，咱们得想想办法了。",
 "Story03_Out_01_Shaundi": "那接下来呢？",
 "SH_Morningstar02_08_Player_BM": "可真够低调的。",
 "Story05_In_02_Player_BM": "有个混蛋在我家泳池里。",
 "Story23_In_05_Kinzie": "我的天。",
 "Story09_Out_02_Matt": "白白折损那么多姑娘，怪可惜的。",
 "SH_Morningstar02_06_Player_BM": "那线索是什么？",
 "Story17_Out_15_Cyrus": "就四个字，琪亚——震撼威慑。",
 "Story13_In_11_Player_BM": "好——走，猎 STAG 去。",
 "Story16_In_01_Pierce": "准备好进虚拟现实里大搞破坏了吗？",
 "Story15_In_17_Matt": "那个小屁孩，就是刚把你直升机干下来的赛博之神。干杯！",
 "Story12_In_10_Player_BM": "那咱们上哪儿找伯克？那废物没准儿躲在哪个犄角旮旯。",
 "Story21_Out_06_Killbane": "这可是老子他妈的名声！",
 "Story17_Mid_09_Pierce": "他妈的搞什么！",
 "Story03_Out_03_Shaundi": "什么？不——这也是我的战斗。",
 "Story10_In_10_Oleg": "我一向是个绅士。",
 "Story02_In_33_Gat": "行行行，细节回头再抠——掩护老大就行！走——这儿我来！",
 "Story21_Zscene01_06_Bobby": "我的天哪，电锯！！",
 "Story21_Out_07_Killbane": "这是我的城市！我就是这座城的凯撒！",
 "Story13_Out_03_Cyrus": "还没完。圣徒仍逍遥法外。我这就传一份情报过去……",
 "Story24_Out_06_Sci_Fi_Killbane": "下次再收拾你们！",
 "Story14_In_11_Shaundi": "那你他妈倒是说啊。",
 "Story11_In_03_Pierce": "妈的——！",
 "Story11_In_05_Pierce": "这事还没完。出什么事了？",
 "SH_Morningstar02_03_Monica": "STAG 计划，标志着美国夺回街头的重要里程碑！",
 "Story02_In_29_Gat": "统共也就六个人吧？我搞得定。",
 "Story14_In_08_Anna": "我们明白了。",
 "Story06_Out02_02_Oleg": "你是想要更爷们儿一点的颜色？比如紫色？",
 "SH_Morningstar02_13_Zimos": "行了，别磨磨唧唧跟个娘们儿似的，上车。",
 "Story07_In_07_Oleg": "他们是杀霸的打手。",
 "SH_Decker_09_Kinzie": "他们把它存放在这儿。",
 "Story10_In_17_Cyrus": "收到。拿下那片区域后立刻联系我。",
 "Story08_Out_04_Kiki": "说说吧，马特。你到底有没有计划？你呢，埃迪？",
 "Story08_In_04_Shaundi": "我对天发誓，我会把那玩意儿整个塞进你的嗓子眼。",
 "Story07_Out_08_Killbane": "你刚才叫我什么？",
 "Story07_In_17_Monica": "你能相信吗？就在我丈夫的桥上！不，不，我不会冷静的。我现在就回国会山。给我安排一场紧急会议。妈的——这是战争！",
 "Story14_Out_03_Shaundi": "妈的！你们干了什么！",
 "Story05_Out_02_Killbane": "马蒂，没什么好担心的。",
 "Story17_Mid_01_Pierce": "下回换你来当这个他妈的俘虏。",
 "Story10_In_13_Viola": "妈的！",
 "Story01_In_13_Gat": "伯克！",
 "SH_Morningstar02_07_Zimos": "都给你安排妥了，老弟。",
 "Story13_In_09_Oleg": "朋友，让我来。",
 "Story07_Out_02_Matt": "薇奥拉和琦琦是洛伦先生的左膀右臂。按理说接班的应该是她们——",
 "Story07_Out_11_Killbane": "想个辙。随便什么都行！趁我还没开始纳闷儿，留着你们这对书立到底图什么。",
 "Story05_In_01_Pierce": "想啥呢？",
 "Story12_In_08_Pierce": "哥们儿，那是强尼的漫画……他把肖像权卖给乌托尔了，人家正拿这破玩意儿拍电影呢。",
 "Story02_In_05_Gat": "不，敬咱们。伯克说得对——咱们把爷们的老二，都换成娘们儿裤裆了。说真的……电影合约？商业代言？圣徒这块招牌过去代表的，可远不止一瓶身体喷雾、一罐屁股味的能量饮料。",
 "Story01_In_09_Gat": "那必须的。谁不想当强尼·盖特？",
 "Story21_Zscene01_01_Bobby": "我的天哪，安吉尔被摔出擂台了！",
 "Story16_Zscene02_02_Matt": "我能还你们清白，证明那座桥不是你们炸的。",
}

# 读 schinese 现有行（保留顺序），对非 T 中的键保持原值；T 中的键用新译
lines = open(SCH, encoding="utf-8").read().replace("\r\n", "\n").split("\n")
out = []
seen = set()
for ln in lines:
    m = re.match(r'^\s*"([^"]+)":\s*"(.*)"\s*$', ln)
    if m and m.group(1) in T:
        k = m.group(1)
        out.append('"%s": "%s"' % (k, T[k]))
        seen.add(k)
    else:
        out.append(ln)
# 若 T 中有键不在原文件中（不应发生），追加
for k in T:
    if k not in seen:
        out.append('"%s": "%s"' % (k, T[k]))

open(SCH, "w", encoding="utf-8").write("\n".join(out) + "\n")
print("written", len([k for k in T]), "translated entries; total lines", len(out))
