# -*- coding: utf-8 -*-
# 接管重译 static：读 original/static_us.txt 抽 KEY，逐条重写中文。
import re, os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCH = os.path.join(BASE, "schinese", "static_us.txt")
ORG = os.path.join(BASE, "original", "static_us.txt")

src = open(ORG, encoding="utf-8").read().replace("\r\n", "\n")
od = dict(re.findall(r'^\s*"([^"]+)":\s*"(.*)"\s*$', src, re.M))

T = {
 "STAT_DRIVING_TWOWHEELS": "双轮行驶",
 "STAT_MAX_STUNT_JUMP_HEIGHT": "最大特技跳跃高度",
 "ESCORT_NAME_24B": "小绵羊",
 "STORE_INVENTORY_EMPTY": "已经没有东西可买了！",
 "STAT_RUNNING_MAN_LEVELS_COMPLETED": "元气博士：已完成",
 "STAT_TANK_MAYHEM_LEVELS_COMPLETED": "坦克大破坏：已完成",
 "STAT_SECRET_AREAS_FOUND": "秘密区域发现数",
 "TAT_REG_R_LEG": "右腿",
 "HORDE_MODE_TITLE_COMPLETE": "第 {0} 波完成",
 "ESCORT_NAME_26B": "圣詹姆斯",
 "WPN_STORE_THROWN_TITLE": "投掷武器",
 "STAT_MONEY_PALLETS_FOUND": "现金托盘发现数",
 "STAT_UNIQUE_VEHICLES_DRIVEN": "驾驶车辆种类数",
 "STAT_SPECIAL_HIT_PCT": "特殊武器命中率",
 "STAT_DRIVING_BACKSEAT_RESPECT": "碾杀获得声望",
 "STAT_DRIVING_STOPPIE_RESPECT": "翘尾获得声望",
 "STAT_MOST_HATED_GANG": "最遭恨的帮派",
 "ESCORT_NAME_20B": "泥石流",
 "GARAGE_CAT_3": "性能",
 "STAT_DRIVING_BIGAIR_HEIGHT": "最大腾空高度",
 "UNLOCKABLE_TITLE_CAPS": "已解锁",
 "GARAGE_CUST_NAME": "菊部改装",
 "STAT_COMBAT_THROWN_RESPECT": "投掷击杀获得声望",
 "ESCORT_NAME_22B": "洞穴探险家",
 "GARAGE_RETRIEVE_TEXT": "确定要取回这辆车吗？",
 "STAT_CAT_MOUSE_LONGEST_KILL_STREAK": "猫捉老鼠：最长连杀",
 "STAT_HELI_ASSAULT_LEVELS_COMPLETED": "直升机突袭已完成",
 "STAT_DIVERSION_RESPECT_EARNED": "即时挑战获得声望",
 "STAT_ENEMY_GANG_KILLED": "帮派击杀数",
 "PCS_RETURN_MAIN": "返回主菜单",
 "STAT_HUMAN_SHIELD_KILLS": "人盾击杀数",
 "ESCORT_NAME_30A": "烈焰",
 "STORE_GARAGE_MSG": "进入你的车库",
 "STAT_GRENADE_KILLS": "手雷击杀数",
 "STAT_MAX_HUMAN_THROWN_DIST": "最远扔人距离",
 "STAT_COOP_TANDEM_DIVERSIONS_COMPLETED": "双人合作：同步即时挑战完成数",
 "STAT_DRIVING_WINDSHIELD_DISTANCE": "挡风玻璃炮弹最远距离",
 "STAT_DRIVING_WINDSHIELD": "挡风玻璃炮弹",
 "ESCORT_NAME_32A": "血腥",
 "STORE_TEXT_DISCARD": "要把这件物品从衣柜中丢弃吗？",
 "HORDE_MODE_TITLE_FINAL_FAIL": "最终波失败",
 "STAT_SEX_DOLLS_FOUND": "充气娃娃发现数",
 "STAT_RIFLE_HIT_PCT": "步枪命中率",
 "STAT_DRIVING_WRONGWAY": "逆行车道",
 "ESCORT_NAME_28B": "双倍夹心",
 "HORDE_MODE_INVULNERABILITY": "无敌！",
 "ESCORT_NAME_34A": "希腊佬",
 "VCUST_GARAGE_EXIT_PROMPT": "确定要离开车库吗？",
 "STAT_DRIVING_NEARMISS_RESPECT": "惊险擦身获得声望",
 "STAT_FAVORITE_WEAPON": "最爱武器",
 "CUSTOM_CONFIRM_OUTFIT_CREATION": "确定要创建这套装扮吗？",
 "STAT_COOP_ACTIVITIES_COMPLETED": "双人合作：活动完成数",
 "STAT_MILES_BY_CAR": "驾车行驶里程（英里）",
 "STAT_FRAUD_DIVES_TAKEN": "碰瓷索赔：扑街次数",
 "STAT_BARN_FOUND": "低空穿越点发现数",
 "ESCORT_NAME_36A": "火辣",
 "STAT_TOTAL_CASH_EARNED": "累计赚取现金",
 "STAT_DRIVING_BIGAIR_DISTANCE": "最远腾空距离",
 "STAT_SHOTS_FIRED": "射击次数",
 "STAT_POLICE_NOTORIETY_TIME": "最高警方恶名持续时长",
 "ACT_HITMAN_LEAVE_FULL": "真的要退出职业杀手吗？",
 "PURCHASEABLE_PROPERTEY_CHOP_SHOP": "卷毛的剁车铺",
 "STAT_HELI_ASSAULT_TARGETS_DESTROYED": "直升机突袭：摧毁目标数",
 "STAT_THROWN_HIT_PCT": "投掷武器命中率",
 "STAT_GUARDIAN_ANGEL_LEVELS_COMPLETED": "守护天使已完成",
 "STAT_COMBAT_CAR": "帮派载具击杀数",
 "GARAGE_CAT_2": "颜色",
 "STAT_SNIPER_SHOTS_FIRED": "狙击枪射击次数",
 "STAT_MISSIONS_COMPLETED": "任务完成数",
 "WPN_STORE_RIFLE_TITLE": "步枪",
 "STORE_ITEM_STYLE_AWARD": "+ {0} 风格值",
 "IMAGE_DESIGNED_NAME": "改头换面",
 "GARAGE_RETRIEVE": "取回",
 "STAT_TEAM_MORNINGSTAR": "晨星帮",
 "ESCORT_NAME_19B": "吉米",
 "STORE_EXIT_WARNING_BODY": "退出商店\\n\\n确定吗？",
 "PLAYER_CREATION_SAVE_CHANGES": "要保存所做的修改吗？",
 "STAT_WHEELIE_LONGEST_DISTANCE": "最长翘头行驶距离",
 "STAT_CIVILIANS_KILLED": "平民击杀数",
 "STAT_DISTANCE_BY_VEHICLE": "载具行驶里程",
 "STAT_CASH_EARNED_PER_DAY": "每小时收入",
 "STAT_FRAUD_BEST_DIVE": "碰瓷索赔：最佳扑街",
 "STAT_ACTIVITY_RESPECT_EARNED": "活动获得声望",
 "STAT_HOSPITAL_BILLS": "医院账单",
 "ESCORT_NAME_8B": "开瓶器",
 "STAT_DRUG_TRAFFICKING_LEVELS_COMPLETED": "黑货押运已完成",
 "STAT_COMBAT_ENEMY": "帮派击杀数",
 "STAT_HOLDUP_CASH": "持械打劫赚取现金",
 "STAT_BASE_JUMP": "高楼跳伞",
 "STORE_TATTOO_PARLOR_MSG": "去纹身",
 "STAT_MAX_POLICE_NOTORIETY_STREAK": "最高警方恶名最长连续时长",
 "ESCORT_NAME_15B": "棒棒糖",
 "ESCORT_NAME_6B": "纹身",
 "STAT_TOTAL_DISTANCE_TRAVELLED": "总行驶里程",
 "STAT_DIVERSIONS_COMPLETED": "即时挑战完成数",
 "STAT_TOTAL_DAMAGE_TAKEN": "累计承受伤害",
 "STAT_MILES_BY_AIRCRAFT": "飞行里程（英里）",
 "STAT_CUSTOM_ITEMS_CASH_SPENT": "自定义物品消费",
 "STAT_MAX_STUNT_JUMP_SPIN": "最大特技跳跃旋转",
 "HORDE_MODE_TITLE_KILLS": "击杀",
 "HORDE_MODE_WAVE_TAG": "波次",
 "STAT_RUNNING_MAN_CASH_EARNED": "元气博士：赚取现金",
 "STAT_PISTOL_SHOTS_FIRED": "手枪射击次数",
 "STAT_ACTIVITIES_COMPLETED": "活动完成数",
 "ESCORT_NAME_17B": "大力钳",
 "ESCORT_NAME_4B": "龙",
 "CUST_DIALOG_DISROBE_BODY": "这会脱掉你身上的所有衣物。\\n一丝不挂才能裸奔。\\n确定吗？",
 "WPNSTOR_TEXT_MAX_AMMO_CRIB": "以下物品的弹药已从据点拿满：“%s。”",
 "STAT_STAG_COMMANDOS_KILLED": "STAG 突击队击杀数",
 "STAT_FBI_KILLED": "FBI 击杀数",
 "STORE_TITLE_INSUFFICIENT_FUNDS": "现金不足",
 "STAT_NEIGHBORHOODS_CONTROLLED": "控制地盘数",
 "ESCORT_NAME_11B": "电击手",
 "ESCORT_NAME_2B": "小号",
 "STAT_COOP_KILLS": "双人合作：击杀玩家数",
 "STAT_MAYHEM_BEST_ROUND": "大破坏：最佳单轮",
 "STAT_GUARDIAN_ANGEL_CELEBS_PROTECTED": "守护天使：保护名人数",
 "STAT_COMBAT_MOTORCYCLE": "飞车挥刀击杀数",
 "STAT_MILES_BY_VEHICLE": "载具行驶里程（英里）",
 "VCUST_EXIT_PROMPT": "确定要退出载具改装吗？",
 "VCUST_EXTRA_HIGH_PROFILE": "超高轮廓",
 "STAT_CAT_MOUSE_MOST_POINTS_EARNED": "猫捉老鼠：最高得分",
 "STAT_SHOTGUN_HIT_PCT": "霰弹枪命中率",
 "STAT_GUARDIAN_ANGEL_ATTACKERS_KILLED": "守护天使：击杀袭击者数",
 "STAT_MUGGINGS_COMPLETED": "打劫路人完成数",
 "ESCORT_NAME_13B": "龙卷风",
 "CUST_ITEM_VIEW_OUTFITS": "查看装扮",
 "STAT_COMBAT_MELEE": "徒手击杀数",
 "STAT_MUGGINGS_CASH": "打劫路人赚取现金",
 "STAT_MILES_ON_FOOT": "步行里程（英里）",
 "NO_OUTFITS_DISPLAY_NAME": "暂无装扮",
 "VEHICLE_COLOR_ADVANCED": "基础",
 "STORE_CRIB_CLOTHING_MSG": "使用你的衣柜",
 "STAT_MULTI_KILL_TOTAL_MULTI_KILLS": "多重击杀总数",
 "STAT_FLASHPOINTS_COMPLETED": "帮派行动完成数",
 "STAT_TAUNTING_TOTAL_TAUNTS_GIVEN": "嘲讽总数",
 "ESCORT_NAME_17A": "毛茸茸",
 "ESCORT_NAME_4A": "愤怒",
 "PLANET_SAINTS_NAME": "圣徒星球",
 "GARAGE_REPAIR_COST": "要支付 %s 吗？",
 "STAT_HOLDUPS_STORES_ROBBED": "打劫商店数",
 "STAT_CAR_CUSTOMIZATION_CASH_SPENT": "车辆改装消费",
 "STAT_CAT_MOUSE_LOSSES": "猫捉老鼠：失败数",
 "STAT_DRIVING_BURNOUT_TIME": "最长烧胎时长",
 "ESCORT_NAME_15A": "棕色",
 "ESCORT_NAME_6A": "蘑菇",
 "STAT_TAUNT": "嘲讽",
 "STAT_WATERCRAFT_DESTROYED": "摧毁船只数",
 "STAT_CARS_UNLOCKED": "解锁车辆数",
 "STAT_COMBAT_HEADSHOT": "爆头数",
 "VCUST_HUBCAP_NUMBER": "轮毂盖 #{0}",
 "STAT_MILES_BY_WATERCRAFT": "驾船行驶里程（英里）",
 "STATS_NO": "序号",
 "STAT_SHOT_HIT_PERCENTAGE": "射击命中率",
 "ESCORT_NAME_13A": "后门",
 "STAT_DRIVING_WHEELIE": "翘头",
 "STAT_UNIQUE_VEHICLES_OWNED": "拥有车辆种类数",
 "STATS_BLANK_OF_BLANK": "%d/%d",
 "GARAGE_CAT_4": "车轮",
 "STAT_THROWN_WEAPON_USES": "投掷武器使用数",
 "ESCORT_NAME_11A": "湿漉漉",
 "ESCORT_NAME_2A": "生锈",
 "HORDE_MODE_ALL_ENEMIES_KILLED": "敌人全灭！",
 "STAT_WEAPON_RIFLE": "步枪",
 "STAT_COOP_STRONGHOLDS_COMPLETED": "双人合作：根据地完成数",
 "GENERAL_YOU": "你",
 "STAT_CAT_MOUSE_KILLS": "猫捉老鼠：击杀数",
 "STAT_RIFLE_SHOTS_FIRED": "步枪射击次数",
 "GARAGE_CAT_1": "车身改装",
 "STORE_CLOTHING_STORE_MSG": "购买服装",
 "MENU_SWAP_WEAPONS_CACHE": "武器库",
 "STORE_TITLE_PURCHASING": "正在购买",
 "STAT_VEHICLES_HIJACKED": "劫持载具数",
 "STAT_HOSTAGE_CASH": "绑架赚取现金",
 "TIME_SET_MIDNIGHT": "时间设为午夜",
 "STORE_CHOOSE_A_CATEGORY": "选择类别",
 "STORE_ZOOM_ROTATE": "缩放 / 旋转",
 "STAT_DRUG_PACKAGES_FOUND": "毒品包裹发现数",
 "STORE_EXIT_CLIPBOARD": "退出选购清单？",
 "STAT_HITMAN_TARGETS_ELIMINATED": "职业杀手目标消灭数",
 "STAT_BIKES_DESTROYED": "摧毁摩托车数",
 "STAT_MELEE_KILLS": "痛殴击杀数",
 "STATS_YES": "是",
 "ESCORT_NAME_8A": "金色",
 "CUSTOMIZE_ITEM_SAVE_CHANGES_EXIT_FULL": "要保存所做的修改\\n再退出吗？",
 "STAT_SMG_SHOTS_FIRED": "冲锋枪射击次数",
 "STAT_SWAT_KILLED": "SWAT 击杀数",
 "COMPLETION_STYLE_BONUS": "风格值加成",
 "PURCHASEABLE_PROPERTEY_THUNDER": "雷霆加油站",
 "STAT_TANK_MAYHEM_DAMAGE_DONE": "坦克大破坏：造成伤害",
 "STAT_TIME_AT_MAX_POLICE_NOTORIETY": "最高警方恶名持续时长",
 "STAT_LONGEST_POWERSLIDE_TIME": "最长漂移时长",
 "STAT_TOTAL_MONEY": "累计赚取现金",
 "ESCORT_NAME_19A": "吐口水",
 "SAVELOAD_CONTINUE_NO_FILES_FOUND": "未找到之前的存档文件。\\n要开始新游戏吗？",
 "STORE_UNDERWEAR_WARNING": "警告",
 "WPNSTOR_TITLE_FRIENDLY_FIRE": "队友火力",
 "HORDE_MODE_WEAPON_UPGRADE_TITLE": "主武器已升级！",
 "GARAGE_CAT_5": "细节",
 "STAT_CAT_MOUSE_TIME": "猫捉老鼠：用时",
 "STAT_FRAUD_CASH_CLAIMED": "碰瓷索赔：骗保金额",
 "STAT_DIVERSION_CASH_EARNED": "即时挑战赚取现金",
 "STAT_BASE_OWNED": "已拥有降落伞",
 "STORE_CAR_MECHANIC_MSG": "去修车",
 "STAT_NEIGHBORHOODS_EXPLORED": "探索街区数",
 "ESCORT_NAME_32B": "女族长",
 "STAT_MISSIONS_FAILED": "任务失败数",
 "STAT_CAT_MOUSE_DEATHS": "猫捉老鼠：死亡数",
 "STAT_COOP_TIME_PLAYED": "双人合作：游戏时长",
 "STAT_COMBAT_MOTORCYCLE_RESPECT": "飞车挥刀获得声望",
 "STAT_MAX_STUNT_JUMP_DISTANCE": "最大特技跳跃距离",
 "ESCORT_NAME_30B": "诺里斯",
 "CUST_TITLE_OUTFIT_CREATION": "创建确认",
 "GARAGE_REPAIR_MUST": "车辆必须完全修复才能改装",
 "STAT_TIME_AT_MAX_DECKER_NOTORIETY": "最高赛博帮恶名持续时长",
 "STAT_SURFING_RESPECT": "载具冲浪获得声望",
 "STAT_COMBAT_NUTSHOT": "蛋击数",
 "HORDE_MODE_NEW_TEXT": "确定要重新开始妓望工程吗？",
 "STAT_SNATCH_LEVELS_COMPLETED": "拐人救美已完成",
 "ESCORT_NAME_36B": "毕晓普",
 "HORDE_MODE_TITLE_FINAL_COMPLETE": "最终波完成",
 "STAT_BRUTES_KILLED": "巨兽击杀数",
 "ESCORT_NAME_28A": "淘气",
 "STAT_STRONGHOLDS_COMPLETED": "根据地完成数",
 "STAT_DRIVING_DRIFTING_DISTANCE": "最长漂移距离",
 "STAT_DRIVING_BIGAIR": "大腾空次数",
 "STAT_CUSTOM_ITEMS_OWNED": "自定义物品拥有数",
 "STAT_CHOPSHOP_COMPLETED": "拆车坊完成数",
 "ESCORT_NAME_34B": "螳螂",
 "HORDE_MODE_NEW_WAVE_MESSAGE": "第 %i 波",
 "STAT_BEST_WEAPON": "最佳武器",
 "STAT_HOSTAGES_EXTORTED": "勒索人质数",
 "ESCORT_NAME_26A": "顺从",
 "PURCHASEABLE_PROPERTEY_COUNTERFITING": "假钞作坊",
 "HORDE_MODE_REMAINING_ENEMIES_TAG": "剩余敌人",
 "STAT_LAW_ENFORCEMENT_KILLED": "执法者击杀总数",
 "MENU_SWAP_WEAPONS_STORE": "武器商店",
 "STAT_WEAPON_PISTOL": "手枪",
 "STAT_COOP_TANDEM_DIVERSION_RECORDS": "双人合作：同步即时挑战纪录",
 "STAT_TIME_PLAYED": "总游戏时长",
 "ESCORT_NAME_24A": "起立",
 "STAT_FRAUD_TOTAL_DIVE_DISTANCE": "碰瓷索赔：累计扑街距离",
 "STAT_HIGHEST_RANK_ACHIEVED": "达到的最高等级",
 "STAT_CAT_MOUSE_CASH_EARNED": "猫捉老鼠：赚取现金",
 "STAT_COMBAT_MULTI": "多重击杀数",
 "STAT_TOTAL_CASH_SPENT": "累计消费金额",
 "STAT_MAX_DRIVER_BAILOUT_DAMAGE_DONE": "跳车造成的最大伤害",
 "ESCORT_NAME_22A": "喷射",
 "WARDROBE_REMOVE_CLOTHING": "要脱掉身上的其他衣物吗？",
 "GANG_CUST_GANG_SIGN_POSE": "移动",
 "STAT_COMBAT_ENEMY_RESPECT": "击杀敌对帮派获得声望",
 "STAT_MAX_WHEELIE_DISTANCE": "最长翘头距离",
 "STAT_PARACHUTE_DISTANCE_TRAVELLED": "降落伞滑翔距离",
 "STAT_DRIVING_WINDSHILED_RESPECT": "挡风玻璃炮获得声望",
 "STAT_MAX_STOPPIE_DISTANCE": "最长翘尾距离",
 "ESCORT_NAME_20A": "王者",
 "WPNSTOR_TEXT_MAX_WEAPONS_CRIB": "以下物品已无法再从据点拿取：“%s。”",
 "STAT_TIME_AT_MAX_MORNINGSTAR_NOTORIETY": "最高晨星帮恶名持续时长",
 "STAT_DRIVING_DRIFTING": "漂移",
 "WARDROBE_REMOVE_CLOTHING_TITLE": "脱掉其他衣物",
 "VCUST_SPINNER_NUMBER": "旋转轮毂 #{0}",
 "PURCHASEABLE_PROPERTEY_CONDOS": "高层公寓",
 "CUST_ITEM_REMOVE_CLOTHING": "脱掉当前所有衣物",
 "STAT_LUCHADOR_SPECIALISTS_KILLED": "摔跤手帮专家击杀数",
 "STAT_MISSIONS_ATTEMPTED": "任务尝试数",
 "STAT_SNIPER_HIT_PCT": "狙击枪命中率",
 "STAT_FRAUD_LONGEST_DIVE_DISTANCE": "碰瓷索赔：最长扑街距离",
 "STAT_SURFING": "载具冲浪",
 "ESCORT_NAME_25B": "凤凰",
}

lines = open(SCH, encoding="utf-8").read().replace("\r\n", "\n").split("\n")
out = []
seen = set()
for ln in lines:
    m = re.match(r'^\s*"([^"]+)":\s*"(.*)"\s*$', ln)
    if m and m.group(1) in T:
        k = m.group(1)
        out.append('"%s": "%s"' % (k, T[k]))
        seen.add(k)
    else:
        out.append(ln)
for k in T:
    if k not in seen:
        out.append('"%s": "%s"' % (k, T[k]))

open(SCH, "w", encoding="utf-8").write("\n".join(out) + "\n")
print("written", len(T), "entries; total lines", len(out))
