import json, os
QA = os.path.dirname(os.path.abspath(__file__))
untrans = json.load(open(os.path.join(QA, "_untrans_mission_us.json"), encoding="utf-8"))
tp = os.path.join(QA, "_trans_mission_us.json")
trans = json.load(open(tp, encoding="utf-8")) if os.path.exists(tp) else {}

skip = set()

add = {
 "HASH_7FEBB0BF": "去 [format][color:Location]车流[/format] 里撒野",
 "HASH_7A4ECFBF": "跳踢在2D横版过关游戏里管用。来看看在这儿灵不灵。",
 "HASH_965654BF": "哭泣",
 "HASH_9D0C91BF": "前往 [format][color:location]通讯室[/format]",
 "HASH_30C83CBF": "你真以为，我会不远万里跑到杰扬星区，却没带上全宇宙最顶尖的厨师？",
 "HASH_1D3CACC0": "在飞船上会见 [format][color:Location]基思[/format]",
 "HASH_FD099CC0": "一位美艳的女施虐者从岛上唯一的阴影中现身。\\n\\n你作何回应？",
 "HASH_B1877CC0": "而一段温馨的回忆，又如何能确切地摧垮他们的意志？",
 "HASH_865F82C0": "新兵训练后，我入伍并被派往贝多星上那场一触即发的大战前线。在那里，我率军冲锋，直取贝多名将弗兰斯科特。凭着我与生俱来的敏锐洞察，我以如下方式令弗兰斯科特措手不及：",
 "HASH_615C1CC1": "前往 [format][color:location]坦克混乱区[/format]",
 "MOL_JB01_FAILURE_VIP_DIED": "贵宾阵亡！",
 "HASH_EB571DC1": "前往 [format][color:location]活动起点[/format]",
 "HASH_521CE6C1": "击败 [format][color:kill]复古克隆体[/format]",
 "HASH_5514BAC1": "指挥部队",
 "HASH_339248C1": "行事要有章法，你难道不懂？没错，我承认，我对那可憎暴徒的私人嫌恶占了上风，像折断枯橡树上剥落的旧树皮般扭断了津法克斯的脖颈。津科夫预校的时光就此落幕，我步入人生的又一阶段——它将带我去往无数异域，最终让我认清自己真正的潜能。",
 "HASH_1FDF33C2": "入侵钢铁厂的拉斯蒂针管店",
 "HASH_07CC6BC2": "在飞船上会见皮尔斯",
 "HASH_991842C2": "击杀 [format][color:Location]尤利乌斯[/format]",
 "HASH_256DA6C2": "开始任务",
 "HASH_76D609C2": "前往 [format][color:location]天使赌场[/format]",
 "HASH_3ACFE4C2": "饮下那杯牛奶",
 "HASH_EE9C9DC3": "在飞船上会见 [format][color:Location]俏皮肖恩蒂[/format]",
 "HASH_A4E21DC3": "进入 [format][color:location]直升机[/format]",
 "HASH_210A03C3": "取走 [format][color:use]直升机[/format]",
 "HASH_79A98EC3": "进入 [format][color:use]直升机[/format]",
 "HASH_D36E3DC3": "走近计算机",
 "HASH_EE92A8C3": "只有我的一生",
 "HASH_4AE775C4": "入侵罗森橡树的辛族星球",
 "HASH_317C84C4": "击杀 [format][color:kill]袭击者[/format]",
 "HASH_55CEF8C4": "前往 [format][color:location]楼顶[/format]",
 "HASH_34F8BFC4": "前往 [format][color:location]送达地点 [/format]",
 "HASH_BDEC4BC4": "进入 [format][color:use]车[/format]",
 "HASH_1346C3C4": "追击 [format][color:location]赛勒斯[/format]",
 "HASH_11089CC4": "借夜色掩护潜入他的基地",
 "HASH_8D063AC4": "科学",
 "HASH_BE6631C5": "杀之任其死",
 "HASH_5B70C9C5": "收集 [format][color:use]霰弹枪[/format]",
 "HASH_BCE483C5": "奎克祖格",
 "HASH_EBD1AEC6": "冷热交替",
 "HASH_97721BC6": "触碰那座钟摆",
 "HASH_C66ED8C7": "入侵 [format][color:Location]无人爱我[/format]",
 "HASH_3846C8C7": "穿越系统竞速",
 "HASH_E77FA9C7": "在飞船上会见 [format][color:Location]金吉[/format]",
 "HASH_033E59C7": "射击 [format][color:kill]发电机[/format]",
 "HASH_7E39F1C7": "拯救人类",
 "HASH_563F51C7": "模拟世界一旦建成，我只需：",
 "HASH_FA379AC8": "你身居领袖之位已久。可还记得为他人效力是何滋味？",
 "HASH_945CD2C8": "回到 [format][color:location]集会[/format]",
 "HASH_9EA69CC8": "做一台椰子收音机",
 "HASH_4A04CAC9": "清剿辛族部队",
 "HASH_7E241AC9": "关闭 [format][color:Location]热点[/format]",
 "HASH_FCD831C9": "前往 [format][color:location]格里夫斯改装厂[/format]",
 "mm_3_3_failure_ufo_abandon": "你离开了幽浮！",
 "HASH_8EDE6FC9": "拍摄宣传照",
 "HASH_20B62FCA": "清剿辛族部队",
 "HASH_638049CA": "完成 [format][color:Location]竞速[/format]",
 "HASH_BFC44ACA": "向马特汇报",
 "MOL_P01_FAILURE_ESCAPE": "目标逃脱了",
 "HASH_E82651CA": "安放 [format][color:use]炸弹 0/2[/format]",
 "HASH_5C91DDCA": "我自己那脆弱的自我",
 "HASH_E84F2FCB": "关闭 [format][color:Location]热点[/format]",
 "HASH_26262CCB": "向金吉汇报",
 "HASH_37DF89CB": "前往 [format][color:location]第三站[/format]",
 "HASH_9CC92BCB": "前往 [format][color:location]微笑杰克店[/format]",
 "HASH_DC11CACB": "驾车前往 [format][color:location]边缘工坊[/format]",
 "HASH_887B06CB": "以 [format][color:defend]盖特[/format] 防守",
 "HASH_C0B0A8CB": "我骄傲地宣告，津杰以惊人的方式通过了每一项测试——尽管我们曾险些出岔子，当时：",
 "HASH_C573BBCB": "在部队面前质疑我的权威",
 "HASH_9F7BC7CC": "在飞船上会见肖恩蒂",
 "HASH_758E69CC": "启动病毒注入",
 "HASH_DC65ADCC": "探索高塔",
 "HASH_67F564CC": "拆除炸弹",
 "HASH_331B63CC": "触碰那座钟摆",
 "HASH_C54064CC": "摧毁 [format][color:kill]外星人[/format]",
 "HASH_0EE7F6CC": "一座献给宇宙最伟大文化的博物馆",
 "HASH_79D120CD": "在飞船上会见基思",
 "HASH_36546ECD": "异常读数",
 "HASH_D9B34FCD": "赛勒斯会为那条该死的蓬蓬裙付出代价的。",
 "HASH_F917FDCD": "了结坦尼娅",
 "HASH_892D0ECD": "进入 [format][color:location]雕像[/format]",
 "HASH_F6EB8ECD": "用海鸥尸体和羽衣甘蓝做一只木筏",
 "HASH_6A637DCE": "上传 [format][color:Location]病毒[/format]",
 "HASH_2C4A9DCE": "出去兜兜风吧。",
 "HASH_3FF709CE": "离开 [format][color:location]赌场[/format]",
 "HASH_6792A2CE": "直接走开",
 "HASH_B921D8CE": "的确！我不再是星际死亡飞船上那名普通乘客，如今我的手已牢牢握住舵柄。当然，这是比喻——星际死亡飞船实则由繁复的导航系统操控。",
 "M06_FAILURE_OUT_OF_TIME": "连接已终止",
 "HASH_5EB6DBCF": "闪避基尔班的反击",
 "HASH_2C8382CF": "我们在一顿美馔的餐前小食环节便遭了袭",
 "HASH_0CEC12CF": "我绝不容忍任何作者妄言，说节俭与对敬业精神的要求竟能成为某种异界干预的借口。我才不管那工人的儿子是不是拄着拐杖！那人有生意要打理！\\n\\n不。绝对不行。",
 "HASH_A2282BD0": "合作裂缝",
 "HASH_62C279D0": "上传 [format][color:Location]病毒[/format]",
 "HASH_1C9969D0": "击杀 [format][color:kill]增援[/format]",
 "HASH_858DA5D0": "等待 [format][color:defend]救援载具[/format]",
 "M01_OBJ_KILL_ZINYAK": "与 [format][color:kill]津亚克[/format] 战斗",
 "HASH_59F431D0": "是时候将坚实大地抛在身后，向群星进发。在强行说服部下为我新晋的职位举办一场致敬晚会后，我们起锚扬帆（再次声明，这是比喻），驶向那些正待采摘的彼岸。\\n\\n而亲爱的读者，我的故事正是在那里变得最为精彩。",
 "HASH_176B30D1": "若你稳住环境，我就能升级你的能力。",
 "HASH_CAD8FBD1": "担任 [format][color:defend]守卫[/format]",
 "HASH_175171D1": "那股灼烧感",
 "HASH_4F34B9D1": "击杀津法克斯，随后参军",
 "HASH_8764EAD2": "入侵 [format][color:Location]辛族星球[/format]",
 "HASH_D17637D2": "入侵新巴拉内克的拉斯蒂针管店",
 "HASH_F4A94CD2": "偷走 [format][color:Location]载具[/format]",
 "HASH_72F161D2": "关闭热点",
 "HASH_E0CFE3D2": "在飞船上会见强尼",
 "HASH_3AC004D2": "攻击 [format][color:kill]病毒载体[/format]",
 "HASH_88EF38D2": "饮下那杯牛奶",
 "HASH_A4BE0CD2": "调查这颗星球",
 "HASH_C7DD6CD2": "按津杰故乡津堡的惯例，他三岁时便与兄长决斗至死。津杰胜了。\\n\\n哦，我得说明，在某些文化里，决斗至死竟被用作问候之礼。何等奇特的习俗。",
 "HASH_917389D3": "%ls 已拒绝",
 "HASH_27DBEBD3": "启动病毒注入",
 "M16_FAIL_BEN_KING_DIED": "本·金阵亡！",
 "HASH_2C3076D3": "永远消灭癌症",
 "HASH_9E71B1D4": "乐趣至上",
 "HASH_27C927D4": "抢走数据",
 "HASH_0C8FD4D4": "在 [format][color:location]天使赌场[/format] 会见天使",
 "HASH_285C2FD4": "打灭 [format][color:kill]灯光[/format]",
 "HASH_B838CED4": "计算机可不会滚蛋。\\n\\n你输入什么？",
 "HASH_818FE7D5": "肃清 [format][color:Location]辛族部队[/format]",
 "HASH_92C647D5": "击杀 [format][color:kill]毒贩 [/format]",
 "MOL_JB01_FAILURE_LIMO_DES": "车被摧毁了！",
 "MOL_BK_01_BEN_DIED": "本·金阵亡！",
 "HASH_0259E0D5": "定位基思·大卫",
 "HASH_48FF7FD5": "再次出拳击打基尔班",
 "HASH_185148D6": "登上高塔",
 "HASH_CF197BD6": "偷走 [format][color:Location]载具[/format]",
 "HASH_12592AD6": "她或许不是最讨喜的人，但你要阻止津亚克，就少不了阿莎。",
 "HASH_5C4C8FD6": "回到 [format][color:location]幽浮[/format]",
 "HASH_983A3AD6": "防守 [format][color:defend]阵地[/format]",
 "HASH_0B81D6D6": "简。甜美的、甜美的简，你多像我母亲的梦境。纵使时光流转数载，如今只要一想到艾玛、艾琳诺与伊丽莎白她们的历险与情路坎坷，我仍不免喉头哽咽。噢，班内特小姐与达西先生之间那令人沉醉的拉锯，我真是百读不厌。",
 "HASH_5326FAD7": "会见 [format][color:location]金吉[/format]",
 "HASH_D01571D7": "前往 [format][color:location]CID[/format]",
 "HASH_C03176D7": "源点生命值",
 "HASH_A2FD77D7": "拾取 [format][color:use]火箭筒[/format]",
 "HASH_BE4C1CD7": "津族或许不是最有文化的天体，但它仍是我的家园。",
 "HASH_87F785D8": "开启摔角手据点",
 "HASH_9ADFDDD8": "若你想要100%，就得做这个。",
 "HASH_057007D8": "击杀 [format][color:Location]目标[/format]",
 "HASH_B846AAD8": "在飞船上会见 [format][color:Location]俏皮肖恩蒂[/format]",
 "HASH_E8C26ED8": "抵达 [format][color:location]掩体[/format]",
 "HASH_B6E7E0D8": "购置新衣",
 "HASH_00D774D8": "在月球上行走",
 "HASH_34FF8CD8": "那番话支撑我熬过四年严苛的求学，令我心无旁骛，更让我得以荣誉毕业于津科夫预校——那是津舍村走出的头一人。",
 "HASH_9CBE96D9": "入侵洛伦广场的友军误击",
 "HASH_C6444CD9": "你好，茶杯",
 "HASH_FA6458D9": "造收音机比你料想的容易……联播重播节目已给了你求生的工具。可惜，你无处可插电。\\n\\n你怎么做？",
 "HASH_B6EAB8D9": "我想，就其本身而言，的确如此。但那并非我要的答案。",
 "HASH_813246D9": "虽是振奋士气的妙招，却非我所用之策。",
 "HASH_E44AFBDA": "赢下 [format][color:Location]M.O.M.[/format]",
 "HASH_C757D7DA": "击杀 [format][color:Location]目标[/format]",
 "HASH_5AA391DA": "研究已初见佳绩。再有更多数据，我便能创造出真正惊人的造物！",
 "HASH_A9ECBBDA": "我照你说的做了。我们已准备好去救你的朋友。",
 "HASH_9249E7DA": "会见 [format][color:location]金吉[/format]",
 "HASH_AB92BEDA": "进入模拟世界",
 "HASH_5D25A1DA": "拯救 [format][color:defend]肖恩蒂[/format]",
 "HASH_433CE3DA": "防守 [format][color:defend]终端[/format]",
 "sh03_failure_defend": "你抛弃了你的兄弟们！",
 "HASH_4BE69BDB": "在飞船上会见 [format][color:Location]基思[/format]",
 "HASH_85FE21DB": "扰乱 [format][color:Location]系统[/format]",
 "HASH_DC87C0DB": "于是……",
 "HASH_1F1B1BDB": "……不。",
 "HASH_8E97E1DC": "探望 [format][color:location]金吉[/format]",
 "HASH_813BBFDC": "离开星球去月球上行走",
 "HASH_F8A336DC": "是的，是的。奎克祖格凭他那身体构造上的优势，在那幼稚的力气测试中胜过了我。一枪射穿他巨大的眼睛后，我向他的尸体祝贺任务完成。我们对杰扬人毫不留情，迅速了结了他们那可悲的星球，至今我仍将奎克祖格干瘪的舌头揣在口袋里。\\n\\n我搓它求好运。",
 "HASH_FD6ECEDD": "憎恨五十年代的女孩",
 "HASH_1DB008DD": "找到 [format][color:location]DJVC [/format]",
 "HASH_E2DA91DD": "前往 [format][color:location]椭圆办公室[/format]",
 "HASH_7937C7DD": "开始把受害者接上！",
 "HASH_4D6EFCDD": "唉，津舍的气候不宜果树生长。",
 "HASH_87B03EDE": "在飞船上会见金吉",
 "HASH_DA88BBDE": "入侵 [format][color:Location]拉斯蒂针管店[/format]",
 "HASH_3B0A4CDE": "这书需要一个更有力的第二幕。你有什么点子吗？",
 "HASH_C409D0DE": "升级一辆车",
 "HASH_21FC61DE": "全员就位",
 "HASH_2055C7DE": "关闭 [format][color:use]发电机 [/format]",
 "HASH_73005FDE": "击杀 [format][color:kill]外星人[/format]",
 "HASH_334F41DE": "炸毁辛族星球，头也不回",
 "HASH_C986D0DF": "入侵阿什伍德的边缘工坊",
 "HASH_1E5258DF": "在飞船上会见金吉",
 "HASH_D3B910DF": "拥抱疯狂",
}

skipped = []
for k, v in add.items():
    if k in skip:
        skipped.append(k)
        continue
    if k not in untrans:
        skipped.append(("not_in_untrans", k))
        continue
    trans[k] = v

if skipped:
    print("skipped:", skipped)
json.dump(trans, open(tp, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("merged. trans size now:", len(trans))
