# -*- coding: utf-8 -*-
import json, os

qa = os.path.dirname(os.path.abspath(__file__))
tp = os.path.join(qa, "_trans_new_sr35_us.json")
todo_p = os.path.join(qa, "_todo_new_sr35_us_05.json")

untrans = json.load(open(todo_p, encoding="utf-8"))
trans = json.load(open(tp, encoding="utf-8")) if os.path.exists(tp) else {}

add = {
    "HASH_3A3A0D95": "选择 {0}",
    "HASH_4C9D1B95": "弧线连击",
    "UNL_DESC_STOMP_1": "提升践踏的范围与眩晕时间。",
    "HASH_ABE96C96": "激活闪电增益",
    "HASH_F8E7EC97": "武器 - 弹跳步枪回弹",
    "HASH_A5A73A97": "机甲战衣 - 悬浮消耗 2",
    "HASH_54943C97": "超级冲刺现在可在水面进行。入水时按住 {SPRINT_IMG} 即可在水面冲刺！",
    "HASH_4C99C697": "从暂停菜单打开选项菜单",
    "HASH_B3CBB397": "队伍：%s\\n接受这支队伍的选择吗？",
    "HASH_D4F85297": "杀戮机器人击杀",
    "HASH_64F89D97": "它们源源不断地涌来……至少直到你炸掉它们的传送门，把它们送回老家。",
    "UNL_SPRINTING_1": "冲刺 - 龙卷风",
    "HASH_B9BC2A98": "@@STOMP_ROCK^^提升被震飞目标受到的伤害。@@STOMP_GRAVITY^^单个目标承受的伤害会分摊给所有处于静滞状态的目标。@@STOMP_SHRINK^^被缩小的目标承受更高伤害。",
    "HASH_A9E39F98": "超级践踏",
    "HASH_59CF2C98": "与本·金交谈",
    "HASH_6740A998": "外星人被超级踢飞数",
    "HASH_29C07A99": "齐尼亚克的人生篇章散落在虚拟钢埠各处。全部收集以了解齐尼亚克的身世。可在飞船休息室的电脑中查阅已收集条目。",
    "HASH_95D0FB99": "按顺序击中每个平台。\\n\\n击中中心可得额外分数。\\n\\n速度更快可获得速度奖励。",
    "M07_FAIL_MATT_DIED": "马特阵亡！",
    "HASH_19B17B9A": "闪电",
    "HASH_E572C89A": "前往[format][color:location]辛迪加塔[/format]",
    "HASH_EAA8809A": "念力接取",
    "HASH_A6860C9B": "践踏地面时使用更大力量，对震飞目标造成额外伤害！",
    "HASH_987D739B": "已放弃战斗！",
    "HASH_D26A829B": "不妨把模拟世界里的一切都玩个遍，顺便还能赚到一个超棒的新玩具！",
    "UNL_RELOAD_COOLDOWN_1": "更快冷却",
    "UNL_HOMIE_DONNIE": "同伴 - 唐尼",
    "HASH_7C89B29C": "{DPAD_LEFT_IMG} 选择冻结[format][color:power_blast]冲击波[/format]  ",
    "HASH_114DB59C": "「徒步大混乱」金牌",
    "UNL_DESC_SHIELD_DAMAGE": "冲刺护盾接触时施加额外伤害。",
    "UNL_DESC_JUMP_REDUCED_MANA_2": "滑翔消耗体力大幅减少。",
    "HASH_E2DD499D": "服装 - 马特·米勒套装",
    "HASH_1EB07C9D": "激活冰冻增益",
    "HASH_4B10D59D": "{SPRINT_IMG} 冲刺 \\n冲刺会产生一个充当攻城锤的护盾，并可反射投射物。\\n\\n把握冲刺时机，将典狱长的火球反射回去。",
    "UNL_SUPER_NUKE": "天降杀戮 - 核爆",
    "UNL_DESC_WEP_PLASMA_CANNON": "为暴君充能，让爆裂等离子飞射而出！\\n在传送门武器库装备它。",
    "HASH_EA72809E": "超级冲刺时达到最高速度。你简直比出膛子弹还快！",
    "HASH_EDA1D19E": "防守[format][color:defend]同伴[/format]",
    "HASH_56FE5C9E": "待在[format][color:location]墓园[/format]",
    "HASH_FE0F0B9E": "投掷外星重锤",
    "UNL_DESC_WEP_GLITCH_GUN": "用故障大师 3000 感染霸主矩阵的原住民。故障化的人类会为你而战！\\n\\n在传送门武器库装备它。",
    "HASH_00778A9F": "给外星人来点重金属式的重创。",
    "UNL_WARDEN_BEATDOWN_3": "典狱长 - 终结技 3",
    "UNL_SAINTS_VEHICLES": "载具 - 圣徒汽车",
    "HASH_DFC5A2A0": "滑翔 - 距离",
    "HASH_6FC8ACA0": "{JUMP_CLIMB_IMG} 启动跳跃喷气机 \\n{PICKUP_RELOAD_IMG} 降低高度 \\n{WEAPON_MENU_IMG} 关闭跳跃喷气机",
    "HASH_E9EA0AA0": "选择第一位战斗专家，在你对抗外星辛族敌人时提供协助。",
    "HASH_607576A0": "与皮尔斯交谈",
    "HASH_F204C3A1": "机甲战衣 - 超频",
    "HASH_366CD8A1": "传送门 - 东卡弗岛",
    "HASH_A7D1E8A1": "激活闪亮增益",
    "HASH_89F6DEA1": "合作目标标记",
    "HASH_FA8C58A1": "念力大混乱",
    "HASH_5CB087A1": "火焰元素点火数",
    "HASH_E6B8ACA2": "念力 - 强化 2",
    "HASH_2E2E88A2": "生命 - 补给价值 3",
    "HASH_5298FEA2": "接受任务分配",
    "HASH_677E9FA2": "营救[format][color:revive]本·金[/format]",
    "UNL_WARDEN_SHIELD_1": "辛族护盾 - 失效时间",
    "HASH_CB8879A3": "践踏 - 伤害",
    "UNL_DESC_TELEKINESIS_3": "念力可以抓起坦克和飞行器！",
    "HASH_4DDFFCA3": "副总统 - 基思·大卫已解锁！\\n\\n你准备好没，兄弟？",
    "HASH_6C4AE4A3": "商店黑客入侵",
    "UNL_SUPER_JUMP": "超级跳跃",
    "UNL_RAGDOLL_RECOVERY": "忍者反射",
    "HASH_452F34A4": "!!弹跳步枪战衣",
    "HASH_2840ACA4": "让你的敌人吓得当场缩小！\\n\\n双击 {SUPER_QUICK_STOMP_IMG} 在元素间快速切换。或在力量菜单中切换元素。",
    "HASH_827DAFA4": "简直像从小孩手里抢糖一样容易，真的。只可惜辛族的生命力尝起来令人作呕。",
    "UNL_DESC_VEHICLE_GENKIMOBILE": "你现已在传送门车库中获得源木战车。",
    "UNL_DESC_TELEKINESIS_REDUCED_MANA_1": "念力能量充能速度更快。",
    "HASH_FC5F39A5": "人工智能在城中还藏有更多裂隙。找到裂隙并完成人工智能布置在任务日志中的挑战，以获取更多奖励。",
    "HASH_EF2098A5": "只可惜没有风笛来搭配。这套服装现已在你的传送门衣橱中提供。",
    "HASH_82755FA5": "暂停游戏",
    "HASH_BA2855A6": "已揭晓 - 北市中心",
    "HASH_6D31F3A6": "冲击波元素 - 冰冻",
    "UNL_DESC_SUPER_NUKE_PC": "你现在可以用核爆摧毁整片城区！\\n\\n从高空使用天降杀戮制造核爆！",
    "HASH_13B222A6": "启用主菜单",
    "HASH_193E89A6": "冻结[format][color:power_blast]冲击波[/format]后射击[format][color:power_blast]敌人[/format]",
    "HASH_FADB68A6": "本·金",
    "UNL_WEP_BLACK_HOLE": "武器 - 奇点枪",
    "UNL_MANA_RECOVERY_2": "超能能量 - 更快恢复 2",
    "HASH_A0A4C1A7": "{PARTNER_NAME} 正在开启一项任务，但你目前正在进行游戏。\\n稍后再尝试加入。",
    "HASH_398E9BA7": "降落在[format][color:location]冲击波护盾[/format]上",
    "HASH_3F6C39A8": "机甲战衣 - 悬浮速度",
    "HASH_A134ABA8": "同伴 - 俏皮肖恩蒂",
    "HASH_CB6F1DA8": "俏皮肖恩蒂",
    "HASH_9599FCA8": "与肖恩蒂恋爱",
    "HASH_1F56EBA9": "同伴 - 超级后援",
    "HASH_3173B1A9": "拆解霸主矩阵",
    "HASH_20ACB2AA": "呼叫 CID",
    "HASH_F68ED9AA": "小地图上的 [image:map_other_coop_obj] 图标显示你搭档当前的目标。",
    "HASH_F21C2AAA": "跳[format][color:location]出[/format]",
    "UNL_JUMP_REDUCED_MANA_3": "滑翔 - 效率 3",
    "HASH_17527BAB": "增益元素 - 闪电",
    "HASH_DEF7D5AB": "线框断言者现已在你的传送门车库中提供。",
    "HASH_67A626AB": "传送门 - 西斯坦菲尔德",
    "HASH_1B9B16AB": "呼叫阿莎·奥德卡",
    "HASH_B41BA0AB": "欢迎来到盖特的内心世界。\\n{ANALOG_LS_IMG} 移动",
    "UNL_MECHMAYHEM": "机甲战衣大混乱",
    "HASH_DF3A0CAC": "飞船现已可用。返回飞船与你的船员交谈、领取任务、收听音频日志条目，并阅读已收集的文字冒险。",
    "HASH_80A4AFAC": "蓄力超级跳跃达到更高高度。",
    "HASH_7F6995AC": "传送门 - 南新科尔文",
    "HASH_5EE7BAAC": "呼叫基思·大卫",
    "HASH_C589B8AC": "前往飞机[format][color:location]后部[/format]",
    "HASH_2361E6AC": "机甲战衣大混乱",
    "UNL_HADOUKEN_2": "核爆 - 更快恢复 2",
    "HASH_E16BBEAD": "略微延长可驾驶机甲战衣的时间。",
    "HASH_A80DB9AD": "参谋长 - 本杰明·金已解锁！\\n\\n本杰明·妈了个巴子·金！",
    "HASH_E6FC9FAD": "闪电",
    "HASH_2FE4BBAD": "前往[format][color:location]监狱[/format]",
    "HASH_5993FDAD": "[format][color:kill]清空[/format]区域",
    "HASH_F0CC51AD": "本·金",
    "HASH_2D22B8AD": "超能格斗俱乐部银牌",
    "UNL_STOMP_CAR_DAMAGE": "践踏 - 载具伤害",
    "HASH_9D8726AE": "已揭晓 - 卡弗岛",
    "UNL_DESC_HADOUKEN_SUPPRESSION_2": "使用核爆后，力量恢复速度更快",
    "HASH_482D67AE": "提升冲击波的作用范围。",
    "HASH_7E7E3AAE": "探索[format][color:location]高塔[/format]",
    "HASH_A165FFAE": "开启此任务即开始最终决战。\\n请确保你已妥善装备、补给充足、完成升级并准备就绪，因为一旦开始，在彻底完成前你将无法返回。",
    "HASH_E37DBEAE": "天降杀戮",
    "UNL_HADOUKEN_REDUCED_MANA_2": "核爆 - 充能 2",
    "INFO_UNLOCKABLES_SUPER_POWERS": "超能力",
    "HASH_DAD0A3AF": "让你新结交的外星朋友见识人类文化表达的种种奥妙。",
    "HASH_33922DB0": "载具 - 宣传卡车",
    "UNL_TELEKINESIS_REDUCED_MANA_2": "念力 - 充能 2",
    "UNL_RELOAD_COOLDOWN_3": "更快冷却 3",
    "UNL_HACKING_EXTRA_TIME": "黑客入侵 - 额外时间",
    "HASH_B0F3B4B0": "俏皮肖恩蒂现在超级好玩了！",
    "HASH_3943D2B0": "服装 - 罗迪套装",
    "HASH_13B927B0": "占据 90%%",
    "HASH_5F165DB1": "船员 - 肖恩蒂",
    "HASH_FF7132B1": " [format][color:use]激活[/format]高塔",
    "HASH_6A52E4B1": "虚拟钢埠中隐藏着许多圣徒与罪人留下的音频日志。找到并全部收听吧。",
    "HASH_62EB4AB2": "已揭晓 - 斯坦菲尔德岛",
    "HASH_047CE1B2": "超级冲刺时速度提升。 ",
    "HOMIES_UFO_DESC": "让一名同伴空投 UFO。",
    "HASH_C4FFFDB2": "呼叫皮尔斯",
    "HASH_676E1DB2": "访问[format][color:use]力量菜单[/format]",
    "HASH_D47DE6B2": "佯攻",
    "HASH_61707EB2": "你能把多少外星人踢飞？",
    "HASH_304741B3": "武器 - 能量剑生命",
    "UNL_DESC_MANA_RECOVERY_4": "超能力能量恢复速度提升 100%%",
    "HASH_2D55F0B3": "{ATTACK_PRIMARY_IMG} 攻击 \\n{MELEE_POWER_ATTACK_IMG} 格挡",
    "UNL_SPRINTING_3": "冲刺 - 减伤",
    "HASH_E959B5B4": "火焰元素将你的身体和子弹包裹在致命的火墙中！\\n\\n你的同伴可以帮你找到更多增益元素！",
    "HASH_1B63B4B4": "消灭[format][color:kill]外星人[/format]",
    "HASH_EB900FB5": "提升击败闪点获得的缓存与经验值。",
    "HASH_AF2CD3B5": "呼叫坦尼娅",
    "HASH_88B8CEB5": "赢得全部「源木·精神制胜」银牌，即可解锁用意念接住投掷物的能力。",
    "HASH_CC88CCB6": "冲刺 - 水面奔跑",
    "HASH_31D1D6B6": "船员 - 皮尔斯·华盛顿",
    "UNL_DESC_NITROUS_DAMAGE": "使用氮气时对其他载具造成极高碰撞伤害。",
    "UNL_DESC_AUDIO_LOGS": "收集散布在模拟世界各处的同伴音频日志。在飞船休息室的电脑上收听已获取的条目。",
    "HASH_078594B6": "[format][color:power_pound]践踏[/format]后收集[format][color:power_pound]簇[/format]",
    "HASH_2D9CB1B6": "UFO 大混乱",
    "HASH_30DBE6B7": "@@TK_FORCE^^大幅提升被投掷载具的伤害。@@TK_LIGHTNING^^大幅增加闪电在物体间弧跳的距离。@@TK_LIFE_STEAL^^大幅提升每秒窃取的生命值。",
    "HASH_4E6C52B7": "传送点已激活",
    "HASH_819A3EB7": "调查[format][color:location]联邦大楼[/format]",
    "HASH_944E8CB7": "用棍子戳外星人。或者直接开枪。无论哪种，都要把他们惹得火冒三丈。",
    "UNL_SUPER_SPRINT": "超级冲刺",
    "HASH_3708F4B8": "机甲战衣 - 持续时间",
    "UNL_HOMIE_CID": "同伴 - C.I.D.",
    "HASH_40FE2EB9": "据说迈达斯对枪械情有独钟：\\n\\nZ9 手炮、异星冲击波、重击枪、主宰者。",
    "HASH_EA1A87B9": "南市中心已揭晓！",
    "HASH_F86A08B9": "激活闪亮践踏",
    "HASH_9B6507B9": "病毒注入",
    "HASH_48A15BB9": "消灭[format][color:kill]警察[/format]",
    "HASH_9BEB72BA": "载具 - 线框维和者",
    "HASH_CB3EAABA": "冲击波元素 - 精神控制",
    "HASH_8291C0BA": "大幅提升可用念力投掷物体的距离。",
    "UNL_DESC_STOMP_3": "最大化践踏的范围与眩晕时间。把整片街区都踏碎！",
    "HASH_5A76E5BA": "攀上高塔顶端以获取缓存与经验值。",
    "HASH_3958B5BA": "防守[format][color:defend]CID 与钥匙[/format]",
    "HASH_4D0C10BA": "[format][color:defend]挺过[/format]伏击",
    "HASH_8FCE10BA": "[format][color:use]拾取[/format]金吉的礼物",
    "HASH_FFEFB0BA": "消灭[format][color:kill]守卫[/format]",
    "UNL_STOMP_HUMAN_DAMAGE": "践踏 - 人类伤害",
    "HASH_373CBDBB": "超级跳跃",
    "HASH_614F9EBC": "冲击波元素 - 火焰",
    "HASH_113A03BC": "你现在可以用能量为身体和武器充能！\\n\\n使用 {SUPER_QUICK_SHIELD_IMG} 快速切换到增益。",
}

skipped = []
for k, v in add.items():
    if k not in untrans:
        skipped.append(("not_in_todo", k))
        continue
    trans[k] = v

# Consistency fix: 元气战车 -> 源木战车 (Genki 约定为 源木)
if "载具 - 元气战车" in trans.values():
    for k in list(trans.keys()):
        if trans[k] == "载具 - 元气战车":
            trans[k] = "载具 - 源木战车"
            print("consistency-fixed 元气战车 -> 源木战车 for", k)

json.dump(trans, open(tp, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("added:", len(add), "skipped:", skipped)
