import json, os
QA = os.path.dirname(os.path.abspath(__file__))
untrans = json.load(open(os.path.join(QA, "_untrans_mission_us.json"), encoding="utf-8"))
tp = os.path.join(QA, "_trans_mission_us.json")
trans = json.load(open(tp, encoding="utf-8")) if os.path.exists(tp) else {}

skip = set()

add = {
 "HASH_5BB9E07E": "入侵 [format][color:Location]拉斯蒂针管店[/format]",
 "HASH_7AA8917E": "扰乱 [format][color:Location]系统[/format]",
 "HASH_8801CD7E": "在葱郁的山坡上斩杀他的副指挥官",
 "HASH_E5D6D57F": "在飞船上会见 [format][color:Location]强尼[/format]",
 "HASH_91FF427F": "我需要更深入地理解这个模拟世界。你愿意来点儿麻烦吗？",
 "HASH_49DD177F": "前往 [format][color:location]军械岛[/format]",
 "HASH_77E0557F": "击杀 [format][color:kill]源木[/format]",
 "HASH_3B6CBC7F": "坚守 [format][color:location]阵地[/format]",
 "HASH_25EDD27F": "我",
 "HASH_66C7A37F": "我们甫一降落他们星球表面，神权政体之首——一位名为奎克祖格主教的威严人物——便不仅为自己的性命、更为其子民的性命求情。我向来公允，便应允在公平的战场上与他相会。君子之争，单挑对决。我甚至让他来选比试项目。令我错愕的是，他选了：",
 "HASH_CCCAA080": "肃清 [format][color:Location]辛族部队[/format]",
 "HASH_8E113880": "你扰乱模拟世界越甚，我们掌控之力便越强。",
 "HASH_F9A6B980": "前往 [format][color:location]雷鸣泵站[/format]",
 "HASH_11275780": "金吉的冒险",
 "M17_FAIL_BOMBS_EXPLODED": "炸弹爆炸了",
 "HASH_65912780": "在 [format][color:defend]文字冒险[/format] 中存活",
 "HASH_A7D55180": "饮下那杯酒",
 "HASH_2A897980": "意料之中，不是吗？我如今正踏入那个数月前我便如饥似渴研读过的、骄傲而充满偏见的社会。尽管津法克斯是个粗鄙之徒、始终如一根刺扎在我心间，我却在学业里寻得慰藉。文学早早便吸引了我，而津科夫预校的课业让我得以拓展至更高远的主题，诸如星际战争，以及如何将外交玩弄于股掌以谋私利。何等广袤的知识世界待我探索！",
 "HASH_8E635681": "扰乱 [format][color:Location]系统[/format]",
 "HASH_C4DD1B81": "清剿辛族部队",
 "HASH_A89C4D81": "我的敌人并非单纯倒于剑下——他们的意志如那多嘴下属的骨头般被我折断。我忆起他们时，不再仅有他们临终之言的回响，更有一整个世界扭曲的意象，以及根深蒂固的疑窦与恐惧。哦，喜悦！哦，奔流而下的极乐！",
 "HASH_9F44B381": "在津科夫预校的岁月过后，我做了所有辛族青年必行之事：参军。坦率说，在入读津科夫之前，我对这场成人礼毫无期待；但之后，我沉迷于将自身磨砺成日后那副模样的念头。",
 "HASH_B7D2ED82": "登上高塔",
 "HASH_79FF5582": "来看看这里是怎么运作的。",
 "HASH_8C3F1282": "前往 [format][color:location]断杖酒馆[/format]",
 "HASH_32193982": "营救 [format][color:defend]阿莎[/format]",
 "HASH_D3BCE482": "前往 [format][color:location]金吉的藏身处[/format]",
 "HASH_1CC2B982": "帮阿莎一把",
 "HASH_14F76682": "弄一辆 [format][color:location]车[/format]",
 "HASH_387E7482": "下楼前往 [format][color:location]厨房[/format]",
 "HASH_B4A02482": "有人或许以为，津舍这等地方养不起一家上好的面包房——你倒没说错；它开了一年便关门了——但绝非因为我母亲不够用心。她盼着独子能领略生活中更精致的馈赠，便以津卡尔那些可口点心开启了我的启蒙。",
 "HASH_04A15783": "清剿辛族部队",
 "HASH_42FDE283": "权力游戏",
 "HASH_C4FA5283": "紫色行动",
 "HASH_5A3AF083": "击退登舰者",
 "HASH_C16CEF83": "取得 [format][color:use]武器[/format]",
 "HASH_E4433C83": "向前 [format][color:location]侦察[/format]",
 "M11_FAILURE_DISCOVERED": "你被发现了！",
 "HASH_D115CC84": "入侵 [format][color:Location]辛族星球[/format]",
 "HASH_E2EAAB84": "抢走数据",
 "HASH_990F0284": "平台裂隙",
 "HASH_065B1B84": "一种心境",
 "HASH_DCEADF84": "击杀 [format][color:kill]恐怖分子[/format]",
 "HASH_E6D5C384": "呵。再说一遍，我就杀了你。",
 "HASH_A574C685": "清剿辛族部队",
 "HASH_0D427585": "前往 [format][color:location]活动起点[/format]",
 "HASH_4A4EAE85": "安放炸弹",
 "HASH_0248AF85": "你从壁烛台上取下水炬，推开门。眼前是一条漆黑走廊，没入墨般幽冥的黑暗。你仿佛走了永恒那么久，才发觉火炬已开始燃尽。\\n\\n你怎么做？\\n\\n",
 "HASH_53180985": "而我母亲则不同，这位嫁入远低于自身门第的巧手裁缝，希望我能享受旁人无从享有的事物。我清晰地记得，十三岁生日前夕，她带我去了：",
 "HASH_CBE76386": "嘿，老大，我瞧你最近有点紧绷。要是想发泄一下，我有些点子。",
 "HASH_6C590886": "在飞船上会见本",
 "HASH_3F8A9486": "现实世界",
 "HASH_DB3E4586": "[format][color:blue]完全[/format]",
 "HASH_4F246086": "模拟世界并非完美。世间无物完美。纵是杰作米洛的维纳斯，也缺了两条臂膀。但它是我的。它很美。对于那些试图逃脱、考验我耐心的家伙，我早有预案。必要时，我亲自介入。尽管鲜有必要。许多实验对象自以为能超然于模拟世界的法则之外，却被我一概打回原形。",
 "HASH_FC519686": "一场检验他基本礼仪素养的测验",
 "HASH_31F78F87": "在飞船上会见 [format][color:Location]阿莎[/format]",
 "HASH_F5BB6E87": "在飞船上会见本",
 "HASH_0CEC5187": "紧急状况",
 "HASH_2BBF7D87": "要进入其他模拟世界，我们需要那个 AI。如果得给他搞具身体，那就去搞。",
 "HASH_4B10DE87": "营救 [format][color:defend]贵宾[/format]",
 "HASH_A1953387": "击杀 [format][color:kill]外星人[/format]",
 "HASH_F9BD5687": "简·奥斯汀",
 "HASH_4969F688": "赢下津亚克最爱的游戏节目",
 "HASH_ADE8EC88": "关闭 [format][color:Location]热点[/format]",
 "HASH_0F354388": "转折",
 "HASH_B2793F88": "前往 [format][color:location]伏击点[/format]",
 "HASH_A8B79C88": "抓起 [format][color:use]报纸[/format]",
 "HASH_2DC67188": "五彩外衣",
 "HASH_FA1A4C89": "穿越系统竞速",
 "HASH_57718089": "在飞船上会见马特",
 "HASH_74FB5D89": "入侵 [format][color:Location]友军误击[/format]",
 "HASH_999D9489": "终结他",
 "HASH_F18FAE89": "保护 [format][color:defend]贵宾[/format]",
 "M17_FAIL_SHAUNDI_DIED": "肖恩蒂阵亡",
 "HASH_6FED9689": "关闭气闸",
 "M06_FAILURE_BIKE_DESTROYED": "摩托被摧毁",
 "HASH_16EB8789": "进入 [format][color:location]餐馆[/format]",
 "HASH_F24F0E89": "说实话，虽我极享受实验室里的种种实验，却觉科学整体是门相当乏味的学科。",
 "HASH_CF490F8A": "服从（再来一次）",
 "HASH_25870F8A": "偷走装置",
 "HASH_D70A038B": "踩踏 [format]花朵[/format]",
 "HASH_C4840C8C": "攀爬 [format][color:Location]高塔[/format]",
 "HASH_6E9C9E8C": "情节发展",
 "HASH_0A9CB68C": "在飞船上会见 [format][color:Location]强尼[/format]",
 "HASH_DC2DFC8C": "暗杀失控程序",
 "HASH_0E2F508C": "拦截宣传 [format][color:kill]卡车[/format]",
 "HASH_899E1D8C": "找到 [format][color:location]邪恶的你[/format]",
 "HASH_A64E3B8C": "这颗星球似乎是个沙漠世界，半径 3100 公里。\\n\\n你怎么做？",
 "HASH_7D18698D": "入侵 [format][color:Location]指定影像[/format]",
 "HASH_862FC28D": "来做我们最擅长的事吧。",
 "HASH_D8985B8D": "跳一支 [format][color:location]性感舞[/format]",
 "HASH_6FFBF38D": "进入 [format][color:use]模拟世界[/format]",
 "m20_failure_homie_dismissed": "小弟被遣散了！ ",
 "HASH_9164EA8E": "在飞船上会见基思",
 "HASH_E8BC678E": "关闭热点",
 "HASH_AE01D68E": "用椰子做两个马天尼杯",
 "HASH_15F7238E": "虽我对欧氏范式并不陌生，数学却并非吸引我的学科。",
 "HASH_8A12908F": "扰乱 [format][color:Location]系统[/format]",
 "HASH_57ABE98F": "在飞船上会见 [format][color:Location]基思[/format]",
 "HASH_08868C8F": "在飞船上会见基思",
 "HASH_38F1D58F": "完成密钥",
 "HASH_DA76108F": "前往 [format][color:location]源头[/format]",
 "HASH_9D7F698F": "击杀 [format][color:kill]典狱长[/format]",
 "HASH_A03AE98F": "然而盛名招致轻蔑，我于军旅生涯中树敌无数，却或许无人比津法布更尖刻、更令人心寒。他之于我，犹如布鲁图斯之于凯撒；津法布曾与我并肩抗衡贝多军队，立下汗马功劳，却在他的骄傲作祟时：",
 "HASH_490C4F90": "上传 [format][color:Location]病毒[/format]",
 "HASH_424B8A90": "找辛族挑事",
 "HASH_681D3E90": "击杀 [format][color:Location]目标[/format]",
 "HASH_15F58D90": "飞向紫色星辰",
 "HASH_901FFE91": "入侵 [format][color:Location]边缘工坊[/format]",
 "HASH_E3D25891": "探索 [format][color:Location]裂缝[/format]",
 "HASH_40EF0091": "说实话，我当时并没多想他。",
 "HASH_1670A092": "我们得回地球。",
 "HASH_75B96D93": "在 [format][color:Location]训练[/format] 中存活",
 "HASH_78583593": "后退",
 "HASH_04D1ED93": "饮下那杯酒",
 "HASH_DEC65D93": "是一位名叫津杰的果敢青年士兵，出类拔萃、鹤立鸡群。我便知他会是个好副官。但按惯例，为考验继任者之价值，我先施以：",
 "HASH_DABB0194": "在飞船上会见CID",
 "HASH_61FE0A94": "入侵 [format][color:Location]指定影像[/format]",
 "HASH_0171DE94": "击杀 [format][color:Location]目标[/format]",
 "HASH_4B763F94": "触碰  [format][color:use]符号[/format]",
 "HASH_380F9994": "取走步枪",
 "HASH_43596795": "在飞船上会见CID",
 "HASH_A597CA95": "探索裂缝",
 "HASH_D8626F95": "在 [format][color:Location]车流[/format] 里撒野",
 "HASH_DB403895": "在飞船上会见金吉",
 "HASH_89FA5195": "会见 [format][color:location]阿莎[/format]",
 "HASH_61AF0295": "返回任务目标",
 "HASH_E4207995": "极速裂缝",
 "HASH_A123FF95": "沉闷的心跳声填满房间。咚咚。咚咚。咚咚……\\n\\n你怎么做？",
 "HASH_DA75E195": "不，但我喜欢你思考的方式。",
 "HASH_96F4F396": "偷走 [format][color:Location]载具[/format]",
 "HASH_A9FBA496": "使用 [format][color:power_tele]念力[/format] 击杀 [format][color:power_tele]敌人[/format]",
 "HASH_A7572D96": "我被带到上级面前，接受一场虚伪的审判——那不过是为满足津法布一时的兴起，我向你保证——在庭上，我被要求就这些指控为自己辩护。",
 "HASH_EBF0E397": "不错。但这只是个开始。",
 "HASH_A4698397": "夜陨",
 "HASH_0315CD97": "关闭发电机",
 "HASH_5F934697": "收集 [format][color:use]武器[/format]",
 "HASH_E39D5597": "保持沉默",
 "HASH_D7932C97": "对敌人刻意为之的仇恨",
 "HASH_129AE797": "正如母亲所愿，津科夫预校是一所以学术课程为傲的学府。为此，它只招收展露学术才华与潜质者。于是，在入学考试前，我熬过了数周的标准化测试与训练。",
 "HASH_FA1C7298": "在飞船上会见俏皮肖恩蒂",
 "HASH_BD672D98": "入侵指定影像",
 "HASH_DF5F7D98": "圣徒之流",
 "HASH_B7BADD98": "使用 [format][color:power_buff]增益[/format] 后射击 [format][color:power_buff]典狱长[/format]",
 "HASH_EF7DC698": "检查 [format][color:location]克隆舱[/format]",
 "HASH_AFF18998": "而试炼模拟世界，还有谁比我的左膀右臂更合适？津杰本不情愿参与模拟，但一番简短——尽管剧痛——的交谈后，他明白了：让设计师自己第一个走进他亲手设计的建筑，大有裨益。",
 "HASH_63FE1499": "在飞船上会见俏皮肖恩蒂",
 "HASH_D02CC399": "攀爬 [format][color:Location]高塔[/format]",
 "HASH_F1A6BF99": "摧毁 [format][color:kill]卡车[/format]",
 "HASH_45CF8B99": "尾随 [format][color:location]夜刃[/format]",
 "HASH_8B80DB99": "进入 [format][color:use]传送门[/format]",
 "HASH_70F3C099": "调试 [format][color:kill]错误画面[/format]",
 "HASH_F721449A": "启动病毒注入",
 "HASH_4DF9C59A": "忠诚度——训练日",
 "HASH_03524B9A": "舞后",
 "HASH_E0A4BC9A": "尾随 [format][color:location]强尼·盖特[/format]",
 "HASH_AE36829A": "踩踏 [format][color:use]花朵[/format]",
 "HASH_FCDDE89A": "按响 [format][color:use]喇叭[/format]",
 "HASH_CCA91C9A": "防守 [format][color:defend]金吉[/format]",
 "HASH_F395359A": "踢 [format][color:use]门[/format]",
 "HASH_06002A9A": "借助杰扬熔融核心的地热能源，神权政体得以在整颗星球外撑起一面类戴森球护盾。它在阳光下熠熠生辉，宛如一列星辰在至纯微光中回旋起舞。而它在我们的中子激光下碎裂的模样，当真美得令人窒息。",
 "HASH_0F832B9B": "摧毁（扰乱系统）",
 "HASH_0081E79B": "这完美人生由“友煎乐”（Friendly Fryer）为你呈现。",
 "HASH_6F41899B": "会见 [format][color:location]皮尔斯[/format]",
 "HASH_8B52D69B": "进入 [format][color:location]模拟世界[/format]",
 "HASH_08B5289B": "等待 [format][color:defend]贵宾[/format]",
 "HASH_35F49F9B": "拾取电池",
 "HASH_E29D469B": "当你走向那靛蓝微光，走廊豁然开朗成一座更大的洞窟，光的源头也随之显形……房间由一汪巨型发光湖泊照亮。湖畔正舔舐水面的，是一头独角兽。\\n\\n你怎么做？\\n\\n",
 "HASH_F19DEE9B": "谋杀计量表",
 "M16_FAIL_ASHA_DIED": "阿莎阵亡！",
 "HASH_56F4D59C": "清剿辛族部队",
 "HASH_672DB89C": "在飞船上会见 [format][color:Location]阿莎[/format]",
 "HASH_1284F89C": "启动病毒注入",
 "HASH_2080019C": "开始任务",
 "HASH_AF1AD79C": "找到 [format][color:location]电池 [/format]",
 "HASH_089F809C": "去 [format][color:location]室外[/format]",
 "HASH_3A74AA9C": "再试一次",
 "HASH_5475CD9C": "那些挣扎之中，首当其冲的是我的双亲。父亲是个平凡的屠夫，个子矮小却脾气火爆。在父亲身上所学种种，最令我铭记于心的莫过于：",
 "HASH_6F05F49D": "在飞船上会见金吉",
 "HASH_5ABB6D9D": "大规模屠杀（启动病毒注入）",
}

skipped = []
for k, v in add.items():
    if k in skip:
        skipped.append(k)
        continue
    if k not in untrans:
        skipped.append(("not_in_untrans", k))
        continue
    trans[k] = v

if skipped:
    print("skipped:", skipped)
json.dump(trans, open(tp, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("merged. trans size now:", len(trans))
