# -*- coding: utf-8 -*-
import json, os

qa = os.path.dirname(os.path.abspath(__file__))
tp = os.path.join(qa, "_trans_new_sr35_us.json")
todo_p = os.path.join(qa, "_todo_new_sr35_us_01.json")

untrans = json.load(open(todo_p, encoding="utf-8"))
trans = json.load(open(tp, encoding="utf-8")) if os.path.exists(tp) else {}

add = {
    "HASH_1B989100": "增加可用念力投掷物体的距离。",
    "UNL_DESC_TELEKINESIS_4": "念力对载具造成极大伤害！",
    "UNL_DESC_SUPER_TK_PC": "你现在可以用念力抓起并投掷人和物体了！\\n\\n使用 {SUPER_QUICK_TELEKINESIS_IMG} 快速切换到念力。",
    "UNL_DESC_STOMP_CAR_DAMAGE": "践踏对载具造成极大伤害。",
    "HASH_C1B58800": "已解锁美国总统之位！\\n\\n按下所有按键以发动全球热核战争！",
    "HASH_6A2C5F00": "变得轻如羽毛，大幅延长滑翔距离。",
    "HASH_A5A03300": "市中心已解锁新的传送门。\\n返回飞船，在这里存取你的武器库、服装、载具和帮派自定义内容。",
    "HASH_E509C000": "增大增益效果的影响范围。",
    "HASH_84D63E00": "激活缩小践踏",
    "HASH_EB2A7D00": "呼叫唐尼",
    "HASH_0794C800": "文字冒险",
    "HASH_E4AC3D00": "本·金阵亡！",
    "HASH_BF7D6000": "念力·源木风格",
    "HASH_84656100": "赢得全部「超能格斗俱乐部」银牌，即可呼叫源木女郎提供支援。",
    "HASH_D2A00A01": "机甲战衣 - 悬浮消耗 3",
    "HASH_D6715D01": "切换念力元素",
    "HASH_FB486401": "用念力杀几个辛族。这既有趣又有教育意义！好吧，没什么教育意义，但绝对有趣！",
    "HASH_8F208401": "这辆载具座位不够所有人坐！",
    "HASH_AE01A502": "机甲战衣 - 持续时间 2",
    "HASH_BECD3402": "卡弗岛已解锁新的传送门。\\n返回飞船，在这里存取你的武器库、服装、载具和帮派自定义内容。",
    "HASH_B6A5B802": "摧毁[format][color:blue]蓝色标记木箱[/format]可获得医疗补给，用于修复机甲战衣。",
    "HASH_474FF502": "劫持病毒",
    "HASH_38566503": "船员 - 基思·大卫",
    "HASH_31B79E03": "MI6 特工阿莎·奥德卡已被救回，现在登上飞船！去找她学习如何使用新武器。",
    "HASH_43250F03": "大幅提升所有医疗补给的价值。",
    "HASH_5EA4DA03": "选择谁去渗透统治矩阵的主机，为你铺路。挑一个你信得过的人来完成任务；一旦你回到现实世界，他们将无法再提供帮助。",
    "HASH_A9AB6203": "[format][color:location]逃离[/format]监狱",
    "HASH_1C94E703": "超能暴打",
    "HASH_281CE803": "完成其他 12 项挑战",
    "HASH_4C9F0E04": "吸血",
    "HASH_9793CA04": "脱光",
    "HASH_1FA03E04": "在整个模拟世界中，总统追逐着辛族爪牙。总统觉得这一切都很好玩。砰！辛族爪牙应声倒下！",
    "HASH_8A459805": "你现在可以用冲击波朝敌人发射能量了！\\n\\n使用 {SUPER_QUICK_FREEZE_IMG} 快速切换到冲击波。",
    "HASH_6D286605": "横版卷轴",
    "HASH_EAC40B05": "{ATTACK_PRIMARY_IMG} 开炮 \\n{ATTACK_SECONDARY_IMG} 发射火箭 \\n{SPRINT_IMG} 冲刺 \\n{MELEE_NUT_SHOT_IMG} 近战猛击 ",
    "HASH_67357C05": "与马特·米勒恋爱",
    "HASH_F7F6BC05": "触手蝙蝠暴打",
    "HASH_34055505": "把音量拉满，低频多砸几下，顺便干掉几个辛族。",
    "HASH_B2C14D05": "天降杀戮击杀数",
    "UNL_JUMP_SPEED": "跳跃 - 距离",
    "UNL_DESC_STOMP_HUMAN_DAMAGE": "践踏对人类造成更高伤害。",
    "HASH_2F8DDF06": "只要装备了增益，攻击就有几率附加元素伤害。",
    "HASH_562C8206": "冻结[format][color:power_blast]冲击波[/format]后射击[format][color:power_blast]典狱长[/format]",
    "HASH_92D78606": "确认队伍分配",
    "HASH_0546FA06": "拯救[format][color:location]强尼·盖特[/format]",
    "HASH_55134E07": "金吉和副总统基思·大卫现已登船。去找他们领取任务，学习如何破坏模拟世界并扰乱津亚克的行动。",
    "HASH_F078B607": "@@BUFF_FIRE^^增益激活期间，附近的同伴免疫火焰。@@BLAST_FREEZE^^附近的同伴有几率发射冰冻子弹。@@BUFF_LIGHTNING^^附近的同伴有几率发射闪电子弹。",
    "HASH_2F225B07": "投掷炸弹摧毁高塔。\\n\\n炸弹只会伤害同色的塔。",
    "HASH_B88BE907": "被冻结的敌人会原地不动，受到的伤害大幅提高。\\n\\n用冻结[format][color:power_blast]冲击波[/format] {ATTACK_SECONDARY_IMG} 击中这些敌人，然后干掉他们。",
    "HASH_5C52AC07": "找到[format][color:location]能量导管[/format]",
    "HASH_DC146207": "[format][color:use]打开[/format]货舱门",
    "HASH_55426207": "UFO 大混乱",
    "HASH_FB299E08": "同伴 - 强尼·盖特",
    "HASH_9D75B008": "超级冲刺时速度更快。",
    "HASH_21C0FF08": "冻结你的敌人，然后用枪攻击他们造成双倍伤害！",
    "HASH_EF07CA08": "斯坦菲尔德岛已解锁新的传送门。\\n返回飞船，在这里存取你的武器库、服装、载具和帮派自定义内容。",
    "HASH_98A44F09": "武器 - 弹跳步枪",
    "UNL_HOMIE_DANE_VOGEL": "同伴 - 德恩·沃格尔",
    "HASH_5267BE09": "大幅提升机甲战衣的悬浮速度。你或许该考虑把它漆成红色。",
    "HASH_C9DDBF09": "机甲生命值",
    "HASH_66A94D09": "黄金 CID 击杀",
    "HASH_4C86210A": "津亚克雕像",
    "UNL_TELEKINESIS_REDUCED_MANA_1": "念力 - 充能",
    "HASH_64B1A00A": "践踏元素 - 缩小",
    "UNL_DESC_UFOMAYHEM": "模拟世界中已开放更高难度的 UFO 大混乱活动。\\n查看地图了解位置。",
    "UNL_DESC_RAGDOLL_RECOVERY": "按下 {JUMP_CLIMB_IMG} 即可在被击倒后立刻起身。\\n\\n对任何踏入超能战斗的圣徒来说都是必备之选。",
    "HASH_8DAD6B0A": "按住 {SUPERJUMP_FORWARD_BOOST_IMG} 滑翔",
    "HASH_41069F0A": "与金吉交谈",
    "HASH_35423F0A": "消灭外星小队",
    "UNL_DESC_JUMP_REDUCED_MANA_3": "滑翔不再消耗体力。",
    "HASH_1423E90B": "对[format][color:kill]敌人[/format]使用天降杀戮",
    "HASH_69303B0B": "文字冒险碎片",
    "HASH_2E4BF00C": "天降杀戮 - 瞄准",
    "HASH_6624CC0C": "肖恩蒂已被救回，现在登上飞船！去找她，帮她与过去和解。",
    "HASH_07C5AA0C": "增益 - 持续时间",
    "HASH_F309E10D": "已解锁崇拜",
    "HASH_A9D2B70D": "@@TK_FORCE^^提升被投掷载具的伤害。@@TK_LIGHTNING^^增加闪电在物体间弧跳的距离。@@TK_LIFE_STEAL^^提升每秒窃取的生命值。",
    "UNL_DESC_HACKING_EXTRA_TIME": "完成商店黑客入侵的时间翻倍。",
    "HASH_5673660D": "脸撞车流",
    "HASH_B58DB80E": "超级同伴 - 阿莎",
    "HASH_0975D00E": "用能量剑击杀敌人时，掉落的治疗量翻倍。把敌人切成美味的治疗碎片吧！",
    "HASH_DE1CFB0E": "核爆",
    "HASH_8C4C5C0E": "{ATTACK_SECONDARY_IMG} [format][color:power_pound]超级践踏[/format]\\n制造巨大冲击波，对附近目标造成毁灭性破坏。 ",
    "HASH_667F2D0E": "{SPRINT_IMG} 猛撞可破坏物体",
    "HASH_DBBAC70E": "双击 {SUPER_QUICK_STOMP_IMG}\\n快速切换[format][color:power_pound]践踏[/format]元素\\n\\n从所有已获得的[format][color:power_pound]践踏[/format]元素中快速选择。",
    "HASH_7032B80F": "NFLATO 射线战衣",
    "HASH_B83DAB0F": "呼叫夜刃",
    "HASH_5B5C280F": "{ANALOG_RS_IMG} 瞄准\\n{ATTACK_PRIMARY_IMG} 射击",
    "HASH_7A93DD0F": "这把外星武器暂时没电了。\\n\\n经过短暂冷却后会迅速重新充能。",
    "HASH_94FBFB0F": "与本·金恋爱",
    "HASH_FB69940F": "恢复",
    "HASH_FBE6570F": "与同伴共处的时间",
    "UNL_DESC_MANA_RECOVERY_3": "超能力能量恢复速度提升 50%%",
    "HASH_EBF7DD10": "消灭[format][color:kill]警察[/format]",
    "HASH_6A06C810": "消灭[format][color:kill]大托尼[/format]",
    "HASH_B5079310": "赢得全部「载具大混乱」金牌，即可在虚拟钢埠停放更多外星载具。",
    "HASH_657E2010": "前往有趣的地方。结识新物种。然后干掉它们。",
    "HASH_ACFBD910": "你召唤 UFO 降临，UFO 把敌人吸上去。它们去了哪儿？谁在乎呢！",
    "HASH_75AF0211": "念力元素 - 闪电",
    "HASH_EA4AA611": "新科尔文岛已揭晓！",
    "HASH_67489511": "津亚克雕像",
    "HASH_C13A7D11": "船上的圣徒可从主菜单 - 手机界面呼叫。叫来支援，或者只是出来聚聚！",
    "HASH_9C418711": "返回传送门",
    "HASH_76A63611": "弹跳步枪击杀数",
    "HASH_356F8E12": "赛博斯特拉达现已在你的传送门车库中提供。",
    "HASH_DCBD7412": "超级护盾",
    "HASH_6591D012": "距离",
    "HASH_8B114312": "找到[format][color:location]军械库[/format]",
    "HASH_00860B13": "载具 - 圣徒 XOR",
    "UNL_RELOAD_COOLDOWN_4": "更快冷却 4",
    "HASH_5D958113": "奇点枪的黑洞充能速度快得多。",
    "HASH_1236A414": "冲刺 - 墙壁奔跑",
    "UNL_DESC_HADOUKEN_SUPPRESSION_1": "使用核爆后，力量恢复速度略快",
    "HASH_87CFA614": "在你周围制造巨大的数据涌流，使敌人故障失控并为你而战！\\n\\n双击 {SUPER_QUICK_FREEZE_IMG} 在冲击波元素间快速切换。或在力量菜单中切换元素。",
    "HASH_D1243614": "大幅提升冲击波的作用范围。",
    "UNL_DESC_AIR_DASH_3": "每次超级跳跃可冲刺三次。",
    "HASH_B6815A14": "冲击波 - 伤害",
    "HASH_A4DFCA14": "{SIDESCROLL_PUNCH_IMG} 拳击 \\n{SIDESCROLL_KICK_IMG} 踢腿",
    "HASH_E0302314": "[format][color:defend]躲避[/format]激光",
    "M18_GO_IN_OFFICE": "进入[format][color:location]办公室[/format]",
    "HASH_8A4A6D14": "与阿莎交谈",
    "UNL_HADOUKEN_REDUCED_MANA_1": "核爆 - 充能",
    "HASH_55851D15": "消灭[format][color:kill]老兵之子[/format]",
    "HASH_B3FD6E15": "碎裂击杀",
    "HASH_17CDBC15": "模拟世界会敬重一个懂得做事之道的圣徒。",
    "HASH_19ADFE16": "蓄力超级跳跃的高度提升。",
    "HASH_2E60EA16": "用电力为你的子弹和周围空气充能。闪电在敌人之间弧跳造成额外伤害！\\n\\n双击 {SUPER_QUICK_SHIELD_IMG} 在增益元素间快速切换。或在力量菜单中切换元素。",
    "HASH_F0A5BD16": "新科尔文岛已解锁新的传送门。\\n返回飞船，在这里存取你的武器库、服装、载具和帮派自定义内容。",
    "HASH_7D231716": "力量",
    "HASH_94269816": "等待其他玩家",
    "HASH_E5710316": "音频日志",
    "HASH_462C5216": "目标区域",
    "UNL_SHIELD_3": "护盾 - 生命恢复",
    "UNL_HADOUKEN_1": "核爆 - 更快恢复",
    "HASH_520A8817": "奖励 - 黑客入侵奖励",
    "HASH_7862EF17": "适度延长可驾驶机甲战衣的时间。",
    "HASH_45D49E17": "{ATTACK_SECONDARY_IMG} 发射火箭\\n炸开上锁的门。",
    "HASH_7FB1FD18": "念力 - 强化",
    "UNL_DESC_STOMP_ARC": "践踏影响的范围更广。",
    "HASH_F0498C18": "服装 - 本·金套装",
    "HASH_D1707E18": "抵达[format][color:location]安全区[/format]",
    "HASH_FDE78A18": "赢得全部「徒步大混乱」金牌，即可解锁更多弹药储备。",
    "UNL_DESC_HADOUKEN_REDUCED_MANA_3": "核爆不再消耗能量",
    "HASH_838CB21A": "你现在可以使用传送门在飞船与模拟世界之间穿梭。\\n使用斯坦菲尔德岛的传送门返回飞船，存取你的武器库、服装、载具和帮派自定义内容。",
    "HASH_9BF4291A": "典狱长暴打",
    "HASH_1830921A": "摧毁[format][color:purple]津亚克雕像[/format]可获得缓存与经验值。",
    "HASH_2D1C431A": "待在[format][color:location]区域内[/format]",
    "HASH_06EAFE1A": " - 简单",
    "HASH_6B0D921B": "机甲战衣 - 超频 2",
    "HASH_A761031B": "奖励 - 闪点奖励",
    "HASH_F6E0F51B": "线框维和者现已在你的传送门车库中提供。",
    "HASH_1B02FA1B": "与阿莎恋爱",
    "HASH_D5BC651C": "与强尼·盖特恋爱",
    "HASH_CAEDDC1C": "故障",
    "UNL_MANA_RECOVERY_1": "超能能量 - 更快恢复",
    "HASH_AE87981D": "{ATTACK_SECONDARY_IMG} 念力 \\n将人、汽车和源木物体投掷到对应目标上。",
    "HASH_DC656C1D": "林凡事三思而后行，在出手前必定摸清所有选项。林随时乐意以任何方式提供帮助。",
    "HASH_81604E1D": "与皮尔斯恋爱",
    "HASH_BBACD41D": "超能格斗俱乐部金牌",
    "HASH_F52EF41E": "源木武器战衣",
    "HASH_6B53C91E": "超级同伴 - 马特·米勒",
    "HASH_A62AF41E": "切换践踏元素",
    "HASH_49C64F1F": "船员 - 金吉·肯辛顿",
    "UNL_DESC_TELEKINESIS_REDUCED_MANA_2": "念力能量充能速度更快。",
    "UNL_DESC_SPRINT_REDUCED_MANA_3": "超级冲刺不再消耗能量。",
    "HASH_41B1921F": "穿回衣服",
    "HASH_0703EE1F": "外星武器 ",
    "HASH_0472DD1F": "机甲战衣行驶距离",
    "HASH_A1F0FD20": "强尼·盖特与本·金",
    "HASH_EA78AB21": "念力大混乱",
    "UNL_SPRINT_BUILDUP": "冲刺 - 急速",
    "HASH_37286021": "黑客入侵[format][color:use]商店[/format]",
    "HASH_3DFA7B21": "指挥官",
    "UNL_SPRINTING_2": "冲刺 - 推撞",
    "HASH_A9AB6E22": "船员 - 阿莎·奥德卡",
    "HASH_4AC7C422": "进入模拟世界",
    "HASH_F4907322": "赢得全部「极速裂隙」银牌，即可在水面上奔跑。",
    "HASH_23C13622": "当你击碎被冻结的敌人时，只想问一个问题：你为什么要这么冷酷？",
    "UNL_TELEKINESIS_HOLD_COST": "念力 - 持续消耗",
    "HASH_B76A0024": "载具 - 铬合金封锁",
}

skipped = []
for k, v in add.items():
    if k not in untrans:
        skipped.append(("not_in_todo", k))
        continue
    trans[k] = v

json.dump(trans, open(tp, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("added:", len(add), "skipped:", skipped)
