# -*- coding: utf-8 -*-
import json, os

qa = os.path.dirname(os.path.abspath(__file__))
tp = os.path.join(qa, "_trans_new_sr35_us.json")
todo_p = os.path.join(qa, "_todo_new_sr35_us_02.json")

untrans = json.load(open(todo_p, encoding="utf-8"))
trans = json.load(open(tp, encoding="utf-8")) if os.path.exists(tp) else {}

add = {
    "HASH_FA4AB124": "灯泡不包含在内。这套服装现已在你的传送门衣橱中提供。",
    "HASH_C6230224": "激活冰冻冲击波",
    "HASH_AB3C6224": "跳跃连锁",
    "HASH_50E4C925": "冲击波 - 伤害 2",
    "HASH_F7882525": "激活重力践踏",
    "HASH_24B9C025": "与在线玩家创建合作模式会话",
    "HASH_1C031F25": "肖恩蒂已成为一个专注而有冲劲的女人，绝不任人摆布。她在战斗中是个狂战士，但必要时也能制定计划。",
    "UNL_WEP_ABDUCTION": "武器 - 绑架机器",
    "UNL_TELEKINESIS_REDUCED_MANA_3": "念力 - 充能 3",
    "UNL_RELOAD_COOLDOWN_2": "更快冷却 2",
    "HASH_F7155326": "攀登高塔",
    "HASH_7F618F26": "访问主菜单",
    "HASH_AA7DAA26": "跟随[format][color:location]副总统[/format]",
    "M18_FAIL_SPEECH": "你离开了区域！",
    "HASH_57E13F27": "载具 - 赛博枪手",
    "UNL_DESC_JUMP_REDUCED_MANA_1": "滑翔消耗更少体力。",
    "HASH_491F6627": "激活火焰冲击波",
    "HASH_958B1227": "角色选择",
    "UNL_SPRINT_REDUCED_MANA_2": "冲刺 - 效率 2",
    "HASH_40571228": "防守区域",
    "HASH_B6AF2B29": "人工智能已被上传到飞船上的 C.I.D. 中。去找这个人工智能，学习如何进一步提升你的超能力。",
    "HASH_A1BE0129": "传送门 - 阿拉皮斯岛",
    "HASH_F0630A29": "念力",
    "HASH_47412D29": "摧毁[format][color:kill]中继器[/format]",
    "HASH_0D444E2A": "念力不再消耗能量。",
    "HASH_3642EB2A": "赢得全部「烈焰」金牌，即可解锁黄金武器战衣。",
    "HASH_E3A1412B": "大幅提升天降杀戮的攻击范围。",
    "HASH_9AEF932B": "激活吸血念力",
    "HASH_C0B7252B": "呼叫俏皮肖恩蒂",
    "HASH_6AE4FE2B": "{DPAD_IMG} 快速切换力量\\n快速切换超能力，自由搭配组合出致命连招。",
    "HASH_5685882B": "被冻结时，典狱长的护盾会暂时失效。\\n\\n用冻结[format][color:power_blast]冲击波[/format] {ATTACK_SECONDARY_IMG} 击中这名典狱长，然后用你的武器造成伤害。",
    "HASH_AD88952B": "消灭[format][color:kill]典狱长[/format]",
    "HASH_20266E2B": "防守[format][color:defend]传送门[/format]",
    "HASH_8B2E272B": "拾取[format][color:power_tele]钥匙[/format]",
    "HASH_A27E4C2B": "完成其他 46 项挑战",
    "HASH_8D6A182C": "载具 - 铬合金虚空",
    "HASH_B0BC962C": "一批怪兽卡车现已在你的传送门车库中提供。",
    "HASH_F596F02C": "最大化可用念力投掷物体的距离。",
    "UNL_DESC_STOMP_2": "大幅提升践踏的范围与眩晕时间。",
    "HASH_A119492C": "[format][color:defend]躲避[/format]碎片",
    "HASH_FCEA8F2C": "真正妙不可言的，是看着它们替你对付敌人。",
    "HASH_895F932C": "再多掌握模拟世界的一些方面，你就能更便宜地穿戴光鲜。",
    "HASH_05E1A12D": "火焰武器战衣",
    "HASH_3CAE6B2D": "机甲战衣 - 悬浮消耗",
    "UNL_DESC_SUPER_STOMP_PC": "你现在可以一脚跺向地面，用超级践踏把附近的一切震飞！\\n\\n使用 {SUPER_QUICK_STOMP_IMG} 快速切换到践踏。",
    "HASH_012F8A2D": "冻结",
    "HASH_9DDF4B2D": "我来了，我看见，我征服",
    "HASH_548EDF2D": "赢得全部「源木·精神制胜」金牌，即可解锁源木武器皮肤。",
    "HASH_C3B8C92D": "外星高通缉时间",
    "HASH_942FDF2D": "UFO 大混乱",
    "HASH_F1712B2E": "已解锁顾问",
    "HASH_C119BA2E": "去[format][color:use]购物[/format]",
    "HASH_585C7F2F": "念力 - 投掷消耗",
    "HASH_B4F24E2F": "它必须是紫色的。",
    "HASH_02DC692F": "强尼·盖特已被救回，现在登上飞船！去找他学习如何制造大规模杀伤性武器。",
    "HASH_AD2B6E2F": "略微提升所有医疗补给的价值。",
    "HASH_C4B5092F": "@@BLAST_FREEZE^^被冻结时目标承受更高伤害。@@BLAST_FIRE^^燃烧时目标每秒承受更多伤害。@@BLAST_GLITCH^^提升可同时控制的目标数量。",
    "HASH_33C4052F": "访问传送门武器库时获得更多免费弹药。",
    "HASH_071B522F": "{ATTACK_PRIMARY_IMG} 开火主炮 \\n{ANALOG_RS_IMG} 精确瞄准",
    "HASH_737C5E2F": "冰冻冲击波",
    "HASH_2C3B962F": "砸碎[format][color:kill]木箱[/format]以修复",
    "HASH_8B48682F": "格斗俱乐部",
    "HASH_95A52230": "用天降杀戮干掉一百个辛族。只要记住……要是光着身子，他们可全看在眼里。",
    "UNL_MANA_RECOVERY_3": "超能能量 - 更快恢复 3",
    "HASH_69928B31": "同伴 - 罗迪·派珀",
    "HASH_A720D331": "精神控制",
    "HASH_18120331": "消灭[format][color:kill]外星人[/format]",
    "HASH_4B124431": "禁用[format][color:use]卫星[/format]",
    "HASH_F6B99F31": "[format][color:location]跳离[/format]飞机",
    "HASH_92114D31": "闯入[format][color:location]牢房[/format]",
    "HASH_61F8FA31": "与肖恩蒂交谈",
    "HASH_43318631": "%%",
    "HASH_478B3E32": "武器 - 半自动霰弹枪",
    "HASH_CD225E32": "和盖特一起大开杀戒。",
    "HASH_EE494432": "缩小敌人被压扁数",
    "HASH_99557733": "奇点枪充能升级",
    "HASH_AD737E33": "载具 - 赛博斯特拉达",
    "UNL_DESC_SPRINT_REDUCED_MANA_1": "超级冲刺消耗更少体力。",
    "HASH_9AB76933": "冲刺滑翔",
    "HASH_FA946F33": "电晕一个敌人不错。看它们在彼此间传递才是真正的目的。你能让闪电弧跳到多少个敌人身上？",
    "HASH_5929B834": "生命 - 补给价值 2",
    "HASH_7ADB9534": "用致命的火墙将自己和子弹一并包裹！",
    "HASH_C3309034": "桶滚",
    "HASH_959ACE34": "达到能量等级 %d",
    "UNL_DESC_TELEKINESIS_2": "念力可以接住朝你扔来的物体！",
    "UNL_DESC_HADOUKEN_REDUCED_MANA_1": "核爆仅消耗 75%% 能量",
    "HASH_D27CEC35": "渗透",
    "HASH_39625C35": "UFO 大混乱",
    "HASH_E8CB8835": "赢得全部「保险欺诈」银牌，即可抵抗被爆炸击倒。",
    "HASH_839A9A35": "充分掌握模拟世界，你甚至能将自己的圣徒人工智能赋予超能力！",
    "UNL_WARDEN_BEATDOWN_2": "典狱长 - 终结技 2",
    "HASH_D8C01F36": "呼叫马特上场。",
    "HASH_A5C95F36": "前往[format][color:location]友军火力[/format]",
    "HASH_28653236": "离开[format][color:use]商店[/format]",
    "HASH_B1A1E136": "探索[format][color:location]教堂[/format]",
    "UNL_WEP_SHRINK_RAY": "武器 - 微缩射线枪",
    "HASH_E9F51F37": "激活闪亮冲击波",
    "HASH_A011EC37": "{ATTACK_PRIMARY_IMG} 激活爆发\\n爆发可击碎障碍物获取资料，并提升所有数据价值。",
    "HASH_FEA4F137": "购买[format][color:use]升级[/format]",
    "m22_2_out_of_time": "未能及时逃脱",
    "UNL_SUPER_TK": "念力",
    "HASH_ABFAB438": "格斗俱乐部",
    "UNL_DESC_HADOUKEN_SUPPRESSION_3": "使用核爆后，力量恢复速度大幅加快",
    "UNL_DESC_AIR_DASH_1": "按下 {SPRINT_IMG} 即可在空中获得加速。",
    "HASH_9E9E6938": "若你坠落，可从塔底传送至已激活的最高传送点以节省时间。",
    "HASH_E46F8E38": "火焰冲击波",
    "HASH_C6997338": "皮尔斯与肖恩蒂",
    "HASH_17106538": "用你的冲刺护盾挡下他们的射击。",
    "UNL_HOMIE_MAERO": "同伴 - 马罗",
    "UNL_HADOUKEN_REDUCED_MANA_3": "核爆 - 充能 3",
    "HASH_4520A339": "超能竞速",
    "UNL_WEP_MINEFIELD": "武器 - 杀戮机器人布雷器",
    "UNL_DESC_WEP_LASER_MINIGUN": "杀戮机器人的迷你枪已被逆向工程。用「灭绝者」在战场上横扫死亡！\\n在传送门武器库装备它。",
    "HASH_F7A39F3A": "蓄力超级跳跃达到最大高度。你能一跃跳过高楼大厦！",
    "HASH_9D46E13A": "冲击波 - 爆炸死亡",
    "HASH_7932603A": "打开选项菜单",
    "HASH_FF88D53A": "进入[format][color:location]监狱[/format]内部",
    "UNL_SHIELD_1": "护盾 - 能量充能",
    "UNL_HADOUKEN_3": "核爆 - 更快恢复 3",
    "HASH_7829013B": "从选项菜单打开音频设置",
    "HASH_FB98D73B": "在被叛徒废黜之前，本·金在斯提尔沃特经营 Vice Kings 帮派多年。金是战术大师与长远谋略者，但动起手来也毫不含糊。",
    "HASH_8323DB3B": "完成其他 27 项挑战",
    "UNL_DESC_MANA_RECOVERY_1": "超能力能量恢复速度提升 10%%",
    "HASH_C2AB1A3C": "机甲跳跃喷射",
    "HASH_7848D93C": "念力击杀",
    "UNL_VEHICLE_UFO": "载具 - UFO",
    "UNL_JUMP_REDUCED_MANA_2": "滑翔 - 效率 2",
    "UNL_HOMIE_UFO": "同伴 - UFO",
    "HASH_C264933D": "天降杀戮 - 伤害",
    "HASH_5734B43D": "这条裤子没有看上去那么花哨。马特·米勒的服装现已在你的传送门衣橱中提供。",
    "HASH_CE7C113D": "增益激活期间提升行走速度。",
    "HASH_5DB98C3D": "增益 - 被动侵略",
    "HASH_83DB9A3D": "与马特·米勒交谈",
    "HASH_7C578C3D": "这是唯一的出行方式。",
    "HASH_8EDBA23E": "念力元素 - 吸血",
    "UNL_DESC_FREEZE_DAMAGE_2": "目标被冻结时承受更高伤害。",
    "HASH_74DC3C3E": "[format][color:location]离开[/format]",
    "HASH_8684E43E": "消灭[format][color:kill]VICE KINGS[/format]",
    "HASH_4F27913E": "它们越大，被你湮灭时炸成数据碎片的动静就越猛。",
    "HASH_6D32043F": "这些来自那个讨人喜欢的疯子「人猫」的私人收藏：\\n\\n荷马，卡达克激光枪。",
    "HASH_7A8B613F": "炮塔控制",
    "HASH_7E99783F": "在病毒上传时消灭敌人",
    "HASH_0A2A2A3F": "移除敌方代码",
    "HASH_2305BB40": "载具 - 赛博怪兽卡车",
    "HASH_1CBEBB40": "斯坦菲尔德岛已解锁新的传送门。\\n返回飞船，在这里存取你的武器库、服装、载具和帮派自定义内容。",
    "HASH_C1E48D40": "冲击波能量充能速度更快。",
    "HASH_0D23E440": "选择一名指挥官，从此处协助协调攻击。领导力是成功指挥官的关键。",
    "HASH_801B7C40": "载具被超级踢飞数",
    "HASH_28878440": "唐尼被杀",
    "HASH_474A8041": "激活火焰增益",
    "UNL_TELEKINESIS_2": "念力 - 接取",
    "HASH_C326BC42": "移除部分安全协议，使机甲战衣的武器充能更快。",
    "HASH_899AA742": "绑架机器",
    "HASH_CDC0A042": "是时候干掉津亚克了",
    "HASH_9D445442": "科学小知识：严格来说，分解器并不会把人彻底消灭。它先把人分解成组成分子……然后再消灭那些分子。去消灭一些辛族分子吧。",
    "HASH_CBA24843": "增益元素 - 火焰",
    "UNL_DESC_WARDEN_BEATDOWN_3": "终结典狱长现在容易得多。",
    "HASH_21C13C43": "激活精神控制冲击波",
    "HASH_2A9B8C43": "带来一点节日欢欣",
    "HASH_49569843": "飞船操控",
    "HASH_83268F43": "防守[format][color:defend]钥匙[/format]",
    "HASH_D0DAF543": "津亚克雕像已摧毁",
    "UNL_TELEKINESIS_FIRE": "念力 - 火焰",
    "HASH_8E3FB544": "正在离开防守区域",
    "HASH_E69FBB45": "卡弗岛已揭晓！",
    "HASH_3E91DD45": "[format][color:kill]摧毁[/format]货舱门",
    "HASH_2CCED245": "西南城区",
    "HASH_3AB32945": "冲刺险过",
    "HASH_3B5B4F46": "铬合金响尾蛇现已在你的传送门车库中提供。",
    "HASH_4231D546": "增大天降杀戮造成的爆炸范围。",
    "HASH_91515246": "呼叫强尼·盖特",
    "HASH_E91B4246": "决定由谁去执行佯攻，而你则专注于引出津亚克。独自在外会很危险，所以挑一个能独当一面的人。",
    "UNL_SUPPRESS_DURATION_1": "压制 - 能量恢复",
    "UNL_DESC_DFA_AIRCRAFT": "天降杀戮可锁定飞行器。",
    "HASH_04710847": "新科尔文岛已解锁新的传送门。\\n返回飞船，在这里存取你的武器库、服装、载具和帮派自定义内容。",
    "HASH_8839FD47": "呼叫圣徒后援",
    "HASH_CE129D47": "复活[format][color:revive]基思·大卫[/format]",
    "HASH_8256BC48": "津亚克在虚拟钢埠各处竖立了雕像。摧毁它们可获得额外缓存与经验值。",
    "HASH_D9B48648": "略微提升医疗补给被吸向你的范围。",
    "HASH_972ECB48": "开始机甲战衣大混乱",
}

skipped = []
for k, v in add.items():
    if k not in untrans:
        skipped.append(("not_in_todo", k))
        continue
    trans[k] = v

json.dump(trans, open(tp, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("added:", len(add), "skipped:", skipped)
