import json, os
QA = os.path.dirname(os.path.abspath(__file__))
untrans = json.load(open(os.path.join(QA, "_untrans_mission_us.json"), encoding="utf-8"))
tp = os.path.join(QA, "_trans_mission_us.json")
trans = json.load(open(tp, encoding="utf-8")) if os.path.exists(tp) else {}

skip = set()

add = {
 "HASH_E1B8079D": "尽管他们为此追求了数个世纪，所有将血肉与科技融合的尝试，最终也不过造出些自动收割机罢了。",
 "HASH_E85F6B9E": "抢走数据",
 "HASH_9688999E": "探索裂缝",
 "HASH_BAEB239E": "卡车被摧毁了！",
 "HASH_6C4F5E9E": "揍那个混蛋",
 "HASH_87C03D9F": "在 [format][color:location]飞船[/format] 上会见金吉",
 "HASH_75084D9F": "完成 [format][color:use]她[/format]",
 "HASH_38E7509F": "马特归队了",
 "HASH_4CF46FA0": "穿越系统竞速",
 "HASH_32239DA0": "清剿辛族部队",
 "HASH_2E3EE1A0": "皮尔斯需要帮忙。十万火急。",
 "HASH_43D20BA0": "偷走弹跳枪",
 "HASH_48405AA0": "你找到了一些元素一号。\\n\\n你怎么做？",
 "HASH_EA2404A0": "借夜色掩护潜入他的基地",
 "HASH_42679DA1": "上传 [format][color:Location]病毒[/format]",
 "HASH_783090A1": "杀杀杀摧毁杀",
 "MOL_P01_FAILURE_PIERCE_CAR": "皮尔斯的车被摧毁了",
 "HASH_A5A484A1": "肃清 [format][color:kill]码头[/format]",
 "HASH_A3AF46A1": "念力裂缝",
 "HASH_DEBC3EA1": "击杀 [format][color:kill]中继外星人[/format]",
 "HASH_AE29AEA1": "前往 [format][color:location]中继站[/format]",
 "sh03_failure_homie_dismissed": "皮尔斯被遣散了！",
 "HASH_7ED2BFA2": "入侵 [format][color:Location]边缘工坊[/format]",
 "HASH_CAD496A2": "固体",
 "HASH_7EE8F2A2": "拾取 [format][color:location]贵宾[/format]",
 "HASH_03FD6DA2": "前往 [format][color:location]活动起点[/format]",
 "HASH_CB43B8A2": "[format][color:defend]存活[/format] 攻击",
 "HASH_A2A3E4A2": "[format][color:location]送达[/format] 圣徒",
 "HASH_EF792AA2": "开始下载",
 "HASH_400FB7A2": "用海鸥尸体和羽衣甘蓝做一只木筏",
 "M00_FAILURE_KILLED_BY_CYRUS": "赛勒斯杀了你！",
 "HASH_FBF942A2": "我的天！你上的是何种野蛮的学府？",
 "HASH_A7C10EA3": "入侵 [format][color:Location]辛族星球[/format]",
 "HASH_B51F64A3": "模拟欺诈",
 "M17_FAIL_PIERCE_DIED": "皮尔斯阵亡",
 "HASH_A12A03A4": "探索 [format][color:Location]裂缝[/format]",
 "HASH_6CCD25A4": "向前 [format][color:location]潜行[/format]",
 "HASH_8E7FEBA4": "制造 [format][color:kill]混乱[/format]",
 "HASH_6BC8CFA4": "借夜色掩护潜入他的基地",
 "HASH_C3C810A4": "显赫的头冠",
 "HASH_14142DA5": "在飞船上会见肖恩蒂",
 "HASH_AB282FA5": "开着该死的坦克大搞破坏",
 "HASH_F22AA9A5": "格茨-布雷同盟",
 "HASH_6E240FA5": "顽童营地",
 "HASH_0FA8C7A6": "前往 [format][color:location]活动起点[/format]",
 "HASH_EDB248A6": "触碰那座钟摆",
 "HASH_37A5F8A6": "正如我拥有敏锐的远见，加之那有时吞噬一切的控制欲，我深知在着手更多行动之前，我必须：",
 "HASH_EFBC9FA7": "扰乱 [format][color:Location]系统[/format]",
 "HASH_21A425A7": "肃清 [format][color:Location]辛族部队[/format]",
 "HASH_486964A7": "前往 [format][color:location]活动起点[/format]",
 "HASH_FD1B22A7": "摧毁 [format][color:kill]门[/format]",
 "HASH_B3D8C8A8": "靶场训练（清剿辛族部队）",
 "HASH_B995F4A8": "会见 [format][color:location]皮尔斯[/format]",
 "HASH_770163A8": "平台裂隙",
 "M17_FAIL_GAT_DIED": "盖特阵亡",
 "HASH_08DBA2A8": "如同塞壬以歌声引船触礁，那天鹅绒般浩瀚的太空对许多人而言是位严苛的主宰。于我，未征服的疆域非但不是威胁，反是求之不得的挑战。多少可怜灵魂浑然不知，若无一只铁腕将他们引向伟大，他们的存在何等平庸。噢，我多么渴望成为那只手。",
 "HASH_8ED34BA9": "在飞船上会见 [format][color:Location]CID[/format]",
 "HASH_FBE75DA9": "清剿辛族部队",
 "HASH_0DC716A9": "查看计算机",
 "HASH_1D3FDDA9": "前往 [format][color:location]公园[/format]",
 "HASH_BD1668A9": "你根本没在听！我父亲迟钝得像津纳月十四日的第二个太阳。",
 "HASH_3DFA5AAA": "若想在下城北区取得飞船通行权，就入侵这些店铺。",
 "HASH_29ED91AA": "在飞船上会见皮尔斯",
 "HASH_35F831AA": "WWGD",
 "HASH_D184F5AA": "圣徒之翼",
 "HASH_125FF7AA": "学业能力倾向测验",
 "HASH_D2DF1AAB": "入侵 [format][color:Location]友军误击[/format]",
 "HASH_013CCEAB": "入侵当地的友军误击",
 "HASH_B00FF7AB": "在飞船上会见皮尔斯",
 "HASH_CE1F84AB": "前往 [format][color:location]任务起点[/format]",
 "HASH_233F35AB": "虽说津洛身为谋求终身教职的教授，必定对此心知肚明，但他有义务维持一副公正的假面，我敢肯定。",
 "HASH_C6987DAC": "肃清 [format][color:Location]辛族部队[/format]",
 "HASH_8AA42CAC": "若想关闭模拟世界，我们得造一把钥匙。",
 "m20_failure_gat_died": "盖特阵亡！ ",
 "HASH_B43446AC": "把CID带到 [format][color:location]能量源[/format]",
 "HASH_49DB30AC": "抚摸鹦鹉",
 "HASH_C48718AC": "虽我视它为自身最出众的特征之一，我这头冠却并非津法克斯怒火的源头。",
 "HASH_AF8B46AD": "前往 [format][color:location]核电厂[/format]",
 "HASH_04FA92AD": "评估 [format][color:location]威胁[/format]",
 "mm_3_2_failure_donnie_died": "唐尼阵亡！",
 "HASH_8E5F43AD": "重新接线 [format][color:use]扬声器[/format]",
 "HASH_46922CAD": "将津杰从他的私人噩梦中解救出来后，他给出了最衷心的认可。当被问及他心目中的地狱是何模样，他说：",
 "HASH_714AD2AD": "有些人没能熬过训练，被遣去矿场做工，或被迫加入津族国家管弦乐团（其音乐之刺耳，七星系皆知）。为熬过训练，我常倚仗：",
 "HASH_59DC8CAE": "探索裂缝",
 "HASH_50F348AE": "上传 [format][color:Location]病毒[/format]",
 "M05_FAIL_CID_DIED": "CID阵亡！",
 "HASH_67FD35AE": "尾随 [format][color:location]阿莎[/format]",
 "HASH_DB3C2EAF": "肃清 [format][color:Location]辛族部队[/format]",
 "HASH_4E26B9AF": "扰乱模拟世界的方法多的是。",
 "HASH_A3A47CAF": "别跟丢夜刃",
 "HASH_B8FAB4B0": "扰乱系统",
 "HASH_4C1763B0": "完成训练计划",
 "HASH_AAEA8BB0": "忠诚度——击败赛勒斯的女孩",
 "HASH_82E49AB0": "前往 [format][color:location]基思的集会[/format]",
 "HASH_2480AEB0": "前往 [format][color:location]活动起点[/format]",
 "HASH_BAE587B0": "营救金吉",
 "HASH_041653B0": "获取更多飞船",
 "HASH_30182AB0": "外交的艺术",
 "HASH_0B890EB1": "清剿辛族部队",
 "HASH_151B28B1": "找到 [format][color:location]最大、最闪亮的那东西[/format]",
 "M03_FAIL_SHIP_DESTROYED": "你死了！",
 "HASH_0FB666B1": "此前征战积累的陆战胜利，往往不足以考验我那敏锐的战术直觉。我诸多敌手所施展的机动与谋略，即便在最佳状态也平庸得可怜。我深知，在星海的襁褓之中，必存一位能真正向我发起挑战的统帅。何其有幸——我不过铲平十二个文明，便得以与杰扬神权政体那支训练有素、才华横溢的劲旅正面对决。",
 "HASH_D8097CB2": "探索 [format][color:Location]裂缝[/format]",
 "HASH_FB1450B2": "在飞船上会见 [format][color:Location]皮尔斯[/format]",
 "HASH_7886F8B2": "穿越系统竞速",
 "HASH_B554C2B2": "超级计算机已摧毁！\\n使用机枪 {TANK_FIRE_PRIMARY_IMG} 来安全摧毁它的轮胎。",
 "HASH_50AA17B2": "收集 [format][color:use]步枪[/format]",
 "HASH_10DEF3B2": "查尔斯·狄更斯",
 "HASH_8DA9F7B3": "报复",
 "HASH_77A51CB3": "上传 [format][color:Location]病毒[/format]",
 "HASH_5F1359B3": "忠诚度——调高音量",
 "HASH_D6E931B3": "为CID充能",
 "HASH_A0E3DDB3": "穿过 [format][color:location]后门[/format]",
 "HASH_919F3BB3": "新兵训练后，我入伍并被派往贝多星上那场一触即发的大战前线。在那里，我率军冲锋，直取贝多名将弗兰斯科特。凭着我与生俱来的敏锐洞察，我以如下方式令弗兰斯科特措手不及：",
 "HASH_53694CB4": "清剿辛族部队",
 "HASH_2DBEBEB4": "抢走数据",
 "HASH_41FFE8B4": "我也很激动，但咱们不能鲁莽。",
 "HASH_EDE66AB4": "册封我为皇帝",
 "HASH_762716B4": "心底那座纯粹仇恨的熔炉熊熊燃烧，任何挑战都无法阻挡我将其征服。\\n\\n训练后期的种种迹象表明，我将在以下方面出类拔萃：",
 "HASH_3B2C2EB5": "机器中的幽灵",
 "HASH_8B7E66B5": "进入 [format][color:location]车[/format]",
 "HASH_A8661AB5": "检查 [format][color:location]尸体[/format]",
 "HASH_323F2CB5": "出拳击打基尔班",
 "HASH_F88C64B5": "取 [format][color:use]邮件[/format]",
 "HASH_74040CB5": "一场剑之对决",
 "HASH_C3EADCB5": "当然，那里的辛族少年并非个个谦恭好学。不出所料，我很快便与一个名叫津法克斯的暴戾青年狭路相逢。我们瞬间便互生厌恶。自始便显而易见，津法克斯对我的以下之处颇有微词：",
 "HASH_192F25B6": "清剿辛族部队",
 "HASH_ECA523B6": "给自己弄身新衣服、一辆干净的车，好重新找回状态。",
 "HASH_3DDD56B6": "击杀 [format][color:kill]赛勒斯[/format]",
 "HASH_EDEE79B6": "返回 [format][color:location]模拟世界[/format]",
 "HASH_A73375B6": "前往 [format][color:location]码头 [/format]",
 "HASH_B922F8B6": "[format][color:defend]防守[/format] CID",
 "HASH_5F9294B6": "离开星球去月球上行走",
 "HASH_626E01B6": "最深的恐惧",
 "HASH_3FD88DB7": "入侵 [format][color:Location]拉斯蒂针管店[/format]",
 "HASH_EBA3B9B7": "要让你从西北岛取得通行权，你得入侵这些店铺。",
 "HASH_4C152BB7": "扰乱 [format][color:Location]系统[/format]",
 "HASH_4824EFB7": "还记得咱们在竞选路上干的那票吗？这摊子事儿，得像在博伊西那样摆平。",
 "HASH_E18D4AB7": "击杀（启动病毒注入）",
 "HASH_814FE8B7": "会见 [format][color:location]唐尼与CID[/format]",
 "HASH_655CB7B7": "前往 [format][color:location]金吉的仓库[/format]",
 "HASH_525B5FB7": "攻击 [format][color:kill]保罗[/format]",
 "HASH_A4101CB7": "踢门",
 "HASH_BBCFE8B7": "见面会",
 "HASH_8D546AB7": "击杀 [format][color:kill]警长[/format]",
 "HASH_F11B39B8": "在飞船上会见 [format][color:Location]金吉[/format]",
 "HASH_C06156B8": "暗恋者",
 "HASH_125A5EB8": "与 [format][color:kill]坦尼娅[/format] 战斗",
 "HASH_CD5311B8": "协助AI进入模拟世界",
 "HASH_D77011B8": "那些早已是我们日常的一部分。我觉得没必要炒冷饭。你看出我刚做什么了吗？我玩了个双关。而且玩得相当妙。",
 "HASH_354E59B9": "入侵当地的友军误击",
 "HASH_0A2E18B9": "极速裂缝",
 "HASH_DE3B6AB9": "击杀 [format][color:kill]邪恶的你[/format]",
 "HASH_02A2E1B9": "抵达 [format][color:location]IO塔[/format]",
 "HASH_4F2D9EB9": "钟摆斩下了你的手。好在模拟世界里你能让它重新长出来。你大概不该再这么干了。\\n\\n你怎么做？",
 "HASH_9A361CBA": "肃清 [format][color:Location]辛族部队[/format]",
 "HASH_93DDB2BA": "去 [format][color:location]制造混乱[/format]",
 "HASH_49594CBA": "不可能。我的人品无可指摘。这一点人尽皆知。",
 "HASH_6234DCBB": "入侵 [format][color:Location]过家家[/format]",
 "HASH_01DFC2BB": "入侵当地的边缘工坊",
 "HASH_67E9E6BB": "与盖特共度美好时光",
 "HASH_0D9334BB": "抨击我的指控者",
 "HASH_399D4DBB": "对我童年的追忆，那段生命中更纯真的时光",
 "HASH_FC9486BB": "我已筹得学费，得以入读津族领地最顶尖的学府，但那仅仅是开始。虽我乐于宣称津科夫预校张开双臂迎接了我，事实却是我并非最出色的学生。为获准入校、踏入那传奇的治学殿堂，我不得不经受严苛的体魄与学业测验。",
 "HASH_1379E9BC": "完成训练计划",
 "HASH_05EC4EBC": "想惹毛津亚克吗？咱们给他来点儿老式冗长演说尝尝。",
 "HASH_AC45EBBC": "在飞船上会见强尼",
 "HASH_26151FBC": "与 [format][color:kill]津亚克[/format] 战斗",
 "HASH_FBFBECBC": "扫描星球",
 "HASH_A00A53BD": "清剿辛族部队",
 "HASH_6352A5BD": "击杀 [format][color:kill]典狱长[/format]",
 "HASH_B32630BD": "津亚克撒谎了",
 "HASH_95B4BFBE": "隐形箱 9000",
 "HASH_3D4246BE": "肃清 [format][color:Location]辛族部队[/format]",
 "HASH_63EEB8BE": "斯提尔沃特之王",
 "HASH_D56A79BE": "感谢上帝赐下选区操纵这等好事。",
 "HASH_94B5A7BE": "我们已拥有这项技术 ",
 "HASH_A895B3BE": "当你灌下那瓶古老的谋杀之酒后，一阵眩晕袭来，你昏死过去。\\n\\n你怎么做？",
 "HASH_5CF69CBF": "上传 [format][color:Location]病毒[/format]",
 "HASH_F7F034BF": "在飞船上会见 [format][color:Location]肖恩蒂[/format]",
}

skipped = []
for k, v in add.items():
    if k in skip:
        skipped.append(k)
        continue
    if k not in untrans:
        skipped.append(("not_in_untrans", k))
        continue
    trans[k] = v

if skipped:
    print("skipped:", skipped)
json.dump(trans, open(tp, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("merged. trans size now:", len(trans))
