# -*- coding: utf-8 -*-
import json, os
QA = os.path.dirname(os.path.abspath(__file__))
stem = "platform_pc_us"
trans = {
 "HASH_041D09C0": "$USER_NAME_OR_ID 已收集全部 %ls 中的 %ls",
 "TUT_TAUNTING_PC": "{TAUNT_TWO_IMG} 嘲讽 \\n{TAUNT_THREE_IMG} 恭维 \\n与人群互动，通过嘲讽外星人并击杀它们来获得[format][color:purple]XP[/format]。",
 "HASH_77DD6141": "红队",
 "HASH_06951702": "{JUMP_CLIMB_IMG} 跳跃 \\n在空中时：\\n{SHOULDER_CAMERA_IMG} 瞄准攻击\\n瞄准时：\\n{SUPERJUMP_DEATH_FROM_ABOVE_IMG} 攻击 \\n\\n从更高处攻击可提升伤害。",
 "HASH_A4FF73C2": "TF2 火箭筒",
 "HASH_8A216882": "切换档案",
 "MAINMENU_ONLINE_GAME": "在线游戏",
 "HASH_00281B04": "启用跨平台联机",
 "HASH_C8C8C144": "成人",
 "HASH_F8517C45": "跨商店匹配",
 "HASH_75748885": "你的 Steam 账户只能在 Epic 网站解绑。是否现在前往？",
 "HASH_53891105": "解绑账户",
 "MENU_MOUSE_BUTTON_5": "鼠标 5",
 "HASH_AB2F1DC5": "$USER_NAME_OR_ID 已完成 %ls",
 "HASH_9D8DF486": "它和红色那款一样，只是蓝色的！",
 "HASH_F980F386": "你相信魔法吗？",
 "HASH_A8B8D48A": "（[format][color:purple]鼠标[/format]）瞄准\\n{ATTACK_PRIMARY_IMG} 开火",
 "CBA_OFC_ATTACK_SECONDARY": "   使用超能力",
 "CELL_CHEAT_ACTIVIATE_DIALOG_BODY": "[format][color:#edc300FF]{0}[/format]\\n{1}使用秘籍将让你无法获得成就，且自动保存会被禁用。\\n\\n你仍要激活此秘籍吗？",
 "PLT_MENU_VIEW_GAMERCARD": "查看玩家卡片",
 "HASH_D96382CD": "可靠挖掘与拆除……加油！",
 "CBA_SUPER_QUICK_NEXT": "   下一个超能力",
 "HASH_D7E6F2CE": "连接 Epic 在线服务失败，无法加入游戏。",
 "HASH_67E5700F": "继续使用 GOG 账户",
 "HASH_15CF644F": "关联 Epic 账户",
 "MENU_XBOX_PARTY_INVITE": "发送派对邀请",
 "MENU_XBOX_PARTY_JOIN": "加入派对游戏",
 "RECORD_MODE_WARNING_TEXT": "录制影院片段将禁用所有任务、活动、商店以及游戏内音乐，直到你返回标题画面。是否开始录制影院片段？",
 "MENU_MOUSE_CONTROLS_VERT_SENS": "鼠标灵敏度 上/下",
 "HASH_9376D4D2": "关联你的 Epic 账户，即可与来自 Epic 商店和 GOG 的朋友们一起游玩。",
 "HASH_53FA8152": "{GAC_NEXT_RADIO_IMG} / {GAC_PREV_RADIO_IMG}\\n切换电台\\n\\n你可以随时在步行或驾驶时收听电台。",
 "MUST_SIGN_IN_PROFILE_CONFIRM": "你当前未使用任何档案登录。\\n是否登录？",
 "CBA_GAC_GRENADE_SELECT_1": "   选择念力",
 "HASH_D0C24594": "挑战会为完成困难任务提供奖励。通过中心枢纽\\n{MAP_MENU_IMG} 追踪你的进度。",
 "CBA_SUPER_QUICK_FREEZE": "   选择冲击波",
 "PLT_MENU_VIEW_PARTNER_GAMERCARD": "查看玩家卡片",
 "HASH_1743DD55": "这是我闭眼所见",
 "PLT_MENU_ASPECT_TOOLTIP": "宽高比只能在标题画面切换",
 "CBA_VDC_SCAN": "   扫描当前载具",
 "COMMUNITY_EXISTING_FOUND_TEXT": "我们找到了与你的玩家代号关联的《黑道圣徒》账户。请登录你现有的账户。",
 "HASH_398E29D7": "社区功能目前因年龄限制而不可用。",
 "HASH_ED357F58": "TF2 火焰喷射器",
 "CBA_GAC_MAP_MENU": "   中心枢纽菜单",
 "CBA_GAC_GRENADE_SWITCH": "   下一个超能力",
 "HASH_9D115DDB": "邀请好友或进行匹配。若要邀请 GOG 以外的好友，请前往“关联账户”。",
 "HASH_8240D7DC": "你未持有在线通行证。请前往标题画面，进入可下载内容商店购买或使用兑换码。",
 "CBA_GAC_GRENADE_SELECT_4": "   选择冲击波",
 "HASH_36E90E9D": "$USER_NAME_OR_ID 已获得 %ls",
 "COMMUNITY_ERROR_PLATFORM_ID_NOT_LINKED": "你的玩家代号未与《黑道圣徒》账户关联。",
 "MENU_CATEGORY_CAR": "汽车 / 摩托",
 "HASH_6EADDD9F": "红队",
 "HASH_324A82DF": "那……东西……它让我害怕。",
 "HASH_1717E19F": "本地游玩",
 "HASH_5E9D5F60": "方向键 上 & 下",
 "COMMUNITY_SUCCESS_LINK_EXT": "你当前的档案已成功关联到《黑道圣徒》账户。",
 "COMMUNITY_ERROR_PLATFORM_ID_MISMATCH": "你正在使用的玩家代号已关联到另一个《黑道圣徒》账户。",
 "HASH_6E241EE1": "请在浮层中完成关联流程以继续。",
 "HASH_DD597AA1": "青少年",
 "CBA_SUPER_QUICK_ENERGY_BLAST": "   选择增益",
 "HASH_C8C1AA63": "双击 {SUPER_QUICK_FREEZE_IMG}\\n快速切换超能力元素\\n\\n切换元素可让你在所有超能力元素类型间快速选择。",
 "PLAYBACK_MODE_WARNING_TEXT": "这将停止你当前的录制，并允许你编辑、保存并将其导出为视频。若要录制新的影院片段，你需要返回标题画面。是否进入影院片段编辑器？",
 "MENU_PC_SIGN_IN_ERROR": "你必须连接互联网，且 Steam 不能处于离线模式，才能使用在线功能。",
 "HASH_E4D0A424": "士兵最好的朋友。",
 "COMMUNITY_SITE_BLURB": "上传你的首个角色即可获得一项成就。\\n\\n在线浏览角色并在游戏中使用它们。\\n\\n追踪你的统计数据并与好友比较进度。\\n\\n浏览用户创建的游戏内截图。\\n\\n获取仅限社区的《黑道圣徒》周边与游戏内容优惠。",
 "HASH_F7A48C25": "蓝队",
 "HASH_8E1D4BE6": "全新武器皮肤已在 Friendly Fire 上架。",
 "HASH_FF67F6E6": "要进行在线游戏，你需要登录 Epic 在线服务。是否要关联一个 Epic 账户以连接 Epic 商店的玩家？",
 "HASH_898478A7": "继续使用 Steam 账户",
 "SAVE_WARNING_BOOT": "本游戏具有自动保存功能。当屏幕上出现此提示时，你的游戏正在保存到自动存档槽。",
 "CBA_SUPER_QUICK_STOMP": "   选择践踏",
 "MENU_MOUSE_CONTROLS_INVERT_Y": "反转鼠标瞄准 上/下",
 "COMMUNITY_ERROR_PLATFORM_ID_IN_USE": "你正在使用的玩家代号已关联到《黑道圣徒》账户。",
 "HASH_6D2BE7A9": "欢迎来到盖特的意识。\\n{WALK_FORW_BACK_IMG} / {WALK_LEFT_RIGHT_IMG} 移动",
 "HASH_C7CAC829": "{SUPER_QUICK_FREEZE_IMG} 选择冰冻 [format][color:power_blast]冲击波[/format]",
 "CBA_GAC_GRENADE_SELECT_2": "   选择践踏",
 "HASH_9549BB2A": "{PLANE_ROLL_TURN_SELECT_IMG} 更快转向\\n双击可执行桶滚！",
 "HASH_E692B72A": "TF2 降雨器",
 "COMMUNITY_CREATE_LINK_TEXT": "你可以在此创建新的《黑道圣徒》账户，或将你的档案关联到现有账户。",
 "HASH_7DE38BEC": "关联账户",
 "HASH_F05567EC": "儿童",
 "HASH_BB14D3EE": "禁用跨平台联机",
 "MAIN_MENU_PRIVILEGE_DENIED": "此档案无法在 Xbox Live 上游玩。请检查你的家长控制设置，或获取 Xbox Live Gold 会员资格。",
 "MULTI_LOST_CONNECTION": "发生连接错误。\\n正在返回标题画面。",
 "HASH_9B5D8AF0": "军团要塞2 武器皮肤",
 "PLT_QUIT_GAME": "退出到桌面",
 "HASH_1CF94FB0": "火焰喷射器弹药",
 "HASH_D211C4F1": "{JUMP_CLIMB_IMG} 启动跳跃喷射 \\n{CROUCH_IMG} 降低高度 \\n{MELEE_NUT_SHOT_IMG} 关闭跳跃喷射",
 "CBA_VDC_OFFHAND_GRENADE": "   使用超能力",
 "PC_DELETE_CZ": "删除",
 "HASH_DB55A772": "在坦克里",
 "HASH_587E01F3": "军团要塞2",
 "PC_SCROLL": "滚动",
 "HASH_5E8759F5": "该武器炸毁载具的速度大幅提升",
 "PC_CA_DELETE": "删除",
 "MENU_MOUSE_CONTROLS_HORIZ_SENS": "鼠标灵敏度 左/右",
 "HASH_77F1E736": "与 Xbox Live 的连接已断开。",
 "HASH_1D55FA37": "关联你的 Epic 账户，即可与来自 Epic 商店和 Steam 的朋友们一起游玩。",
 "HASH_32DE2B37": "圣徒帮遇上喷火兵",
 "HASH_406AD377": "建筑者联盟永存！",
 "HASH_A0159179": "本地游玩",
 "PC_MOUSE": "鼠标",
 "PC_WATERMARK_HINT": "导出时在角落添加《黑道圣徒IV》标志",
 "HASH_EED430FB": "蓝队",
 "HASH_3446597C": "TF2 火焰喷射器",
 "HASH_0484A53C": "它和蓝色那款一样，只是红色的！",
 "HASH_290FDE3D": "邀请好友或进行匹配。若要邀请 Steam 以外的好友，请前往“关联账户”。",
 "HASH_A6D294BD": "是否要解绑你的 Epic 账户？",
 "PLT_MENU_DISPLAY_MODE_TOOLTIP": "全屏或窗口化",
 "PC_RECORD_MODE_TEXT": "启用录制模式可将你最后时刻的游戏画面直接保存为视频。按 ([format][color:#9400C5]{0}[/format]) 导出。\\n\\n视频保存至：",
 "CBA_SUPER_QUICK_TELEKINESIS": "   选择念力",
 "MENU_MOUSE_CONTROLS_INVERT_X": "反转鼠标瞄准 左/右",
 "COOP_REMOTE_CHEAT_STARTING": "你的合作搭档正在使用秘籍。任何新建的存档都将启用秘籍。\\n自动保存已禁用，你将无法再获得任何成就。",
 "TUT_STREAKING_PC": "{RECRUIT_DISMISS_IMG} 开始天体活动。 \\n在不穿任何衣物时，天体娱乐活动可用。 ",
 "CBA_GAC_GRENADE_SELECT_3": "   选择增益",
 "CBA_GAC_CELL_OPEN": "   中心枢纽菜单",
}
out = os.path.join(QA, "_trans_" + stem + ".json")
json.dump(trans, open(out, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("wrote", out, "entries:", len(trans))
