# -*- coding: utf-8 -*-
import json, os

qa = os.path.dirname(os.path.abspath(__file__))
tp = os.path.join(qa, "_trans_new_sr35_us.json")
todo_p = os.path.join(qa, "_todo_new_sr35_us_06.json")

untrans = json.load(open(todo_p, encoding="utf-8"))
trans = json.load(open(tp, encoding="utf-8")) if os.path.exists(tp) else {}

add = {
    "HASH_504451BC": "[format][color:use]发电机[/format]已禁用",
    "HASH_FE8176BC": "找到[format][color:location]副总统[/format]",
    "HASH_0AB53EBC": "「平台裂隙」银牌",
    "HASH_436BFFBD": "冰冻元素会让目标僵硬，使你的枪械造成双倍伤害！\\n\\n在力量菜单中切换元素。你的同伴可以帮你找到更多冲击波元素！",
    "HASH_152E4DBD": "市中心已解锁新的传送门。\\n返回飞船，在这里存取你的武器库、服装、载具和帮派自定义内容。",
    "HASH_2182B8BD": "被冻结的载具会失控，即便它们在飞行。\\n\\n用冰冻[format][color:power_blast]冲击波[/format] {ATTACK_SECONDARY_IMG} 击中这架 UFO 将其摧毁。",
    "HASH_1CEB2BBD": "文字冒险已收集",
    "HASH_8DCA55BD": "敌人已分解数",
    "HASH_08949FBE": "载具 - 线框断言者",
    "UNL_SPRINT_REDUCED_MANA_3": "冲刺 - 效率 3",
    "HASH_83AE0BBE": "超级同伴 - 基思·大卫",
    "HASH_395E0EBF": "把你抓起的一切变成毁灭性的闪电球！\\n\\n双击 {SUPER_QUICK_TELEKINESIS_IMG} 在元素间快速切换。或在力量菜单中切换元素。",
    "HASH_0C05DCBF": "腾空时：\\n{SUPERJUMP_FORWARD_BOOST_IMG} 向前冲刺",
    "HASH_C56A58BF": "前往[format][color:location]军械库[/format]",
    "m02_failure_homie_dismissed": "你丢下了警长！\\n履行你身为总统的职责！",
    "UNL_STOMP_2": "践踏 - 距离 2",
    "UNL_MECH_SUIT": "机甲战衣",
    "UNL_JUMP_3": "跳跃 - 滑翔",
    "UNL_DESC_HADOUKEN_2": "核爆恢复速度提升 50%%",
    "HASH_68F39BC0": "冲击波 - 范围 3",
    "HASH_9F23E9C0": "炮塔控制",
    "HASH_2889E7C0": "平台裂隙",
    "HASH_1455B2C0": "点按 {JUMP_CLIMB_IMG} 墙壁跳跃\\n按住 {JUMP_CLIMB_IMG} 蓄力墙壁跳跃\\n沿墙壁跳跃可快速到达顶部。",
    "HASH_294966C0": "黑客入侵失败",
    "HASH_F73994C0": "「念力裂隙」银牌",
    "HASH_E5695CC0": "用反弹射击击杀很有趣！记住，只有击杀辛族才算数。",
    "HASH_25BB32C0": "格斗俱乐部",
    "UNL_HADOUKEN_SUPPRESSION_3": "核爆 - 能量恢复 3",
    "UNL_DESC_MECHMAYHEM": "模拟世界中已开放更高难度的机甲战衣大混乱活动。\\n查看地图了解位置。",
    "HASH_8C453DC1": "访问[format][color:use]主菜单[/format]",
    "HASH_E8E08DC1": "进入[format][color:location]教堂[/format]",
    "HASH_F68659C1": "这仅次于真的揍他一顿。",
    "HASH_CD4C7EC2": "能量剑战衣",
    "HASH_DAA69CC2": "阿拉皮斯岛已解锁新的传送门。\\n返回飞船，在这里存取你的武器库、服装、载具和帮派自定义内容。",
    "HASH_F50C65C2": "增益能量充能速度更快。",
    "m02_failure_car_destroyed": "逃跑载具被摧毁！",
    "HASH_3F044CC2": "退出机甲战衣",
    "HASH_16CA6AC2": "「载具大混乱」金牌",
    "HASH_B97126C3": "冲击波",
    "HASH_37C3B1C3": "钢铁圣徒套装现已在你的传送门衣橱中提供。",
    "HASH_6080F7C3": "冲击波 - 充能 3",
    "HASH_D01F74C3": "{ATTACK_SECONDARY_IMG} [format][color:power_pound]践踏[/format]以解锁其中的数据簇。",
    "HASH_C3FD69C3": "机甲战衣击杀数",
    "HASH_D957DCC3": "回响贝斯枪击杀数",
    "HASH_444B01C4": "找到[format][color:location]盖特的舱体[/format]",
    "HASH_7C395CC4": "下一次传送",
    "HASH_675D7EC4": "完成其他 57 项挑战",
    "HASH_5AB160C5": "生命 - 吸取 3",
    "UNL_DESC_RELOAD_COOLDOWN_2": "点按 {PICKUP_RELOAD_IMG} 让外星武器冷却得更快。",
    "HASH_D5CC16C5": "训练你的同伴在挨枪子时少些退缩。",
    "HASH_63537EC5": "破坏模拟世界",
    "HASH_DDA802C5": "这双靴子生来就是为践踏，它也确实会那么做。用这双践踏靴踩扁一群辛族吧，好吗？",
    "HASH_6DFA41C6": "念力 - 投掷距离 3",
    "HASH_96948DC6": "传送门 - 中央市中心",
    "HASH_D63D7EC6": "增益 - 范围",
    "HASH_164CEFC6": "冻结[format][color:power_blast]冲击波[/format]后收集[format][color:power_blast]簇[/format]",
    "UNL_VEHICLE_NG_TANK": "载具 - 挑战者",
    "HASH_82EBF0C7": "宣传卡车现已在你的车库中提供。",
    "HASH_5ABFA4C7": "美国的崇拜已解锁！",
    "HASH_9B99CCC8": "奇点枪现在可容纳两倍数量的黑洞。",
    "HUD_COLLECTION_REWARD_UNLOCKED": "新升级可用",
    "HASH_CC3AE6C8": "{SIDESCROLL_GRAB_IMG} 擒抱\\n{SIDESCROLL_SLAP_IMG} 攻击\\n{SIDESCROLL_THROW_IMG} 投掷",
    "HASH_1A4F73C8": "用你意念的伟力接住典狱长扔出的物体！！！",
    "HASH_C4BB6EC9": "同伴 - 基思·大卫",
    "UNL_DESC_SUPER_JUMP": "你现在可以用墙壁跳跃攀爬垂直表面，或用蓄力超级跳跃跳得比楼房还高！\\n\\n按住 {JUMP_CLIMB_IMG} 蓄力跳跃，跃得更高更远。",
    "HASH_00EB42C9": "@@STOMP_ROCK^^增加目标被震飞的距离。@@STOMP_GRAVITY^^延长目标受静滞影响的时间。@@STOMP_SHRINK^^延长目标保持缩小状态的时间。",
    "HASH_07199FC9": "强尼·盖特",
    "HASH_4B884CC9": "开始新战役时使用休闲难度",
    "HASH_A4A77DC9": "启用并保持语音识别开启",
    "MOL_JG_01_FAILURE_TIME_UP": "你时间不够了！",
    "HASH_7FABFBC9": "防守[format][color:defend]马特[/format]",
    "UNL_STOMP_REDUCED_MANA_3": "践踏 - 充能 3",
    "UNL_SHIELD_REDUCED_MANA_2": "护盾 - 充能 2",
    "HASH_6803CDCA": "已解锁总统之位",
    "UNL_HOMIE_VETERAN_CHILD": "同伴 - DJ 老兵之子",
    "HASH_916036CA": "模拟世界中已开放更高难度的念力大混乱活动。\\n查看地图了解新位置。",
    "HASH_DA6A36CA": "马特·米勒",
    "HASH_C0317BCA": "{TANK_FIRE_SECONDARY_IMG} 发射主炮 \\n{TANK_FIRE_PRIMARY_IMG} 发射火箭",
    "HASH_724760CA": "黑洞发射器",
    "HASH_5C6517CA": "找到[format][color:location]数据簇[/format]",
    "M22_1_FAIL_CID_DESTROYED": "CID 被摧毁！",
    "UNL_DESC_SUPPRESS_DURATION_3": "被能量压制手雷击中后，力量恢复速度大幅加快。",
    "HASH_B691C9CB": "{ATTACK_SECONDARY_IMG} 用[format][color:power_blast]冲击波[/format]击中目标以解锁其中的数据簇。",
    "HASH_B5791CCB": "禁用[format][color:use]压制装置[/format]",
    "HASH_647BE7CB": "占据 50%%",
    "HASH_2A99BACB": "与金吉交谈",
    "HASH_3F0745CB": "开启格斗俱乐部",
    "HASH_D8942BCC": "激活爆炸念力",
    "HASH_E56481CC": "高塔",
    "HASH_E5A577CC": "CID 击杀",
    "HASH_FA928ECC": "进一步掌握模拟世界，让你玩转高端座驾变得更划算。",
    "UNL_HOMIE_JULIUS": "同伴 - 尤利乌斯",
    "HASH_DA7334CD": "!!这是武器战衣！",
    "HASH_090876CD": "目标受冲击波影响的时间更长。",
    "HASH_C25B27CD": "赢得全部「平台裂隙」金牌，即可解锁减缓滑翔以飞得更远的能力。",
    "HASH_416D2DCD": "完成其他六项挑战",
    "UNL_SPRINTING_SHIELD": "冲刺 - 护盾",
    "HASH_F7C7F1CE": "充气射线的受害者现在会爆炸，伤害附近敌人。",
    "HASH_B39C48CE": "连任内容已解锁！",
    "HASH_FB5B3ECE": "{ATTACK_PRIMARY_IMG}、{SHOULDER_CAMERA_IMG}、{MELEE_NUT_SHOT_IMG} 近战攻击\\n{SPRINT_IMG} 肩部猛撞",
    "HASH_B59781CE": "禁用装置",
    "HASH_350703CE": "「保险欺诈」银牌",
    "HASH_FF83D8CF": "念力元素 - 力量",
    "UNL_DESC_HOMIE_ALL_NOTORIETY": "被呼叫时，清除所有通缉值。",
    "HASH_2AFA96CF": "{GRENADE_4_IMG} 选择冻结[format][color:power_blast]冲击波[/format]  ",
    "HASH_F6159DCF": "做个[format][color:location]狠角色[/format]",
    "UNL_WEP_ANAL_PROBE": "武器 - 整顿者",
    "HASH_AAA1C9D0": "当你从模拟世界中救出某人时，忠诚任务会出现在任务列表中。\\n完成这些任务会赋予该人在模拟世界中的超能力。 ",
    "HASH_7529D6D0": "从主菜单打开显示设置",
    "HASH_595A3CD0": "摧毁[format][color:kill]门[/format]",
    "M10_FAIL_GRAVEYARD": "你离开了墓园！",
    "HASH_269920D1": "增益",
    "UNL_DESC_SHIELD_REDUCED_MANA_1": "护盾仅消耗 75%% 体力。",
    "HASH_728817D1": "从敌人身上收集[format][color:blue]医疗补给[/format]以恢复生命。",
    "HASH_BA46BED1": "接住！",
    "HASH_9A5F20D1": "可曾享受过脚趾间泥土的触感？辛族可不会有这种感觉。",
    "HASH_9A2596D2": "「徒步大混乱」银牌",
    "HASH_1A783ED3": "MI6 特工马特·米勒已被救回，现在可在飞船上找到。去找他学习如何进一步提升你的超能力。",
    "HASH_D0E229D3": "模拟世界中已开放更高难度的格斗俱乐部活动。\\n查看地图了解位置。",
    "HASH_2017F5D3": "机甲战衣大混乱",
    "UNL_TELEKINESIS_3": "念力 - 特殊载具",
    "HASH_AF64F1D4": "超级冲刺不再消耗能量。",
    "HASH_9D12F3D4": "略微降低驾驶机甲战衣时的悬浮消耗。",
    "HASH_EBFB62D4": "{ACTION_IMG} 进入载具\\n{ACCELERATE_IMG} 谨慎加速\\n{BRAKE_REVERSE_IMG} 为停车标志刹车",
    "HASH_56A93BD4": "访问主菜单",
    "HASH_B2C5D6D4": "齐尼亚克雕像",
    "HASH_A50D05D5": "增益元素 - 吸血",
    "UNL_DESC_WARDEN_BEATDOWN_2": "终结典狱长现在容易得多。",
    "HASH_233CB5D5": "赢得全部「保险欺诈」金牌，即可抵抗被载具击倒。",
    "HASH_95C8FFD5": "念力击杀数",
    "HASH_F05787D5": "对虚拟钢埠的统治更进一步，你便能更好地掌控武器商店。所有的枪！",
    "HASH_F9E0E7D6": "念力投掷物体时消耗更少能量。",
    "HASH_B6E3BDD6": "冲击波能量充能极快。",
    "HASH_F102ABD6": "进入主菜单",
    "HASH_D1EA94D6": "从选项菜单更改难度",
    "HASH_640257D6": "攻击典狱长以助将其终结。",
    "HASH_334147D6": "猫鼠游戏",
    "HASH_A07B53D6": "超级践踏",
    "HASH_56425AD7": "[format][color:location]离开[/format]教堂",
    "HASH_91A5D3D8": "增益元素 - 冰冻",
    "UNL_DESC_JUMP_2": "超级跳跃蓄力速度大幅加快。",
    "HASH_D9ECC9D8": "增益 - 充能 2",
    "HASH_1D051DD8": "你拥有的任何载具都可通过主菜单 - 手机界面传送给你。",
    "HASH_93F4D8D8": "摧毁[format][color:kill]发电机[/format]",
    "HASH_18A6CCD8": "外星人击杀",
    "UNL_WEP_LASER_MINIGUN": "武器 - 杀戮机器人迷你枪",
    "HASH_685691D9": "践踏元素 - 岩石",
    "HASH_8E1331D9": "呼叫金吉",
    "HASH_39D441D9": "切换增益元素",
    "HASH_04B447DA": "阿莎·奥德卡",
    "HASH_6020B6DA": "激活爆炸践踏",
    "HASH_0FD753DA": "{ATTACK_PRIMARY_IMG} 发射黑洞 \\n别靠太近！",
    "HASH_7C6650DA": "逃往[format][color:location]金吉处[/format]",
    "HASH_DD0C4EDA": "强化[format][color:use]断路器[/format]",
    "HASH_29AFCEDA": "敌人已被精神控制数",
    "HASH_E710E7DB": "文字冒险",
    "HASH_31DD72DB": "跳跃 - 高度 2",
    "HASH_1C2548DB": "据说迈达斯对枪械情有独钟：\\n\\n暴君、弹跳步枪、绑架机器、分解器。",
    "HASH_BAC33EDB": "服装 - CID 套装",
    "UNL_AUDIO_LOGS": "音频日志",
    "HASH_E2AF74DB": "开始新战役时使用普通难度",
    "HASH_59F015DB": "通过局域网创建合作会话",
    "HASH_FEFE01DB": "呼叫霸主矩阵",
    "HASH_B26BCDDB": "冰冻 - 典狱长",
    "HASH_696086DB": "切换力量元素",
    "MM_1_1_FAIL_ABANDON_FIGHT": "已放弃战斗！",
    "HASH_809156DB": "进入[format][color:location]系统[/format]",
    "HASH_DE1689DB": "找到[format][color:location]盖特[/format]",
    "HASH_1170EADB": "下一次传送",
    "UNL_DESC_SUPER_SHIELD": "冲刺会生成护盾，可阻挡所有来袭伤害并反射投射物！",
    "HASH_633D96DC": "力量元素会让念力在命中时对目标造成额外伤害！\\n\\n你的同伴可以帮你找到更多念力元素！",
    "HASH_073929DC": "打开数字手册",
    "HASH_E24C43DC": "{ATTACK_SECONDARY_IMG} 发射[format][color:power_buff]增益[/format] \\n启用火焰增益，用伤害附近敌人的火墙将自己包裹。\\n\\n立即使用[format][color:power_buff]增益[/format]，跑到目标附近将其击杀。",
    "HASH_9BA138DC": "购买[format][color:use]武器[/format]",
    "HASH_DC0E54DC": "前往[format][color:use]地图[/format]",
    "HASH_112FF5DC": "与招募进你团队的同伴共度时光。对他们的穿搭品味评头论足则全凭自愿。",
    "UNL_WEP_GLITCH_GUN": "武器 - 故障大师 3000",
    "UNL_DESC_SHIELD_3": "击中护盾可为你的生命值充能。",
    "HASH_BFF9DDDD": "把你抓到的任何生物的数码生命吸干，据为己有！\\n\\n双击 {SUPER_QUICK_TELEKINESIS_IMG} 在元素间快速切换。或在力量菜单中切换元素。",
    "HASH_5BF629DD": "服装 - 俏皮肖恩蒂套装",
}

skipped = []
for k, v in add.items():
    if k not in untrans:
        skipped.append(("not_in_todo", k))
        continue
    trans[k] = v

json.dump(trans, open(tp, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("added:", len(add), "skipped:", skipped)
