# -*- coding: utf-8 -*-
import json, os

qa = os.path.dirname(os.path.abspath(__file__))
tp = os.path.join(qa, "_trans_new_sr35_us.json")
todo_p = os.path.join(qa, "_todo_new_sr35_us_04.json")

untrans = json.load(open(todo_p, encoding="utf-8"))
trans = json.load(open(tp, encoding="utf-8")) if os.path.exists(tp) else {}

add = {
    "UNL_SHIELD_REDUCED_MANA_1": "护盾 - 充能",
    "HASH_6F9A0570": "激活闪电念力",
    "HASH_08941D70": "在主菜单中从最近保存的游戏继续",
    "HASH_55B6CF70": "合作任务 - 忙碌",
    "HASH_A4844170": "消灭[format][color:kill]老兵之子[/format]",
    "HASH_4F701470": "软糯连击",
    "HASH_3FF91070": "你能打通这个游戏里的游戏吗？那可是游戏套游戏套游戏……",
    "UNL_WEP_LIGHT_SWORD": "武器 - 能量剑",
    "HASH_B9A1C371": "生命 - 行人伤亡",
    "HASH_D82E4971": "过载[format][color:kill]导管[/format]",
    "HASH_2EED4671": "前往[format][color:location]教堂[/format]",
    "UNL_DESC_SPRINTING_3": "超级冲刺时受到的伤害降低。",
    "HASH_6EF9C272": "前往[format][color:location]传送门位置[/format]",
    "HASH_C8081B72": "使模拟世界失稳",
    "HASH_4F1F0572": "发生连接错误",
    "HASH_80440672": "「载具大混乱」银牌",
    "HASH_CEF56073": "充气射线升级",
    "HASH_DF6DA973": "武器 - 回响贝斯枪",
    "HASH_3DAE2C73": "启用单次指令的语音识别",
    "HASH_5DBE3573": "黑洞就是爱吸。看看你能吸住多少外星人。",
    "HASH_9A761274": "用充气射线来一场非自燃式的燃烧吧！你懂这感觉吗？在传送门武器库装备它。",
    "HASH_892FB874": "副总统基思·大卫现已登船。去找他学习如何控制模拟世界。",
    "HASH_F6653E74": "{ATTACK_SECONDARY_IMG} 火焰冲击波\\n\\n使用火焰[format][color:power_blast]冲击波[/format]超能力元素击杀目标。",
    "HASH_37CF5474": "偷窃[format][color:use]汽车[/format]",
    "HASH_031A8574": "马特·米勒与阿莎",
    "HASH_69012374": "集结并出发",
    "HASH_6F047E74": "浮空连击",
    "HASH_6FDC7C74": "赢得全部「平台裂隙」银牌，即可跳得更远更快。",
    "HASH_66D69074": "「念力裂隙」金牌",
    "HASH_0F93FC74": "让那些机器人渣发出脆响。布雷器还是激光迷你枪——你更中意哪种口味？",
    "HASH_BADA2B74": "自信",
    "HASH_50D44475": "黄金武器战衣",
    "UNL_DESC_WEP_SHRINK_RAY": "用微缩射线枪把敌人缩小到可被踩扁的尺寸！\\n\\n在传送门武器库装备它。",
    "HASH_10E4F875": "在你和你的子弹周围制造真空，汲取附近敌人的生命力并据为己有！\\n\\n双击 {SUPER_QUICK_SHIELD_IMG} 在增益元素间快速切换。或在力量菜单中切换元素。",
    "HASH_28872875": "冲击波不再消耗能量。",
    "HASH_47034175": "CPU",
    "HASH_8DF71075": "正在进入圣徒控制的街区",
    "HASH_A70F9D76": "在主菜单中开始战役",
    "HASH_F9CF4F76": "死亡标签",
    "UNL_TELEKINESIS_4": "念力 - 载具伤害",
    "HASH_E7E51377": "肩部猛撞[format][color:kill]门[/format]",
    "HASH_64771F78": "船员 - 本·金",
    "HASH_6C053478": "增益能量充能速度更快。",
    "HASH_73905D78": "拯救[format][color:location]林[/format]",
    "HASH_570E2878": "与副总统交谈",
    "UNL_HOMIE_SHARP": "同伴 - 威廉·夏普",
    "UNL_AIR_DASH_3": "跳跃 - 空中冲刺 3",
    "HASH_5ED36A79": "收听过津亚克电台",
    "HASH_08AD2079": "挑战勋章_金牌_烈焰_5",
    "UNL_STOMP_1": "践踏 - 距离",
    "HASH_E395FD7A": "冲刺 - 无限冲刺",
    "UNL_DESC_HADOUKEN_1": "核爆恢复速度提升 25%%",
    "HASH_8D5CE37A": "点按 {JUMP_CLIMB_IMG} 小跳\\n按住 {JUMP_CLIMB_IMG} 蓄力超级跳跃",
    "HASH_8015CB7A": "恭喜！\\n你已击败津亚克并接管了辛族帝国！\\n\\n钢埠模拟世界仍可供你完成活动、支线任务与挑战。\\n出去把它们全部搞定吧！",
    "HASH_D303977A": "进入[format][color:location]友军火力[/format]",
    "HASH_B6BC777B": "延长增益的持续时间。",
    "HASH_B21B5C7B": "极速裂隙",
    "HASH_E812257B": "已收集同伴",
    "UNL_VEHICLE_GENKI_DLC_CARS": "载具 - 源木",
    "UNL_DFA_AIRCRAFT": "天降杀戮 - 飞行器",
    "HASH_2CACA17C": "践踏不再消耗能量。",
    "UNL_WEP_PLASMA_CANNON": "武器 - 暴君",
    "HASH_DB50FF7D": "冲刺 - 速度 3",
    "HASH_FABB2C7D": "完成[format][color:location]训练[/format]",
    "HASH_E650C57E": "忠诚任务",
    "HASH_8EE3827E": "岩石元素会在敌人被震飞时造成伤害！\\n\\n你的同伴可以帮你找到更多践踏元素！",
    "HASH_0566437E": "找到[format][color:location]本·金[/format]",
    "HASH_2333637E": "烧吧，宝贝，烧吧",
    "HASH_D92E397F": "已揭晓 - 南市中心",
    "HASH_74B87C7F": "超级同伴 - 本·金",
    "UNL_DESC_RELOAD_COOLDOWN_1": "点按 {PICKUP_RELOAD_IMG} 让外星武器冷却得稍快。",
    "HASH_4CC5477F": "训练你的同伴在挨枪子时毫不退缩。",
    "HASH_9105157F": "选择这支队伍",
    "HASH_FA7CBE7F": "消灭[format][color:kill]坦尼娅[/format]",
    "HASH_CA25D080": "双击 {SUPER_QUICK_FREEZE_IMG}\\n快速切换[format][color:power_blast]冲击波[/format]元素\\n\\n从所有已获得的[format][color:power_blast]冲击波[/format]元素中快速选择。",
    "HASH_32CE2780": "穿上[format][color:use]动力装甲[/format]",
    "UNL_SHIELD_2": "护盾 - 带电",
    "UNL_DESC_SAINTS_VEHICLES": "你现已在传送门车库中获得圣徒的标准载具。",
    "HASH_0F65DF81": "大幅延长可驾驶机甲战衣的时间。这一趟你或许该带点零食。",
    "HASH_08AFD981": "缩小",
    "HASH_5649D281": "返回[format][color:location]马特[/format]处",
    "HASH_FC4D9A82": "载具 - 怪兽卡车",
    "HASH_2E84A682": "弹跳步枪的子弹现在能弹回目标身上。这里是不是有回声？",
    "UNL_DESC_WARDEN_SHIELD_1": "津亚克、典狱长和专家的护盾在被超能力击中后，失效时间略微延长。",
    "UNL_DESC_TELEKINESIS_HOLD_COST": "@@TK_FORCE^^用念力举着物体时不消耗能量。@@TK_LIGHTNING^^用念力举着物体时仅消耗一半能量。@@TK_LIFE_STEAL^^用念力举着物体时仅消耗一半能量。",
    "HASH_A6230682": "最大化冲击波的作用范围。把整片交叉路口都炸个通透！",
    "UNL_DESC_AIR_DASH_2": "每次超级跳跃可冲刺两次。",
    "HASH_4910AD83": "它当然不是真的在喷火，但我很确定你射的那些家伙已经不在乎这个了。",
    "UNL_DESC_SUPER_SPRINT": "你现在能用超级冲刺跑得比汽车还快！",
    "HASH_A01AAD83": "返回游戏",
    "HASH_19F61A83": "摧毁[format][color:kill]UFO[/format]",
    "HASH_F21AD183": "皮尔斯是你的左膀右臂。他技术娴熟、随机应变，随时准备为保圣徒地位做任何必要之事。",
    "HASH_85659B83": "攀登高塔",
    "UNL_DESC_WEP_DISINTEGRATOR": "用分解器一劳永逸地清除模拟体！\\n在传送门武器库装备它。",
    "HASH_267AA384": "开始新战役时使用硬核难度",
    "HASH_5A1A8D84": "传送门击杀",
    "HASH_18F95384": "地面践踏眩晕",
    "HASH_D0FB5884": "已收集音频日志",
    "HASH_EC8B8C85": "念力 - 充能 4",
    "UNL_DESC_VEHICLE_GENKI_DLC_CARS": "你现已在传送门车库中获得源木的「投脑车」「愤怒老虎」「性感小猫」和「忧伤熊猫」。",
    "HASH_83648985": "关闭发电机",
    "HASH_66EE6C85": "开始病毒注入",
    "HASH_1F9BBA86": "践踏元素 - 重力",
    "HASH_3AEAB886": "赛博枪手现已在你的传送门车库中提供。",
    "UNL_DESC_MANA_RECOVERY_2": "超能力能量恢复速度提升 25%%",
    "HASH_725C0F86": "将玩家带回，或继续游戏",
    "HASH_6F429786": "生命宝珠",
    "UNL_JUMP_REDUCED_MANA_1": "滑翔 - 效率",
    "HASH_104FA587": "数据簇",
    "HASH_A49B7987": "冲击波簇",
    "HASH_43585B87": " - 中等",
    "HASH_A8D41C87": "典狱长击杀",
    "HASH_181D5B88": "行人死亡时现在会掉落医疗补给。",
    "HASH_69B02388": "超级践踏",
    "HASH_3BE08488": "按住 {ATTACK_SECONDARY_IMG} [format][color:yellow]核爆[/format] \\n核爆会消灭所有敌人，但会消耗你一段时间的能量。\\n\\n用[format][color:yellow]核爆[/format]击杀目标。",
    "HASH_57E26288": "冻结[format][color:power_blast]冲击波 UFO[/format]",
    "UNL_HOMIE_A_TEAM": "同伴 - 盟友",
    "UNL_DESC_TELEKINESIS_REDUCED_MANA_3": "念力能量充能极快。",
    "UNL_DESC_SPRINT_REDUCED_MANA_2": "超级冲刺消耗体力大幅减少。",
    "HASH_7EC65789": "摧毁[format][color:kill]路障[/format]",
    "HASH_4FFBB889": "消灭[format][color:kill]最终守卫[/format]",
    "HASH_7D69AA8A": "机甲武器",
    "M22_3_FAIL_MATT_DIED": "马特阵亡！",
    "HASH_B48C408A": "C.I.D.？金吉说它代表「控制与接口装置」。只要它在试图保护外星人时被炸成碎片就行。",
    "HASH_CE3BDF8B": "践踏 - 持续时间",
    "UNL_DESC_SUPER_STOMP": "你现在可以一脚跺向地面，用超级践踏把附近的一切震飞！\\n\\n使用 {SUPER_QUICK_STOMP_IMG} 快速切换到践踏。",
    "HASH_CFA8A08B": "念力裂隙",
    "HASH_C0DA518B": "[format][color:use]进入[/format]模拟世界",
    "UNL_WARDEN_BEATDOWN_1": "典狱长 - 终结技",
    "HASH_6C0D598C": "超级同伴 - 金吉",
    "HASH_291E418C": "同伴 - 本·金",
    "HASH_EB87908C": "天降杀戮 - 范围",
    "HASH_8949B58C": "冻结",
    "HASH_F65C758C": "激活念力",
    "HASH_C087F38C": "在暂停菜单中读取先前保存的游戏",
    "HASH_6F37A28C": "收集[format][color:purple]数据簇[/format]以解锁强化的超能力。\\n访问主菜单中的力量菜单购买它们。",
    "HASH_1C5CA88C": "有一条永恒不变的真理你永远可以信赖：东西总会爆炸。",
    "HASH_1C0AA28D": "机甲战衣 - 超频 3",
    "HASH_BD01AD8D": "你现在可以用能量为身体和武器充能！\\n\\n使用 {SUPER_QUICK_SHIELD_IMG} 快速切换到增益。",
    "HASH_CB9CAD8D": "呼叫猛禽内德",
    "HASH_8F264B8D": "超级冲刺距离",
    "HASH_C020E98E": "生命 - 补给价值",
    "HASH_F51F4D8E": "禁用语音识别",
    "HASH_7F13888E": "{PARTNER_NAME} 正在开启一项你已完成过的任务。",
    "HASH_6700718E": "挑战勋章_金牌_烈焰_5_描述",
    "HASH_14A3A98F": "!!武器战衣",
    "UNL_DESC_TELEKINESIS_1": "念力可以抓起汽车！",
    "UNL_DESC_HADOUKEN_REDUCED_MANA_2": "核爆仅消耗 50%% 能量",
    "HASH_0D30BC8F": "传送门 - 南市中心",
    "HASH_C7D8EB8F": "冲击波 - 持续时间",
    "HASH_E91C1B8F": "开始新的存档游戏",
    "HASH_C215C48F": "践踏簇",
    "HASH_6E0C178F": "源木教授的 M.O.M.",
    "HASH_74334290": "超级同伴 - 俏皮肖恩蒂",
    "HASH_F046F390": "增益 - 范围效果",
    "HASH_B7B5E390": "切换冲击波元素",
    "HASH_4D434B90": "用火[format][color:power_blast]冲击波消灭敌人[/format]",
    "HASH_EB25C390": "禁用发电机",
    "UNL_DESC_DFA_RANGE_1": "提升天降杀戮的攻击范围。",
    "HASH_A028E191": "摧毁门",
    "HASH_09D46291": "簇",
    "UNL_SPRINT_REDUCED_MANA_1": "冲刺 - 效率",
    "UNL_MANA_RECOVERY_4": "超能能量 - 更快恢复 4",
    "UNL_DESC_WEP_ANAL_PROBE": "用整顿者以老派方式获取情报！\\n在传送门武器库装备它。",
    "HASH_4D32D392": "基思·大卫",
    "HASH_902FFE92": "找到[format][color:location]马特[/format]",
    "HASH_86A9A892": "消灭[format][color:kill]警察[/format]",
    "HASH_D69B9893": "{ATTACK_SECONDARY_IMG} [format][color:power_pound]超级践踏[/format] \\n制造巨大冲击波，重创附近目标。\\n\\n立即使用[format][color:power_pound]超级践踏[/format]击杀目标。",
    "HASH_A65BCF93": "玩家 1",
    "HASH_CD743E93": "活动层级完成",
    "HASH_9FEB1493": "目标已被绑架",
    "HASH_D9069594": "机甲战衣 - 持续时间 3",
    "HASH_A9460494": "消灭[format][color:kill]津亚克[/format]",
    "HASH_2FE46894": "找到[format][color:location]马特[/format]",
    "HASH_BBB7D194": "用念力扔人",
    "HASH_E39CA794": "「保险欺诈」金牌",
    "HASH_34223F95": "适度提升所有医疗补给的价值。",
    "HASH_AACD5495": "访问传送门武器库时获得更多免费弹药。",
    "HASH_CBB22995": "{JUMP_CLIMB_IMG} 跳跃 \\n腾空时：\\n按住 {SHOULDER_CAMERA_IMG} 瞄准攻击\\n{SUPERJUMP_DEATH_FROM_ABOVE_IMG} 发起攻击 \\n\\n从更高处攻击以提升伤害。",
    "HASH_21633695": "肖恩蒂热衷于享乐，却对圣徒忠贞不渝直至最后。她既能引人注目，也能融入任何场合。",
}

skipped = []
for k, v in add.items():
    if k not in untrans:
        skipped.append(("not_in_todo", k))
        continue
    trans[k] = v

json.dump(trans, open(tp, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("added:", len(add), "skipped:", skipped)
