# -*- coding: utf-8 -*-
import json, os

qa = os.path.dirname(os.path.abspath(__file__))
tp = os.path.join(qa, "_trans_new_sr35_us.json")
todo_p = os.path.join(qa, "_todo_new_sr35_us_03.json")

untrans = json.load(open(todo_p, encoding="utf-8"))
trans = json.load(open(tp, encoding="utf-8")) if os.path.exists(tp) else {}

add = {
    "UNL_DESC_STOMP_REDUCED_MANA_2": "践踏能量充能速度更快。",
    "HASH_4C24E349": "外星载具击杀",
    "HASH_4D74454A": "卡弗岛已解锁新的传送门。\\n返回飞船，在这里存取你的武器库、服装、载具和帮派自定义内容。",
    "HASH_5674D24B": "弹跳步枪射出社交蝴蝶……非常致命的社交蝴蝶。在传送门武器库装备它。",
    "UNL_DESC_SHIELD_2": "接触护盾的敌人会被眩晕/电击。",
    "UNL_DESC_VEHICLE_HOVER_TANK": "你现已在传送门车库中获得外星悬浮坦克。",
    "HASH_48D99D4C": "消灭典狱长",
    "UNL_VEHICLE_NO_RAGDOLL": "不可移动物体",
    "UNL_SUPER_STOMP": "践踏",
    "HASH_46DA424D": "跳跃 - 高度 3",
    "UNL_DESC_WEP_MINEFIELD": "杀戮机器人的布雷器已被逆向工程。用布雷器让城市遍布感应地雷！\\n在传送门武器库装备它。",
    "HASH_8566914D": "增益不再消耗能量。",
    "HASH_2C3F3C4D": "@@BLAST_FREEZE^^目标被击碎时爆炸，伤害周围一切。@@BLAST_FIRE^^目标死亡时爆炸，将火焰蔓延给附近的人。@@BLAST_GLITCH^^目标死亡时爆炸，使附近敌人故障失控。",
    "HASH_36FD114D": "呼叫源木后援",
    "HASH_C56CFD4D": "冰冻 - 载具",
    "UNL_DESC_JUMP_3": "飞上天空，在城市上空滑翔！\\n\\n空中冲刺后按住 {SPRINT_IMG} 即可滑翔。",
    "HASH_AEEBF94E": "增益 - 充能 3",
    "HASH_E4E8BF4E": "摧毁[format][color:kill]路由器[/format]",
    "HASH_21380B4F": "飞船",
    "HASH_B0E72D4F": "在暂停菜单中保存游戏",
    "HASH_0382984F": "呼叫赛勒斯·坦普尔",
    "HASH_83F8134F": "墙壁跳跃",
    "HASH_BB4E1D4F": "消灭[format][color:kill]爪牙[/format]",
    "HASH_1AFD7150": "念力 - 投掷距离 2",
    "UNL_DESC_WEP_LIGHT_SWORD": "打得他们够狠，能量剑就能把他们熔毁！\\n在传送门武器库装备它。",
    "HASH_F5C7B050": "提升对受天降杀戮影响的目标造成的伤害。",
    "HASH_A02B2F50": "使用忍者反射时恢复生命值。",
    "HASH_F9DF3250": "增益 - 极速恶魔",
    "HASH_C86E4650": "打开地图",
    "HASH_7762EB50": "挑战完成",
    "HASH_F7C8B950": "完全掌握模拟世界的所有方面，你便能直接从其他虚拟生命身上汲取力量！",
    "HASH_528E1850": "超级加速",
    "HASH_355E9E51": "冲刺 - 速度",
    "UNL_DESC_WEP_ABDUCTION": "让你的敌人近距离体验绑架机器！\\n在传送门武器库装备它。",
    "HASH_4695A551": "呼叫尤利乌斯",
    "M18_KILL_ATTACKERS": "消灭[format][color:kill]攻击者[/format]",
    "HASH_111EBB51": "前往[format][color:location]屋顶[/format]",
    "HASH_4680FF51": "赢得全部「极速裂隙」金牌，即可解锁冲刺疾速，更快达到最高速度。",
    "HASH_B941C352": "超级冲刺",
    "HASH_2DB65053": "生命 - 吸取 2",
    "UNL_DESC_RELOAD_COOLDOWN_3": "点按 {PICKUP_RELOAD_IMG} 让外星武器冷却得更快。",
    "HASH_99F9EA53": "传送门武器库弹药 2",
    "HASH_71BFA154": "激活爆炸冲击波",
    "HASH_FECD2754": "双击 {MENU_DP_LEFT_IMG}\\n快速切换超能力元素\\n\\n切换元素可让你在所有超能力元素类型间快速选择。",
    "HASH_47DCA854": "与强尼·盖特交谈",
    "HASH_E5EC1B54": "重力漂浮击杀",
    "HASH_026AE255": "武器 - 充气射线",
    "HASH_6ECABE55": "同伴 - 源木后援",
    "UNL_HOMIE_CYRUS": "同伴 - 赛勒斯·坦普尔",
    "HASH_D8179E55": "线框幻影现已在你的传送门车库中提供。",
    "HASH_F566F155": "赛博怪兽卡车现已在你的传送门车库中提供。",
    "HASH_00F3A955": "皮尔斯已被救回，现在登上飞船！去找他，学习如何好好享乐。",
    "HASH_9CDA1555": "提升从黑客入侵商店获得的缓存与经验值。",
    "HASH_1787C755": "冲击波 - 充能 2",
    "UNL_AIR_DASH_1": "跳跃 - 空中冲刺",
    "HASH_09564155": "打开合作选项",
    "HASH_FC03B355": "摧毁[format][color:kill]闪点[/format]",
    "HASH_35FEDA55": "将[format][color:defend]CID[/format]砸向津亚克",
    "HASH_91304555": "与金吉恋爱",
    "UNL_STOMP_3": "践踏 - 距离 3",
    "UNL_JUMP_2": "跳跃 - 更快蓄力",
    "HASH_DCE63956": "跳上建筑物侧壁并按住 {SPRINT_IMG} 沿墙冲刺！\\n\\n对任何超能圣徒来说都是必备之选。",
    "UNL_DESC_HADOUKEN_3": "核爆恢复速度提升 100%%",
    "HASH_6E36D056": "传送门 - 北市中心",
    "HASH_1FF4AB56": "冲击波 - 范围 2",
    "HASH_5FA52756": "{SPRINT_IMG} 肩部猛撞",
    "HASH_AE79E056": "双击 {SUPER_QUICK_SHIELD_IMG}\\n快速切换[format][color:power_buff]增益[/format]元素\\n\\n从所有已获得的[format][color:power_buff]增益[/format]元素中快速选择。",
    "HASH_473E8856": "消灭[format][color:kill]典狱长[/format]",
    "UNL_HADOUKEN_SUPPRESSION_2": "核爆 - 能量恢复 2",
    "UNL_DFA_RANGE_1": "天降杀戮 - 范围",
    "HASH_659DFE57": "重力",
    "HASH_DB263157": "机甲战衣猛砸",
    "HASH_E5813657": "蓄力中",
    "HASH_5B63AB57": "摧毁传送门",
    "HASH_E6535158": "{SPRINT_IMG} 冲刺",
    "HASH_AEA4D958": "{ATTACK_PRIMARY_IMG} 激活爆发\\n执行病毒可短暂击穿障碍物、伤害附近敌人并收集额外数据。",
    "HASH_409C2D58": "消灭外星人",
    "HASH_19F3D759": "斯坦菲尔德岛已揭晓！",
    "HASH_FC6BEF59": "参谋长本·金已被救回，可在飞船上找到。去找他学习如何进一步提升你的超能力。",
    "HASH_E5F16359": "激活岩石践踏",
    "HASH_34445759": "天降杀戮",
    "HASH_8A018659": "合作任务 - 完成",
    "HASH_F4D7E659": "[format][color:location]放下[/format]马特",
    "HASH_E2303059": "合作：猫鼠游戏",
    "HASH_84526759": "赢得全部「烈焰」银牌，即可获得火焰免疫。",
    "M22_3_FAIL_ASHA_DIED": "阿莎阵亡！",
    "HASH_7BE9F25A": "在时间耗尽前，用右侧栏提供的黑客节点将数据访问电路从左到右连通。\\n([format][color:purple]鼠标[/format]) 高亮节点 \\n([format][color:purple]鼠标滚轮[/format]) 切换节点类型 \\n([format][color:purple]鼠标左键[/format]) 放置节点",
    "HASH_8851925A": "还有什么比击杀漂浮在半空、无助的辛族更有趣？",
    "HASH_7C56C35B": "安全驾驶",
    "HASH_5BBAAE5B": "进入模拟世界",
    "HASH_D6FA265B": "进入[format][color:location]车库[/format]",
    "HASH_7176595B": "与[format][color:use]金吉[/format]交谈",
    "HASH_8F00F25B": "打击外星目标",
    "HASH_FA19C25B": "超能战斗训练",
    "UNL_STOMP_REDUCED_MANA_2": "践踏 - 充能 2",
    "UNL_SHIELD_REDUCED_MANA_3": "护盾 - 充能 3",
    "HASH_5A0B9E5C": "大量服装、套装、武器、秘籍和载具已添加到你的衣橱、武器库、手机和传送门车库。还在等什么？快去拯救人类！",
    "HASH_22BBF45C": "重置",
    "HASH_B0F9615C": "外星人被嘲讽数",
    "UNL_WEP_TENTACLE_BAT": "武器 - 侵犯者",
    "HASH_E493AC5D": "武器 -!!弹跳步枪战衣",
    "UNL_DESC_SUPPRESS_DURATION_2": "被能量压制手雷击中后，力量恢复速度更快。",
    "HASH_B354AB5D": "查看制作人员名单",
    "HASH_97AC2D5D": "禁用装置",
    "HASH_5D269F5D": "赢得全部「徒步大混乱」银牌，即可解锁更多弹药储备。",
    "HASH_737EB05D": "驾驶帅气的外星座驾在虚拟钢埠兜风，再没有比这更棒的了。",
    "UNL_DESC_SPRINTING_1": "超级冲刺现在会产生龙卷风效果，将玩家身后的物体掀翻！",
    "HASH_856A885E": "呼叫马特·米勒",
    "HASH_43347B5E": "黑客入侵完成",
    "HASH_8E9D7B5F": " - 困难",
    "HASH_6EA95E5F": "通常我只会撞断脚趾。你那边情况如何？",
    "HASH_C5A28860": "裂隙",
    "UNL_DESC_SPRINTING_SHIELD": "超级冲刺期间冲刺护盾持续存在。",
    "HASH_891CEB60": "北市中心已揭晓！",
    "HASH_FEE46260": "冲击波 - 充能 4",
    "HASH_C5313460": "从选项菜单打开显示设置",
    "HASH_64638B60": "机甲武器",
    "HASH_A8D42361": "跳跃 - 高度",
    "HASH_8C37DF61": "从先前保存的游戏列表中读取",
    "HASH_3BB18161": "击倒[format][color:kill]副总统[/format]",
    "UNL_DESC_JUMP_1": "按住 {SHOULDER_CAMERA_IMG} 在空中悬停，然后按 {ATTACK_PRIMARY_IMG} 以超高速砸向地面。",
    "HASH_40E59862": "增益 - 充能",
    "UNL_DESC_SPRINT_BUILDUP": "超级冲刺更快达到最高速度！",
    "HASH_822A4C63": "服装 - 钢铁圣徒",
    "HASH_F20CF363": "外星压制手雷可暂时禁用你的超能力。",
    "HASH_8F308F63": "{ATTACK_PRIMARY_IMG} 开炮 \\n{ATTACK_SECONDARY_IMG} 发射火箭 \\n{SPRINT_IMG} 冲刺 \\n{MELEE_NUT_SHOT_IMG} 近战猛击 ",
    "HASH_07171F63": "赢得全部「载具大混乱」银牌，即可解锁怪兽卡车。",
    "HASH_262A2063": "%%",
    "HASH_B8C79164": "同伴 - 铁骨",
    "HASH_37BAE764": "大幅提升医疗补给被吸向你的范围。",
    "HASH_76282164": "市中心已解锁新的传送门。\\n返回飞船，在这里存取你的武器库、服装、载具和帮派自定义内容。",
    "HASH_1E958764": "{SPRINT_IMG} 冲刺",
    "m22_2_portal_destroyed": "传送门已被摧毁！",
    "HASH_B3516964": "在时间耗尽前，用右侧栏提供的黑客节点将数据访问电路从左到右连通。\\n{ANALOG_LS_IMG} 移动选择\\n{ANALOG_RS_IMG} 滚动黑客节点\\n{MENU_SELECT_IMG} 放置黑客节点",
    "HASH_92ACA564": "你当然可以用老办法把敌人烧了。但真正重要的是那份亲手了结的快感。",
    "HASH_2EB9C565": "将敌人举到空中并锁进静滞力场。就像瓮中捉鳖！\\n\\n双击 {SUPER_QUICK_STOMP_IMG} 在元素间快速切换。或在力量菜单中切换元素。",
    "HASH_71D9FE65": "逃离[format][color:location]模拟世界[/format]",
    "HASH_0080D765": "有时候你就是想亲自动手。亲手解决几个外星人，行不行？",
    "HASH_79BA9D66": "铬合金封锁现已在你的传送门车库中提供。",
    "HASH_83F1AF66": "现在你才能真正体会那个壳里有多冷清孤独。CID 战衣现已在你的传送门衣橱中提供。",
    "HASH_A1203966": "消灭[format][color:kill]所有人[/format]",
    "HASH_0136C666": "吸血鬼",
    "HASH_2B563F66": "摧毁外星载具",
    "UNL_WEP_DISINTEGRATOR": "武器 - 分解器",
    "HASH_40DF3967": "通过收集散布在模拟世界各处的音频日志，了解同伴们的过去。\\n\\n访问飞船休息室中的电脑，收听已收集的条目。",
    "HASH_78EE4E67": "切换力量",
    "HASH_511DEA67": "前往[format][color:location]闪点[/format]",
    "HASH_9607AE68": "射击[format][color:kill]津亚克的脸[/format]",
    "HASH_F6924B69": "奇点枪弹药升级",
    "HASH_FACFEB69": "践踏 - 充能 4",
    "HASH_E35E4369": "召唤你的座驾",
    "HASH_DECF3A69": "呼叫 DJ 老兵之子",
    "HASH_5B51A269": "呼叫本·金",
    "HASH_03AA126A": "收集[format][color:purple]文字冒险碎片[/format]以探究津亚克的起源。",
    "HASH_520BE86A": "冰冻碎裂",
    "UNL_SUPPRESS_DURATION_3": "压制 - 能量恢复 3",
    "HASH_787FB66B": "船员 - C.I.D.",
    "UNL_DESC_SHIELD_REDUCED_MANA_2": "护盾仅消耗 50%% 体力。",
    "UNL_DESC_JUMP_SPEED": "蓄力超级跳跃飞得更远更快。",
    "HASH_3A6EBD6B": "火焰",
    "HASH_CAC53D6B": "呼叫马罗",
    "HASH_D24F876B": "双击 {SUPER_QUICK_TELEKINESIS_IMG}\\n快速切换[format][color:power_tele]念力[/format]元素\\n\\n从所有已获得的[format][color:power_tele]念力[/format]元素中快速选择。",
    "HASH_A13D016C": "激活践踏",
    "HASH_271BD96C": "[format][color:power_pound]践踏敌人[/format]",
    "HASH_CC0CF46D": "船员 - 强尼·盖特",
    "HASH_15723D6D": "{ATTACK_SECONDARY_IMG} 用[format][color:power_tele]念力[/format]攻击球体使其破裂，释放其中的数据簇。",
    "HASH_6BEAE46D": "机甲战衣大混乱",
    "HASH_43BA856E": "铬合金虚空现已在你的传送门车库中提供。",
    "HASH_041BA26E": "适度降低驾驶机甲战衣时的悬浮消耗。",
    "HASH_2D28DD6E": "移除所有限制器，让机甲战衣的武器发挥全部潜力。",
    "HASH_37AC686E": "{ATTACK_SECONDARY_IMG} 发射[format][color:power_buff]增益[/format] \\n火焰增益将火焰之力注入你的武器。\\n\\n立即启用[format][color:power_buff]增益[/format]，然后射击目标用火焰击杀他们。",
    "HASH_2CAE306E": "[format][color:power_pound]践踏[/format]后射击[format][color:power_pound]典狱长[/format]",
    "HASH_E0BC326E": "退出模拟世界",
    "HASH_FA2F406E": "抓起一个敌人。扔出一个敌人。简单、有效，而且啊，真是令人满足。",
    "HASH_236A656E": "「烈焰」金牌",
    "HASH_DF09B86E": "完成其他一项挑战",
    "UNL_HOMIE_ALL_NOTORIETY": "通缉清零 - 全部",
    "UNL_DESC_WARDEN_BEATDOWN_1": "终结典狱长现在略微容易。",
    "HASH_DC1B0E6F": "呼叫罗迪·派珀",
    "HASH_2139086F": "「极速裂隙」金牌",
}

skipped = []
for k, v in add.items():
    if k not in untrans:
        skipped.append(("not_in_todo", k))
        continue
    trans[k] = v

json.dump(trans, open(tp, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("added:", len(add), "skipped:", skipped)
