import json, os
QA = os.path.dirname(os.path.abspath(__file__))
untrans = json.load(open(os.path.join(QA, "_untrans_mission_us.json"), encoding="utf-8"))
tp = os.path.join(QA, "_trans_mission_us.json")
trans = json.load(open(tp, encoding="utf-8")) if os.path.exists(tp) else {}

skip = set()

add = {
 "HASH_6A0186DF": "扰乱系统",
 "HASH_EC9607DF": "哭泣",
 "HASH_D306B4DF": "拍摄 [format][color:use]宣传照[/format]",
 "HASH_B0BA1AE0": "入侵 [format][color:Location]友军误击[/format]",
 "HASH_70FA2DE0": "精心筹划",
 "HASH_DD1502E0": "饮下那杯酒",
 "HASH_E0E997E0": "模拟世界",
 "HASH_69A9ABE1": "入侵 [format][color:Location]拉斯蒂针管店[/format]",
 "HASH_D83F25E1": "那个狗娘养的让我受尽折磨。我们要让他付出代价。",
 "HASH_27B704E1": "报名",
 "HASH_18E5EFE1": "用棕榈树搭一座房子",
 "HASH_515B6BE1": "这是一台计算机。\\n\\n你怎么做？",
 "HASH_1DD58BE1": "于是我着手从已知世界所有文明中采集典范样本。唯有一处例外。那是一处我愿细细品味的征伐之地。一个其艺术贡献最初将我引上此路的地方。那里有个人，我尤其想要会面——凭母舰扭曲时间之能，我办得到。但我亦深知，任何能孕育出那等文学造诣的星球，必也培养出无与伦比的战士。我激动难抑，读者。我灵魂的每一寸都在因期待而战栗。",
 "HASH_551C89E2": "上传 [format][color:Location]病毒[/format]",
 "HASH_57AB08E2": "前往 [format][color:location]活动起点[/format]",
 "HASH_127844E2": "拾取 [format][color:use]电池 [/format]",
 "HASH_D36FAEE2": "使用终端",
 "HASH_572FB9E2": "事后，我将指控者追捕归案，就地处决。\\n\\n那桩龌龊事既已了结，我非但继续履行在辛族军队中的职责，更将其发挥到极致！在又一番对敌的陆战告捷之后，长官们认为理应：",
 "HASH_9B73A8E2": "新鲜水果挞",
 "HASH_F132EDE3": "启动病毒注入",
 "HASH_700BABE3": "前往 [format][color:location]技术上合法[/format]",
 "HASH_79F4BFE3": "盖特时光，欢乐时光",
 "HASH_B0B8BAE3": "后退",
 "HASH_C28DE3E3": "在一场关于星际政治的激烈辩论中，一头暴怒的辛猪在飞船上脱了缰",
 "HASH_E2E273E3": "我对文学的挚爱由此奠定，入读津科夫预校之事亦成定局。正是在那里，我遇见了那位助我寻得此生真意的恩师。\\n\\n不过，那又是另一个故事了。",
 "HASH_36DF31E4": "肃清 [format][color:Location]辛族部队[/format]",
 "HASH_D9E829E4": "[format][color:kill]肃清[/format] 码头",
 "m09_failure_pierce_died": "皮尔斯阵亡",
 "HASH_BE356BE5": "白兔",
 "HASH_A40AABE5": "去车流里撒野。稍微打破点规矩。",
 "HASH_1DB23DE5": "破坏征途",
 "HASH_5D5D9DE6": "我们在拉长游戏流程。来找我吧！",
 "HASH_E28697E6": "会见联手扳倒津亚克的船员",
 "HASH_B5255AE6": "击败 [format][color:kill]复古克隆体[/format]",
 "HASH_3681B8E6": "前往 [format][color:location]逻辑门[/format]",
 "HASH_B29FBCE6": "我的战术直觉",
 "HASH_381592E7": "入侵布里奇波特的友军误击",
 "HASH_B65117E7": "探索 [format][color:Location]裂缝[/format]",
 "HASH_9B92C4E7": "清剿辛族部队",
 "HASH_CC096EE7": "来超能格斗俱乐部一试身手吧。",
 "HASH_83D0D6E7": "前往 [format][color:location]交易地点 [/format]",
 "HASH_4AE324E7": "吸收 [format][color:use]病毒[/format]",
 "HASH_2EBEC9E7": "随后，津杰与我享用了最美妙的一餐，满桌新鲜布恩牛排，言谈甚欢。",
 "HASH_2B7DDAE7": "质疑我指挥的就绪",
 "HASH_A4E914E8": "注入最终病毒",
 "HASH_C5A40EE8": "偷走 [format][color:Location]载具[/format]",
 "HASH_067976E8": "前往一处 [format][color:location]战斗地点[/format]",
 "HASH_F55DFFE8": "你用手拂过独角兽的鬃毛。独角兽轻嘶一声，以头顶蹭了蹭你的头作为回应。它的角却戳中了你的眼，你痛得缩回。就在此刻，你的脚绊上一块松动的石板。\\n\\n你跌倒，折断颈骨。\\n\\n你死了。\\n\\n感谢游玩《龙与泪：螺旋黑暗三部曲·第一部》\\n\\n",
 "HASH_63085BE8": "数学",
 "HASH_7C386BE9": "肃清 [format][color:Location]辛族部队[/format]",
 "HASH_11C093E9": "作为神权教义的一环，杰扬人不信平坦表面这一套。",
 "HASH_20E575EA": "入侵阿什伍德的拉斯蒂针管店",
 "HASH_99A85FEA": "在飞船上会见 [format][color:Location]CID[/format]",
 "HASH_95F784EA": "基思说，在津亚克死前他没法去约会。咱们能快点吗？",
 "HASH_32AEF7EA": "完成 [format][color:Location]竞速[/format]",
 "HASH_836223EA": "登上高塔",
 "HASH_3C5702EA": "尾随 [format][color:location]目标[/format]",
 "HASH_804DB2EA": "收集造钥匙的零件",
 "HASH_7CB885EA": "拯救 [format][color:location]肖恩蒂[/format]",
 "HASH_8C6024EB": "进入 [format][color:location]车[/format]",
 "HASH_C89FC4EB": "X先生案\\n",
 "HASH_175AB8EB": "击杀 [format][color:kill]摩托车[/format]",
 "HASH_75DD33EC": "入侵日落公园的辛族星球",
 "HASH_ED564BEC": "与 [format][color:Location]金吉[/format] 碰头",
 "HASH_CC473AEC": "肃清 [format][color:Location]辛族部队[/format]",
 "HASH_8EE694EC": "城市占领教程",
 "HASH_D420E7EC": "要找回你的参谋长，你得重访你们共同的过去。",
 "HASH_C95CB0EC": "加入马特的冒险",
 "HASH_55DCB3EC": "重新接线扬声器",
 "HASH_BB2A7EEC": "前往 [format][color:location]护盾发生器[/format]",
 "HASH_5F891DEC": "那些败于我威势之下的人，我绝不敢任其在现实世界中游荡；但虚拟世界另当别论。这念头如异象般降临！一张庞大互联的模拟世界之网，不仅用以囚禁宇宙间最杰出之辈，更要摧垮他们的意志，令其俯首称臣于我——津亚克，辛族帝国的银河霸主、至高皇帝。哦，我是否忘了提及，我弑了前任、将那王座据为己有？恕我失言。",
 "HASH_6851E3EC": "新兵训练后，我入伍并被派往贝多星上那场一触即发的大战前线。在那里，我率军冲锋，直取贝多名将弗兰斯科特。凭着我与生俱来的敏锐洞察，我以如下方式令弗兰斯科特措手不及：",
 "HASH_CD8090ED": "天降死神",
 "HASH_F1D152EE": "入侵洛伦广场的辛族星球",
 "HASH_E9C20AEE": "打破现实的规则",
 "HASH_507A9CEE": "模拟世界识别到……",
 "HASH_6E15B8EF": "找到 [format][color:location]圈养栏[/format]",
 "HASH_7B2A42EF": "前往 [format][color:location]金吉的仓库[/format]",
 "HASH_A91BAEEF": "前往 [format][color:location]小巷[/format]",
 "HASH_D0C411EF": "进一步了解天降死神",
 "HASH_27A8A7EF": "真正的游戏现在开始 >:)\\n\\n按任意键继续",
 "HASH_9F4244F0": "听着，要是得困在这模拟世界里，就帮我个忙。",
 "HASH_60DE08F0": "肃清 [format][color:Location]辛族部队[/format]",
 "HASH_4270C1F0": "狼獾",
 "HASH_16AD57F0": "我哪曾料到，杰扬人那头足类的生理构造，加之充当桌面的曲面，竟让他们在此运动中占尽杠杆优势。哦嗬！奎克祖格何其狡黠！将我诱入一个利用我自己偏见的陷阱！干得漂亮！当真漂亮。而事实证明，那场比试的胜者乃是：",
 "HASH_1BF960F1": "使用 [format][color:use]核弹[/format] 之力",
 "HASH_A384D0F1": "入侵卡马诺广场的皮革与蕾丝店",
 "HASH_CF7268F1": "肃清 [format][color:Location]辛族部队[/format]",
 "HASH_D9426DF1": "探索 [format][color:Location]裂缝[/format]",
 "HASH_9BFFABF1": "前往 [format][color:location]断杖酒馆[/format]",
 "HASH_9739A6F1": "找一个实验对象！",
 "HASH_A3609DF1": "唉，津格拉特的暴动青年营本季已预订一空。",
 "HASH_D1256DF2": "启动病毒注入",
 "HASH_FAA345F2": "击败 [format][color:kill]超级源木[/format]",
 "HASH_BBCFACF2": "偷走 [format][color:location]幽浮[/format]",
 "HASH_CFF200F2": "欢迎回来",
 "HASH_F14AE4F2": "找到 [format][color:location]要紧的东西[/format]",
 "HASH_DD4120F2": "启程迈向冒险",
 "HASH_88840AF2": "别那么粗俗。",
 "HASH_7541FFF2": "手刃双亲",
 "HASH_2788B1F3": "入侵伯恩斯山的指定影像",
 "HASH_840FE7F3": "在飞船上会见基思",
 "HASH_2DA642F3": "谁需要背景故事？",
 "HASH_A2C6B0F3": "找到 [format][color:location]金吉[/format]",
 "HASH_723C33F3": "[format][color:power_tele]念力[/format] 将物体掷入后射击 [format][color:power_tele]典狱长[/format]",
 "HASH_029866F3": "后退",
 "HASH_7E11BEF3": "饮下那杯酒",
 "HASH_DE7764F3": "开始死亡捉迷藏？",
 "HASH_ECA399F3": "求知欲",
 "HASH_28A399F4": "入侵 [format][color:Location]友军误击[/format]",
 "HASH_5B6E3FF4": "上传 [format][color:Location]病毒[/format]",
 "HASH_15D908F4": "在飞船上会见阿莎",
 "HASH_EED915F4": "飞向紫色星辰",
 "HASH_CCFC6CF4": "处决 [format][color:use]恐怖分子[/format]",
 "HASH_F55D5AF4": "开始猫鼠游戏？",
 "HASH_DAF1EDF4": "未免有些短视，你不觉得吗？",
 "HASH_72B0F7F5": "注入最终代码",
 "HASH_8C3B6EF5": "在飞船上会见阿莎",
 "HASH_D0A159F5": "入侵 [format][color:Location]边缘工坊[/format]",
 "HASH_146A39F5": "你笨手笨脚地做出两只鸡尾酒杯，倒入椰奶。\\n\\n你怎么做？",
 "HASH_A5EC74F5": "[format][color:blue]喂饱饥饿[/format]",
 "HASH_58E4D9F5": "没错，我手中握有宇宙的钥匙，却仍有所缺。这些胜利虽多，却觉空洞。我发现自己想要更多、需要更多。我究竟还缺什么？我拥有一切。我现身之时，文明为之震颤。我自己的军队也活在对我雷霆之怒的恐惧中。我又能缺什么呢？",
 "HASH_6F3C27F5": "即便此刻回首，我仍不禁微笑。\\n\\n自那以后，我率军追击辛族帝国的诸多敌寇。很快，整支贝多军队溃败于我们面前，我们那本已雕刻得颇为可观的腰带，又添一道刻痕。",
 "HASH_609E76F6": "前往 [format][color:location]裂缝[/format]",
 "HASH_7C4786F6": "前往 [format][color:location]断杖酒馆[/format]",
 "HASH_C9FCDFF6": "接上 [format][color:location]贵宾与阿莎[/format]",
 "HASH_919CC6F6": "前往 [format][color:location]齐莫斯的地盘[/format]",
 "HASH_A76BB6F6": "前往 [format][color:location]出口[/format]",
 "HASH_F6BC96F7": "入侵亨利钢铁厂的友军误击",
 "HASH_BB8C7CF7": "在飞船上会见 [format][color:Location]金吉[/format]",
 "MOL_MM_01_FAILURE_MATT_DIED": "马特阵亡！",
 "HASH_65FD09F7": "盛大终幕 第三部",
 "M15_PLAYER_DIED": "你死了！",
 "HASH_3289A1F7": "然后醒来……",
 "HASH_686C88F8": "苍白的阴影",
 "HASH_C9C746F8": "清剿辛族部队",
 "HASH_606EE3F8": "我需要热热身。",
 "HASH_5636AFF8": "计算机可不会滚蛋。\\n\\n你输入什么？",
 "HASH_9CEDCCF9": "穿越系统竞速",
 "HASH_F0DA48F9": "金吉的棋局",
 "HASH_7FEF38F9": "模拟世界里正发生怪事。 [format][color:red]在事态解决前，你会持续遭到攻击。[/format]",
 "HASH_A858CDF9": "击杀 [format][color:kill]典狱长[/format]",
 "HASH_7797E9F9": "被压抑的",
 "HASH_C0BDC5F9": "尾随 [format][color:location]CID[/format]",
 "HASH_199107F9": "摧毁 [format][color:kill]门钥[/format]",
 "HASH_CE6B20F9": "即便初出茅庐的辛族人也该知道，那场「大语言误会」在数千年前便割裂出一道宽广的政治鸿沟，令格茨-布雷同盟分崩离析。如今的学堂都教些什么啊？",
 "HASH_4DCB27FA": "清剿辛族部队",
 "HASH_89EA98FA": "提升 [format][color:kill]恶名[/format]",
 "HASH_420904FA": "掩护 [format][color:defend]圣徒[/format]",
 "HASH_E58FB7FA": "宇宙中某些最杰出的文学，竟出自一颗千万光年外、水汪汪的小小星球，这让我何等错愕！虽要再过些时日我才造访那看似平平无奇的中转站，我早已倾心于它的艺术馈赠。尤其有一位作者的作品攫住了我的想象。你能猜出那位文豪是谁吗？",
 "HASH_E6602DFB": "在飞船上会见 [format][color:Location]金吉[/format]",
 "HASH_3BD884FB": "前往 [format][color:location]内部[/format]",
 "HASH_636F28FB": "前往训练计划",
 "HASH_7DEF51FB": " [format][color:location]逃脱[/format]",
 "HASH_EEEF48FB": "突破 [format][color:use]门[/format]",
 "HASH_E08B20FC": "在飞船上会见 [format][color:Location]肖恩蒂[/format]",
 "HASH_6890A4FC": "肃清 [format][color:Location]辛族部队[/format]",
 "HASH_8C77DDFD": "破门",
 "HASH_A13AD8FD": "击杀津法克斯",
 "HASH_3F7856FE": "入侵萨兰德的辛族星球",
 "HASH_9CFF00FE": "扰乱系统",
 "HASH_3D6A73FE": "钥匙大师",
 "HASH_FD1A5BFE": "前往 [format][color:location]三回合[/format]",
 "HASH_368A4AFE": "与马特·米勒交谈",
 "HASH_EBBB5DFE": "学习基础",
 "M19_FAIL_CID": "CID阵亡",
 "HASH_33836BFE": "前往 [format][color:location]终端[/format]",
 "HASH_C9D58AFF": "抢走数据",
 "HASH_0A47FFFF": "能量训练",
 "HASH_B18E82FF": "房间消融殆尽，为你展开一幅摄人心魄的宇宙景象。\\n\\n你怎么做？",
}

skipped = []
for k, v in add.items():
    if k in skip:
        skipped.append(k)
        continue
    if k not in untrans:
        skipped.append(("not_in_untrans", k))
        continue
    trans[k] = v

if skipped:
    print("skipped:", skipped)
json.dump(trans, open(tp, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("merged. trans size now:", len(trans))
