# -*- coding: utf-8 -*-
# Phase B: mission 未译占位补译（任务目标文案，术语沿用已译区）
import re, os
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCH = os.path.join(BASE, "schinese", "mission_us.txt")
T = {
 "M09_OBJ_TO_BROTHEL": "开车去[format][color:location]晨星帮妓院[/format]",
 "M08_OBJ_GO_TO_ROOF": "乘[format][color:use]电梯[/format]上到屋顶",
 "m06_failure_pierce_died": "皮尔斯阵亡！",
 "MSN_PROTO_SELECT_BIKE_DESC": "原型单人攻击/运输载具，采用了与 VTOL 相同的悬浮与变形技术。",
 "M12_OBJ_ENTER_THE_PR_CENTER": "进入[format][color:location]公关中心[/format]",
 "SH03_TURN_OFF_FINAL": "关闭最后一台[format][color:use]路由器[/format]",
 "M16_TXT_ADV_SC_09_CH1": "看看那头独角兽",
 "M16_CHOOSE_COMPANY_A": "武器制造商",
 "m05_fail_left": "你离开了派对！",
 "m03_failure_shaundi_killed": "肖恩蒂阵亡！",
 "M06_OBJ_KILL_BRUTE": "杀死[format][color:kill]巨兽[/format]",
 "M05_OBJ_CLEAR_AREA": "肃清[format][color:kill]晨星帮[/format]",
 "METAGAME_NUTSHOT_KILL": "蛋击",
 "m22_failure_statue_blown_up": "雕像被摧毁了！\\n 用音爆对付炸弹时小心点，别让它们碰到任何东西。",
 "m03_failure_bomb_destroyed": "炸弹被摧毁了！",
 "MISSION_COMPLETE": "任务完成！",
 "M05_OBJ_BASEMENT": "找到[format][color:location]储物室[/format]",
 "M01_SIGN_AUTOGRAPH": "签名留念",
 "MISSION_HUD_TITLE": "任务",
 "M22_OBJ_STOP_KILLBANE": "拦下[format][color:kill]杀霸的飞机[/format]",
 "M11_OBJ_HELP_CONVOY": "协助[format][color:location]车队[/format]",
 "m09_failure_ship_abandoned": "任务已放弃！",
 "M09_OBJ_SOUTH_PLATFORM": "赶到[format][color:location]南侧平台[/format]",
 "m07_failure_shaundi_died": "肖恩蒂阵亡！",
 "M03_OBJ_GO_TO_ARMORY": "前往[format][color:location]守军军械库[/format]",
 "m01_failure_shaundi_died": "肖恩蒂阵亡！",
 "sh04_failure_left_casino": "你还没干完活就离开了赌场！",
 "M17_OBJ_HIJACK_VTOL": "夺取一架[format][color:use]VTOL[/format]",
 "M21_OBJ_ENTER_THE_RING": "走进[format][color:location]擂台[/format]",
 "M20_PEDS": "行人",
 "M17_TIMER_ESCAPE": "逃跑",
 "m07_failure_pierce_died": "皮尔斯阵亡！",
 "M01_KILL_LOBBY_GUARDS": "杀掉[format][color:kill]守卫[/format]",
 "M16_TXT_ADV_SC_03_CH2": "搜寻暗门",
 "M08_OBJ_PROTECT_PIERCE": "保护[format][color:defend]皮尔斯[/format]",
 "m12_failure_josh_died": "乔什死了！",
 "STRONGHOLD_START_MESSAGE_LUCH": "开始摔跤手帮根据地",
 "m03_failure_heli_destroyed": "直升机被摧毁了！",
 "M02_OBJ_SHOOT_PLANE": "打碎[format][color:kill]挡风玻璃[/format]",
 "M03_OBJ_EXIT_STORE": "离开商店",
 "MSN_DECK_START": "开始赛博帮任务",
 "M05_OBJ_TAUNT": "挑衅[format][color:location]守卫[/format]",
 "M03_OBJ_ACCESS_MAP": "打开[format][color:location]手机地图[/format]",
 "m14_failure_shaundi_abandoned": "肖恩蒂被抛弃了！\\n圣徒可不能各自单飞！",
 "m11_fail_oleg": "奥列格阵亡！",
 "m05_fail_chase": "副官逃掉了！\\n压低身形，别跟丢他。",
 "M08_USE_TRIGGER_RESTORE_POWER": "恢复电力",
 "M08_OBJ_STAIRS_TO_ROOF": "找到通往屋顶的[format][color:location]楼梯[/format]",
 "METAGAME_SUCCESS_LOSE": "你的搭档得分超过了你。",
 "METAGAME_EXPLOSION_KILL": "爆炸击杀",
 "M03_OBJ_GO_TO_CHOPPER": "登上[format][color:location]皮尔斯的直升机[/format]",
 "M01_SURVIVE": "守住[format][color:defend]自己[/format]",
 "M16_TXT_ADV_SC_09_CH3": "杀了那头独角兽",
 "M07_ACTION_INTERROGATE": "审问",
 "m05_fail_time": "时间到！\\n赶快抓住副官，逼问出停止炸弹的密码。",
 "M05_OBJ_GET_TO_HELI": "登上[format][color:use]直升机[/format]",
 "MISSION_NAME_MM_Z_04": "勾勒一幅画卷",
 "M05_OBJ_WAIT_FOR_SAINTS": "守住[format][color:defend]电梯[/format]",
 "M03_OBJ_STEAL_A_CAR": "偷一辆[format][color:use]车[/format]",
 "METAGAME_GANG_VEHICLE": "帮派载具",
 "M18_OBJ_BAIL_FROM_TANK": "跳出[format][color:use]坦克[/format]",
 "M09_OBJ_PUT_GIRLS_IN_CRATE": "把姑娘们带往[format][color:location]集装箱[/format]",
 "M08_ACTION_USE_ELEVATOR": "使用电梯",
 "M07_OBJ_KILL_LUCHADORES": "消灭[format][color:kill]摔跤手帮[/format]",
 "M03_OBJ_ELIMINATE_REINFORCEMENTS": "消灭[format][color:kill]增援[/format]",
 "M07_OBJ_KILL_MORNINGSTAR": "消灭[format][color:kill]晨星帮[/format]",
 "M03_OBJ_DESTROY_TARGETS": "摧毁[format][color:kill]目标[/format]",
 "M05_FAIL_LT_DIED": "副官死了！",
 "M03_OBJ_FIND_WEAPONS_CACHE": "找到[format][color:location]武器库[/format]",
 "M21_USE_TEXT_GO_RING_SIDE": "前往擂台边",
 "M13_OBJ_DESTROY_STAG_BANNER": "烧掉[format][color:kill]STAG 旗帜[/format]",
 "m04_failure_abandon_pierce": "皮尔斯被抛弃了！\\n圣徒可不能各自单飞！",
 "M16_OBJ_CHOOSE_A_COMPANY": "选择[format][color:use]公司[/format]",
 "M10_OBJ_KILL_STAG_SNIPERS": "消灭[format][color:kill]STAG 狙击手[/format]",
 "MISSION_CHECKPOINT": "检查点！",
 "M09_OBJ_CHOICE": "开车去[format][color:location]妓院[/format]，或去[format][color:saints]圣徒总部[/format]",
 "M03_OBJ_PURCHASE_AN_UPGRADE": "购买[format][color:use]武器升级[/format]",
 "M02_OBJ_FIND_PARACHUTE": "找一顶[format][color:location]降落伞[/format]",
 "M01_GO_UPSTAIRS": "上[format][color:location]楼[/format]",
 "METAGAME_GANG_BOSS": "帮派老大",
 "M09_OBJ_NORTH_PLATFORM": "赶到[format][color:location]北侧平台[/format]",
 "METAGAME_SUCCESS_TIE": "你和搭档打成了平手。",
 "METAGAME_GANG_MEMBER": "帮派成员",
 "M17_OBJ_FIND_HELI": "找一架[format][color:location]VTOL[/format]",
 "M07_OBJ_UNTIE_KINZIE": "给[format][color:use]金吉[/format]松绑",
 "M12_USE_LOAD_JOSH": "把乔什放进车里",
 "m10_failure_viola_died": "薇奥拉阵亡！",
 "M09_OBJ_GO_TO_SHIP": "赶到[format][color:location]货船[/format]",
 "M16_OBJ_GOTO_FIREWALL": "赶到[format][color:location]防火墙[/format]",
 "M09_OBJ_WAIT_FOR_CHOPPER": "等待直升机",
 "M06_OBJ_DECIDE": "[format][color:use]拆除炸弹[/format]或[format][color:kill]摧毁大楼[/format]",
 "M11_OBJ_GO_OLEG": "赶到[format][color:location]奥列格[/format]身边",
 "M07_FAILURE_PATRONS_DIED": "别杀客人，用 {ACTION_IMG} 审问他们",
 "M11_OBJ_GO_AIR_BASE": "拦截[format][color:location]监视飞机[/format]",
 "M05_OBJ_FIND_LIEUTENANT": "找到[format][color:location]副官[/format]",
 "M04_OBJ_USE_MECHANIC": "使用[format][color:use]修车行[/format]",
 "MSN_STAG_START": "开始 STAG 任务",
 "M22_OBJ_GOTO_STATUE": "赶到[format][color:location]雕像[/format]前",
 "m06_failure_oleg_died": "奥列格阵亡！",
 "M06_OBJ_DOCK_THUGS": "消灭[format][color:kill]码头守卫[/format]",
 "M04_OBJ_BUY_CLOTHES": "购买[format][color:use]服装[/format]",
 "M12_OBJ_ENTER_THE_ELEVATOR": "走进[format][color:location]电梯[/format]",
 "M10_OBJ_ESCAPE_STAG": "[format][color:location]逃出[/format]STAG 的伏击",
 "MSN_ACTIVITES_RESPECT_REPEAT": "活动{MAP_IMG_UNKNOWN_ACT}能赚取声望。查看地图确认活动位置。",
 "M12_OBJ_GO_TO_RECEPTION_DESK": "前往[format][color:location]前台[/format]",
 "M08_OBJ_GO_TO_CHOPPER": "拿[format][color:use]防空武器[/format]",
 "M18_OBJ_HIJACK_TANK": "夺下[format][color:location]坦克[/format]",
 "METAGAME_REVIVE_HOMIE": "救起兄弟",
 "M03_OBJ_KILL_GUARDS": "消灭[format][color:kill]守卫[/format]",
 "M16_CHOOSE_COMPANY_B": "汽车经销商",
 "M14_OBJ_GO_TO_INTERVIEW": "前往[format][color:location]采访现场[/format]",
 "M09_OBJ_GET_TO_THE_CHOPPER": "跳上[format][color:location]直升机[/format]",
 "M20_OBJ_CRASH_BEACH_PARTY": "闯进[format][color:location]海滩派对[/format]",
 "M12_OBJ_ESCAPE_TO_THE_SAINTS_HQ": "逃回[format][color:location]圣徒总部[/format]",
 "M12_OBJ_GO_TO_THE_PR_CENTER": "前往[format][color:location]公关中心[/format]",
 "M05_OBJ_CHASE_HELI": "跟上[format][color:location]副官[/format]",
 "MSN_RESPECT_HELP_REPEAT": "游玩拐人救美等活动{MAP_IMG_UNKNOWN_ACT}即可赚取声望。  ",
 "METAGAME_MELEE_KILL": "近战击杀",
 "M13_OBJ_GOTO_SHAUNDI": "赶到[format][color:location]肖恩蒂[/format]身边",
 "m08_failure_pierce_died": "皮尔斯阵亡！",
 "M05_ELEVATOR": "呼叫电梯",
 "M02_OBJ_ESCAPE": "带着[format][color:defend]肖恩蒂[/format]逃跑",
 "M01_KILL_CHOPPER": "射击[format][color:kill]直升机[/format]",
 "M16_OBJ_GOTO_INTERNET_SECURITY": "赶到[format][color:location]网络安全室[/format]",
 "m13_failure_pierce_abandoned": "皮尔斯被抛弃了！\\n圣徒可不能各自单飞！",
 "m12_failure_suko_abandoned": "薇奥拉被抛弃了！\\n圣徒可不能各自单飞！",
 "M12_PICKUP_JOSH_BIRK": "带上[format][color:use]乔什·伯克[/format]",
 "M08_OBJ_RESTORE_POWER": "恢复[format][color:use]电力[/format]",
 "M13_OBJ_GOTO_SAINTS_HQ": "返回[format][color:location]圣徒总部[/format]",
 "M08_OBJ_GO_TO_BASEMENT": "乘[format][color:use]电梯[/format]下到地下室",
 "m07_failure_kinzie_died": "金吉阵亡！",
 "STRONGHOLD_START_MESSAGE_DECK": "开始赛博帮根据地",
 "M07_OBJ_INTERROGATE_PATRONS": "抓住[format][color:use]客人[/format]",
 "M06_OBJ_SYN_TOWER": "前往[format][color:location]SYN 塔[/format]",
 "MISSION_FAILED": "任务失败！",
 "m17_failure_viola_died": "薇奥拉阵亡！",
 "M13_OBJ_GOTO_PIERCE": "赶到[format][color:location]皮尔斯[/format]身边",
}
lines = open(SCH, encoding="utf-8").read().replace("\r\n", "\n").split("\n")
out, seen = [], set()
for ln in lines:
    m = re.match(r'^\s*"([^"]+)":\s*"(.*)"\s*$', ln)
    if m and m.group(1) in T:
        k = m.group(1); out.append('"%s": "%s"' % (k, T[k])); seen.add(k)
    else:
        out.append(ln)
open(SCH, "w", encoding="utf-8").write("\n".join(out) + "\n")
print("written", len(T), "; lines", len(out))
