# -*- coding: utf-8 -*-
# activity 人工翻译批1
import re, os
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCH = os.path.join(BASE, "schinese", "activity_us.txt")
T = {
 "CHOPSHOP_VIEW_DETAILS": "查看详情",
 "ACT_TORCH_START_TEXT2": "点燃路人与载具来累积奖励分",
 "ACT_PIMPING_RECRUIT_CONTACTS_TEXT": "{RECRUIT_DISMISS_IMG} 招募[format][color:green]联络人[/format]",
 "ACT_PIMPING_RETURN_TO_BROTHEL": "把[format][color:green]姑娘[/format]带回[format][color:teal]齐莫斯[/format]处",
 "ACT_GUARDIAN_ANGEL_TITLE": "天使护卫关卡选择",
 "ACT_WHORED_MALLCOP": "商场正义！",
 "ACT_RUNNING_MAN_BUTTON": "按下按钮？",
 "STRONGHOLD_FAILURE_SUB_TEXT": "据点失败",
 "ACT_PIMPING_RESCUE_COPS_REROUTE": "[format][color:green]姑娘[/format]们被捕了，快去保释她们",
 "ACT_TRAFFIC_CHASE_HELICOPTER_KILLED": "干得好！警察跟丢了目标。",
 "ACT_HELI_CONVOY_DOWNTOWN_DESTINATION_MESSAGE": "市中心",
 "ACT_FRAUD_EARN_MONEY": "你只能在标示的[format][color:teal]计分区[/format]内赚钱",
 "CRITICAL_VEHICLE_DESTROYED_VEHICLE_TEXT": "你摧毁了那辆车",
 "ACT_PIMPING_RETURN_CONTACT_TO_SAFEHOUSE": "把[format][color:green]联络人[/format]带回来",
 "ACT_WHORED_DRUNKEN_BOXING": "喝醉时，你拥有超人般的力量。",
 "ACT_ESCORT_TIGER_START": "开始老虎护驾",
 "ACT_FRAUD_GO_GET_HURT": "按 {ATTACK_PRIMARY_IMG} 或 {ATTACK_SECONDARY_IMG} 摔一跤。摔得越惨，赚得越多",
 "ACT_TORCH_TIME_LABEL_TEXT": "时间",
 "ACT_HELI_ACTIVITY_HELI_RESCUE_MESSAGE": "帮助你的[format][color:green]兄弟[/format]抵达[format][color:blue]目的地[/format]。",
 "ACT_ESCORT_PI_SPAWNED": "甩开[format][color:red]私家侦探[/format]",
 "ACT_CHOP_SHOP_LOCATION_ON_MAP_MSG": "位置已标示。",
 "ACT_PIMPING_FAIL_TOOK_TOO_LONG": "你时间用完了",
 "ACT_CHOPSHOP_NONE": "没有列出拆车坊",
 "ACT_HELI_PROTECTION_START_MESSAGE": "你的[format][color:green]兄弟[/format]需要你的保护",
 "ACT_VANDAL_STATIC_BONUS_CIVILIAN_MSG": "平民奖励",
 "ACT_HELI_SATELLITE_DISH_DESTROY_TEXT": "摧毁卫星天线",
 "ACT_VANDAL_SUMMARY_PROPERTY": "财产",
 "ACT_TRAFFIC_BUYER_FLEE_FAIL": "[format][color:red]买家[/format]逃走了",
 "ACT_PIMPING_VEHICLE_ROUTE_CONTACTS": "拦下[format][color:red]车辆[/format]并带走[format][color:green]联络人[/format]",
 "ACT_PIMPING_TRAP_ATTACK_GET_HOS": "你中计了！招募[format][color:green]姑娘[/format]并迅速撤离。",
 "ACT_GUARDIAN_ANGEL_LEFT_ATTACKER": "攻击者从[format][color:red]左侧[/format]来袭",
 "ACT_CHOP_SHOP_MORE_CARS_MSG": "车不够。再去弄几辆来。",
 "ACT_VANDAL_COP": "警察",
 "ACT_TRAFFIC_BUYER_DEAD": "一名买家被杀了",
 "ACT_GUARDIAN_ANGEL_HUD_LIFE_MESSAGE": "名人的生命",
 "ACT_FRAUD_BONUS_AIR_TIME": "滞空奖励",
 "ACT_ESCORT_IRS_SPAWNED": "甩开[format][color:red]国税局[/format]",
 "ACT_PIMPING_TRAP_ATTACK_KILL_PIMPS": "你中计了！在招募[format][color:green]姑娘[/format]之前先杀光所有[format][color:red]晨星帮[/format]成员。",
 "ACT_ESCORT_STICK_ROTATION_MSG": "[format][color:green]客户[/format]想要舞女表演疯狂旋转",
 "ACT_WHORED_MINIGUNBRUTE": "迷你机枪壮汉来袭！",
 "ACT_VANDAL_VEHICLE_BONUS_MSG": "摧毁[format][color:red]%ls[/format]可获得奖励",
 "ACT_VANDAL_BONUS_MULTI_VEHICLE": "奖励：摧毁 %s  （X%d）",
 "ACT_TORCH_TIME_BONUS_EARNED": "获得奖励秒数！",
 "ACT_VANDAL_CAR_SPORTS_MSG": "跑车",
 "ACT_HELI_VAN_CRITICAL_HEALTH_TEXT": "[format][color:green]你兄弟的车[/format]即将被摧毁",
 "ACT_FRAUD_GOAL": "在时间耗尽前赚取 %ls",
 "ACT_CHOP_SHOP_CARS_ON_MAP_MSG": "所需车辆已标示。",
 "CHOP_RETRO_SPOILER": "复古尾翼",
 "ACT_HELI_GANG_FIGHT_START_MESSAGE": "一些[format][color:green]圣徒[/format]在交火中被压制。帮助他们击退[format][color:red]袭击者[/format]。",
 "ACT_VANDAL_BONUS_MULTIPLIER_PCT": "%",
 "ACT_HELI_KILL_AIRPLANE_START_MESSAGE": "摧毁[format][color:red]飞机[/format]",
 "ACT_ESCORT_TIGER_BUTTON_MASHING_MSG": "持续分散老虎的注意力！",
 "ACT_RUNNING_MAN_WAITING_ON_HOST_TITLE": "等待主机",
 "GAME_COMBO_TEXT": "连击：",
 "ACT_HELI_BOAT_DELIVER_TEXT": "把船上的毒品送到你兄弟手里",
 "ACT_PIMPING_CONTACTS_SLASH": "/",
 "ACT_ESCORT_TRIP_THEATER_MSG": "带[format][color:green]客户[/format]去[format][color:teal]成人影院[/format]",
 "ACT_HELI_OBJECTIVE_MSG": "完成全部 %d 项任务",
 "ACT_ESCORT_CAR_SWITCH_MSG": "那辆车看起来有点旧了，去[format][color:teal]脱衣舞俱乐部[/format]换辆新车",
 "ACT_TRAFFIC_DEAL_SUCCESS": "交易完成。前往下一个[format][color:teal]地点[/format]。",
 "ACT_TORCH_START_TEXT3": "穿过检查点来兑现你的奖励时间",
 "ACT_PIMPING_FAIL_CONTACTS_ALL_DIED": "太多联络人死了，招募他们 {RECRUIT_DISMISS_IMG} 然后迅速逃离现场",
 "ACT_HELI_CONVOY_LEVEL_START_MESSAGE": "%s 有一批武器正沿高速公路运来。在[format][color:red]卡车[/format]抵达目的地前摧毁它们。",
 "ACT_CHOP_SHOP_LIST_IN_PAUSE": "所需车辆清单可在暂停菜单中查看。",
 "ACT_TANK_MAYHEM_COMBO_GSI": "连击",
 "CHOPSHOP_VEHICLES": "车辆",
 "ACT_TRAFFIC_POLICE_STING_DEALER_ARRESTED_2SEC": "2……",
 "ACT_TORCH_OBJECTIVE_01": "在时间耗尽前穿过所有[format][color:teal]检查点[/format]",
 "ACT_VANDAL_STATIC_BONUS_MOTORCYCLE": "摩托车奖励",
 "ACT_FRAUD_TOTAL_LAST_HIT": "末次撞击合计",
 "ACT_ESCORT_FAST_MSG": "[format][color:green]客户[/format]要你以 55 英里/小时行驶 %d 秒",
 "TOUCH_COMBO_TUTORIAL_PART_1_MESSAGE": "移动 {ANALOG_RS_IMG} 到热点位置来热热身",
 "ACT_ZOMBIE_TITLE": "丧尸关卡选择",
 "ACT_TRAFFIC_POLICE_STING_DEALER_ARRESTED_10SEC": "毒贩将在 10 秒后被逮捕！",
 "ACT_HELI_LIBERATOR_FULLY_LOADED_MESSAGE": "直升机已满，把乘客送到[format][color:blue]安全地点[/format]",
 "ACT_GUARDIAN_ANGEL_UNDERNEATH_ATTACKER": "攻击者正从我们[format][color:red]下方[/format]来袭。",
 "ACT_ESCORT_IRATE_CLIENT_SPAWNED": "甩开[format][color:red]恼怒的客户[/format]",
 "ACT_ZOMBIE_HUD_HIGH_SCORE": "最高分：",
 "ACT_HELI_NEWS_VAN_KILL_TEXT": "摧毁新闻车",
 "ACT_PIMPING_CONTACT_OBJECTIVE": "营救 %d 名金吉的联络人并把他们带回来",
 "ACT_ESCORT_ESCORTING_TIGER_MSG": "快速驾驶让老虎保持愉快，同时积累你的勇气。",
 "ACT_VANDAL_BONUS_COMBO_MULT": "连击奖励",
 "ACT_FRAUD_BONUS_WITNESS": "路人目击奖励",
 "ACT_ESCORT_ESCORTING_MSG": "四处兜风，让[format][color:green]客户[/format]玩得开心",
 "ACT_HELI_PROTECTION_START_MOVING_MESSAGE": "你的[format][color:green]兄弟[/format]正要出门做交易，保护他们免受攻击",
 "ACT_HELI_PROTECTION_PICKUP_MESSAGE": "你[format][color:green]兄弟[/format]的车没油了，接上他们，把他们送[format][color:teal]回家。[/format]",
 "ACT_FRAUD_BONUS_VEHICLE_SURFING": "车顶冲浪奖励",
 "ACT_ESCORT_STOP_MSG": "停车 %d 秒",
 "ACT_ESCORT_START": "开始护送",
 "CHOP_HOT_ROD_HOOD": "改装车引擎盖",
 "ACT_TRAFFIC_OBJECTIVE_1": "在[format][color:green]毒贩[/format]送货时保护他们",
 "ACT_HELI_HOMIES_COMPLICATION_FAILED_MESSAGE": "你的兄弟已经死了",
 "ACT_ESCORT_STRIPPER_SWITCH_MSG": "舞女累坏了，去[format][color:teal]脱衣舞俱乐部[/format]换个新姑娘、换辆新车",
 "ACT_ZOMBIE_CANT_REVIVE": "你至少需要 1 个食物道具才能救人！",
 "ACT_VANDAL_SUMMARY_FAVORITE_TARGET": "最爱目标",
 "ACT_PIMPING_RECRUIT_HOS_TEXT": "{RECRUIT_DISMISS_IMG} 招募[format][color:green]姑娘[/format]",
 "ACT_FRAUD_BONUS_DONE": "前往另一个[format][color:teal]奖励区[/format]",
 "TUT_TITLE_ACT_INTRO_GUARDIAN_ANGEL": "天使护卫",
 "ACT_TORCH_RACE_TARGETS": "杀死[format][color:red]标记目标[/format]",
 "ACT_PIMPING_DRIVE_TO_LOCATION": "招募[format][color:green]姑娘[/format]并把她们带回[format][color:teal]齐莫斯[/format]处",
 "ACT_RUNNING_MAN_WAITING_ON_HOST_DESCRIPTION": "等待主机对下一轮下注",
 "ACT_TANK_MAYHEM_START": "开始坦克大破坏",
 "GAMEPLAY_BUSTED": "你被捕了！",
 "ACT_VANDAL_SUMMARY_TOTAL": "总计",
 "ACT_FRAUD_OBJECTIVE": "把自己扔进危险之中，在时间耗尽前累积 $%d 的伤害。",
 "ACT_TRAFFIC_DRIVER_LOST": "毒贩被丢下了。",
 "ACT_ESCORT_PLEASURE": "愉悦",
 "ACT_ESCORT_KILL_MSG": "杀死[format][color:red]目标[/format]",
 "CHOP_LUXERY_BODY_KIT": "豪华车身套件",
 "ACT_VANDAL_CAR_LUXURY_MSG": "豪华车",
 "ACT_ESCORT_FAIL_LEFT_CAR": "你弃车了",
 "ACT_TRAFFIC_OBJECTIVE_2": "[format][color:green]毒贩[/format]必须成功完成 %d 笔交易",
 "ACT_GUARDIAN_ANGEL_CLIENT_DIED_MESSAGE": "他们抓到了她！她没了。",
 "ACT_ESCORT_TRIP_MOTEL_MSG": "带[format][color:green]客户[/format]去[format][color:teal]汽车旅馆[/format]按小时快活",
 "ACT_PIMPING_FAIL_KILLED_CONTACT": "你杀死了一名联络人",
 "STRONGHOLD_FAILURE_CANCEL_TEXT": "据点已取消",
 "ACT_FRAUD_NAME": "碰瓷索赔",
 "ACT_FRAUD_GO_SCORING_AREA": "前往[format][color:teal]%ls 区[/format]",
 "ACT_GUARDIAN_ANGEL_HELPER_DIED_MESSAGE": "帮手死了",
 "ACT_GUARDIAN_ANGEL_CLIENT_HUMAN_SHIELDED_MESSAGE": "你的客户不喜欢被当成人盾。",
 "ACT_ESCORT_FIRST FOOTAGE_MSG": "别让那些新闻车拍到任何画面",
 "ACT_TORCH_TIME_EARNED_PARAMETERIZED": "获得[format][color:teal]%2.1f[/format] 秒奖励！",
 "ACT_PIMPING_RESCUE_CONTACT_DECKERS_REROUTE": "[format][color:green]联络人[/format]被带走了，去救他们",
 "ACT_PIMPING_HOS_SLASH": "/",
 "ACT_FRAUD_MESSAGE_CRAZY_MULT_TYPE": "碰瓷疯狂车流纪录",
 "ACT_ESCORT_BUTTON_MASHING_MSG": "[format][color:green]客户[/format]想要黑道圣徒特供",
 "ACT_ESCORT_RETURN_MSG": "返回脱衣舞俱乐部",
 "ACT_ESCORT_CRASH_MSG": "[format][color:green]客户[/format]要你用你的车对别的车造成 %d 点伤害",
 "CHOP_MUSCLE_RIMS": "肌肉车轮辋",
 "ACT_TRAFFIC_DRIVE_HOME": "开车[format][color:teal]回家[/format]途中保护[format][color:green]毒贩[/format]",
 "ACT_FRAUD_BONUS_CRAZY_DRIVER": "疯狂司机奖励",
 "ACT_GUARDIAN_ANGEL_PLAYER_KILLED_CLIENT_MESSAGE": "你杀了名人，敌人欢呼雀跃！",
 "ACT_FRAUD_MESSAGE_AIRTIME_MULT_TYPE": "碰瓷滞空纪录",
 "ACT_FRAUD_BONUS_COOP_GANGBANG": "群殴奖励",
 "ACT_CHOP_LIST": "把清单上的车开回[format][color:green]拆车坊[/format]。",
 "ACT_HELI_KILL_CARS_START_MESSAGE": "摧毁[format][color:red]车辆[/format]",
 "ACT_ESCORT_DRIFT_MSG": "[format][color:green]客户[/format]要你 {HANDBRAKE_IMG} 漂移 %d 秒",
 "ACT_VANDAL_TRUCK_SMALL_PICKUPS_MSG": "皮卡",
 "ACT_VANDAL_COMBO_BREAKER_MSG": "连击中断！",
 "ACT_TRAFFIC_DRIVER_DEAD": "毒贩被杀了。",
 "ACT_TORCH_OBJECTIVE_02": "通过造成伤害赚取额外时间，然后穿过检查点",
 "ACT_HUMAN_TORCH_START": "开始烈火流星",
 "ACT_TRAFFIC_POLICE_STING_ESCAPE": "[format][color:red]警察[/format]在跟踪你！",
 "ACT_TRAFFIC_POLICE_STING_DEALER_ARRESTED_5SEC": "5……",
 "ACT_TORCH_LOST_TIME": "你时间用完了",
 "ACTIVITY_SUCCESS_SUB_TEXT": "完成",
 "ACT_VANDAL_SUMMARY_DESTRUCTION": "破坏",
 "ACT_HELI_LIBERATOR_START_MESSAGE": "一批圣徒被捕了，摧毁[format][color:red]巴士[/format]逼停它们，然后把圣徒们送到安全处",
 "ACT_FRAUD_CHANGE_LOCATION": "[format][color:teal]计分区[/format]已移动",
 "ACT_ESCORT_TIGER_MINIGAME_MSG": "用 {ANALOG_RS_IMG} 找到老虎的痒处。再用 {ANALOG_LS_IMG} 小心地挠它",
 "ACT_VANDAL_BONUS_CLOSE_CHAOS": "近距离混乱奖励",
 "ACT_PIMPING_RESCUE_CONTACT_KILL_COPS": "杀死[format][color:red]警察[/format]并营救[format][color:green]联络人[/format]",
 "ACT_PIMPING_RECAPTURE_CONTACT_START": "一名[format][color:red]赛博帮[/format]成员正抓住一名[format][color:green]联络人[/format]，快抢回来！",
 "ACT_PIMPING_YOU_NEED_MORE_HOS": "你需要更多[format][color:green]姑娘[/format]",
 "ACT_ESCORT_AIR_MSG": "获得 %.2f 秒滞空时间",
 "ACT_PIMPING_TRAP_GET_CONTACTS": "干得好，现在去带走[format][color:green]联络人[/format]！",
 "ACT_GUARDIAN_ANGEL_BEHIND_ATTACKER": "攻击者正从客户[format][color:red]身后[/format]来袭",
 "ACT_FRAUD_DONT_KILL": "每杀一个人你都会被扣分",
 "ACT_ESCORT_TRIP_BROTHEL_MSG": "带[format][color:green]客户[/format]去[format][color:teal]妓院[/format]找点额外乐子",
 "ACT_VANDAL_HELICOPTER_MSG": "直升机",
 "ACT_TORCH_TIME_EARN_PARAMETERIZED_STRING": "穿过检查点会把奖励秒数加到剩余时间上",
 "ACT_FRAUD_BONUS_LOCATION": "如果你在小地图标示的区域内摔倒，将获得奖励",
 "ACT_ESCORT_FOOTAGE": "画面",
 "ACT_VANDAL_COMBO_TOTAL": "连击合计：%ls",
 "ACT_PIMPING_TRAP_SPRUNG_KILL_DECKERS": "有埋伏！在招募[format][color:green]联络人[/format]之前先杀光所有[format][color:red]赛博帮[/format]成员。",
 "ACT_HELI_ACTIVITY_BOMB_MESSAGE": "安装炸药摧毁这座[format][color:blue]建筑[/format]",
 "GAMEPLAY_SMOKED": "你被干掉了！",
 "ACTIVITY_FAILURE_SUB_TEXT": "失败",
 "ACT_TRAFFICKING_NAME": "黑货押运",
 "CHOP_SPORT_FRONT_BUMPER": "运动前保险杠",
 "ACT_ESCORT_NEWS_WARNING_MSG": "如果你离新闻车太近，愉悦条就会停止增长",
 "CHOP_OFF_ROAD_1_BUMPERS": "越野 1 保险杠",
 "ACT_VANDAL_START_3_MSG": "如果你连续快速破坏物品，将获得连击奖励",
 "ACT_RUNNING_MAN_WAGER_DESCRIPTION": "要在下一关拿你目前的赢款赌一把翻倍或清零吗？\\n\\n成功通关下一关，你的钱就翻倍！！！只要别搞砸，否则你将两手空空地离开。\\n\\n你意下如何？",
 "ACTIVITY_NAME_ESCORT": "护送",
 "ACT_ZOMBIE_FAIL": "你没能击退丧尸",
 "ACT_VANDAL_BONUS_TOTAL": "总计",
 "ACT_VANDAL_PROPERTY": "财产",
 "ACT_TRAFFIC_CHASE_HELICOPTER_NOTORIETY": "[format][color:red]新闻直升机[/format]正在抬高你的警方恶名！",
 "ACT_TORCH_START_TEXT1": "点燃汽油痕迹和油桶制造大爆炸",
 "ACT_CHOP_SHOP_DELIVER_CAR_MSG": "把车送到拆车坊。",
 "ACT_PIMPING_RESCUE_KILL_COPS": "杀死[format][color:red]警察[/format]并营救[format][color:green]姑娘[/format]",
 "ACT_HELI_START": "开始武直突击",
 "ACT_HELI_LIBERATOR_PICKUP_INFORMATION_MESSAGE": "接上圣徒们，把他们送到[format][color:blue]安全地点[/format]",
 "ACT_VANDAL_SMG_MSG": "冲锋枪",
 "ACT_FRAUD_BONUS_CLIFF_DIVER": "垂直距离奖励",
 "ACT_TRAFFIC_DEALING_PROTECT": "保护[format][color:green]毒贩[/format]与[format][color:green]买家[/format]",
 "ACT_PIMPING_RESCUE_CONTACT_KILL_DECKERS": "杀死[format][color:red]赛博帮[/format]成员并营救[format][color:green]联络人[/format]",
 "ACT_PIMPING_VEHICLE_ROUTE_HOS": "拦下[format][color:red]车辆[/format]并带走[format][color:green]姑娘[/format]",
 "ACT_TRAFFIC_DEALER_ATTACK": "[format][color:green]毒贩[/format]正遭到攻击",
 "ACT_PIMPING_RECAPTURE_START": "一名[format][color:red]晨星帮[/format]成员正抓住你的[format][color:green]姑娘[/format]，快把她抢回来",
 "ACT_FRAUD_BONUSES": "你的奖励：",
 "ACT_VANDAL_BONUS_MSG": "奖励",
 "ACT_PIMPING_TRAP_GET_HOS": "干得好，现在去带走[format][color:green]姑娘[/format]！",
 "ACT_GUARDIAN_ANGEL_RIGHT_ATTACKER": "攻击者从[format][color:red]右侧[/format]来袭",
 "ACT_FRAUD_BONUS_SUCCESSIVE_CARS": "弹球奖励",
 "ACT_ESCORT_FAIL_FOOTAGE": "被拍到太多画面了，走小巷甩掉他们",
 "ACT_ESCORT_TOUCH_MINIGAME_MSG": "用 {ANALOG_RS_IMG} 找到特殊位置，再用 {ANALOG_LS_IMG} 触发它",
 "ACT_ESCORT_OBJECTIVE_MSG": "开车载[format][color:green]客户[/format]在城里兜风取乐，同时避开狗仔队。",
 "ACT_VANDAL_CAR_STANDARD_MSG": "轿车",
}

lines = open(SCH, encoding="utf-8").read().replace("\r\n", "\n").split("\n")
out, seen = [], set()
for ln in lines:
    m = re.match(r'^\s*"((?:[^"\\]|\\.)*)":\s*"(.*)"\s*$', ln)
    if m and m.group(1) in T:
        out.append('"%s": "%s"' % (m.group(1), T[m.group(1)]))
        seen.add(m.group(1))
    else:
        out.append(ln)
miss = [k for k in T if k not in seen]
open(SCH, "w", encoding="utf-8").write("\n".join(out) + "\n")
print("written", len(T) - len(miss), "miss", miss)
