# -*- coding: utf-8 -*-
# hud 人工翻译批2(末批)
import re, os
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCH = os.path.join(BASE, "schinese", "hud_us.txt")
T = {
 "FLASHPOINT_TOTAL_COMPLETED": "帮派行动已完成 %d/%d",
 "HUD_FOOTAGE": "录像",
 "FRIENDLY_FIRE_LIGHT_TURNED_ON__NYOU_CAN_NOW_DEAL_SOME_DAMAGE_TO_YOUR_PARTNER": "轻量队友伤害已开启！\\n你现在可以对你的搭档造成一定伤害。",
 "UNL_GANG_WEAPONS_RIFLE": "帮派 - 武器 - 步枪",
 "TUT_WHORED_HOBO_SHOTGUN": "街头正义",
 "TUT_TAKEOVER_RESPECT": "完成任务、活动、即时挑战并接管城市会赚取声望，声望会提升你的等级并允许你购买升级。",
 "TUT_TITLE_MISSION_CHECKPOINT": "任务检查点",
 "TUT_ACT_INTRO_MAYHEM": "用提供的武器制造一场大范围屠杀。",
 "TUT_COMBAT_MELEE_SPRINT": "{SPRINT_IMG} + {MELEE_POWER_ATTACK_IMG} / {ATTACK_PRIMARY_IMG} 冲刺近战攻击",
 "WPN_RIFLENG_DESCRIPT": "更高级的步枪，配有可升级的瞄准镜。",
 "HUD_PRESS_BACK_CANCEL_HOSTAGE": "%ls 以退出人质状态",
 "PLAYER_ALREADY_HEALED": "兄弟，你已经满血了！",
 "TUT_TITLE_CASH_INCOME": "每小时城市收入",
 "MAP_HIDDENNAME_ACTIVITY": "活动",
 "PAUSE_ACT_HITMAN_ADD_HUD": "添加到 HUD",
 "TUT_WHORED_A_GOOD_VIBRATIONS": "美好共鸣",
 "TUT_TITLE_PLAYER_CHOICE": "玩家抉择",
 "SATELLITE_RC_SIGNAL_STRENGTH": "信号 {0}",
 "HUD_CANCEL_DIVERSION": "退出即时挑战",
 "HUD_HITMAN_LOCATED": "可在以下地点找到：",
 "HUD_MILES": "英里",
 "GENKI_AMMO": "元气发射器弹药",
 "STRONGHOLD_UPGRADE_BASE": "基地",
 "ACHIEVE_SR3_TANK_YOU_VERY_MUCH": "多谢你坦克",
 "RIFLE_KILLSHOT": "TOGO-13",
 "TUT_TITLE_DIV_INTRO_TAGGING": "涂鸦",
 "TUT_CASH_INCOME": "你的手机“CASH”菜单中有 $%ls 可取。你因拥有钢埠的领地，每小时可获得 $%ls 城市收入。",
 "ACHIEVE_SR3_FENCE_KILLA_2011": "2011 篱笆杀手",
 "UNL_NOTORIETY_DECKERS_2": "恶名 - 赛博帮 2",
 "UNL_DAMAGE_VEHICLE_1": "伤害 - 载具",
 "HUD_AMT_SECS_B": "+{0} 秒",
 "UNL_DESC_UPGRADE_AMMO_EXPLOSIVE_1": "爆炸弹药携带量提升 25%%",
 "TUT_WHORED_MONEYSHOTS": "一击命中",
 "TUT_TITLE_QUICK_KILL": "人盾 - 处决",
 "HUD_DAMAGE": "伤害",
 "TUT_TITLE_STRONGHOLD_START": "据点",
 "ACHIEVE_SR3_HATERS_GONNA_HATE": "黑子就是爱黑",
 "Grenade": "手雷",
 "TUT_TITLE_HUMAN_SHIELD": "人盾",
 "TUT_VTOL_CONTROL_A": "{HELI_UP_IMG} 升高\\n{HELI_DOWN_IMG} 降低\\n{VTOL_TRANSITION_IMG} 切换飞行模式",
 "TUT_SHOOTING_STUNTS": "击杀帮派成员能赚取声望。你完成的击杀越极限、越困难，获得的声望就越多。",
 "RESTRICTED_ZONE_EXIT": "正在离开限制区域",
 "TUT_WHORED_BOWLING": "保龄球",
 "SMG_GANG": "TEK Z-10",
 "TUT_WHORED_A_4_JULY": "七月四日",
 "TUT_LOW_AMMO": "你的弹药不足。前往队友火力商店 {MAP_IMG_WEAPON} 购买更多弹药。",
 "TUT_TITLE_STORE_INTRO_FOOD": "餐厅",
 "TUT_DIVERSION_COMPLETE": "你已完成这项即时挑战！你仍然可以继续游玩该挑战以赚取更多声望或现金。",
 "CS_TITLE_POWDER": "火药",
 "PLAYER_CHOICE_M16_OPTION1_BODY": "奖励：载具自定义费用减免",
 "ACTIVITY_CANCEL_SUB_TEXT": "活动已取消",
 "TUT_RESPECT_DIVERSIONS": "你做的一切都能赚取声望。\\n即时挑战 HUD 会追踪你通过即时挑战赚取的声望，其中包括从逆行驾驶到用蛋蛋射击击杀敌人等一切行为。",
 "BEHEMOTH": "巨兽",
 "Temp_Minigun": "迷你机枪",
 "STRONGHOLD_UPGRADE2": "升级 2",
 "UNL_HOMIE_JOSH": "兄弟 - 乔什·伯克",
 "TUT_WHORED_A_MEAN_GIRLS": "坏女孩",
 "TUT_TITLE_UPGRADE_STORE": "升级商店",
 "TUT_ACT_INTRO_CYBER_BLAZING": "在赛博空间中极速穿行，在时间耗尽前击中[format][color:blue]赛博帮目标[/format]，同时避开[format][color:red]防火墙[/format]。",
 "TUT_WHORED_D_CYPRIAN_ORDER": "塞浦路斯教团",
 "TUT_WHORED_GIMPS": "被束缚",
 "TUT_WHORED_PICKUPS_TITLE": "拾取品",
 "GARAGE_LICENSED_VEHICLES_ONLY": "你不能存放未购买的下载内容",
 "TUT_WHORED_DRUNK": "饮酒游戏",
 "TUT_ACT_INTRO_HELI_ASSAULT": "使用攻击直升机保护你的联络人。",
 "HUD_RIDE_TRAIN": "乘火车",
 "SYSTEM_PAUSED": "已暂停",
 "TUT_SECONDARY_FIRE": "{ATTACK_SECONDARY_IMG} 副武器开火 \\n这把武器有可用的副开火模式。",
 "TUT_PLAYER_CHOICE": "你需要做出选择：为圣徒保留辛迪加大厦以赚取金钱，或摧毁辛迪加大厦以赚取声望。\\n请慎重选择。",
 "TUT_TITLE_SATCHEL_CHARGES": "炸药包",
 "HUD_TRIGGER_DISABLED_SH": "此据点期间你不能来这里",
 "MISSION_CANCEL_TEXT": "确定要离开任务吗？\\n你将丢失自上一个检查点以来的全部进度。",
 "TUT_TITLE_ACT_INTRO_INS_FRAUD": "保险诈骗",
 "ACHIEVE_SR3_MURDERBRAWL_31": "屠杀格斗 31",
 "TUT_NP_MOTORCYCLE_CONTROLS": "{ACCELERATE_IMG} 加速 \\n{BRAKE_REVERSE_IMG} 刹车 + 倒车 \\n使用 {ANALOG_LS_IMG} 转移重心以抬起前轮或进行翘尾停车。",
 "TUT_ANNIHILATOR": "通过缩放 {SHOULDER_CAMERA_IMG} 锁定载具目标。\\n用准星控制已发射火箭的飞行方向。",
 "UNL_HOMIE_HEALTH_2": "帮派 - 生命提升 2",
 "UNL_DAMAGE_EXPLOSIVE_4": "伤害 - 爆炸 4",
 "TUT_WHORED_GRENADIERS": "掷弹兵",
 "TUT_WHORED_STARPOWER": "追星族",
 "UNL_DESC_HEALTH_REGEN_2": "生命值恢复速度加快",
 "UNL_DESC_WEEKLY_PAYMENTS_4": "每小时城市收入 $2,500",
 "TUT_ACT_INS_FRAUD_ANDRENALINE": "肾上腺素条充满后，使用肾上腺素模式连续打出疯狂的强化撞击！",
 "TUT_COMBAT_MELEE_BASH": "{CBA_OFC_HS_EXECUTE_IMG} 快速近战猛击",
 "WPNCAT_RIFLE": "步枪",
 "TUT_WHORED_TAUNT": "粗鲁叫醒",
 "TEMP_LUCHAGRENADE": "GL G20",
 "TUT_TITLE_NAG_WEAPON_UPGRADES": "武器升级",
 "TUT_NOTORIETY_DECREASES": "躲进任何一座你名下的建筑，恶名即刻清零：{MAP_IMG_CRIB}、{MAP_IMG_CLOTHING} 等。",
 "WPN_CRICKETBAT": "板球棒",
 "SATELLITE_GUIDED_MISSILE": "制导导弹",
 "TUT_DLC_MANCANNON": "{ATTACK_PRIMARY_IMG} 弹飞人类 \\n驾驶载具撞向路人将其收集起来，然后从加农炮中发射出去。",
 "TUT_TITLE_COMBAT_FINEAIM": "镜头缩放",
 "CS_TITLE_STILWATER_BRIDGE": "斯蒂尔沃特 - 休斯纪念大桥",
 "UNL_DAMAGE_VEHICLE_3": "伤害 - 载具 3",
 "TUT_WHORED_Z_FOOD_TRUCK": "餐车梦魇",
 "TUT_WHORED_WEENIEROAST": "烤香肠",
 "TUT_TITLE_HEALTH_SPRINT_METER": "生命 / 冲刺条",
 "UNL_DESC_UPGRADE_AMMO_EXPLOSIVE_3": "爆炸弹药携带量提升 75%%",
 "UNL_DESC_CASH_MULTIPLIER_2": "获得的所有现金提升 10%%",
 "TUT_TITLE_UNLOCKABLES": "解锁项/奖励",
 "TUT_TITLE_SMOKED": "被干掉了！",
 "OBJECT_PARTNER_COLLECTED": "%ls 发现了一个你错过的收集品",
 "TUT_TITLE_DRIVING_STUNTS": "驾驶特技",
 "TUT_HITMAN_NEW": "{MAP_MENU_IMG} 打开圣徒簿 \\n暗杀目标现在出现在圣徒簿中。追踪并杀死他们以快速赚取现金。",
 "TUT_M16_AVATAR_ATTACKS": "{AVATAR_SHOCKWAVE_IMG} 冲击波 \\n{AVATAR_SWORD_SWEEP_IMG} 挥剑 \\n{AVATAR_DASH_IMG} 冲刺 \\n{AVATAR_FLAME_BREATH_IMG} 火焰吐息",
 "HUD_PRESS_BACK_CANCEL_STRONGHOLD": "按住 %ls 退出据点",
 "ENTER_VEHICLE_DRIVER_SEAT_MESSAGE": "%ls 进入载具驾驶座",
 "TUT_TITLE_VEHICLE_TURRET": "载具炮塔",
 "HUD_CANT_CUST_PARTNERS_CAR": "你不能自定义搭档的载具。",
 "RIFLE_STAG": "毒蛇激光步枪",
 "TUT_TITLE_ACT_INTRO_SNATCH": "营救",
 "WPN_VTOL01": "激光束",
 "GRENADE_ELECTRIC": "电击手雷",
 "CUTSCENE_HOST_SKIPPING": "你投票跳过了",
 "TUT_WHORED_A_FISTING": "拳交",
 "TUT_DIVERSION_HUD": "当你在做能赚取声望的特殊行为时，即时挑战星级会出现在这里。星级越多，获得的声望越多。",
 "TUT_TITLE_NP_BOAT_CONTROLS": "船只操控",
 "decker_sword": "夜曲",
 "RESPECT_WIDGET_LABEL": "声望",
 "STRONGHOLD_COOP_START_MSG": "开始合作据点？",
 "UNL_DESC_DAMAGE_VEHICLE_4": "被载具撞击时你不会受到任何伤害。",
 "UNL_DESC_DOESNOTEXIST": "这项升级尚未开放。",
 "TUT_ESCORT_REMOTE": "使用 {ANALOG_RS_IMG} 找到特殊位置。\\n将 {ANALOG_RS_IMG} 保持在那里，然后跟随箭头及时推动 {ANALOG_LS_IMG} 以击中目标位置。",
 "HUD_ZOOM_IN_AND_OUT": "%ls 与 %ls 拉近和拉远镜头",
 "UNL_HOMIE_REPAIR": "兄弟 - 维修",
 "UNL_DESC_HOMIE_HELI": "直升机兄弟可在你的手机“PHONE”菜单中找到。他会在战斗中给你送来一架直升机。",
 "UNL_CRIB_BDSM": "据点 - 安全词",
 "TUT_WHORED_THE_END": "终结",
 "HUD_USE_HAND_BRAKE_MESSAGE": "按住 {HANDBRAKE_IMG} 使用手刹",
 "UNL_WEP_PREDATOR_DRONE": "武器 - 死神无人机",
 "TUT_WHORED_OLDSCHOOL": "老派",
 "TUT_TITLE_DIV_INTRO_HOSTAGE": "人质",
 "TUT_TITLE_DLC_MANCANNON": "元气战车",
 "HOMIES_KILLED": "%ls 已被杀死！",
 "WPN_CHAINSAW_DESCRIPT": "把你的敌人撕成碎片，大卸八块！",
 "HOMIES_FALLEN": "%s 倒下了！",
 "TUT_WHORED_SONICBOOMSTICK": "音爆",
 "HUD_BORDER_TURNAROUND": "圣徒需要你回钢埠",
 "STOPPING_BLOCKED_PATH": "有什么东西挡住了你的路。",
 "TUT_SNIPER_UPGRADE": "{ACTION_IMG} 开镜缩放模式",
 "TUT_TITLE_NOTORIETY_DECREASE_STORE": "恶名清除",
 "TUT_WHORED_D_COUNTING_CALS": "计算卡路里",
 "TUT_TITLE_HUMAN_SHIELD_GENERAL": "人盾",
 "USE_TRIGGER_HELI": "前往直升机停机坪",
 "TUT_WHORED_BAT": "球棒 VS 妓女",
 "TUT_CAR_SHOOTING": "{FIREARM_IMG} 发射主武器 \\n{ATTACK_SECONDARY_IMG} 投掷手雷",
 "TUT_TITLE_BUSTED": "被捕了！",
 "WPN_SMGSTORM_DESCRIPT": "更高级的冲锋枪，能以极快的射速连续射击。",
 "HUD_RESPECT_RANK_010": "皮条客",
 "HOOD_GAINED": "已获得街区",
 "TUT_TITLE_FLASHPOINT": "帮派行动",
 "CS_TITLE_STAG_AIRCRAFT_CARRIER": "STAG 航母：温泉关",
 "ACHIEVE_SR3_THE_WELCOME_WAGON": "欢迎车队",
 "TUT_CROUCH": "按下 {CROUCH_IMG} 蹲下 \\n蹲下射击时精度更高。",
 "TUT_JUMP_CLIMB": "{JUMP_CLIMB_IMG} 跳跃/攀爬 \\n {SPRINT_IMG} + {JUMP_CLIMB_IMG} 快速扑倒 \\n跳跃、攀爬和扑倒能让你迅速脱离危险处境。",
 "TUT_DIV_INTRO_HOLDUP": "继续用缩放瞄准对准店员以抢劫这家商店。",
 "CS_TITLE_S_1ST_NAT": "斯蒂尔沃特第一国家银行",
 "HUD_PRESS_DPADUP_PARTY_DISMISS": "再次按下以遣散队伍",
 "TUT_TITLE_DIVERSION_HUD": "即时挑战 HUD",
 "CS_TITLE_SKIES_OVER_STEELPORT": "钢埠上空",
 "PLAYER_REVIVE_FOLLOWER": "救起你的[format][color:purple]兄弟[/format]",
 "TUT_ACT_INS_FRAUD_FIRST_HIT": "{PRATFALL_ALT_IMG} / {PRATFALL_IMG} 布娃娃摔 \\n{ANALOG_LS_IMG} 空中调整",
 "ACHIEVE_SR3_CREW_OF_TWO": "两人小队",
 "SNIPER_AMMO": "狙击枪弹药",
 "HUD_ATTACK_MATT": "攻击马特",
 "TUT_WHORED_Z_GIRLS_NIGHT": "女孩之夜",
 "ACHIEVE_SR3_HACK_THE_PLANET": "入侵地球",
 "STRONG_CANCEL_TEXT": "确定要离开据点吗？\\n你将丢失自上一个检查点以来的全部进度。",
 "HUD_SECONDS": "秒",
 "HUD_RESTART_TEXT": "%s 重新开始",
 "TUT_CROUCH_SR3": "按下 {CROUCH_IMG} 蹲下 \\n蹲下射击时精度更高。",
 "TUT_TITLE_ESCORT_MINIGAME": "护送",
 "ACHIEVE_SR3_DOUBLE_DOSE_OF_PIMPING": "双倍拉皮条",
 "WPN_CYBERCANNON_DESCRIPT": "金吉那把赛博帮用户网臂炮的实用模型。她哪来这么多时间？",
 "FLASHPOINT_DISCOVERED": "已发现帮派行动",
 "TUT_TITLE_CROUCH": "蹲下",
 "HUD_PRESS_BACK_CANCEL_MISSION": "按住 %ls 退出任务",
 "MISSION_CANCEL_TITLE": "重试或退出任务？",
 "ENTER_TAXI_MESSAGE": "%ls 进入出租车",
 "CUTSCENE_LOCAL_SKIPPING": "正在等待另一名玩家跳过这段过场动画。",
 "HUD_USE_RIGHT_STICK_MESSAGE": "使用 {ANALOG_RS_IMG} 环顾四周并瞄准",
}

lines = open(SCH, encoding="utf-8").read().replace("\r\n", "\n").split("\n")
out, seen = [], set()
for ln in lines:
    m = re.match(r'^\s*"((?:[^"\\]|\\.)*)":\s*"(.*)"\s*$', ln)
    if m and m.group(1) in T:
        out.append('"%s": "%s"' % (m.group(1), T[m.group(1)]))
        seen.add(m.group(1))
    else:
        out.append(ln)
miss = [k for k in T if k not in seen]
open(SCH, "w", encoding="utf-8").write("\n".join(out) + "\n")
print("written", len(T) - len(miss), "miss", miss)
