# -*- coding: utf-8 -*-
# static 人工翻译批1（接管剩余条目）
# 保留英文：MAP_IMG_*(8,纯image标签)、RADIO站名(GENX/THE_MIX/K12/KRHYME)、
#           STATS_DISTANCE_FEET/METERS(单位格式)、STAT_MANUALLY_AWARDED('-')、DUMMY_CHARACTERS_RUSSIAN('AB')
# 注：迪克帮/摔角手 为用户有意保留的风格译法，不做统一（勿改）
import re, os
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCH = os.path.join(BASE, "schinese", "static_us.txt")
T = {
 # ---- HORDE / WHORED MODE (妓望工程) ----
 "HORDE_MODE_RETRY_TEXT": "确定要重试妓望工程的这一波吗？",
 "HORDE_MODE_UNLIMITED_AMMO": "无限弹药！",
 "HORDE_MODE_TITLE_ZOMBIE_WAVE": "僵尸波",
 "HORDE_MODE_TITLE_PLAYER_SCORES": "玩家得分",
 "HORDE_MODE_GAMEPLAY_TITLE": "妓望工程",
 "HORDE_MODE_NEW_WAVE_MESSAGE_TITLE": "新一波！",
 "HORDE_MODE_TEAM_SCORE": "队伍得分",
 "HORDE_MODE_MENU_NEW_GAME": "新游戏",
 "HORDE_MODE_NEW_CHALLENGE_WAVE_TITLE": "挑战波！",
 "HORDE_MODE_MENU_EXIT": "返回主菜单",
 "HORDE_MODE_MENU_RETRY": "重试",
 "HORDE_MODE_TITLE_SURVIVAL_TIME": "生存时间",
 "HORDE_MODE_WEAPON_UPGRADE": "你的 %ls 现已升至第 %i/%i 级",
 "HORDE_MODE_TITLE_FAIL": "第 {0} 波完成",
 "HORDE_MODE_KILL_COUNT": "击杀数",
 "HORDE_MODE_SURVIVAL_TIMER_TAG": "已存活",
 "HORDE_MODE_WAITING_FOR_HOST": "正在等待主机。",
 "HORDE_MODE_QUIT_TEXT": "确定要退出吗？\\n(这会结束双方玩家的妓望工程)",
 # ---- STAT：嘲讽 / 挑衅系列（全库主用“嘲讽”）----
 "STAT_TAUNT_GANG": "嘲讽的帮派成员数",
 "STAT_TAUNTING_TOTAL_COPS_TAUNTED": "嘲讽警察总数",
 "STAT_TAUNTING_TOTAL_GANG_MEMBERS_TAUNTED": "嘲讽帮派成员总数",
 "STAT_TAUNTING_TOTAL_COMPLIMENTS_GIVEN": "称赞他人总数",
 "STAT_TAUNT_RESPECT": "嘲讽获得声望",
 # ---- STAT：通用 ----
 "STAT_SPECIAL_AMMO_USED": "特殊武器射击次数",
 "STAT_RPG_HIT_PCT": "RPG 命中率",
 "STAT_SMG_HIT_PCT": "冲锋枪命中率",
 "STAT_SHOTGUN_SHOTS_FIRED": "霰弹枪射击次数",
 "STAT_RPG_SHOTS_FIRED": "RPG 射击次数",
 "STAT_VEHICLES_DESTROYED": "摧毁载具数",
 "STAT_CARS_DESTROYED": "摧毁汽车数",
 "STAT_AIRCRAFT_DESTROYED": "摧毁飞行器数",
 "STAT_TOTAL_RESPECT": "累计获得声望",
 "STAT_BAIL_MONEY": "缴纳保释金",
 "STAT_LEVELS_COMPLETED": "关卡完成数",
 "STAT_STORES_OWNED": "拥有商店数",
 "STAT_MISSION_SUCCESS_RATE": "任务成功率",
 "STAT_MISSION_STRONGHOLD_CASH_EARNED": "任务/根据地赚取现金",
 "STAT_ACTIVITY_CASH_EARNED": "活动赚取现金",
 "STAT_DEATHS": "死亡次数",
 "STAT_ARRESTS": "被捕次数",
 "STAT_HOMIES_RECRUITED": "招募兄弟数",
 "STAT_HOMIEZ_ACQUIRED": "已招募兄弟数",
 "STAT_CRIBS_ACQUIRED": "已收购藏身处数",
 "STAT_FAVORITE_TRANSPORTATION": "最常用的交通方式",
 "STAT_HOLDUP_ROBBED": "打劫商店数",
 "STAT_HITMAN_TARGETS": "消灭目标数",
 "STAT_HITMAN_COMPLETED": "暗杀完成数",
 "STAT_JUMPS_FOUND": "特技跳跃点发现数",
 "STAT_AERIAL_STUNTS_FOUND": "低空穿越点发现数",
 "STAT_PHOTO_OP_FOUND": "拍照点发现数",
 "STAT_PEOPLE_RUN_OVER": "碾过的行人",
 "STAT_GANG_NOTORIETY_TIME": "最高帮派恶名持续时长",
 "STAT_COOP_GANG_NOTORIETY_TIME": "合作：最高帮派恶名持续时长",
 "STAT_COOP_MAX_POLICE_NOTORIETY_STREAK": "双人合作：最高警方恶名最长连续时长",
 "STAT_COOP_DEATHS": "双人合作：玩家造成的死亡数",
 "STAT_COOP_MISSIONS_COMPLETED": "双人合作：任务完成数",
 "STAT_CAT_MOUSE_LONGEST_DEATH_STREAK": "猫捉老鼠：最长连续死亡",
 "STAT_CAT_MOUSE_MOST_ROUND_DEATHS": "猫捉老鼠：单轮最多死亡数",
 "STAT_CAT_MOUSE_WINS": "猫捉老鼠：获胜次数",
 "STAT_CAT_MOUSE_MOST_ROUND_KILLS": "猫捉老鼠：单轮最多击杀数",
 # ---- STAT：驾驶/特技 ----
 "STAT_DRIVING_BAILOUT_DISTANCE": "最长跳车距离",
 "STAT_DRIVING_BAILOUT_RESPECT": "跳车获得声望",
 "STAT_DRIVING_BAILOUT": "跳车",
 "STAT_DRIVING_DRIFTING_RESPECT": "漂移获得声望",
 "STAT_DRIVING_BIGAIR_RESPECT": "大腾空获得声望",
 "STAT_DRIVING_BURNOUT_RESPECT": "烧胎获得声望",
 "STAT_DRIVING_BURNOUT": "烧胎",
 "STAT_DRIVING_WHEELIE_RESPECT": "翘头获得声望",
 "STAT_DRIVING_STOPPIE_TIME": "最长翘尾时长",
 "STAT_DRIVING_STOPPIE": "翘尾",
 "STAT_DRIVING_WRONGWAY_RESPECT": "逆行车道获得声望",
 "STAT_DRIVING_WRONGWAY_TIME": "最长逆行车道行驶",
 "STAT_DRIVING_TWOWHEELS_RESPECT": "双轮行驶获得声望",
 "STAT_DRIVING_TWOWHEELS_TIME": "双轮行驶最长时间",
 "STAT_DRIVING_NEARMISS_CHAIN": "最长惊险擦身连击",
 "STAT_DRIVING_NEARMISS": "惊险擦身",
 "STAT_DRIVING_BACKSEAT": "碾杀",
 "STAT_MAX_TWO_WHEELS_DISTANCE": "双轮行驶最远距离",
 "STAT_MAX_WINDSHIELD_CANNON_DISTANCE": "挡风玻璃炮弹最远距离",
 "STAT_MAX_STUNT_JUMP_FLIP": "最大特技跳跃空翻",
 "STAT_MAX_STUNT_JUMP_ROLL": "最大特技跳跃翻滚",
 "STAT_MAX_STUNT_FALL_DIST": "最长坠落距离",
 "STAT_MAX_WRONG_WAY_DISTANCE": "最远逆行车道距离",
 "STAT_MAX_DRIVER_BAILOUT_DISTANCE": "跳车最远距离",
 "STAT_LONGEST_VEHICLE_SURF_HANDSTAND_TIME": "载具冲浪倒立最长时间",
 "STAT_LONGEST_VEHICLE_SURFING_TIME": "载具冲浪最长时间",
 "STAT_SURFING_TIME": "载具冲浪最长时间",
 "STAT_BIG_AIR_LONGEST_JUMP": "大腾空：最长跳跃",
 "STAT_DRIVING_WHEEILE_TIME": "最长翘头时长",
 # ---- STAT：战斗 ----
 "STAT_COMBAT_MELEE_RESPECT": "徒手击杀获得声望",
 "STAT_COMBAT_HEADSHOT_RESPECT": "爆头获得声望",
 "STAT_COMBAT_ONE_HIT_RESPECT": "一击必杀获得声望",
 "STAT_COMBAT_ONE_HIT": "一击必杀数",
 "STAT_COMBAT_MULTI_RESPECT": "多重击杀获得声望",
 "STAT_COMBAT_NUTSHOT_RESPECT": "蛋击获得声望",
 "STAT_COMBAT_CAR_RESPECT": "帮派载具击杀获得声望",
 "STAT_COMBAT_THROWN": "投掷",
 "STAT_BEAT_COPS_KILLED": "巡警击杀数",
 "STAT_MASCOTS_KILLED": "吉祥物击杀数",
 "STAT_DECKERS_KILLED": "击杀赛博帮",
 "STAT_MORNINGSTAR_SPECIALISTS_KILLED": "击杀晨星帮专家",
 "STAT_LUCHADORES_KILLED": "击杀摔跤手帮",
 "STAT_STAG_KILLED": "STAG 击杀数",
 # ---- STAT：活动 ----
 "STAT_MAYHEM_LEVELS_COMPLETED": "大破坏：已完成",
 "STAT_MAYHEM_BEST_COMBO": "大破坏：最佳连击",
 "STAT_MAYHEM_DAMAGE_DONE": "大破坏：造成伤害",
 "STAT_MAYHEM_OBJECTS_DESTROYED": "大破坏：摧毁物体数",
 "STAT_FRAUD_LEVELS_COMPLETED": "碰瓷索赔已完成",
 "STAT_HUMAN_TORCH_LEVELS_COMPLETED": "烈火流星已完成",
 "STAT_HUMAN_TORCH_OBJECTS_TORCHED": "烈火流星：烧毁物体数",
 "STAT_HUMAN_TORCH_BONUS_EARNED": "烈火流星：获得的奖励时间",
 "STAT_CHOPSHOP_CASH": "拆车坊赚取现金",
 "STAT_CHOPSHOP_VEHICLES": "拆车坊收集车辆数",
 "STAT_ESCORT_CLIENTS_SERVICED": "护送：服务客户数",
 "STAT_ESCORT_LEVELS_COMPLETED": "护送已完成",
 "STAT_SNATCH_PIMPS_KILLED": "快抢：击杀皮条客数",
 "STAT_DRUG_TRAFFICKING_BUYERS_SATISFIED": "黑货押运：满意买家数",
 "STAT_HOSTAGES_TAKEN": "劫持人质数",
 "STAT_STREAKING_PEOPLE": "裸奔经过人数",
 "STAT_STREAKING_CASH": "裸奔获得声望",
 "STAT_STREAKING_TOTAL_TIME": "裸奔总时长",
 "STAT_MILES_BY_BIKE": "摩托车行驶里程（英里）",
 "STAT_BASE_HIGH": "最高跳跃",
 # ---- STAT：类别/武器 ----
 "STAT_VEHICLE_BIKE": "摩托车",
 "STAT_VEHICLE_AIRCRAFT": "飞行器",
 "STAT_WEAPON_SNIPER": "狙击枪",
 "STAT_WEAPON_RPG": "RPG",
 "STAT_TEAM_LUCHADORES": "摔跤手帮",
 # ---- HUD / 确认框 ----
 "HUD_FOUND_CASH": "你从藏金处取出了 %ls！",
 "HUD_CRIB_CHANGE_RADIO_STATION": "切换电台",
 "HUD_RETRY_MISSION_MESSAGE_FULL": "重试任务会让你失去任务中获得的武器或声望。",
 "ACHIEVEMENTS_LOG_IN_EXPOSITION": "要查看成就，你需要先登录玩家档案。",
 "QUIT_GAME_TEXT_FULL": "你确定要退出吗？\\n(任何未保存的进度都会丢失。)",
 "MENU_EXPORT_SIGN_IN_FULL": "你必须登录 Xbox LIVE\\n才能导出到多人模式。",
 "MENU_TITLE_INSUFFICIENT_FUNDS": "现金不足",
 "PLAYER_CREATION_ABOUT_TO_REVERT": "要取消这些修改吗？",
 # ---- 服装/衣橱/装扮 ----
 "CONFIRM_DELETE_OUTFIT": "你确定要删除这套装扮吗？\\n你的衣物仍会保留在衣橱中。",
 "WARDROBE_REMOVE_OUTFIT": "要把这套装扮从衣橱中移除吗？",
 "WARDROBE_REMOVE_OUTFIT_TITLE": "移除装扮",
 "CONFIRM_WEAR_OUTFIT": "你确定要穿上这套装扮吗？",
 "WEAR_OUTFIT_TITLE": "穿上装扮",
 "DELETE_OUTFIT": "删除装扮",
 "CUST_ITEM_DELETE_OUTFIT": "删除装扮",
 "CUST_BROWSER_TITLE": "自定义浏览",
 "STORE_TITLE_DISCARD": "丢弃物品",
 "STORE_TITLE_WITHDRAW": "取出",
 "NO_ITEMS_DISPLAY_NAME": "无物品",
 "STORE_NO_ITEMS_IN_CATEGORY": "该类别下没有可用物品。",
 "STORE_TEXT_CONFIRM_PURCHASE_AND_SAVE_FULL": "你愿意花 %s 购买并保存“%s”吗？",
 "STORE_TEXT_INSUFFICIENT_FUNDS_BLANK": "你的钱不够购买这件物品。",
 "STORE_NOT_AVAILABLE": "不可用",
 "STORE_LEVEL_REQ": "需要等级 {0}",
 "STORE_AMBULANCE_MSG": "请求治疗",
 "STORE_WEAPON_STORE_MSG": "购买武器",
 "STORE_PLANET_SAINTS_MSG": "!!购买物品",
 "SURGEON_INSUFFICIENT_FUNDS": "你的钱不够去看整形医生。",
 "DEALER_NO_PALETTE": "没有可选涂装。",
 "DEALER_NO_SPACE": "你的车库没有足够空间停放 %s。",
 "WPNSTOR_TEXT_MAX_WEAPONS_STORE": "你已经拥有这把武器了。",
 "WPNSTOR_LEAVE_FULL_FRIENDLY_FIRE": "你确定要离开队友火力吗？",
 "UNLOCKABLE_TITLE_TEXT": "已解锁",
 "LINGERIE_STORE_NAME": "皮革与蕾丝",
 # ---- 载具/车库/改装 ----
 "VEHICLE_TYPE_TITLE": "载具类型",
 "VEHICLE_FREE": "免费",
 "GARAGE_NONE": "车库中没有车辆。",
 "GARAGE_CANNOT_REPAIR": "载具没有完全修复，无法改装\\n你的钱不够修复这辆载具。",
 "GARAGE_HANGAR": "机库",
 "GARAGE_DOCK": "船坞",
 "GARAGE_INSUFFICIENT_FUNDS": "你的钱不够修复这辆载具。",
 "GARAGE_REPAIR": "修复",
 "TUT_CRIB_GARAGE": "按 {ACTION_IMG} 把这辆载具存入车库",
 "VCUST_RIM_STYLE_OPTION": "轮毂样式",
 "VCUST_WHEEL_WIDTH_OPTION": "轮胎宽度",
 "VCUST_HIGH_PROFILE": "高扁平",
 "VCUST_REAR_AXLE_OPTION": "后轴",
 "VCUST_FRONT_AXLE_OPTION": "前轴",
 "VCUST_PURCHASE_WHEELS_PROMPT": "你愿意花 ${0} 购买这套轮胎配置吗？",
 # ---- 房产 ----
 "PURCHASEABLE_PROPERTEY_FLATS": "帕克维尤公寓",
 "PURCHASEABLE_PROPERTEY_POWER": "电力照明公司",
 "PURCHASEABLE_PROPERTEY_ORGAN_BLACKMARKET": "器官黑市",
 "PURCHASEABLE_PROPERTEY_WARF": "亨利钢铁码头",
 "PURCHASEABLE_PROPERTEY_HOSPITAL": "医院",
 # ---- 捏人/身体/杂项 UI ----
 "BODY_TITLE": "身体",
 "TAT_REG_BACK": "背部",
 "CUST_ICON_WRISTS": "手腕",
 "HAIR_CAT_NONE": "无",
 "STATS_NONE": "无",
 "CONTROL_QUIT_WITHOUT_SAVING": "不保存退出",
 "CONTROL_CANCEL": "取消",
 "MUSIC_METAL": "金属",
 "RADIO_STATION_OFF": "关闭",
 "DEMO_EXIT": "退出演示",
 "DEMO_FREEPLAY": "自由模式",
 "GIANT_PLAYER_DESC": "你吃了你的青豆，长成了大个子。",
 "HASH_E632737E": "游戏完成度",
 # ---- ESCORT 客户名（A=形容词/动词、B=名词、单译）---- "ESCORT_NAME_1A": "下流",
 "ESCORT_NAME_1B": "桑切斯",
 "ESCORT_NAME_3A": "驴",
 "ESCORT_NAME_3B": "拳",
 "ESCORT_NAME_5A": "金色",
 "ESCORT_NAME_5B": "淋浴",
 "ESCORT_NAME_7A": "珍珠",
 "ESCORT_NAME_7B": "项链",
 "ESCORT_NAME_9A": "滑溜",
 "ESCORT_NAME_9B": "龙",
 "ESCORT_NAME_10A": "愤怒",
 "ESCORT_NAME_10B": "指虎",
 "ESCORT_NAME_12A": "湿润",
 "ESCORT_NAME_12B": "富兰克林",
 "ESCORT_NAME_14A": "滚烫",
 "ESCORT_NAME_14B": "约翰逊",
 "ESCORT_NAME_16A": "挠痒",
 "ESCORT_NAME_16B": "漩涡",
 "ESCORT_NAME_18A": "下流",
 "ESCORT_NAME_18B": "桑切斯",
 "ESCORT_NAME_21A": "潜水",
 "ESCORT_NAME_21B": "玉米洞",
 "ESCORT_NAME_23A": "臭烘烘",
 "ESCORT_NAME_23B": "迪洛",
 "ESCORT_NAME_25A": "复仇",
 "ESCORT_NAME_27A": "疯狂",
 "ESCORT_NAME_27B": "奶昔",
 "ESCORT_NAME_29A": "皇家",
 "ESCORT_NAME_29B": "公主",
 "ESCORT_NAME_31A": "爬行",
 "ESCORT_NAME_31B": "蜥蜴",
 "ESCORT_NAME_33A": "罗曼",
 "ESCORT_NAME_33B": "蝴蝶",
 "ESCORT_NAME_35A": "坐姿",
 "ESCORT_NAME_35B": "响尾蛇",
 "ESCORT_NAME_37A": "倒转",
 "ESCORT_NAME_37B": "淋浴",
 "ESCORT_NAME_38_A": "顺时针",
 "ESCORT_NAME_38_B": "猴子扳手",
 "ESCORT_NAME_39_A": "双拳",
 "ESCORT_NAME_39_B": "揉捏",
}

lines = open(SCH, encoding="utf-8").read().replace("\r\n", "\n").split("\n")
out, seen = [], set()
for ln in lines:
    m = re.match(r'^\s*"((?:[^"\\]|\\.)*)":\s*"(.*)"\s*$', ln)
    if m and m.group(1) in T:
        out.append('"%s": "%s"' % (m.group(1), T[m.group(1)]))
        seen.add(m.group(1))
    else:
        out.append(ln)
miss = [k for k in T if k not in seen]
open(SCH, "w", encoding="utf-8").write("\n".join(out) + "\n")
print("written", len(T) - len(miss), "miss", miss)
