# -*- coding: utf-8 -*-
import re, io, sys

src = 'original/mission_us.txt'
out = 'schinese/mission_us.txt'

T = {
"M16_OBJ_KILL_TANKS": "搜寻并摧毁敌方[format][color:kill]坦克[/format]",
"M14_OBJ_TALK_TO_JANE": "与[format][color:location]简[/format]交谈",
"m13_failure_josh_died": "乔什死了！",
"M13_OBJ_TAKE_OUT_THE_TANKS": "摧毁[format][color:kill]坦克[/format]",
"MSN_PRE_CALL_OBJ_MMP03": "与[format][color:location]皮尔斯[/format]碰头",
"MSN_PRE_CALL_OBJ_M10": "与[format][color:location]薇奥拉[/format]碰头",
"m20_failure_ctb_destroyed": "你错过了好戏！",
"MM_K_01_obj_meet_kinzie": "前往[format][color:location]金齐的藏身处[/format]",
"MISSION_NAME_M23": "STAG 影片",
"M24_OBJ_RUN_FOR_COVER": "寻找掩体",
"M23_OBJ_FLY_TO_REAR_DECK": "飞往[format][color:location]后甲板[/format]",
"M17_OBJ_FIND_REACTOR": "找到[format][color:location]反应堆[/format]",
"MM_Z_02_obj_goto_dt": "前往[format][color:location]活动起点[/format]",
"MISSION_NAME_MM_P_04": "坦克大破坏",
"MISSION_NAME_MM_P_01": "天使护卫",
"MM05_OBJ_GOTO_RM": "前往[format][color:location]活动起点[/format]",
"MSN_PRE_CALL_OBJ_MMK02": "前往[format][color:location]活动起点[/format]",
"MISSION_NAME_M03": "我们得搞点枪",
"MM04_OBJ_GOTO_TM": "前往[format][color:location]活动起点[/format]",
"MM03_FAIL_PIERCE_DIED": "皮尔斯死了！",
"M23_TRIGGER_AUTO_DESTRUCT": "启动自毁程序",
"M23_OBJ_KILL_BRIDGE_GUARDS": "击杀[format][color:kill]舰桥守卫[/format]",
"M22_FAILURE_OLEG_ABANDONED": "奥列格被抛弃了！\n圣徒必须团结一致！",
"MM01_START_GA": "开始天使护卫",
"M03_OBJ_HOLD_YOUR_POSITION": "守住你的[format][color:defend]阵地[/format]",
"MM_K_03_obj_goto_mh": "前往[format][color:location]活动起点[/format]",
"MISSION_NAME_M06": "比利时难题",
"M22_OI_SHAUNDI_TITLE_TEXT": "前往雕像",
"MISSION_NAME_MM_K_01": "赛博烈焰",
"M19_OBJ_GO_TO_VIOLA": "前往[format][color:location]薇奥拉[/format]",
"M18_OBJ_SEARCH_FOR_GUN": "搜索[format][color:use]武器箱[/format]",
"M03_USE_TRIGGER_SATELLITE_WEAPON": "使用卫星武器。",
"M23_OBJ_FLY_TO_SIDE_DECK": "飞往[format][color:location]侧甲板[/format]",
"M21_OBJ_PROTECT_ANGEL": "保护[format][color:defend]安吉尔[/format]",
"m20_failure_rc_too_late": "你遥控载具太磨蹭了！",
"MSN_PRE_CALL_OBJ_SH02": "与[format][color:location]齐莫斯[/format]碰头",
"MSN_PRE_CALL_OBJ_M15": "前往[format][color:location]金齐的藏身处[/format]",
"MISSION_NAME_MM_K_05": "电话飞客",
"M16_TXT_ADV_SC_01_CH1": "打开门",
"MSN_PRE_CALL_OBJ_MMP06": "前往[format][color:location]断木棍酒吧[/format]",
"MISSION_NAME_M08": "特洛伊妓女们",
"SH03_TURN_OFF_ROUTERS": "[format][color:use]路由器[/format]已关闭：",
"M24_HELP_HOMIE": "帮助你的[format][color:use]兄弟[/format]",
"SH03_CALL_CHOPPA": "!!金齐：我喊个朋友来空中支援",
"sh01_failure_pierce_died": "皮尔斯死了！",
"MSN_PRE_CALL_OBJ_MMK03": "前往[format][color:location]活动起点[/format]",
"MISSION_NAME_M02": "我自由了——自由坠落",
"MM03_NAG_FP": "你正离开[format][color:kill]交火点！[/format]",
"SH02_OBJ_CLEAN_HOUSE": "清除所有[format][color:kill]晨星帮[/format]",
"M23_USE_PLANT_BOMB_TRIGGER": "安放炸弹",
"M21_OBJ_GO_TO_ANGEL": "查看[format][color:location]安吉尔[/format]",
"M20_OBJ_RC_THE_CAR": "遥控[format][color:use]摔角手的车[/format]",
"MISSION_NAME_M22": "三方混战",
"MM03_OBJ_ACQUIRE_COLLECTIBLE": "获取[format][color:location]充气娃娃[/format]",
"SH03_MSG_JUMP": "跳伞",
"SH03_KINZIE_DIED": "金齐死了！",
"M20_OBJ_STAY_CLOSE": "紧贴[format][color:location]载具[/format]",
"M20_OBJ_GET_IN_ANGEL_HELI": "登上[format][color:location]安吉尔的直升机[/format]",
"MISSION_CHECKPOINT_ALERT": "检查点已抵达",
"MISSION_NAME_MM_P_05": "元气博士",
"SH01_OBJ_MEET_PIERCE": "前往[format][color:location]火药[/format]",
"M22_OBJ_KILL_KILLBANE": "击杀[format][color:kill]杀霸[/format]",
"M16_TXT_ADV_SC_02": "你小心翼翼地推开门往前走，脚下却踩到一块松动的石板。\n\n你摔倒了，摔断了脖子。\n\n你死了。\n\n感谢游玩《龙与泪：螺旋黑暗三部曲》第一部\n\n",
"MSN_PRE_CALL_OBJ_M11": "前往[format][color:location]圣徒总部[/format]",
"m17_failure_pierce_died": "皮尔斯死了！",
"SH01_OBJ_CLEAN_HOUSE": "击杀[format][color:kill]守卫[/format]",
"m20_failure_rc_heli_destroyed": "诱饵直升机被击毁！",
"MSN_PROTO_SELECT_SATCHEL_TITLE": "背包炸药",
"M23_OBJ_LAND_ON_DAEDALUS": "降落在[format][color:location]代达罗斯号[/format]",
"MSN_PROTO_CONFIRM_ACTION": "确认",
"m13_failure_viola_abandoned": "薇奥拉被抛弃了！\n圣徒必须团结一致！",
"M12_OBJ_STEAL_A_VEHICLE": "偷一台[format][color:use]载具[/format]",
"MSN_PRE_CALL_OBJ_MMP02": "与[format][color:location]皮尔斯[/format]碰头",
"MM03_OBJ_PURCHASE_PROPERTY": "购买[format][color:location]庄园[/format]",
"M23_OBJ_DESTROY_DEFENSES": "摧毁[format][color:kill]地面防御[/format]",
"M20_OBJ_USE_RAMP": "冲上[format][color:use]斜坡[/format]",
"M16_TXT_ADV_SC_07_CH2": "拔剑",
"MISSION_NAME_M09": "妓女船",
"SH03_FAIL_CHAIR": "迪克帮把椅子毁了！",
"M24_OBJ_DISABLE_SECURITY_NETWORK": "关闭[format][color:use]力场[/format]",
"M19_OBJ_OPEN_DOOR": "打开[format][color:use]门[/format]",
"MISSION_UNLOCALIZED_STRING": "警告！检测到未本地化字符串通过网络传输！",
"sh02_failure_zimos_died": "齐莫斯死了",
"M19_OBJ_GO_TO_ENTRANCE": "前往[format][color:location]隔离区[/format]",
"M16_OBJ_DEBUG_ERROR": "调试[format][color:kill]错误界面[/format]",
"M23_OBJ_GET_HELICOPTER": "搞一架[format][color:location]直升机[/format]",
"M13_OBJ_GOTO_ELEVATOR": "前往一部[format][color:location]电梯[/format]",
"MSN_PRE_CALL_OBJ_SH03": "前往[format][color:location]金齐处[/format]",
"MSN_PRE_CALL_OBJ_M14": "前往[format][color:location]笑面杰克的店[/format]",
"MISSION_NAME_MM_K_04": "武直突击",
"M20_OBJ_GO_TO_BOAT": "找到[format][color:location]摔角手的船[/format]",
"MISSION_COOP_SKIP_PROMPT": "跳过",
"M19_OBJ_KILL_ZOMBIES": "击杀[format][color:red]丧尸[/format]",
"M16_TXT_ADV_SC_07": "你压根不会魔法。\n\n你想做什么？\n\n",
"sh02_failure_abandon_zimos": "齐莫斯被抛弃了！\n圣徒必须团结一致！",
"M16_TXT_ADV_SC_06_CH1": "继续前行",
"M16_OBJ_SURVIVE_ONSLAUGHT": "挺过猛攻",
"MISSION_PARTNER_REPSECT": "%ls 的声望还不够",
"M20_OBJ_KILL_THE_LAST_WRESTLER": "干掉最后一个[format][color:kill]摔角手[/format]",
"m19_failure_rimjobs_timer": "没能及时赶到边缘工坊！",
"MISSION_NAME_M07": "重返钢埠",
"m22_failure_oleg_died": "奥列格死了！",
"MM06_OBJ_MEET_PIERCE": "在[format][color:location]笑面杰克的店[/format]与皮尔斯碰头",
"M24_HACK_TERMINAL": "入侵终端",
"m14_failure_heli_destroyed": "你的直升机被击毁了！",
"MSN_PRE_CALL_OBJ_M17": "前往[format][color:location]意象工坊[/format]",
"MISSION_NAME_MM_M_16_5": "斯蒂尔沃特蓝调",
"M16_TXT_ADV_SC_01_CH3": "打个盹",
"MSN_PRE_CALL_OBJ_MMP04": "前往[format][color:location]活动起点[/format]",
"MM_K_02_obj_goto_ga": "前往[format][color:location]活动起点[/format]",
"M20_OBJ_WAIT_FOR_ENTER": "等[format][color:use]摔角手[/format]上车",
"M18_OBJ_KILL_THE_GUNNER": "击杀[format][color:kill]坦克炮手[/format]",
"M10_OBJ_KILL_STAG_ON_ROOFS": "击杀[format][color:kill]STAG 敌军[/format]",
"M24_OBJ_GOTO_KILLBANE_LAIR": "前往[format][color:location]杀霸的老巢[/format]",
"M19_OBJ_PROTECT_VIOLA": "保护[format][color:defend]薇奥拉[/format]",
"MSN_PRE_CALL_OBJ_MMK05": "前往[format][color:location]金齐的藏身处[/format]",
"MSG_PLAY_SN": "开始拐人救美",
"MISSION_NAME_M04": "钢埠我来了",
"M24_PLANT_CHARGE": "安放炸药",
"M20_OBJ_RC_THE_BOAT": "遥控[format][color:use]摔角手的船[/format]",
"MSN_PRE_CALL_OBJ_M19": "与[format][color:location]市长[/format]碰头",
"MM_A_02_obj_goto_tb": "前往[format][color:location]活动起点[/format]",
"MISSION_NAME_MM_P_03": "接管城市",
"m16_failure_tank_destroyed": "哈哈，你的坦克被爆了！",
"M16_TXT_ADV_SC_04": "这里没有暗门。\n\n你想做什么？\n\n",
"m13_failure_viola_died": "薇奥拉死了！",
"MM_Z_01_obj_goto_sn": "前往[format][color:location]活动起点[/format]",
"MISSION_NAME_M24": "太空匪帮",
"MISSION_NAME_M21": "第三十一届谋杀乱斗",
"SH01_OBJ_ENTER_WAREHOUSE": "进入[format][color:location]仓库[/format]",
"m22_failure_pierce_abandoned": "皮尔斯被抛弃了！\n圣徒必须团结一致！",
"M18_OBJ_GET_TO_COCKPIT": "打开[format][color:use]舱门[/format]",
"MISSION_NAME_MM_P_06": "才刚刚开始",
"M23_OBJ_DESTROY_TANKS": "摧毁守护登陆区的[format][color:kill]坦克[/format]",
"M21_FAILURE_ANGEL_DIED": "安吉尔死了！",
"M16_TXT_ADV_SC_01": "你个子不够大，钻不过那个洞。\n\n你想做什么？\n\n",
"DANGER__UNLOCALIZED_STRING_OVER_NETWORK": "危险！未本地化字符串通过网络传输！",
"MISSION_NAME_M01": "当完美劫案搞砸时",
"MSN_OBJ_PRE_PHONE_CALL": "前往[format][color:location]任务起点[/format]",
"MSG_PLAY_ES": "开始护花使者",
"MM03_OBJ_MEET_PIERCE": "在[format][color:location]待定店铺[/format]与皮尔斯碰头",
"MM01_OBJ_GOTO_GA": "前往[format][color:location]活动起点[/format]",
"M20_OBJ_CRASH_THE_HELICOPTER": "撞向[format][color:kill]直升机[/format]",
"M20_OBJ_GO_TO_GAS_STATION": "赶到[format][color:location]加油站[/format]",
"MISSIONS_CURRENT": "当前任务",
"MSN_PRE_CALL_OBJ_MMP01": "前往[format][color:location]圣徒总部[/format]",
"MM01_OBJ_DROP_OFF": "把皮尔斯送到[format][color:location]银行[/format]",
"M20_OBJ_RC_THE_HELICOPTER": "遥控[format][color:use]直升机[/format]",
"MSN_PRE_CALL_OBJ_M12": "前往[format][color:location]漫画店[/format]",
"MSG_PLAY_HA": "开始武直突击",
"MISSION_NAME_MM_K_02": "天使护卫",
"SH01_OBJ_MANAGER_OFFICE": "前往[format][color:location]经理办公室[/format]",
"m13_failure_pierce_died": "皮尔斯死了！",
"MSN_PRE_CALL_OBJ_M18": "前往[format][color:location]机场[/format]",
"MM_K_04_obj_goto_ha": "前往[format][color:location]活动起点[/format]",
"MISSION_NAME_MM_P_02": "黑货押运",
"SH04_OBJ_DESTROY_LUCHADORES": "击杀残余的[format][color:kill]摔角手[/format]",
"SH03_MSG_ROUTERS_USE": "关闭[format][color:use]路由器[/format]",
"SH03_OBJ_ENTER_HELI": "登上[format][color:location]直升机[/format]",
"SH02_OBJ_KILL_BRUTE": "击杀[format][color:kill]壮汉[/format]",
"SH02_OBJ_OVERRIDE_BUTTON": "解除[format][color:use]安保系统[/format]",
"SH04_DAMAGE": "砸烂老虎机",
"sh01_failure_shaundi_died": "肖迪死了！",
"MSN_PROTO_COOP_WAIT_ACTION": "请稍候",
"MISSION_PARTNER_BUSY": "%ls 正忙",
"MSN_PRE_CALL_OBJ_MMK04": "前往[format][color:location]活动起点[/format]",
"MISSION_NAME_M05": "派对时刻",
"SH04_OBJ_MGR": "审问[format][color:use]经理[/format]",
"MSN_PRE_CALL_OBJ_MMP05": "前往[format][color:location]活动起点[/format]",
"SH03_START_MESSAGE": "前往[format][color:location]核电站[/format]",
"M19_OBJ_GO_TO_RIMJOBS": "前往[format][color:location]边缘工坊[/format]",
"M16_OBJ_MOVE_THROUGH_DATA": "穿越数据",
"MISSION_PARTNER_CONNECTED": "合作玩家已连接",
"SH04_OBJ_BRUTES": "击杀[format][color:kill]壮汉[/format]",
"M21_USE_TEXT_LEAVE_RING_SIDE": "离开擂台边",
"M20_OBJ_RC_A_TANK": "遥控一台[format][color:use]STAG 坦克[/format]",
"MSN_PRE_CALL_OBJ_SH01": "前往[format][color:location]火药[/format]",
"MSN_PRE_CALL_OBJ_M16": "前往[format][color:location]金齐的藏身处[/format]",
"MISSION_NAME_MM_K_06": "宿醉清晨",
"SH02_OBJ_COLLECTION_ROOM": "前往[format][color:location]收藏室[/format]",
"M19_OBJ_RESCUE_VIOLA": "前往[format][color:location]薇奥拉[/format]",
"MSN_PRE_CALL_OBJ_SH04": "前往[format][color:location]三秒压制[/format]",
"MSN_PRE_CALL_OBJ_M13": "前往[format][color:location]圣徒总部[/format]",
"MISSION_NAME_MM_K_03": "大破坏",
"M19_OBJ_NEUTRALIZE_CONTAINERS": "[format][color:red]浸没[/format]集装箱 ",
"m17_failure_homie_abandoned": "兄弟被抛弃了！\n圣徒必须团结一致！",
"MISSION_COOP_REPLAY_MSG": "重玩合作任务？",
"m17_failure_follow": "掩护赛勒斯的行动暴露了！\n 别轻举妄动引人注目。",
"M15_OBJ_ESCAPE_THE_GARAGE": "[format][color:location]逃出[/format]车库",
"M21_HELP_TEXT_WATING_TO_TAG": "等待搭档将你标记为可登场。",
"MM_K_02_KINZIE_ABANDONDED": "金齐被抛弃了！\n圣徒必须团结一致！",
"M23_OBJ_KILL_CYRUS": "击杀[format][color:kill]赛勒斯[/format]",
"MSN_PRE_CALL_OBJ_MMK01": "前往[format][color:location]金齐的藏身处[/format]",
"M23_OBJ_CLEAR_MIDSECTION": "击杀[format][color:kill]STAG[/format]",
"m19_failure_container_destroyed": "集装箱被毁！\n 只能用音爆让集装箱保持完好。",
"M16_OBJ_KILL_ALL_ENEMIES": "击杀所有[format][color:kill]迪克帮[/format]",
"M12_OBJ_GET_TO_THE_GARAGE": "赶到[format][color:location]车库[/format]",
"M23_OBJ_INITIATE_SELF_DESTRUCT": "使用[format][color:use]控制台[/format]",
"M21_OBJ_FIGHT_KILLBANE": "对决[format][color:kill]杀霸[/format]",
"MISSION_NAME_M20": "遥控良机",
"SH02_OBJ_MEET_ZIMOS": "与[format][color:location]齐莫斯[/format]碰头",
"M22_OI_SHAUNDI_BODY_TEXT": "救下肖迪，但杀霸会逃走",
"M20_OBJ_GO_TO_HELICOPTER": "前往[format][color:location]直升机[/format]",
"MSN_PROTO_SELECT_TITLE": "S.T.A.G. 原型机",
"M15_OBJ_CLEAR_THE_LOBBY": "肃清[format][color:kill]大厅[/format]",
"MISSION_NAME_MM_P_07": "酒吧巡游",
"M20_OBJ_RUN_OVER_PEOPLE": "碾过[format][color:kill]行人[/format]",
"M18_HELP_CLEARING_DEBRIS": "[format][color:use]音爆[/format]武器是清走瓦砾和挡路杂物的最佳工具",
"M16_TXT_ADV_SC_00": "你醒来时发现自己躺在冰冷的石板上。起身时你注意到这间小屋由两支火把照亮。北面是一扇门，南面是墙上一个洞。\n\n你要怎么做？\n\n",
"M13_OBJ_GOTO_PR_CENTER": "前往[format][color:location]公关中心[/format]",
"MSN_PRE_CALL_OBJ_MMZ02": "前往[format][color:location]活动起点[/format]",
"MSN_PRE_CALL_OBJ_M20": "前往[format][color:location]断木棍酒吧[/format]",
"MM_A_03_obj_goto_es": "前往[format][color:location]活动起点[/format]",
"MM_A_04_obj_meet_angel": "前往[format][color:location]安吉尔的赌场[/format]",
"MISSION_NAME_MM_Z_03": "护花使者",
"M16_TXT_ADV_SC_12_CH2": "退出游戏",
"SH01_OBJ_KILL_BRUTE": "击杀[format][color:kill]壮汉[/format]",
"m20_failure_ctc_destroyed": "碾死的行人不够多！",
"M13_PROMPT_THROW_JOSH_TO_SHAUNDI": "把乔什交给肖迪",
"MM_K_01_obj_goto_tb": "前往[format][color:location]活动起点[/format]",
"SH03_OBJ_CHOPPA": "前往[format][color:location]降落点[/format]",
"SH04_OBJ_DESTROY_STATUES": "[format][color:kill]雕像[/format]已摧毁",
"SH02_OBJ_FREE_HOS": "解救妓女们",
"MSN_PRE_CALL_OBJ_MMA03": "前往[format][color:location]活动起点[/format]",
"SH02_OBJ_GARAGE": "前往[format][color:location]车库[/format]",
"MISSION_NAME_M13": "STAG 派对",
"M23_OBJ_GO_TO_DAEDALUS": "前往[format][color:location]代达罗斯号[/format]",
"M20_OBJ_GO_TO_GYM": "前往[format][color:location]健身房[/format]",
"m17_failure_escape": "你死了！\n 快移动以躲开爆炸。",
"M16_TXT_ADV_SC_04_CH2": "跑回去拿另一支火把",
"MISSION_NAME_M16": "HTTP://迪克帮.去死",
"MM01_PIERCE_ABANDONDED": "皮尔斯被抛弃了！\n圣徒必须团结一致！",
"MSG_PLAY_TB": "开始烈焰开路",
"MSG_PLAY_DT": "开始黑货押运",
"MISSION_NAME_MM_A_02": "烈焰开路",
"SH03_OBJ_KILL_TARGETS": "击杀残余的[format][color:kill]迪克帮守卫[/format]",
"M22_OBJ_KILLBANE_OR_SHAUNDI": "[format][color:red]除掉杀霸[/format] 或 [format][color:defend]救下肖迪[/format]",
"MM_K_05_obj_meet_kinzie": "前往[format][color:location]笑面杰克的店[/format]",
"M24_OBJ_DEFEAT_KILLBANE": "击碎[format][color:kill]熔岩水晶[/format]",
"MSN_PRE_CALL_OBJ_M05": "前往[format][color:location]机场[/format]",
"MSG_PLAY_IF": "开始碰瓷索赔",
"SH04_OBJ_FIND_THE_VAULT": "找到[format][color:location]金库[/format]",
"MM_K_02_obj_goto_safe": "!!前往[format][color:location]安全屋[/format]",
"m23_failure_cyrus_escaped": "赛勒斯逃走了！\n 在他死前别离开代达罗斯号。",
"M16_TXT_ADV_SC_05_CH1": "重新开始",
"MISSION_COOP_TITLE": "合作任务",
"MM01_PIERCE_DIED": "皮尔斯死了！",
"MSN_PROTO_CONFIRM_DESC": "你已选择 {0} 和 {1}。确认进行原型选择？",
"MSG_PLAY_MH": "开始大破坏",
"MM_K_06_obj_meet_kinzie": "前往[format][color:location]金齐的藏身处[/format]",
"MISSION_NAME_M18": "空降钢埠",
"MM03_FAIL_FLASHPOINT": "帮派行动失败！\n 紧贴帮派行动，否则他们会逃走。",
"MSN_PRE_CALL_OBJ_MMA02": "前往[format][color:location]活动起点[/format]",
"SH01_OBJ_SHOWROOM": "前往[format][color:location]展厅[/format]",
"m13_failure_failed_to_escape": "未能及时逃出圣徒总部",
"m11_fail_convoy": "车队被摧毁了。",
"MISSION_NAME_M12": "夜刃的归来",
"sh04_failure_angel_died": "安吉尔死了！",
"sh01_failure_abandon_shaundi": "肖迪被抛弃了！\n圣徒必须团结一致！",
"M23_OBJ_GO_TO_REAR_DECK": "前往[format][color:location]后甲板[/format]",
"M18_OBJ_SURVIVE": "击杀[format][color:kill]STAG 袭击者[/format]",
"MSN_PROTO_COOP_WAIT_DESC": "房主正在选择要建造的原型机。",
"MSN_PROTO_SELECT_TANK_DESC": "STAG 坦克的升级型号，伤害更高、装甲更厚、杀得更狠。",
"M16_TXT_ADV_SC_12": "你赢了。\n\n感谢游玩《龙与泪：螺旋黑暗三部曲》第一部\n\n",
"MISSION_PARTNER_DECLINED": "%s 拒绝了",
"MM_A_05_obj_meet_angel": "前往[format][color:location]安吉尔的赌场[/format]",
"MISSION_NAME_SH04": "三秒压制暴打",
"MM_A_01_obj_meet_angel": "在[format][color:location]安吉尔的赌场[/format]与安吉尔碰头",
"MISSION_NAME_MM_Z_02": "妓女运输",
"MM03_OBJ_GOTO_FP": "前往[format][color:location]帮派行动[/format]",
"SH04_FAILURE_ANGEL_ABANDONDED": "安吉尔被抛弃了！\n圣徒必须团结一致！",
"SH03_KINZIE_ABANDONDED": "你抛弃了金齐！",
"M20_OBJ_GO_TO_HARBOR": "前往[format][color:location]港口[/format]",
"M03_OBJ_SET_GPS": "设定[format][color:location]GPS[/format]",
"MISSION_PARTNER_DISCONNECTED": "合作玩家已断开",
"MSN_PRE_CALL_OBJ_MMZ03": "前往[format][color:location]活动起点[/format]",
"MSN_PRE_CALL_OBJ_M21": "前往[format][color:location]谋杀乱斗[/format]",
"MSG_PLAY_TM": "开始坦克大破坏",
"M16_OBJ_SURVIVE_TEXT": "挺过这场[format][color:defend]文字冒险[/format]",
"MISSION_NAME_M19": "丧尸来袭",
"M20_OBJ_ALIGN_TO_BOATS": "悬停在[format][color:location]船只[/format]附近",
"MSN_PRE_CALL_OBJ_M04": "与[format][color:location]皮尔斯[/format]碰头",
"m14_failure_van_destroyed": "转播车被毁！\n 靠近并用 {ANALOG_RS_IMG} 锁定转播车。",
"M12_OBJ_UNEQUIP_YOUR_WEAPON": "卸下你的武器",
"M21_USE_TEXT_TAG_OUT": "把搭档标记登场",
"M11_OBJ_HIJACK_VTOL": "劫持一架[format][color:use]VTOL[/format]",
"M09_TITLE": "妓女船",
"MISSION_NAME_MM_A_03": "猛虎之眼",
"MISSION_NAME_SH01": "杀进火药房",
"MM03_OBJ_GOTO_PHOTO_OP": "前往[format][color:location]拍照点[/format]",
"M16_TXT_ADV_SC_02_CH1": "重新开始",
"m09_failure_girls_truck": "卡车被毁！",
"MSG_PLAY_RM": "开始元气博士",
"MISSION_NAME_M17": "我是赛勒斯·坦普尔",
"MM03_OBJ_PURCHASE_STORE": "购买[format][color:location]队友火力[/format]",
"m20_failure_angel_heli_destroyed": "直升机被毁！",
"M23_OBJ_ESCAPE": "逃离[format][color:location]代达罗斯号[/format]",
"M18_OBJ_ESCAPE_IN_TANK": "[format][color:location]逃离[/format]飞机",
"MM03_FAIL_PIERCE_ABANDONDED": "皮尔斯被抛弃了！\n圣徒必须团结一致！",
"M23_OBJ_GO_TO_BRIDGE": "赶到[format][color:location]舰桥[/format]",
"M22_OBJ_GOTO_ARMORY": "前往[format][color:location]军械库[/format]",
"M20_FAILURE_LOST_SIGNAL": "信号丢失！",
"MSG_PLAY_GA": "开始天使护卫",
"MM_Z_03_obj_goto_es": "前往[format][color:location]活动起点[/format]",
"M17_OBJ_ESCAPE_SHIP": "[format][color:location]逃离[/format]温泉关号",
"M09_OBJ_TO_SAINTS_HQ": "开车前往[format][color:location]圣徒总部[/format]",
"MM07_OBJ_MEET_PIERCE": "在[format][color:location]笑面杰克的店[/format]与皮尔斯碰头",
"SH04_GET_BACK_TO_THE_CASINO": "回到[format][color:location]赌场[/format]",
"M23_OBJ_DESTROY_GUNS": "摧毁[format][color:kill]火炮[/format]",
"MISSION_NAME_M14": "直播！与杀霸面对面",
"m14_failure_heli_unreachable": "直升机遥不可及！",
"M14_OBJ_ENTER_BUILDING": "进入[format][color:location]大楼[/format]",
"MSN_PRE_CALL_OBJ_MMA04": "前往[format][color:location]安吉尔的赌场[/format]",
"m22_failure_killbane_escaped": "杀霸逃走了！\n 用火箭筒拦住他。",
"M17_OBJ_FOLLOW_KIA": "跟踪[format][color:location]琪亚[/format]",
"MISSION_NAME_SH02": "皮条客起，妓女倒",
"M21_OBJ_DEFEND_THE_RING": "守住[format][color:defend]擂台[/format]",
"MSN_PROTO_SELECT_BIKE_TITLE": "S.T.A.G 摩托",
"MSN_PRE_CALL_OBJ_M09": "前往[format][color:location]码头[/format]",
"MM_Z_04_obj_meet_zimos": "前往[format][color:location]齐莫斯的据点[/format]",
"SH03_OBJ_SURVIVE": "等待直升机",
"SH01_TITLE": "火药",
"M22_OBJ_GOTO_BATTLEZONE": "前往一处[format][color:location]战斗地点[/format]",
"MSN_PROTO_SELECT_TANK_TITLE": "S.T.A.G. 坦克 v2",
"M16_TXT_ADV_SC_11": "你伸手抚摸独角兽的鬃毛。独角兽轻轻嘶鸣，用头蹭了蹭你的脑袋。它的角戳到你的眼睛，你疼得缩了回去。就在这时，你的脚绊到了一块松动的石板。\n\n你摔倒了，摔断了脖子。\n\n你死了。\n\n感谢游玩《龙与泪：螺旋黑暗三部曲》第一部\n\n",
"MM_K_02_KINZIE_DIED": "金齐死了！",
"MISSION_NAME_MM_A_05": "没有尝试二字",
"M22_OI_KILLBANE_TITLE_TEXT": "前往机场",
"m15_failure_pierce_died": "皮尔斯死了！",
"M14_OBJ_GET_IN_HELI": "登上[format][color:location]直升机[/format]",
"MSN_PRE_CALL_OBJ_MMA01": "前往[format][color:location]安吉尔的赌场[/format]",
"M22_OBJ_REMOVE_BOMBS": "[format][color:use]炸弹[/format]已拆除",
"m19_failure_suko_abandoned": "薇奥拉被抛弃了！\n圣徒必须团结一致！",
"MISSION_NAME_M11": "车队诱饵",
"MM01_OBJ_MEET_PIERCE": "在[format][color:location]顶层公寓[/format]与皮尔斯碰头",
"M20_OBJ_ALIGN_TO_TANKS": "悬停在[format][color:location]坦克[/format]附近",
"M22_OBJ_CLEAR_BATTLEZONE": "肃清[format][color:kill]区域[/format]",
"M19_OBJ_CHOICE": "[format][color:location]逃离[/format] 或 [format][color:red]浸没[/format]卡车",
"M15_MSG_USE_ALT_FIRE": "{TANK_FIRE_PRIMARY_IMG} 开火：机枪",
"MSN_PRE_CALL_OBJ_M22": "前往[format][color:location]圣徒总部[/format]",
"MM_A_01_obj_goto_if": "前往[format][color:location]活动起点[/format]",
"M16_TXT_ADV_SC_03_CH1": "继续前行",
"MISSION_NAME_MM_Z_01": "拐人救美",
"MM02_OBJ_MEET_PIERCE": "前往[format][color:location]活动起点[/format]",
"M14_OBJ_CATCH_KILLBANE": "抓住[format][color:location]杀霸[/format]",
"MISSION_NAME_MM_A_01": "碰瓷索赔",
"MISSION_NAME_SH03": "掐断一切下载",
"SH03_OBJ_PARA": "伞降进入[format][color:location]核电站[/format]",
"M20_OBJ_CRASH_THE_CAR": "撞向[format][color:location]油泵[/format]",
"MSN_PRE_CALL_OBJ_M08": "前往[format][color:location]派对[/format]",
"MM_Z_01_obj_meet_zimos": "前往[format][color:location]齐莫斯的据点[/format]",
"SH02_OBJ_BASEMENT": "前往[format][color:location]安保中心[/format]",
"SH01_OBJ_USE_COMPUTER": "[format][color:use]入侵中[/format]",
"m22_failure_pierce_died": "皮尔斯死了！",
"MISSION_NAME_M15": "学习电脑",
"SH01_OBJ_UPSTAIRS": "设法前往[format][color:location]楼上[/format]",
"M14_OBJ_CLEAR_DECKERS": "肃清[format][color:kill]迪克帮[/format]",
"M14_OBJ_GO_TO_VAN": "靠近[format][color:location]转播车[/format]",
"CHECKPOINT_PASSED": "检查点已抵达  ",
"MSN_TSS_START": "开始第三街圣徒任务",
"M19_OBJ_GET_IN_TRUCK": "开走[format][color:use]化学卡车[/format]",
"MSN_PRE_CALL_OBJ_MMZ04": "前往[format][color:location]齐莫斯的据点[/format]",
"M24_OBJ_PLANT_CHARGES": "安放[format][color:use]炸药包[/format]",
"M18_BAIL_FROM_TANK": "弃坦克逃生",
"MM03_OBJ_GOTO_PROPERTY": "前往[format][color:location]庄园[/format]",
"M08_OBJ_KILL_SNIPERS": "击杀[format][color:kill]狙击手[/format]",
"MSN_PRE_CALL_OBJ_M06": "前往[format][color:location]圣徒总部[/format]",
"MM_Z_05_obj_meet_zimos": "前往[format][color:location]齐莫斯的据点[/format]",
"M17_OBJ_BOARD_SHIP": "降落在[format][color:location]温泉关号[/format]",
"M16_TXT_ADV_SC_09_CH2": "摸摸独角兽",
"MISSION_NAME_MM_Z_05": "嗨翻时刻",
"SH04_MSG_GRAB": "审问[format][color:use]经理[/format]",
"M23_OBJ_PLANT_BOMB": "安放[format][color:use]炸弹[/format]",
"M16_TXT_ADV_SC_12_CH1": "再玩一次",
"M10_OBJ_ESCAPE_TO_SAINTS_HQ": "逃往[format][color:location]圣徒总部[/format]",
"m09_failure_zimos_died": "齐莫斯死了！",
"M13_OBJ_THROW_JOSH": "把[format][color:use]乔什[/format]交给[format][color:purple]肖迪[/format] 或 [format][color:blue]赛勒斯[/format]",
"M07_ACTION_UNTIE_KINZIE": "解开金齐",
"MM03_OBJ_COMPLETE_PHOTO_OP": "完成[format][color:location]拍照点[/format]",
"SH03_OBJ_GO_DOWNSTAIRS": "前往[format][color:location]楼下[/format]",
"m15_failure_truck_deckers_hq": "迪克帮抢走了超级计算机！",
"MSN_PRE_CALL_OBJ_MMZ01": "前往[format][color:location]齐莫斯的据点[/format]",
"MSN_PRE_CALL_OBJ_M23": "前往[format][color:location]断木棍酒吧[/format]",
"m22_failure_shaundi_died": "肖迪死了！\n 用手榴弹把琪亚和肖迪分开，再轰掉琪亚。",
"M14_OBJ_GO_TO_TOWER": "前往[format][color:location]广播塔[/format]",
"MISSION_COOP_START_MSG": "开始合作任务？",
"m20_failure_premature_hijackulation": "你跳得太早了！",
"M20_OBJ_CRASH_THE_BOAT": "撞毁[format][color:kill]船只[/format]",
"M17_OBJ_DESTROY_REACTOR": "摧毁[format][color:kill]控制台[/format]",
"M16_TXT_ADV_SC_08_CH1": "重新开始",
"MISSION_COOP_REPLAY_PROMPT": "重玩",
"MISSION_NAME_M10": "帮派火并",
"MM03_OBJ_CLEAR_NOTORIETY": "[format][color:location]躲藏[/format]以降低恶名",
"M16_TXT_ADV_SC_04_CH1": "继续前行",
"M22_OBJ_KILL_KIA": "击杀[format][color:kill]琪亚[/format]",
"M22_OBJ_HELP_ANGEL": "帮助[format][color:defend]安吉尔[/format]",
"M16_TXT_ADV_SC_10": "这看起来像一头独角兽。\n\n你想做什么？\n\n",
"M16_OBJ_KILL_MATT": "摧毁[format][color:kill]马特·米勒的化身[/format]",
"MISSION_NAME_MM_A_04": "直面恐惧",
"MM03_OBJ_GOTO_COLLECTIBLE": "找到[format][color:location]充气娃娃[/format]",
"sh01_failure_abandon_pierce": "皮尔斯被抛弃了！\n圣徒必须团结一致！",
}

missing=[]
lines=open(src,encoding='utf-8').read().split('\n')
out_lines=[]
for raw in lines:
    if raw=='' :
        continue
    m=re.match(r'^"([^"]+)":\s*"(.*)"\s*$', raw)
    if not m:
        # try without trailing check
        m2=re.match(r'^"([^"]+)":', raw)
        raise SystemExit("UNPARSED LINE: "+raw)
    key=m.group(1)
    if key not in T:
        missing.append(key)
        continue
    out_lines.append('"%s": "%s"' % (key, T[key]))

if missing:
    raise SystemExit("MISSING KEYS: "+", ".join(missing))

open(out,'w',encoding='utf-8').write('\n'.join(out_lines)+'\n')
print("written", len(out_lines), "lines to", out)
