# -*- coding: utf-8 -*-
# 接管重译 menu：读 original/menu_us.txt 抽 KEY，逐条重写中文。
import re, os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCH = os.path.join(BASE, "schinese", "menu_us.txt")
ORG = os.path.join(BASE, "original", "menu_us.txt")

src = open(ORG, encoding="utf-8").read().replace("\r\n", "\n")
od = dict(re.findall(r'^\s*"([^"]+)":\s*"(.*)"\s*$', src, re.M))

T = {
 "INFO_UNLOCKABLES_STRONGHOLDS": "根据地",
 "CONTROL_CHANGE_TRACK": "切换曲目",
 "PLAYLIST_PREVIEW_TRACK": "试听",
 "MAP_RESPECT_BLANK_OF_BLANK": "声望：%d/%d",
 "INFO_UNLOCKABLES_DAMAGE": "伤害",
 "CONTROLS_STICK": "{ANALOG_LS_IMG} 加速/刹车",
 "CONTROLS_DESC_KICK": "踢击",
 "MENU_CONTROL_OPTIONS": "控制选项",
 "MAP_ICON_SNATCH": "拐人救美",
 "CONTROL_DESC_FOOT_COMPLIMENT": "赞美",
 "PAUSE_INFO_DRIVING_STUNTS": "驾驶特技",
 "CONTROLS_INVERT_ROTATION": "反转视角旋转",
 "CELL_OPTION_PHONEBOOK": "电话簿",
 "PAUSE_MAP_FILTER_LOCKED": "已锁定",
 "MENU_STYLE_DIALOG_CONTINUE": "继续",
 "MAINMENU_OPTIONS": "选项",
 "INFO_COLLECTIONS_CHOPSHOP": "拆车厂",
 "COMPLETION_UNLOCKED": "已解锁",
 "CELL_VEHICLE_DIALOG_NO_CASH_BODY": "你的现金不足，无法修理并取回这辆载具。",
 "ADD_BOOKMARK": "添加书签",
 "MENU_SEARCHING": "搜索中...",
 "COOP_SERVER_SAVEGAME_LOADING": "%ls 正在读取存档。\\n重新加入前，要先保存你的进度吗？",
 "MP3_CONFIRM_DELETE_LIST_TITLE": "删除播放列表",
 "COMPLETION_STRONGHOLD": "根据地",
 "CONTROLS_RESET_DEFUALT_CONFIRM1": "恢复默认设置？",
 "CONTROL_DESC_FOOT_MOVE": "移动",
 "PAUSE_MENU_COOP": "联机合作",
 "PHONE_OPTION_3": "拨号",
 "CONTROL_SCHEME_B": "方案 B",
 "CONTROL_DESC_VEH_RUDDER_RIGHT": "右转",
 "MENU_DISPLAY_MONITOR_ADJUSTMENT": "显示设置",
 "CELL_VEHICLE_DIALOG_NO_CASH_HEADER": "现金不足",
 "MENU_OPTIONS_QUIT_GAME": "退出游戏",
 "MENU_OPTIONS_GAMMA": "伽马",
 "INVALID_SAVE_TITLE": "无效存档",
 "COMPLETION_NEIGHBORHOODS_OWNED": "已占地盘",
 "DLT_CHALLENGE": "给我来点挑战",
 "CONTROL_DESC_PRESS": "按下",
 "COMPLETION_CASH": "现金",
 "COMMUNITY_EXISTING_USER_NAME_EXT": "请输入你的 THQ ID。",
 "HELP_TEXT_THROW_PUNCH": "按 {ATTACK_PRIMARY_IMG} 出拳",
 "DOWNLOADABLE_REMOVED_CANCEL": "退回主菜单",
 "AMMO_MAX_REACHED": "已满",
 "HASH_D7B70F8C": "正在加载 {0}%%%",
 "MENU_XBOX_LIVE_STARTUP": "启动时自动登录",
 "MAINMENU_NEW": "新游戏",
 "INFO_HELP": "帮助",
 "CRIB_CASH_INCOME": "城市每小时收入",
 "OPT_UPDATE_TITLE": "选项更新",
 "PAUSE_MENU_OF": "{0}/{1}",
 "OPT_UPDATE_DISCARD": "放弃",
 "CONTROL_DESC_VEH_CRUISE_CONTROL": "定速巡航",
 "COMMUNITY_AGE_FIELD": "出生日期",
 "MAP_ACTIVITY_HARD": "难度：困难",
 "SAVELOAD_DURING_MISSION_CONTINUE": "继续吗？",
 "CONTROLS_RESET_DEFAULT": "恢复默认设置",
 "MENU_AUDIO_MUSIC": "音乐",
 "CONTROL_DESC_FOOT_ACTION": "动作/进入载具",
 "CELL_OPTION_END": "挂断",
 "SAVELOAD_LOAD_ABORT": "不读取存档，继续游戏",
 "SAVELOAD_CORRUPT_DISPLAY_NAME": "损坏的存档",
 "PHONE_OPTION_2": "电话簿",
 "MENU_AUDIO_AMBIENCE": "环境音",
 "INFO_OBJECTIVES_TITLE": "目标",
 "CONTROL_SCHEME_C": "方案 C",
 "SAVELOAD_SAVE_GAME_CONFIRM_EXPOSITION": "确定要覆盖这份存档吗？\\n原有的所有进度都将被覆盖。",
 "CONTROL_DESC_VEH_HANDBRAKE": "漂移",
 "MENU_OPTIONS_TITLE": "选项",
 "COMPLETION_RETRY_STRONGHOLD": "重试根据地",
 "HELP_TEXT_SKYDIVE_STEER_CONTROL": "用 {ANALOG_RS_IMG} 左右转向",
 "CONTROL_DESC_VEH_LOOK_RIGHT": "向右看",
 "CONTROL_CHEAT_NO": "返回",
 "COMPLETION_COOP_DISCONNECT": "断开连接",
 "SAVELOAD_FAILED_TO_SAVE_PROFILE": "硬盘空间不足。\\n请删除一些存档腾出空间，或返回 XMB。",
 "INFO_COLLECTIONS_STUNT_JUMPS": "特技跳跃",
 "CONTROL_DESC_VEH_ACTION": "动作/离开载具",
 "DLT_DESC_HARDCORE": "你喜欢那种命悬一线的刺激感。",
 "CONTROL_DESC_CLICK": "按下",
 "COMPLETION_MISSION_COMPLETE": "{0} 已完成",
 "MENU_CONTROLS_INVERT_ROTATION": "反转视角旋转",
 "CONTROLS_SETUP_DRIVING_SCHEMES": "驾驶控制方案",
 "CONTROL_DESC_VEH_HELI_UP": "（直升机）上升",
 "HELP_TEXT_WIELDABLE_PROP": "按 {ATTACK_PRIMARY_IMG} 挥舞道具，或按 {ATTACK_SECONDARY_IMG} 扔出它",
 "MAP_SALE_PERCENT_OFF": "促销 -%d%%%%",
 "MAINMENU_START_DEMO": "试玩演示",
 "MAINMENU_MULTI": "多人游戏",
 "CONTROLS_SENSE_H": "水平灵敏度",
 "CONTROL_DESC_FOOT_CROUCH": "蹲下",
 "COMMUNITY_INVALID_PASSWORD_CHARACTERS": "密码只能由字母、数字和符号 -_.@ 组成",
 "HUMAN_TEAM_LUCHADORES": "摔跤手帮",
 "COOP_MENU_FRIENDLY_FIRE": "友军伤害",
 "DIALOG_PAUSE_DISCONNECT_PROMPT": "确定要断开连接吗？",
 "GAMER_PROFILE_REINSERT_TEXT": "与您的玩家档案关联的存储设备已被移除。",
 "CONTROLS_SETUP_VCAM_NEAR": "近景",
 "CONTROLS_SETUP_CROUCH_TOG": "蹲下切换",
 "INFO_ACTIVITIES_TITLE": "活动",
 "COMPLETION_COOP_WAITING": "正在等待 {0}",
 "COMPLETION_FAILED": "失败",
 "CACHING_PERCENT": "% 已完成",
 "AUTOSAVING": "保存中...",
 "SAVELOAD_LOAD_DEVICE_UNAVAILABLE_LINE2": "存储设备已不可用。",
 "MENU_RADIO": "电台",
 "Hidden": "已隐藏",
 "COMPLETION_EXIT_ACTIVITY_CONFIRMATION": "要退出当前活动吗？",
 "SAVELOAD_DEFAULT_NAME": "默认",
 "MENU_STYLE_DIALOG_HEADER": "风格提升",
 "CONTROL_DESC_VEH_PLANE_BRAKE_REV": "（飞机）刹车/倒车",
 "CONTROL_DESC_VEH_TOGGLE_CAM_2": "按住切换视角",
 "CRIB_NAME_DOCK": "罗迪尼船坞",
 "OPTIONS_MENU_DEFAULTS_DESC": "确定要将选项重置为默认值吗？",
 "SAVELOAD_NEW_SAVE_GAME": "新建存档",
 "MAP_RESPECT_BLANK": "声望：%d",
 "CONTROL_DESC_VEH_PLANE_ACCELERATE": "（飞机）加速",
 "CONTROL_DESC_CANCEL_ACT": "退出游戏模式",
 "INFO_COLLECTIONS_SECRET_AREAS": "隐藏区域",
 "CONTROL_DESC_FOOT_NXT_TRK": "下一曲（音频播放器）",
 "COOP_LOBBY_QUIT": "返回主菜单",
 "MENU_AUDIO_SPEAKERS": "扬声器",
 "HASH_A91AEAA3": "按下 [format][scale:0.5][color:full_bright][image:uhd_ui_xbox_ctrl-a][/format]",
 "CONTROLS_DESC_CHANGE_RADIO": "切换电台",
 "SAVELOAD_LOAD_DEVICE_UNAVAILABLE_LINE1": "读取失败：默认",
 "CHEAT_CATEGORY_WEAPONS": "武器",
 "SB_CAT_ASSASSINATION": "暗杀目标",
 "MENU_REFRESH_SYSLINK": "刷新",
 "PAUSE_MENU_QUIT_TEXT": "真的要退出吗？\\n（未保存的进度将会丢失。）",
 "INFO_DIVERSIONS_GAMES": "小游戏",
 "SAVELOAD_CONFIRM_QUERY": "继续？",
 "RADIO_STATION_GENRE_KRHYME": "嘻哈与说唱音乐",
 "DLT_DESC_CASUAL": "你喜欢按自己的节奏大杀四方。",
 "CONTROL_DESC_FOOT_QUICKTHROW": "投掷人盾",
 "INFO_UNLOCKABLES": "可解锁奖励",
 "INFO_OBJECTIVES": "目标",
 "COMPLETION_RESPECT": "声望",
 "OPTIONS_MENU_DEFAULTS_TITLE": "恢复默认设置？",
 "MENU_OPTIONS_WIRELESS": "无线",
 "MAP_ICON_SAVE": "存档点",
 "CONTROL_DESC_MP_FAST_WEAPON_SWITCH": "武器切换",
 "SAVELOAD_CANCEL_JOIN": "取消正在进行的加入",
 "PAUSE_OBJECTIVES_NONE": "暂无目标",
 "INFO_STATS": "统计",
 "HELP_TEXT_MELEE_LOCK": "空手时按住 {SHOULDER_CAMERA_IMG} 锁定单个目标",
 "CONTROL_DESC_FOOT_FINEAIM": "精确瞄准",
 "SAVELOAD_IMPORT_CORRUPT_ABORT": "返回角色自定义",
 "PHONE_OPTION_1": "兄弟",
 "MENU_CHECK_UPDATES_TITLE": "检查更新",
 "DOWNLOADABLE_REMOVED_CONFIRM_QUERY": "重新连接存储设备并继续",
 "MUSIC_STORE_DISCOUNT": "音乐商店 100%% 折扣",
 "PAUSE_MENU_QUIT_NO_SAVE_CONFIRM_TEXT": "不保存并退出。\\n \\n确定吗？",
 "SAVELOAD_LOAD_FAILED": "读取失败",
 "OPT_UPDATE_KEEP": "保留",
 "CELL_HEADER_DEACTIVATED": "已停用",
 "DISCONNECT_SCREEN_QUIT": "按 %s 退出",
 "CONTROL_DESC_SEC_ATTACK": "次要攻击",
 "ACHIEVE_NOW": "成就已解锁！  ",
 "INFO_ACTIVITIES": "活动",
 "CONTROL_DESC_MP_SCORE": "记分板",
 "CONTROL_DESC_FOOT_CLICK_CROUCH": "蹲下",
 "SAVELOAD_DURING_MISSION_ABORT": "不保存并继续",
 "SAVELOAD_DURING_ACTIVITY_ABORT": "不保存并继续",
 "MAP_PLAYER_CASH": "现金",
 "DLT_EXPERIENCED": "老手",
 "CONTROL_DESC_VEH_ACCELERATE": "加速",
 "COMPLETION_COMPLETE": "完成",
 "RADIO_STATION_GENRE_GEN_X": "现代摇滚音乐",
 "PAUSE_ACTIVITIES_NONE": "暂无可用活动",
 "GAMER_PROFILE_REINSERT_TITLE": "存储设备不可用",
 "VCUST_PERFORMANCE_WARNING": "无法同时装备液压悬挂和氮气加速。\\n仍要购买吗？",
 "SAVELOAD_IMPORT_DEVICE_UNAVAILABLE_FULL": "导入失败：默认\\n存储设备已不可用。",
 "SAVELOAD_DURING_MISSION_EXPOSITION": "当前任务中的进度将不会被保存！\\n要继续吗？",
 "HELP_TEXT_SKYDIVE_MOVE_CONTROL": "使用 {ANALOG_LS_IMG} 前后移动、左右平移",
 "COMMUNITY_ERROR_AGE_GATE": "您输入的年龄不符合限制要求。",
 "SAVELOAD_SAVE_FAILED": "保存失败",
 "MENU_CONTROLS_TITLE": "操作",
 "DLT_DESC_NORMAL": "你要的就是原汁原味的玩法。",
 "CONTROL_DESC_VEH_HELI_DOWN": "（直升机）下降",
 "SAVELOAD_LOAD_GAME": "读取存档",
 "MENU_AUDIO_MIC_NONE": "无麦克风",
 "GAME_CACHING": "正在缓存",
 "CONTROL_DESC_VEH_LOOK_LEFT": "向左看",
 "CONTROL_DESC_FOOT_SPRINT": "冲刺",
 "INVITE_ONLY": "本局游戏已设为仅限邀请。",
 "SB_CAT_CHOP_SHOP": "偷车目标",
 "RADIO_ALWAYS_ON": "始终开启",
 "MP3_CONFIRM_DELETE_LIST_BODY": "删除后，该播放列表将无法恢复。确定吗？",
 "CONTROL_DESC_FOOT_PRV_TRK": "上一曲（音频播放器）",
 "CONTROLS_TITLE": "操作",
 "CONTROL_DESC_VEH_RUDDER_LEFT": "向左转向",
 "CONTROL_DESC_CHANGE_CAMERA_VIEW": "切换视角",
 "MENU_PLAYLIST": "混音带",
 "INFO_STATS_TITLE": "统计信息",
 "GAMER_PROFILE_REINSERT_TRY_AGAIN": "重新连接存储设备并重试",
 "CONTROLS_DESC_CHANGE_AUDIO": "切换音轨",
 "CELL_CHEAT_ACTIVIATE_DIALOG_HEADER": "启用作弊？",
 "MAP_ACTIVITY_NOT_STARTED": "未开始",
 "REPLAY_LEVEL_REPLAY": "重玩关卡",
 "CELL_HEADER_GARAGE": "车库",
 "MENU_STATS": "统计",
 "PAUSE_ACT_CHOP_TITLE": "拆车坊",
 "OBJECTIVES_NEED_RESPECT": "游玩活动与小游戏，赚取足够声望以解锁主线任务",
 "INFO_STORY": "剧情",
 "CONTROL_DESC_VEH_RADIO_NEXT": "切换电台",
 "CELL_OPTION_DIAL": "拨号",
 "SAVELOAD_NOTHING_TO_LOAD": "没有可用存档",
 "SAVELOAD_ERROR": "警告",
 "SAVELOAD_DATE_DEFAULT": "现在！",
 "PAUSE_MAP_FILTER_MISSIONS": "任务",
 "MENU_QUICKMATCH_TYPE": "游戏类型",
 "CONTROL_SCHEME_A": "方案 A",
 "COMPLETION_EXIT": "退出",
 "COMPLETION_EXIT_MISSION_CONFIRMATION": "要退出当前任务吗？",
 "AUTOSAVING_NOW": "正在更新档案...",
 "COOP_LOBBY_WAVE": "第 {0} 波",
 "MENU_RESTORE_DEFAULTS": "恢复默认设置",
 "COMPLETION_EXIT_STRONGHOLD": "退出根据地",
 "SAVELOAD_LOAD_GAME_TITLE": "读取存档",
 "SAVELOAD_CHECK_FREE_SPACE": "硬盘空间不足，\\n无法保存主存档与用户档案。\\n请返回系统菜单，\\n腾出约 %iKB 空间。",
 "MAP_PLAYER_INCOME": "每小时收入",
 "MAINMENU_QUIT_DEMO": "退出试玩版",
 "RADIO_STATION_GENRE_MIX": "80、90 年代流行与摇滚",
 "PHONE_OPTION_CHEATS": "作弊",
 "MSGLOG_TITLE_TUT": "教程",
 "MAP_SALE_CASH_OFF": "特卖 - 立减 $%d",
 "INFO_ACHIEVE": "成就",
 "HELP_TEXT_MELEE_BLOCK": "按 {ATTACK_SECONDARY_IMG} 格挡敌人攻击",
 "CONTROL_DESC_VEH_HYDRAULICS": "喇叭/液压悬挂",
 "SAVELOAD_SAVEFILE_CORRUPT_EXPOSITION": "此存档已损坏，可能无法继续使用。",
 "SAVELOAD_DEVICE_UNAVAILABLE_OPEN_DEVICE_SELECTOR": "选择其他设备",
 "MAINMENU_LOAD": "读取存档",
 "CONTROLS_CONFIRM2": "确定吗？",
 "CONTROL_DESC_FOOT_MV_CAM": "视角",
 "RADIO_STATION_GENRE_EZZZY": "轻音乐",
 "MAINMENU_DOWNLOADABLE_CONTENT_REMOVED_EXPOSITION": "由于存有可下载内容的\\n存储设备已被移除，\\n你已返回主菜单。",
 "CANCEL_JOIN_IN_PROGRESS": "取消正在进行的加入",
 "MAP_ICON_COLLECTIBLE_MONEY": "现金托盘",
 "CONTROL_DESC_PAUSE_MP": "选项",
 "CANCEL_LOAD_SAVEGAME": "取消读取存档",
 "RANDOM_WARNING_BODY": "随机化可能会改动你的部分或全部调整。\\n此操作无法撤销。\\n\\n要继续吗？",
 "SAVELOAD_IMPORT_FAILED": "导入失败",
 "MENU_XBOX_LIVE_OFFLINE": "显示为离线",
 "DIRTY_DISK_TEXT": "无法从光盘读取文件",
 "CONTROLS_SETUP_FOOT": "步行操作",
 "MECHANIC_UNAVAILABLE": "恶名太高，暂不可用",
 "MAP_STORE_CLOSED": "已打烊",
 "DLT_NORMAL": "普通",
 "DEVICE_FULL_OR_REMOVED_TEXT": "与您的玩家档案关联的存储设备已被移除或已满。",
 "OPTIONS_TITLE": "选项",
 "OPT_PAUSE_AUDIO_W_GAME": "随游戏暂停音频播放器",
 "MENU_GAME_PAUSED": "游戏已暂停",
 "CHEAT_NOT_FOUND": "未找到该作弊码",
 "MAP_COLLECTIBLE": "收集品",
 "SAVELOAD_LOAD_GAME_NO_CLIENT": "在合作模式中，如果你不是主机方，且正在执行任务、根据地或活动，将无法读取存档。",
 "REPLAY_LEVEL_SKIP": "跳过关卡",
 "DLT_SAINTS": "给我黑道圣徒",
 "MENU_AUDIO_OVERALL": "总音量",
 "INFO_COLLECTIONS_BARNSTORMING": "低空穿越",
 "CONTROLS_CROUCH_TOGGLE": "蹲下切换",
 "COMPLETION_CONTINUE": "继续",
 "DLC_PREVIEW": "预览包",
}

lines = open(SCH, encoding="utf-8").read().replace("\r\n", "\n").split("\n")
out = []
seen = set()
for ln in lines:
    m = re.match(r'^\s*"([^"]+)":\s*"(.*)"\s*$', ln)
    if m and m.group(1) in T:
        k = m.group(1)
        out.append('"%s": "%s"' % (k, T[k]))
        seen.add(k)
    else:
        out.append(ln)
for k in T:
    if k not in seen:
        out.append('"%s": "%s"' % (k, T[k]))

open(SCH, "w", encoding="utf-8").write("\n".join(out) + "\n")
print("written", len(T), "entries; total lines", len(out))
